### 웹 크롤링
- 라이브러리
    - requests
        - 웹서버에 요청을 보내고 응답을 받는 기능
        - 응답 데이터는 문자나 바이트형으로 들어온다.
    - bs4
        - BeautifulSoup Class 이용
        - html로 이루어진 문자 데이터를 parsing 작업을 통해서 데이터 타입을 변경하여 데이터를 쉽게 추출하기 위한 기능
        - html은 TAG(element)를 기준으로 하여 데이터 접근
        - 웹의 기본 구조를 파악을 하고 사용을 하면 조금 더 쉽게 접근 가능
    - selenium
        - 웹 어플리케이션을 테스트하기 위한 라이브러리
        - 웹 브라우져를 python code를 이용하여 제어
            - 함수를 이용해서 특정 버튼을 클릭
            - 특정 위치에 데이터를 대입
        - 구글 크롬의 버전이 구버전인 경우에는 별도의 소프트웨어 설치가 필요

In [1]:
# 라이브러리 로드
import requests

In [2]:
# requests 안에 get() 함수를 이용하여 openapi에 요청을 보냈을 때는
# data가 json, xml 형태로 들어온다.
# 그러면 naver에 요청을 보내면 어떤 데이터가 들어올 것인가?
res = requests.get("http://www.naver.com")

In [3]:
res

In [7]:
# res에서 바이트형식으로 데이터를 받을 때는 content
# 문자열로 데이터를 확인할 때는 text
html_text = res.text

In [8]:
# html_text에서 네이버 글자를 찾아본다.
html_text.find('네이버')

378

In [16]:
html_text[ 378:381 ]

'네이버'

In [ ]:
# html 문서가 문자열로 이루어져있을때는 데이터를 추출하기가 어렵다.
# 별도의 라이브러리 설치
# !pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting beautifulsoup4 (from bs4)
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4)
  Downloading soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4->bs4)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading beautifulsoup4-4.13.5-py3-none-any.whl (105 kB)
Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, beautifulsoup4, bs4

   ---------- ----------------------------- 1/4 [soupsieve]
   -------------------- ------------------- 2/4 [beautifulsoup4]
   -------------------- ------------------- 2/4 [beautifulsoup4]
   ---------------------------------------- 4/4 [bs4]

Successfully installed beautifulsoup4-4.13.5 bs4-0.0.2 soupsieve-2.8 typing-extensions-4.15.0

In [20]:
# 라이브러리 로드
from bs4 import BeautifulSoup as bs

In [21]:
# BeautifulSoup class 생성 -> class 안에 데이터를 대입
# class 안에 데이터를 이용하여 추가적인 작업
# 해당 class를 생성할 때 생성자 함수는 2개의 인자 필요
# 첫번째 인자 : 문자열로 이루어진 html
# 두번째 인자 : 첫번째 인자의 따라 변경 ( html 문서를 변환 : html.parser )
soup = bs(html_text, 'html.parser')

In [22]:
soup

 <!DOCTYPE html>
 <html class="fzoom" lang="ko"> <head> <meta charset="utf-8"/> <meta content="origin" name="Referrer"/> <meta content="IE=edge" http-equiv="X-UA-Compatible"/> <meta content="width=1190" name="viewport"/> <title>NAVER</title> <meta content="NAVER" name="apple-mobile-web-app-title"> <meta content="index,nofollow" name="robots"> <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description"> <meta content="네이버" property="og:title"/> <meta content="https://www.naver.com/" property="og:url"/> <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/> <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description"> <meta content="summary" name="twitter:card"/> <meta content="" name="twitter:title"/> <meta content="https://www.naver.com/" name="twitter:url"/> <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" name="twitter:image"/> <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="twitter:description"> <meta content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g" name="google-site-verification"> <link href="/favicon.ico?1" rel="shortcut icon" type="image/x-icon"/> <link href="https://s.pstatic.net/static/www/nFavicon96.png" rel="apple-touch-icon-precomposed"> <link href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png" rel="apple-touch-icon" sizes="114x114"/> <link href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png" rel="apple-touch-icon"/> <link href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_250828.css" rel="stylesheet"/> <link href="https://www.naver.com/" rel="canonical"/> <link href="https://m.naver.com/" media="only screen and (max-width: 767px)" rel="alternate"/> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async="" src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async="" src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script defer="defer" src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js"></script> <script>
window["EAGER-DATA"] = window["EAGER-DATA"] || {};
window["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"((⭐))  3000일을 방송했지만 2/3확률로 13번 맞춰야 탈출하는 게임 Door(2/3)¹³ 을 2일차 하는 사람 ","url":"https://chzzk.naver.com/live/80b36a0ae8e887e893ce0014dbfece4a?tracking_code=navermain_game_live","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Flivecloud-thumb.akamaized.net%2Fchzzk%2Flivecloud%2FKR%2Fstream%2F26441957%2Flive%2F14408901%2Frecord%2F44517026%2Fthumbnail%2Fimage_720.jpg%3Ftimestamp%3D2025-09-09T11%253A25%22&type=f504_292&service=navermain"},"highlight":"도어(2/3)¹³","source":{"name":"나나양","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fnng-phinf.pstatic.net%2FMjAyNTA0MDJfOTcg%2FMDAxNzQzNTIwMjk0NDMw.uC_u2oZAMeqN2vqwLyO-A6lQxqvw8G1mWiIzePpyqt8g.4S1l4uVV1laPLcjDY5pBLrfY_5VMxNyX9ELSlJJcwbAg.PNG%2F%25EA%25B5%25B0%25EC%25A3%25BC.png%22&type=nf96_96&service=navermain"}},"chzzkLiveId":"80b36a0ae8e887e893ce0014dbfece4a","showLiveBadge":true,"_id":"65308fd13c50cd9912162f6a"},{"@type":"MATERIAL-PC-FEED","title":"i`m Ryze","url":"https://chzzk.naver.com/live/47c49bff55111a6cfd30bb299e9d2e5d?tracking_code=navermain_game_live","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Flivecloud-thumb.akamaized.net%2Fchzzk%2Flivecloud%2FKR%2Fstream%2F26480071%2Flive%2F14398236%2Frecord%2F44501441%2Fthumbnail%2Fimage_720.jpg%3Ftimestamp%3D2025-09-09T11%253A25%22&type=f504_292&service=navermain"},"highlight":"전략적 팀 전투: K.O. 콜로세움","source":{"name":"인섹","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fnng-phinf.pstatic.net%2FMjAyNDEwMTVfMTU0%2FMDAxNzI5MDAwNzc5OTg2.m_dS377hiuCKT9yqAQeVizNx6frnV1bM6hbWr2Jcof8g.46Z9cogCgAqriBbSrnyWRFlO-2QdkW1n9gaOjsuouS8g.PNG%2F%25EC%259D%25B8%25EC%2584%25B92.png%22&type=nf96_96&service=navermain"}},"chzzkLiveId":"47c49bff55111a6cfd30bb299e9d2e5d","showLiveBadge":true,"_id":"65308fd13c50cd9912162f6b"},{"@type":"MATERIAL-PC-FEED","title":"예쁜말만 하는 블린의 불법실크송 ","url":"https://chzzk.naver.com/live/e14259667937be6e561d28ab156718be?tracking_code=navermain_game_live","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Flivecloud-thumb.akamaized.net%2Fchzzk%2Flivecloud%2FKR%2Fstream%2F26590898%2Flive%2F14408388%2Frecord%2F44516192%2Fthumbnail%2Fimage_720.jpg%3Ftimestamp%3D2025-09-09T11%253A25%22&type=f504_292&service=navermain"},"highlight":"할로우 나이트: 실크송","source":{"name":"해블린","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fnng-phinf.pstatic.net%2FMjAyNTA3MjNfOTkg%2FMDAxNzUzMjIzMDQ1MTQ5.x2FFUZ7gULgKjokeggw5YwZu4cHGAPoQGry82ESbblQg._3F0_Tu5VoQOy6QvfmA-wg2eZbui3Dgxcv6A-IOvsNMg.JPEG%2F1280%25EF%25BC%25BFScreenshot%25EF%25BC%25BF20250722%25EF%25BC%25BF185957%25EF%25BC%25BFGallery.jpg%22&type=nf96_96&service=navermain"}},"chzzkLiveId":"e14259667937be6e561d28ab156718be","showLiveBadge":true,"_id":"654ad80598c6dbca70ba6ce6"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@template":"NONE"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-GAMEAPP-TOP-HIGHLIGHTED","@template":"HIGHLIGHTED-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"에이크라운 신규멤버 소개 - 승 님 (with 스타레일 파이논 코스프레)","url":"https://game.naver.com/original_series/14/detail/6640774","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320341924y4n80.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"ACROWN"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b3"},{"@type":"MATERIAL-PC-FEED","title":"괴수 8호 더 게임 – 팬심과 평범함 사이에서","url":"https://game.naver.com/original_series/64/detail/6640784","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320368427IN9Gi.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"게임인 "},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b4"},{"@type":"MATERIAL-PC-FEED","title":"[게임처방전] '나이트 시티' 다음에 방문할 장소를 원해요","url":"https://game.naver.com/original_series/75/detail/6640772","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320391974uZA87.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"PNN"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b5"},{"@type":"MATERIAL-PC-FEED","title":"뜨거운 햇살 아래 Summer Vacation! - 에반게리온 ","url":"https://game.naver.com/original_series/2/detail/6629507","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757064647522DyQna.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"Team CSL 코스프레"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b6"},{"@type":"MATERIAL-PC-FEED","title":"9번째 시리즈 '바이오하자드 레퀴엠', 도망만 다니는 무력감이란","url":"https://game.naver.com/original_series/4/detail/6628383","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757064683604rTGef.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"GAMEVU"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b7"},{"@type":"MATERIAL-PC-FEED","title":"[밈과사전] 아제로스에서는 ‘물빵’으로 영양을 챙겨요","url":"https://game.naver.com/original_series/52/temp/245190","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_17570643280991rUrU.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"PNN"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b8"},{"@type":"MATERIAL-PC-FEED","title":"날씨 이게 맞나... 계속해서 더운 요즘 여러분이 해본 가장 무서운(호러 장르) 게임은? (Feat. 호러 찌질이)","url":"https://game.naver.com/original_series/53/detail/6628645","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757064384524uBWPH.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"사신청룡"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4b9"},{"@type":"MATERIAL-PC-FEED","title":"하이엔드 게임즈 김태준 대표, 멋진 수록곡에 예쁜 캐릭터를 더하다","url":"https://game.naver.com/original_series/74/detail/6629934","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757064427318XJjwk.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"게임조선 "},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c4ba"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-GAMEAPP-ORIGINAL-SERIES","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","excludeInPaging":false,"positionForPaging":0,"realtime":false,"title":"치지직 추천 LIVE","needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-GAMEAPP-CHZZK-RECOMMEND","@template":"FOUR-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"「꿈을 좇는 표류병」 이벤트 설명","url":"https://game.naver.com/lounge/ZZZ/board/detail/6640097","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320989420Y3Z90.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"젠레스 존 제로"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c24"},{"@type":"MATERIAL-PC-FEED","title":"푸른하늘의 날 환경 지킴이 이벤트 안내","url":"https://game.naver.com/lounge/Ragnarok_BacktoGlory/board/detail/6639906","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320882802QIUmP.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"라그나로크 : Back to Glory"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c25"},{"@type":"MATERIAL-PC-FEED","title":"에피카의 인형극장 진행 예정 안내","url":"https://game.naver.com/lounge/Trickcal/board/detail/6640874","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320853423KhKSs.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"트릭컬 리바이브"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c26"},{"@type":"MATERIAL-PC-FEED","title":"다양한 병영 중 족장님은 어떤 병영을 주로 사용하시나요!? ","url":"https://game.naver.com/lounge/Fate_War/board/detail/6639565","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250908_1095%2Fupload_1757320824777Bf2MH.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"페이트 워"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c27"},{"@type":"MATERIAL-PC-FEED","title":"💖 짱구 닮은꼴 진단 테스트 이벤트 🎉 💖","url":"https://game.naver.com/lounge/Crayon_Shinchan_My_Sugoroku_Great_Strategy/board/detail/6630228","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757065542616PkpII.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"짱구는 못말려 나의 주사위 놀이 대작전"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c28"},{"@type":"MATERIAL-PC-FEED","title":"🎁「시드」는 산책 중","url":"https://game.naver.com/lounge/ZZZ/board/detail/6629550","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757065631878udShZ.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"젠레스 존 제로"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c29"},{"@type":"MATERIAL-PC-FEED","title":"⚔️ 성채의 충돌 리그 (Beta) 개막! ⚔️ ","url":"https://game.naver.com/lounge/Top_Herose/board/detail/6625491","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757065791691D0ZHx.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"탑 히어로즈"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c2a"},{"@type":"MATERIAL-PC-FEED","title":"1.63.0 업데이트 미리보기 안내","url":"https://game.naver.com/lounge/Blade_idle/board/detail/6624869","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250905_1095%2Fupload_1757065667670Ni9QO.jpg%22&type=nf308_200&service=navermain"},"source":{"name":"블레이드 키우기"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6c2b"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-GAMEAPP-LOUNGE-NEWS","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"2025시즌 마지막 여정, 플레이오프 개막 [LCK]","url":"https://m.sports.naver.com/esports/article/236/0000251005","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F236%2F2025%2F09%2F09%2F0000251005_001_20250909102510134.jpg%22&type=nf365_240&service=navermain"},"showLiveBadge":false,"_id":"65e03bedf9834a2ada7d6ce9"},{"@type":"MATERIAL-PC-FEED","title":"성승헌-정노철-고수진, MBC LCK 결승 중계진 합류","url":"https://m.sports.naver.com/esports/article/347/0000188782","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F347%2F2025%2F09%2F09%2F2025090910081400322b91e133c1f11015245119_20250909101106891.png%22&type=nf365_240&service=navermain"},"showLiveBadge":false,"_id":"65e03bedf9834a2ada7d6cea"},{"@type":"MATERIAL-PC-FEED","title":"쵸비 정지훈, 강릉시 가뭄 피해 지원에 2,000만 원 기부","url":"https://m.sports.naver.com/esports/article/356/0000076631","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F356%2F2025%2F09%2F08%2F0000076631_001_20250908162614630.jpg%22&type=nf365_240&service=navermain"},"showLiveBadge":false,"_id":"65e03bedf9834a2ada7d6ceb"},{"@type":"MATERIAL-PC-FEED","title":"BFX 랩터 \"강팀들과 대결 통해 우리 실력 보여주고파…KT전 승산 있어\" (LCK) [인터뷰]","url":"https://m.sports.naver.com/esports/article/311/0001914588","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F311%2F2025%2F09%2F08%2F0001914588_001_20250908134207480.jpeg%22&type=nf365_240&service=navermain"},"showLiveBadge":false,"_id":"65e03bedf9834a2ada7d6cec"},{"@type":"MATERIAL-PC-FEED","title":"‘2025 이스포츠 대학리그’ 개막… 개편된 구조·참가 대학 공개","url":"https://m.sports.naver.com/esports/article/311/0001914602","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F311%2F2025%2F09%2F08%2F0001914602_001_20250908143110651.png%22&type=nf365_240&service=navermain"},"showLiveBadge":false,"_id":"65e03bedf9834a2ada7d6ced"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"title":"e스포츠 소식","needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-GAMEAPP-ESPORTS-NEWS","@template":"FOUR-COLUMNS"}],"materials":null,"excludeInPaging":false,"positionForPaging":0,"realtime":false,"_id":null,"@type":"BLOCK","@code":"PC-FEED-GAMEAPP","@template":"NONE","@flowId":null,"@flowExecutionId":null,"@provider":null,"@lastModifiedAt":null}],"materials":null,"excludeInPaging":false,"positionForPaging":0,"realtime":false,"_id":"6441ca92a10d3006855f9acd","@type":"BLOCK","@code":"PC-FEED-WRAPPER","@template":"PC-FEED-WRAPPER","@flowId":"PC-FEED-WRAPPER","@flowExecutionId":"a74c26cc-8d24-11f0-a32e-a558b87c3bbd","@provider":"lambda","@lastModifiedAt":[2025,9,9,2,28,21,875000000]}
window["EAGER-DATA"]["CAS-MINICONTENT-PC-SPECIAL-LOGO"] = {"@type":"MINI-CONTENT-BLOCK","blocks":null,"materials":null,"excludeInPaging":false,"positionForPaging":0,"realtime":false,"items":[],"_id":"6433d8e3a10d3006850274e8","@type":"MINI-CONTENT-BLOCK","@code":"CAS-MINICONTENT-PC-SPECIAL-LOGO","@template":"NONE","@flowId":"CAS-MINICONTENT","@flowExecutionId":"8e24ca6e-8d24-11f0-96c8-d7c95cd68a9d","@provider":"lambda","@lastModifiedAt":[2025,9,9,2,27,39,198000000]}

- 태그의 이름을 기준으로 검색
    - soup.태그명 -> 해당 html 문서에서 해당 태그의 첫번째 태그를 되돌려준다.
    - soup.태그명.string -> 첫번째 태그에서 콘텐츠(태그 안에 데이터)를 되돌려준다.
        - ex) `<p>test data</p>` -> test data 출력
    - soup.태그명['속성명'] -> 첫번째 태그에서 특정 속성의 값을 되돌려준다.
        - ex) `<a href = 'http://www.google.com'>google</a>` ->
        'http://www.google.com' 출력

In [23]:
soup.a

In [26]:
soup.a.string

'상단영역 바로가기'

In [27]:
soup.a['href']

'#topAsideButton'

- find()
    - html 데이터에서 특정 태그의 첫번째 정보를 출력
    - find(속성명 = 속성값) : 태그들 중에 특정 속성에 특정한 값을 가진 태그의 첫번째 정보를 출력
    - 함수의 결과의 타입은 TAG 데이터의 타입으로 되돌려준다.
- find_all()
    - html 데이터에서 특정 태그의 모든 정보를 출력
    - limit 매개변수 : 찾는 태그의 개수를 지정
    - 함수의 결과의 타입은 TAG 데이터들이 모인 ResultSet 타입으로 되돌려준다.
    (find(), find_all() 함수를 사용하려면 TAG 데이터 타입으로 데이터를 추출하여 사용)

In [28]:
type(soup)

bs4.BeautifulSoup

In [29]:
type(soup.find('a'))

bs4.element.Tag

In [30]:
type(soup.find_all('a'))

bs4.element.ResultSet

In [32]:
soup.find('a')

In [33]:
# html 문서 안에 존재하는 모든 a태그의 정보를 확인
soup.find_all('a')

[<a href="#topAsideButton"><span>상단영역 바로가기</span></a>,
 <a href="#shortcutArea"><span>서비스 메뉴 바로가기</span></a>,
 <a href="#newsstand"><span>새소식 블록 바로가기</span></a>,
 <a href="#shopping"><span>쇼핑 블록 바로가기</span></a>,
 <a href="#feed"><span>관심사 블록 바로가기</span></a>,
 <a href="#account"><span>MY 영역 바로가기</span></a>,
 <a href="#widgetboard"><span>위젯 보드 바로가기</span></a>,
 <a href="#viewSetting"><span>보기 설정 바로가기</span></a>]

In [35]:
# 네이버 메인페이지는 비동기 방식 페이지이므로 전체의 html를 requests만 가지고 로드가 불가능
# 'http://finance.naver.com/' 이 주소의 html를 불러와서 실습

# 특정 주소에 요청을 보낸다.
res = requests.get('http://finance.naver.com/')
# res에서 html데이터를 문자열로 저장
html_data = res.text
# BeautifulSoup을 이용하여 데이터 파싱
soup = bs(html_data, 'html.parser')

In [41]:
# soup에서 div 태그중 class의 값이 'section_sise_top' 태그를 찾는다.
# 해당 조건의 태그가 1개인가 확인
len(
    soup.find_all(
        'div',
        attrs = {
            'class' : 'section_sise_top'
            }
    )
)

1

In [42]:
# len() 함수를 이용하여 길이 확인하니 1이다. -> 해당 조건의 태그는 하나
div_data = soup.find(
    'div',
    attrs = {
        'class' : 'section_sise_top'
    }
)

In [45]:
# div_data table 태그의 개수를 확인
len(
    div_data.find_all(
        'table',
        attrs = {
            'class' : 'tbl_home'
        }
    )
)

# div_data에는 테이블이 8개 존재 -> KRX 4, NXT 4

8

In [46]:
table_list = div_data.find_all(
    'table'
)

In [47]:
table_data = table_list[0]

In [48]:
# table data에서 thead를 찾는다.
thead_data = table_data.find('thead')

In [50]:
# 데이터들은 열을 나타내는 태그에 존재
# th 태그들에 데이터가 존재
# th 태그를 모두 찾는다.
th_list = thead_data.find_all('th')

In [59]:
# th 데이터에서 문자만 추출
# map( 함수(lambda), 1차원 데이터 )
cols = list(
    map(
        lambda x : x.string,
        th_list
    )
)

In [60]:
# table_data에서 tbody를 찾는다.
tbody_data = table_data.find('tbody')

In [62]:
# tbody_data에서 모든 tr태그를 찾는다. (tr 안에 th, td 데이터를 이용하여 1차원 데이터를 구성)
tr_list = tbody_data.find_all('tr')

In [75]:
tr_list[0].find_all( ['th', 'td'] )

[<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>,
 <td>1,247</td>,
 <td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 32</td>,
 <td>
 <em class="down">
 				-2.50%
 				</em>
 </td>]

In [79]:
# tr_list에서 첫번째 데이터를 이용하여 th, td를 찾는다.
list(
    map(
        lambda x : x.get_text().strip(),
        tr_list[0].find_all( ['th', 'td'] )
    )
)

['KODEX 200선물인버스2X', '1,247', '하락 32', '-2.50%']

In [80]:
# 비어있는 리스트 생성
values = []
# tr_list를 이용하여 반복문을 실행
for td_data in tr_list:
    # td_data에는 반복 실행할때마다 tr_list의 첫번째, 두번째, ... 대입
    value = list(
        map(
            lambda x : x.get_text().strip(),
            td_data.find_all( ['th', 'td'] )
        )
    )
    values.append(value)
values

[['KODEX 200선물인버스2X', '1,247', '하락 32', '-2.50%'],
 ['이트론', '5', '하락 5', '-50.00%'],
 ['엔케이', '1,398', '상승 8', '+0.58%'],
 ['씨피시스템', '2,550', '상승 140', '+5.81%'],
 ['KD', '930', '상승 163', '+21.25%'],
 ['보성파워텍', '4,310', '상승 355', '+8.98%'],
 ['이아이디', '83', '하락 19', '-18.63%'],
 ['KODEX 인버스', '3,412', '하락 48', '-1.39%'],
 ['한국선재', '4,305', '상승 385', '+9.82%'],
 ['KODEX 2차전지산업레버리지', '1,023', '상승 23', '+2.30%'],
 ['일승', '8,170', '상승 1,640', '+25.11%'],
 ['대창솔루션', '509', '상승 18', '+3.67%'],
 ['이화전기', '319', '상승 24', '+8.14%'],
 ['미투온', '6,410', '상승 610', '+10.52%'],
 ['상상인증권', '853', '상승 172', '+25.26%']]

In [81]:
import pandas as pd

In [83]:
df = pd.DataFrame(values, columns = cols)
df

                 종목명    현재가      전일대비      등락률
0   KODEX 200선물인버스2X  1,247     하락 32   -2.50%
1                이트론      5      하락 5  -50.00%
2                엔케이  1,398      상승 8   +0.58%
3              씨피시스템  2,550    상승 140   +5.81%
4                 KD    930    상승 163  +21.25%
5              보성파워텍  4,310    상승 355   +8.98%
6               이아이디     83     하락 19  -18.63%
7          KODEX 인버스  3,412     하락 48   -1.39%
8               한국선재  4,305    상승 385   +9.82%
9   KODEX 2차전지산업레버리지  1,023     상승 23   +2.30%
10                일승  8,170  상승 1,640  +25.11%
11             대창솔루션    509     상승 18   +3.67%
12              이화전기    319     상승 24   +8.14%
13               미투온  6,410    상승 610  +10.52%
14             상상인증권    853    상승 172  +25.26%

In [96]:
# section_sise_top class 이름을 가진 div 태그의 모든 table를 데이터프레임으로 생성
file_num = 1
for table_data in table_list:
    thead_data = table_data.find('thead')
    th_list = thead_data.find_all('th')
    cols = list(
        map(
            lambda x : x.string,
            th_list
        )
    )
    tbody_data = table_data.find('tbody')
    tr_list = tbody_data.find_all('tr')
    values = []
    # tr_list를 이용하여 반복문을 실행
    for td_data in tr_list:
        # td_data에는 반복 실행할때마다 tr_list의 첫번째, 두번째, ... 대입
        value = list(
            map(
                lambda x : x.get_text().strip(),
                td_data.find_all( ['th', 'td'] )
            )
        )
        values.append(value)
    globals()[f'df{file_num}'] = pd.DataFrame(values, columns = cols)
    # 각각의 파일로 저장
    globals()[f'df{file_num}'].to_csv(f'df{file_num}.csv')
    file_num += 1

In [97]:
df5

          종목명     현재가       전일대비      등락률
0         이트론       5      하락 -5  -50.00%
1        이아이디      83     하락 -19  -18.63%
2          오아  15,020  하락 -3,210  -17.61%
3        딥노이드   4,895    하락 -835  -14.57%
4     압타머사이언스   1,119    하락 -181  -13.92%
5      테고사이언스  16,890  하락 -1,860   -9.92%
6      대양전기공업  29,100  하락 -2,900   -9.06%
7       그린리소스  10,730  하락 -1,020   -8.68%
8        에프알텍   2,510    하락 -225   -8.23%
9       HJ중공업  26,900  하락 -2,300   -7.88%
10  디에이치엑스컴퍼니     921     하락 -77   -7.72%
11      STX엔진  44,000  하락 -3,550   -7.47%
12      동성화인텍  31,550  하락 -2,500   -7.34%
13      고바이오랩   6,180    하락 -470   -7.07%
14      헬릭스미스   6,470    하락 -480   -6.91%

In [99]:
type(div_data)

bs4.element.Tag

In [100]:
str(div_data)

'<div class="section_sise_top">\n<h2 class="h_type"><span>TOP 종목</span></h2>\n<!-- KRX, NXT 탭 -->\n<div class="area_tab_type">\n<ul class="top_tab_list">\n<!-- [D] 선택된 탭 \'is_active\' -->\n<li class="top_tab_item top_tab_krx is_active">\n<a class="top_tab_link" href="#" onclick="clickcr(this, \'top.krx\', \'\', \'\', event);return false;">KRX</a>\n</li>\n<li class="top_tab_item top_tab_nxt">\n<a class="top_tab_link" href="#" onclick="clickcr(this, \'top.nxt\', \'\', \'\', event);return false;">NXT</a>\n</li>\n</ul>\n<div class="text_nxt">\n                                넥스트레이드(NXT)\n                                <button class="buttton_tooltip" type="button">\n<span class="icon">\n<span class="blind">도움말</span>\n</span>\n</button>\n<div class="area_tooltip">\n<p>\n<strong>넥스트레이드(NXT)</strong>\n                                        넥스트레이드(NXT)란 대한민국\n                                        최초의 대체거래소(ATS,\n                                        Alternative Trading\n                                        System)입니다. 아래는\n                                        넥스트레이드에서 거래가 가능한\n                                        종목들입니다.\n                                    </p>\n<span class="arrow"></span>\n</div>\n</div>\n</div>\n<!-- //KRX, NXT 탭 -->\n<ul class="tab_sort_list">\n<!-- [D] 선택된 탭 \'is_active\' -->\n<li class="tab_sort_item is_active"><a class="link tab_sort_sale" href="#" onclick="clickcr(this, \'spe.sale\', \'\', \'\', event);return false;"><span class="tab1"><span class="blind">거래상위</span></span></a></li>\n<li class="tab_sort_item"><a class="link tab_sort_ceiling" href="#" onclick="clickcr(this, \'spe.ceiling\', \'\', \'\', event);return false;"><span class="tab2"><span class="blind">상승</span></span></a></li>\n<li class="tab_sort_item"><a class="link tab_sort_bottom" href="#" onclick="clickcr(this, \'spe.bottom\', \'\', \'\', event);return false;"><span class="tab3"><span class="blind">하락</span></span></a></li>\n<li class="tab_sort_item"><a class="link tab_sort_value" href="#" onclick="clickcr(this, \'spe.value\', \'\', \'\', event);return false;"><span class="tab4"><span class="blind">시가총액 상위</span></span></a></li>\n</ul>\n<div class="group_type krx_group_type tab1 is_active">\n<table class="tbl_home">\n<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>\n<colgroup>\n<col width="40%"/>\n<col/>\n</colgroup>\n<thead>\n<tr>\n<th scope="col">종목명</th>\n<th scope="col">현재가</th>\n<th scope="col">전일대비</th>\n<th scope="col">등락률</th>\n</tr>\n</thead>\n<tbody id="_topItems1">\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, \'spe.slist\', \'252670\', \'1\', event);">KODEX 200선물인버스2X</a></th>\n<td>1,247</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 32</td>\n<td>\n<em class="down">\n\t\t\t\t-2.50%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=096040" onclick="clickcr(this, \'spe.slist\', \'096040\', \'2\', event);">이트론</a></th>\n<td>5</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 5</td>\n<td>\n<em class="down">\n\t\t\t\t-50.00%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=085310" onclick="clickcr(this, \'spe.slist\', \'085310\', \'3\', event);">엔케이</a></th>\n<td>1,398</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 8</td>\n<td>\n<em class="up">\n\t\t\t\t+0.58%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=413630" onclick="clickcr(this, \'spe.slist\', \'413630\', \'4\', event);">씨피시스템</a></th>\n<td>2,550</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 140</td>\n<td>\n<em class="up">\n\t\t\t\t+5.81%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=044180" onclick="clickcr(this, \'spe.slist\', \'044180\', \'5\', event);">KD</a></th>\n<td>930</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 163</td>\n<td>\n<em class="up">\n\t\t\t\t+21.25%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=006910" onclick="clickcr(this, \'spe.slist\', \'006910\', \'6\', event);">보성파워텍</a></th>\n<td>4,310</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 355</td>\n<td>\n<em class="up">\n\t\t\t\t+8.98%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=093230" onclick="clickcr(this, \'spe.slist\', \'093230\', \'7\', event);">이아이디</a></th>\n<td>83</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 19</td>\n<td>\n<em class="down">\n\t\t\t\t-18.63%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, \'spe.slist\', \'114800\', \'8\', event);">KODEX 인버스</a></th>\n<td>3,412</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 48</td>\n<td>\n<em class="down">\n\t\t\t\t-1.39%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=025550" onclick="clickcr(this, \'spe.slist\', \'025550\', \'9\', event);">한국선재</a></th>\n<td>4,305</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 385</td>\n<td>\n<em class="up">\n\t\t\t\t+9.82%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, \'spe.slist\', \'462330\', \'10\', event);">KODEX 2차전지산업레버리지</a></th>\n<td>1,023</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 23</td>\n<td>\n<em class="up">\n\t\t\t\t+2.30%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=333430" onclick="clickcr(this, \'spe.slist\', \'333430\', \'11\', event);">일승</a></th>\n<td>8,170</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,640</td>\n<td>\n<em class="up">\n\t\t\t\t+25.11%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=096350" onclick="clickcr(this, \'spe.slist\', \'096350\', \'12\', event);">대창솔루션</a></th>\n<td>509</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 18</td>\n<td>\n<em class="up">\n\t\t\t\t+3.67%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=024810" onclick="clickcr(this, \'spe.slist\', \'024810\', \'13\', event);">이화전기</a></th>\n<td>319</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 24</td>\n<td>\n<em class="up">\n\t\t\t\t+8.14%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=201490" onclick="clickcr(this, \'spe.slist\', \'201490\', \'14\', event);">미투온</a></th>\n<td>6,410</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 610</td>\n<td>\n<em class="up">\n\t\t\t\t+10.52%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=001290" onclick="clickcr(this, \'spe.slist\', \'001290\', \'15\', event);">상상인증권</a></th>\n<td>853</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 172</td>\n<td>\n<em class="up">\n\t\t\t\t+25.26%\n\t\t\t\t</em>\n</td>\n</tr>\n</tbody>\n</table>\n<a class="btn_more" href="/sise/sise_quant.naver" onclick="clickcr(this, \'spe.more\', \'\', \'\', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>\n</div>\n<div class="group_type nxt_group_type tab1 is_active" style="display:none">\n<table class="tbl_home">\n<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>\n<colgroup>\n<col width="40%"/>\n<col/>\n</colgroup>\n<thead>\n<tr>\n<th scope="col">종목명</th>\n<th scope="col">현재가</th>\n<th scope="col">전일대비</th>\n<th scope="col">등락률</th>\n</tr>\n</thead>\n<tbody id="nxt_topItems1">\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=014940" onclick="clickcr(this, \'spe.slist\', \'014940\', \'1\', event);">오리엔탈정공</a></th>\n<td>11,370</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 470</td>\n<td>\n<em class="up">\n\t\t\t\t+4.31%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=030530" onclick="clickcr(this, \'spe.slist\', \'030530\', \'2\', event);">원익홀딩스</a></th>\n<td>11,400</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,060</td>\n<td>\n<em class="up">\n\t\t\t\t+22.06%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=437730" onclick="clickcr(this, \'spe.slist\', \'437730\', \'3\', event);">삼현</a></th>\n<td>17,350</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,480</td>\n<td>\n<em class="up">\n\t\t\t\t+16.68%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=075580" onclick="clickcr(this, \'spe.slist\', \'075580\', \'4\', event);">세진중공업</a></th>\n<td>22,200</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 1,300</td>\n<td>\n<em class="down">\n\t\t\t\t-5.53%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=253590" onclick="clickcr(this, \'spe.slist\', \'253590\', \'5\', event);">네오셈</a></th>\n<td>9,120</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 700</td>\n<td>\n<em class="up">\n\t\t\t\t+8.31%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=067310" onclick="clickcr(this, \'spe.slist\', \'067310\', \'6\', event);">하나마이크론</a></th>\n<td>15,640</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,620</td>\n<td>\n<em class="up">\n\t\t\t\t+11.55%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=006800" onclick="clickcr(this, \'spe.slist\', \'006800\', \'7\', event);">미래에셋증권</a></th>\n<td>21,550</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,850</td>\n<td>\n<em class="up">\n\t\t\t\t+9.39%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=034020" onclick="clickcr(this, \'spe.slist\', \'034020\', \'8\', event);">두산에너빌리티</a></th>\n<td>62,100</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,200</td>\n<td>\n<em class="up">\n\t\t\t\t+1.97%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=452280" onclick="clickcr(this, \'spe.slist\', \'452280\', \'9\', event);">한선엔지니어링</a></th>\n<td>8,680</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 510</td>\n<td>\n<em class="up">\n\t\t\t\t+6.24%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=005930" onclick="clickcr(this, \'spe.slist\', \'005930\', \'10\', event);">삼성전자</a></th>\n<td>71,100</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,000</td>\n<td>\n<em class="up">\n\t\t\t\t+1.43%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=010140" onclick="clickcr(this, \'spe.slist\', \'010140\', \'11\', event);">삼성중공업</a></th>\n<td>20,950</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 300</td>\n<td>\n<em class="down">\n\t\t\t\t-1.41%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=059210" onclick="clickcr(this, \'spe.slist\', \'059210\', \'12\', event);">메타바이오메드</a></th>\n<td>6,340</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 60</td>\n<td>\n<em class="down">\n\t\t\t\t-0.94%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=290650" onclick="clickcr(this, \'spe.slist\', \'290650\', \'13\', event);">엘앤씨바이오</a></th>\n<td>50,700</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,750</td>\n<td>\n<em class="up">\n\t\t\t\t+3.58%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=080220" onclick="clickcr(this, \'spe.slist\', \'080220\', \'14\', event);">제주반도체</a></th>\n<td>18,060</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 350</td>\n<td>\n<em class="up">\n\t\t\t\t+1.98%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="down">\n<th scope="row"><a href="/item/main.naver?code=0008Z0" onclick="clickcr(this, \'spe.slist\', \'0008Z0\', \'15\', event);">에스엔시스</a></th>\n<td>49,000</td>\n<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 2,200</td>\n<td>\n<em class="down">\n\t\t\t\t-4.30%\n\t\t\t\t</em>\n</td>\n</tr>\n</tbody>\n</table>\n<a class="btn_more" href="/sise/nxt_sise_quant.naver" onclick="clickcr(this, \'spe.more\', \'\', \'\', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>\n</div>\n<div class="group_type krx_group_type tab2">\n<table class="tbl_home">\n<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>\n<colgroup>\n<col width="40%"/>\n<col/>\n</colgroup>\n<thead>\n<tr>\n<th scope="col">종목명</th>\n<th scope="col">현재가</th>\n<th scope="col">전일대비</th>\n<th scope="col">등락률</th>\n</tr>\n</thead>\n<tbody id="_topItems2">\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=023790" onclick="clickcr(this, \'spe.clist\', \'023790\', \'1\', event);">동일스틸럭스</a></th>\n<td>3,640</td>\n<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 840 </td>\n<td>\n<em class="up">\n\t\t\t\t+30.00%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=049180" onclick="clickcr(this, \'spe.clist\', \'049180\', \'2\', event);">셀루메드</a></th>\n<td>802</td>\n<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 185 </td>\n<td>\n<em class="up">\n\t\t\t\t+29.98%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=066900" onclick="clickcr(this, \'spe.clist\', \'066900\', \'3\', event);">디에이피</a></th>\n<td>2,510</td>\n<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 578 </td>\n<td>\n<em class="up">\n\t\t\t\t+29.92%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=001290" onclick="clickcr(this, \'spe.clist\', \'001290\', \'4\', event);">상상인증권</a></th>\n<td>853</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 172 </td>\n<td>\n<em class="up">\n\t\t\t\t+25.26%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=333430" onclick="clickcr(this, \'spe.clist\', \'333430\', \'5\', event);">일승</a></th>\n<td>8,170</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,640 </td>\n<td>\n<em class="up">\n\t\t\t\t+25.11%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=030530" onclick="clickcr(this, \'spe.clist\', \'030530\', \'6\', event);">원익홀딩스</a></th>\n<td>11,400</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,060 </td>\n<td>\n<em class="up">\n\t\t\t\t+22.06%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=053260" onclick="clickcr(this, \'spe.clist\', \'053260\', \'7\', event);">금강철강</a></th>\n<td>4,920</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 865 </td>\n<td>\n<em class="up">\n\t\t\t\t+21.33%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=044180" onclick="clickcr(this, \'spe.clist\', \'044180\', \'8\', event);">KD</a></th>\n<td>930</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 163 </td>\n<td>\n<em class="up">\n\t\t\t\t+21.25%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=120030" onclick="clickcr(this, \'spe.clist\', \'120030\', \'9\', event);">조선선재</a></th>\n<td>131,800</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 22,700 </td>\n<td>\n<em class="up">\n\t\t\t\t+20.81%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=200470" onclick="clickcr(this, \'spe.clist\', \'200470\', \'10\', event);">에이팩트</a></th>\n<td>3,480</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 515 </td>\n<td>\n<em class="up">\n\t\t\t\t+17.37%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=437730" onclick="clickcr(this, \'spe.clist\', \'437730\', \'11\', event);">삼현</a></th>\n<td>17,360</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,490 </td>\n<td>\n<em class="up">\n\t\t\t\t+16.75%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=042520" onclick="clickcr(this, \'spe.clist\', \'042520\', \'12\', event);">한스바이오메드</a></th>\n<td>9,550</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,300 </td>\n<td>\n<em class="up">\n\t\t\t\t+15.76%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=099410" onclick="clickcr(this, \'spe.clist\', \'099410\', \'13\', event);">동방선기</a></th>\n<td>5,780</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 750 </td>\n<td>\n<em class="up">\n\t\t\t\t+14.91%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=082270" onclick="clickcr(this, \'spe.clist\', \'082270\', \'14\', event);">젬백스</a></th>\n<td>56,400</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7,150 </td>\n<td>\n<em class="up">\n\t\t\t\t+14.52%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=380550" onclick="clickcr(this, \'spe.clist\', \'380550\', \'15\', event);">뉴로핏</a></th>\n<td>15,070</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,910 </td>\n<td>\n<em class="up">\n\t\t\t\t+14.51%\n\t\t\t\t</em>\n</td>\n</tr>\n</tbody>\n</table>\n<a class="btn_more" href="/sise/sise_rise.naver" onclick="clickcr(this, \'spe.more\', \'\', \'\', event);"><em class="btn_more4"><span class="blind">상승 더보기</span></em></a>\n</div>\n<div class="group_type nxt_group_type tab2" style="display:none">\n<table class="tbl_home">\n<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>\n<colgroup>\n<col width="40%"/>\n<col/>\n</colgroup>\n<thead>\n<tr>\n<th scope="col">종목명</th>\n<th scope="col">현재가</th>\n<th scope="col">전일대비</th>\n<th scope="col">등락률</th>\n</tr>\n</thead>\n<tbody id="nxt_topItems2">\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=030530" onclick="clickcr(this, \'spe.clist\', \'030530\', \'1\', event);">원익홀딩스</a></th>\n<td>11,400</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,060 </td>\n<td>\n<em class="up">\n\t\t\t\t+22.06%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=437730" onclick="clickcr(this, \'spe.clist\', \'437730\', \'2\', event);">삼현</a></th>\n<td>17,350</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,480 </td>\n<td>\n<em class="up">\n\t\t\t\t+16.68%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=082270" onclick="clickcr(this, \'spe.clist\', \'082270\', \'3\', event);">젬백스</a></th>\n<td>56,400</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7,150 </td>\n<td>\n<em class="up">\n\t\t\t\t+14.52%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=067310" onclick="clickcr(this, \'spe.clist\', \'067310\', \'4\', event);">하나마이크론</a></th>\n<td>15,640</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,620 </td>\n<td>\n<em class="up">\n\t\t\t\t+11.55%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr class="up">\n<th scope="row"><a href="/item/main.naver?code=222800" onclick="clickcr(this, \'spe.clist\', \'222800\', \'5\', event);">심텍</a></th>\n<td>27,500</td>\n<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,650 </td>\n<td>\n<em class="up">\n\t\t\t\t+10.66%\n\t\t\t\t</em>\n</td>\n</tr>\n<tr c

In [101]:
# html 문서(url, file, html으로 이루어진 문자)를 read_html()에 입력하면 ->
# html 안에 있는 table 태그를 찾아서 데이터프레임으로 생성
pd.read_html(str(div_data))

C:\Users\student\AppData\Local\Temp\ipykernel_9484\3801918927.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(str(div_data))

[                 종목명   현재가      전일대비      등락률
 0   KODEX 200선물인버스2X  1247     하락 32   -2.50%
 1                이트론     5      하락 5  -50.00%
 2                엔케이  1398      상승 8   +0.58%
 3              씨피시스템  2550    상승 140   +5.81%
 4                 KD   930    상승 163  +21.25%
 5              보성파워텍  4310    상승 355   +8.98%
 6               이아이디    83     하락 19  -18.63%
 7          KODEX 인버스  3412     하락 48   -1.39%
 8               한국선재  4305    상승 385   +9.82%
 9   KODEX 2차전지산업레버리지  1023     상승 23   +2.30%
 10                일승  8170  상승 1,640  +25.11%
 11             대창솔루션   509     상승 18   +3.67%
 12              이화전기   319     상승 24   +8.14%
 13               미투온  6410    상승 610  +10.52%
 14             상상인증권   853    상승 172  +25.26%,
         종목명    현재가      전일대비      등락률
 0    오리엔탈정공  11370    상승 470   +4.31%
 1     원익홀딩스  11400  상승 2,060  +22.06%
 2        삼현  17350  상승 2,480  +16.68%
 3     세진중공업  22200  하락 1,300   -5.53%
 4       네오셈   9120    상승 700   +8.31%
 5    하나마이크론  15640  상승 1,620  +11.55%
 6    미래에셋증권  21550  상승 1,850   +9.39%
 7   두산에너빌리티  62100  상승 1,200   +1.97%
 8   한선엔지니어링   8680    상승 510   +6.24%
 9      삼성전자  71100  상승 1,000   +1.43%
 10    삼성중공업  20950    하락 300   -1.41%
 11  메타바이오메드   6340     하락 60   -0.94%
 12   엘앤씨바이오  50700  상승 1,750   +3.58%
 13    제주반도체  18060    상승 350   +1.98%
 14    에스엔시스  49000  하락 2,200   -4.30%,
         종목명     현재가       전일대비      등락률
 0    동일스틸럭스    3640    상한가 840  +30.00%
 1      셀루메드     802    상한가 185  +29.98%
 2      디에이피    2510    상한가 578  +29.92%
 3     상상인증권     853     상승 172  +25.26%
 4        일승    8170   상승 1,640  +25.11%
 5     원익홀딩스   11400   상승 2,060  +22.06%
 6      금강철강    4920     상승 865  +21.33%
 7        KD     930     상승 163  +21.25%
 8      조선선재  131800  상승 22,700  +20.81%
 9      에이팩트    3480     상승 515  +17.37%
 10       삼현   17360   상승 2,490  +16.75%
 11  한스바이오메드    9550   상승 1,300  +15.76%
 12     동방선기    5780     상승 750  +14.91%
 13      젬백스   56400   상승 7,150  +14.52%
 14      뉴로핏   15070   상승 1,910  +14.51%,
         종목명     현재가       전일대비      등락률
 0     원익홀딩스   11400   상승 2,060  +22.06%
 1        삼현   17350   상승 2,480  +16.68%
 2       젬백스   56400   상승 7,150  +14.52%
 3    하나마이크론   15640   상승 1,620  +11.55%
 4        심텍   27500   상승 2,650  +10.66%
 5    미래에셋증권   21550   상승 1,850   +9.39%
 6   코스메카코리아   65600   상승 5,500   +9.15%
 7      HS효성   60800   상승 4,900   +8.77%
 8       네오셈    9120     상승 700   +8.31%
 9    코리아써키트   14160   상승 1,060   +8.09%
 10      셀비온   23650   상승 1,700   +7.74%
 11       테스   30850   상승 2,150   +7.49%
 12     기가비스   29100   상승 2,000   +7.38%
 13    동진쎄미켐   31350   상승 2,100   +7.18%
 14     키움증권  227500  상승 15,000   +7.06%,
           종목명    현재가       전일대비      등락률
 0         이트론      5      하락 -5  -50.00%
 1        이아이디     83     하락 -19  -18.63%
 2          오아  15020  하락 -3,210  -17.61%
 3        딥노이드   4895    하락 -835  -14.57%
 4     압타머사이언스   1119    하락 -181  -13.92%
 5      테고사이언스  16890  하락 -1,860   -9.92%
 6      대양전기공업  29100  하락 -2,900   -9.06%
 7       그린리소스  10730  하락 -1,020   -8.68%
 8        에프알텍   2510    하락 -225   -8.23%
 9       HJ중공업  26900  하락 -2,300   -7.88%
 10  디에이치엑스컴퍼니    921     하락 -77   -7.72%
 11      STX엔진  44000  하락 -3,550   -7.47%
 12      동성화인텍  31550  하락 -2,500   -7.34%
 13      고바이오랩   6180    하락 -470   -7.07%
 14      헬릭스미스   6470    하락 -480   -6.91%,
        종목명     현재가        전일대비      등락률
 0     딥노이드    4895     하락 -835  -14.57%
 1    그린리소스   10720   하락 -1,030   -8.77%
 2    STX엔진   43950   하락 -3,600   -7.57%
 3    동성화인텍   31500   하락 -2,550   -7.49%
 4     한국카본   33450   하락 -2,100   -5.91%
 5   우리기술투자   10335     하락 -625   -5.70%
 6    세진중공업   22200   하락 -1,300   -5.53%
 7      솔루엠   18310   하락 -1,040   -5.37%
 8    더존비즈온   80700   하락 -4,400   -5.17%
 9     한미약품  290500  하락 -15,500   -5.07%
 10    에스티팜   93500   하락 -4,800   -4.88%
 11   에스엔시스   49000   하락 -2,200   -4.30%
 12      태광   26200   하락 -1,150   -4.20%
 13     메지온   53500   하락 -2,300   -4.12%
 14  데브시스터즈   49050   하락 -2,050   -4.01%,
           종목명      현재가       전일대비     등락률
 0        삼성전자    71050     상승 950  +1.36%
 1      SK하이닉스   287000  상승 10,000  +3.61%
 2    LG에너지솔루션   347000   상승 3,500  +1.02%
 3    삼성바이오로직스  1036000   상승 5,000  +0.48%
 4   한화에어로스페이스   949000   하락 2,000  -0.21%
 5       삼성전자우    58200     상승 700  +1.22%
 6         현대차   220250   상승 1,750  +0.80%
 7     HD현대중공업   501000  하락 10,000  -1.96%
 8        KB금융   109400   상승 2,700  +2.53%
 9          기아   105700     상승 800  +0.76%
 10    두산에너빌리티    62200   상승 1,300  +2.13%
 11       셀트리온   169700     하락 300  -0.18%
 12      NAVER   232500   상승 4,500  +1.97%
 13       한화오션   110100     하락 800  -0.72%
 14       신한지주    65500   상승 1,100  +1.71%,
           종목명      현재가       전일대비     등락률
 0        삼성전자    71100   상승 1,000  +1.43%
 1      SK하이닉스   287000  상승 10,000  +3.61%
 2    LG에너지솔루션   347000   상승 3,500  +1.02%
 3    삼성바이오로직스  1036000   상승 5,000  +0.48%
 4   한화에어로스페이스   947000   하락 4,000  -0.42%
 5         현대차   220000   상승 1,500  +0.69%
 6     HD현대중공업   501000  하락 10,000  -1.96%
 7        KB금융   109300   상승 2,600  +2.44%
 8          기아   105700     상승 800  +0.76%
 9     두산에너빌리티    62100   상승 1,200  +1.97%
 10       셀트리온   169700     하락 300  -0.18%
 11      NAVER   232000   상승 4,000  +1.75%
 12       한화오션   110100     하락 800  -0.72%
 13       신한지주    65500   상승 1,100  +1.71%
 14       삼성생명   158200   상승 7,800  +5.19%]

In [ ]:
df1.to_sql

In [ ]:
# 데이터프레임을 sqlserver에 insert
# !pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\student\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 55.1 MB/s  0:00:00
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.2.4 sqlalchemy-2.0.43

In [106]:
from sqlalchemy import create_engine

In [107]:
# DB server의 정보를 입력
engine = create_engine(
    "mysql+pymysql://root:1234@localhost:3306/multicam"
)

In [ ]:
# to_sql() 매개변수
# name : 테이블의 이름
# con : 데이터베이스의 주소
# index : index 데이터를 포함할것인가( 기본값 : True )
# if_exists : replace(교체), fail(실패 처리, 기본값), append(데이터를 추가)
df1.to_sql(
    name = 'test1234',
    con = engine
)

15

In [110]:
# pymysql을 이용하여 데이터프레임의 정보를 DB에 insert
from database import MyDB

In [111]:
# MyDB class 생성 -> 로컬 피씨
db1 = MyDB()

In [112]:
# 데이터를 대입할 table을 생성
table_query = """
    create table
    if not exists
    `krx_top`(
    `No` int primary key auto_increment,
    `종목명` varchar(50) not null,
    `현재가` int not null,
    `전일대비` varchar(20) not null,
    `등락률` varchar(10) not null
    )
"""
db1.sql_query(table_query)

'Query OK'

In [115]:
df1.loc[0, ].to_list()

['KODEX 200선물인버스2X', '1,247', '하락 32', '-2.50%']

In [116]:
insert_query = """
    insert into
    `krx_top`(
    `종목명`, `현재가`, `전일대비`, `등락률`
    )
    values
    (%s, %s, %s, %s)
"""

In [125]:
df1['현재가'] = df1['현재가'].str.replace(',', '')

In [126]:
db1.sql_query(insert_query, *df1.loc[0, ].to_list())
# 현재가 컬럼의 데이터가 숫자형으로 변환 불가능 -> ','제거

'Query OK'

In [ ]:
# Cursor에 데이터를 대입
for i in range( 0, len(df1) ):
    db1.sql_query(insert_query, *df1.loc[i, ].to_list())

In [128]:
# DB server와 cursor의 동기화
db1.db_commit()

commit 완료
서버와의 연결 종료

In [ ]:
# requests -> 요청
# bs4 -> crawlling
# selenium -> 비동기 통신 방식인 경우, 아니면 requests 사용