In [1]:
import os
from glob import glob
import pandas as pd

In [2]:
# 특정 경로의 파일의 목록을 가져오는 기능
# os 라이브러리
os.listdir('./')

['01_review.ipynb',
 '02_word2vec.ipynb',
 '1-1.여성의류(196).json',
 '1-1.여성의류(197).json',
 '1-1.여성의류(198).json',
 '1-1.여성의류(199).json',
 '1-1.여성의류(200).json',
 '1-1.여성의류(201).json',
 '1-1.여성의류(202).json',
 '1-1.여성의류(203).json',
 '1-1.여성의류(204).json',
 '1-1.여성의류(205).json',
 '1-1.여성의류(206).json',
 '1-1.여성의류(207).json',
 '1-1.여성의류(208).json',
 '1-1.여성의류(209).json']

In [3]:
# glob 이용
# 장점 : 파일의 경로와 파일의 이름을 하나의 리스트로 생성
#       특정 확장자만 선택해서 리스트로 생성이 가능
json_list = glob('./*.json')

In [4]:
# json_list를 이용하여 상위의 5개의 데이터를 하나의 데이터프레임으로 단순 행 결합

# 빈 데이터프레임을 생성
total_df = pd.DataFrame()

for file_path in json_list:
    # print(file_path)
    df = pd.read_json(file_path)
    # print(df)
    # break
    # total_df, df를 단순 행결합을 하여 total_df에 대입
    total_df = pd.concat([total_df, df], axis=0)
total_df.reset_index(drop=True, inplace=True)
total_df

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1024338,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,SNS,패션,여성의류,OO 경량 다운 자켓,513,121,1.0,"[{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인..."
1,1024477,드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드...,SNS,패션,여성의류,OO 아** 구스코트,464,105,1.0,"[{'Aspect': '사이즈', 'SentimentText': '저는 블랙90 사..."
2,1025044,오늘도 정말 춥네요... 롱패딩 찾고 계신 분을 위한 후기 공유합니다. 키 158...,SNS,패션,여성의류,OO 아** 구스코트,314,78,1.0,"[{'Aspect': '사이즈', 'SentimentText': '키 158센티로에..."
3,1025046,이웃님들 오늘도 안녕하신가요? 오늘은 따끈한 신상 패딩 후기 올려봅니다~~ 겨울이...,SNS,패션,여성의류,OO 아** 구스코트,307,74,1.0,"[{'Aspect': '색상', 'SentimentText': '흰색 패딩이 너무나..."
4,1025071,OOO 구스로 소문난 OO의 롱패딩~ 한번 구경 가봐요. 일단 보는 순간 고급스럽...,SNS,패션,여성의류,OO 아** 구스코트,279,68,1.0,"[{'Aspect': '소재', 'SentimentText': ' 일단 보는 순간 ..."
...,...,...,...,...,...,...,...,...,...,...
1418,1038072,안녕하세요~ 점점 추워지는 날씨에 감기 안걸리고 잘 지내고 계신가요? 오늘은 후드 ...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,303,72,1.0,"[{'Aspect': '가격', 'SentimentText': '이번에 적당한 가격..."
1419,1038073,겨울에 패딩만 입고 다니셨나요? 그렇다면 올해는 밍크자켓 하나 구입하시는 거 어떠신...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,296,64,1.0,"[{'Aspect': '디자인', 'SentimentText': '디자인이 너무너무..."
1420,1038074,밍크가 너무 비싸서 못 사고 계셨다면 이번에 겟해보세요! 적당한 밍크 후드 자켓이예...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,273,69,1.0,"[{'Aspect': '가격', 'SentimentText': '가격 대비 가성비 ..."
1421,1038075,플리츠 디자인 좋아하시나요? 저는 치마도 플리츠 치마가 많아요~ 플리츠 디자인 좋아...,SNS,패션,여성의류,OO 클** 후드 하프 자켓,294,64,1.0,"[{'Aspect': '무게', 'SentimentText': ' 이 옷은 무게가 ..."
1422,1038076,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,SNS,패션,여성의류,OO 클** 후드 하프 자켓,317,76,1.0,"[{'Aspect': '사이즈', 'SentimentText': '입어보니 후드가 ..."

In [5]:
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            1423 non-null   int64
 1   RawText          1423 non-null   object
 2   Source           1423 non-null   object
 3   Domain           1423 non-null   object
 4   MainCategory     1423 non-null   object
 5   ProductName      1423 non-null   object
 6   Syllable         1423 non-null   int64
 7   Word             1423 non-null   int64
 8   GeneralPolarity  1418 non-null   float64
 9   Aspects          1423 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 111.3+ KB

In [6]:
pd.concat([pd.read_json(file_path) for file_path in json_list]).info()

<class 'pandas.core.frame.DataFrame'>
Index: 1423 entries, 0 to 99
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            1423 non-null   int64
 1   RawText          1423 non-null   object
 2   Source           1423 non-null   object
 3   Domain           1423 non-null   object
 4   MainCategory     1423 non-null   object
 5   ProductName      1423 non-null   object
 6   Syllable         1423 non-null   int64
 7   Word             1423 non-null   int64
 8   GeneralPolarity  1418 non-null   float64
 9   Aspects          1423 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 122.3+ KB

In [7]:
# Aspects의 데이터를 하나로 합치고 새로운 데이터 프레임을 생성
aspect_df = pd.DataFrame(sum(total_df['Aspects'], []))

In [8]:
aspect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10962 entries, 0 to 10961
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Aspect             10962 non-null  object
 1   SentimentText      10962 non-null  object
 2   SentimentWord      10962 non-null  object
 3   SentimentPolarity  10962 non-null  object
dtypes: object(4)
memory usage: 342.7+ KB

In [9]:
# 데이터의 불균형 문제 확인
aspect_df['SentimentPolarity'].value_counts()

SentimentPolarity
1     9664
-1    1005
0      293
Name: count, dtype: int64

In [10]:
aspect_df.isna().sum()

Aspect               0
SentimentText        0
SentimentWord        0
SentimentPolarity    0
dtype: int64

In [11]:
# 데이터셋에서 문자열의 좌우의 공백을 제거
# 모든 컬럼이 Object형이기 때문에 strip() 바로 사용 가능
aspect_df = aspect_df.map(lambda x : x.strip())

In [12]:
aspect_df.isin(['']).sum()

Aspect               0
SentimentText        0
SentimentWord        0
SentimentPolarity    0
dtype: int64

In [13]:
aspect_df['SentimentText'].value_counts()

SentimentText
가볍고                                           38
따뜻하고                                          25
저렴한 가격에                                       15
가격도 저렴하고                                      12
시원하고                                          11
                                              ..
비싼 밍크코트의 품질을 기대하지는 마시길 바랍니다.                   1
디자인이 너무너무 예쁩니다.                                1
색상도 고급스러워서 마음에 들구요.                            1
바느질도 꼼꼼하게 잘 되어 있어요.                            1
딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서     1
Name: count, Length: 10467, dtype: int64

In [14]:
before_cnt = len(aspect_df)

aspect_df.drop_duplicates('SentimentText', inplace=True)

after_cnt = len(aspect_df)

print(f"제거가 된 행의 개수 {before_cnt - after_cnt}")

제거가 된 행의 개수 495

In [15]:
# 1, 0, -1의 비율을 확인
aspect_df['SentimentPolarity'].value_counts()

SentimentPolarity
1     9183
-1     994
0      290
Name: count, dtype: int64

In [16]:
# 인덱스를 초기화
aspect_df.reset_index(drop=True, inplace=True)

In [17]:
# 토큰화 -> 벡터화
from konlpy.tag import Komoran
from sklearn.feature_extraction.text import TfidfVectorizer

komoran = Komoran()
allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'SL']

def komoran_tokenize(text):
    tokens = []
    for word, pos in komoran.pos(text):
        if (pos in allow_pos) & (len(word) >= 2):
            tokens.append(word)
    return tokens

vectorizer = TfidfVectorizer(
    tokenizer=komoran_tokenize,
    ngram_range=(1,2),
    min_df=3,
    max_df=0.8,
    max_features=30000
)

In [18]:
# 모델 생성
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.multioutput import MultiOutputClassifier

In [19]:
svc = LinearSVC(random_state=42, class_weight='balanced')

multi_model = MultiOutputClassifier(svc)

pipe = Pipeline(
    [
        ('vector', vectorizer),
        ('model', multi_model)
    ]
)

In [20]:
# 계층화 폴드
from sklearn.model_selection import KFold

skfold = KFold(n_splits=3, shuffle=True, random_state=42)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()
aspect_df['Aspect'] = le.fit_transform(aspect_df['Aspect'])
aspect_df['SentimentPolarity'] = aspect_df['SentimentPolarity'].astype('int')

In [23]:
# 독립변수, 종속변수 생성
X = aspect_df['SentimentText'].values
Y = aspect_df[['Aspect', 'SentimentPolarity']].values

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
params = {
    'model__estimator__C' : [1.0, 2.0]
}

grid = GridSearchCV(
    estimator=pipe,
    param_grid=params,
    cv=3,
    scoring='accuracy'
)

In [26]:
grid.fit(X, Y)

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 359, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py", line 117, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [nan nan]
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('vector',
                                        TfidfVectorizer(max_df=0.8,
                                                        max_features=30000,
                                                        min_df=3,
                                                        ngram_range=(1, 2),
                                                        tokenizer=<function komoran_tokenize at 0x0000016E61D61E40>)),
                                       ('model',
                                        MultiOutputClassifier(estimator=LinearSVC(class_weight='balanced',
                                                                                  random_state=42)))]),
             param_grid={'model__estimator__C': [1.0, 2.0]},
             scoring='accuracy')

In [27]:
grid.best_score_

np.float64(nan)

In [28]:
total_df.head(1)

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1024338,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,SNS,패션,여성의류,OO 경량 다운 자켓,513,121,1.0,"[{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인..."

1. total_df에서 RawText 컬럼의 데이터들을 이용하여 Kkma를 이용하여 문장별로 나눠준다.
2. grid의 best_estimator_에서 예측을 실행
3. 실행된 결과 값을 이용하여 데이터프레임(RawText, Aspect_pred, Pola_pred)으로 생성
4. RawText, Aspect_pred 값을 이용하여 그룹화 -> 그룹화 연산에는 평균

In [29]:
best_model = grid.best_estimator_

In [30]:
best_model

Pipeline(steps=[('vector',
                 TfidfVectorizer(max_df=0.8, max_features=30000, min_df=3,
                                 ngram_range=(1, 2),
                                 tokenizer=<function komoran_tokenize at 0x0000016E61D61E40>)),
                ('model',
                 MultiOutputClassifier(estimator=LinearSVC(class_weight='balanced',
                                                           random_state=42)))])

In [31]:
total_df.loc[0, 'RawText']

'안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.  다 함께 go go go~~  제가 입어보고 좋아서 엄마께도 구매해드렸네요. 딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.  엄마도 제가 입은 것 보시더니 탐내셔서  주문해드렸어요. 영하로 내려가는 날씨에는 이것만 입기엔 얇지만 초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요. 색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈때 코디하기도 좋아요. 앞으로 코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요! 맘같아선 색깔별로 쟁이고 싶습니다.  20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~  설명 끝! 좀 도움이 되셨나요? 그러면 좋아요 꾹 눌러 주시고 전 이만 총총총~~ 항상 여러 이웃님들께 감사드립니다. '

In [32]:
from konlpy.tag import Kkma

In [33]:
kkma = Kkma()

In [34]:
for i in range(len(total_df)):
    X = kkma.sentences(total_df.loc[i, 'RawText'])
    pred = best_model.predict(X)
    print(pred)
    print(le.inverse_transform(pred[:, 0]))
    break

[[ 1  1]
 [ 1  1]
 [ 1  1]
 [17  1]
 [ 5  0]
 [17  1]
 [ 1  1]
 [17  1]
 [17  1]
 [ 9 -1]
 [ 5  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]]
['기능' '기능' '기능' '활용성' '디자인' '활용성' '기능' '활용성' '활용성' '색상' '디자인' '기능' '기능'
 '기능' '기능']

In [35]:
kkma = Kkma()
# raw_list에는 리뷰 문단을 문장으로 나눈 리스트를 담기 위한 공간
raw_list = []
# raw_dict 리뷰 문단마다 index를 키 값으로 value는 리뷰 문단
raw_dict = {}
for i in range(len(total_df)):
    # print(kkma.sentences(total_df.loc[i, 'RawText]))
    # break
    raw_list.append(kkma.sentences(total_df.loc[i, 'RawText']))
    print(raw_list)
    break
    # print(total_df.loc[i, 'RawText'])
    # break
    raw_dict[i] = total_df.loc[i, 'RawText']

[['안녕 하세요 이웃님 들 반갑습니다.', '요즘 날씨가 많이 쌀쌀 해졌죠?', '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.', '다 함께 go go go~~ 제가 입어 보고 좋아서 엄마께도 구매해 드렸네요.', '딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해 보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.', '엄마도 제가 입은 것 보시더니 탐내셔서 주문해 드렸어요.', '영하로 내려가는 날씨에는 이것만 입 기엔 얇지만 초겨울 까지는 운동 갈 때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.', '색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈 때 코디하기도 좋아요.', '앞으로 코트를 입거나 할 때 안에 내피로 활용하기도 딱 일 듯요!', '맘 같아선 색깔 별로 쟁이고 싶습니다.', '20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~', '설명 끝! 좀 도움이 되셨나요?', '그러면 좋아요', '꾹 눌러 주시고 전 이만 총총 총~~ 항상 여러 이웃님 들께', '감사 드립니다.']]

In [36]:
X = list()
for i in range(len(total_df)):
    texts = kkma.sentences(total_df.loc[i, 'RawText'])
    # print(texts)
    # break
    X.append(texts)

In [175]:
 
aspect_pred = []
pola_pred = []
for text in X:
    pred = best_model.predict(text)
    print(pred[:, 0])
    print(le.inverse_transform(pred[:, 0]))
    break
    aspect_pred.append(le.inverse_transform(pred[:, 0]))
    pola_pred.append(pred[:, 1])

[ 1  1  1 17  5 17  1 17 17  9  5  1  1  1  1]
['기능' '기능' '기능' '활용성' '디자인' '활용성' '기능' '활용성' '활용성' '색상' '디자인' '기능' '기능'
 '기능' '기능']

In [53]:
pred_df = pd.DataFrame()
aspect_pred = []
pola_pred = []
raw = []
raw_l = []
for i in range(len(total_df)):
    raw.append(total_df.loc[i, 'RawText'])
a = 0
for text in X:
    pred = best_model.predict(text)
    for i in pred[:,0]:
        aspect_pred.append(i)
    for j in pred[:,1]:
        pola_pred.append(j)
    for k in range(len(pred)):
        raw_l.append(raw[a])
        
    a += 1

In [54]:
pola_pred

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(0),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(0),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(0),
 np.int64(-1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(-1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 ...]

In [40]:
raw[1]

'드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드릴게요.   작년부터 눈여겨 보던 OO입니다. 저는 블랙90 사이즈 구매했는데 딱 잘 맞네요. 작년에 비해 저렴하게 구매해서 아주 만족해요. 신제품은 경량패딩으로 되서 3in1기능이더라구요. 경량 패딩 구매 따로 하셔야 하는 분들에겐 신제품 매장에서 확인하시라고 권하고 싶네요. 저는 경량이 있는 관계로 이 제품 구매했는데 슬림핏이라 날씬해 보여요. 하지만 안에 두껍게 입기엔 좀 불편하더라구요. 간편하게 니트 티셔츠에 입기에는 딱입니다. 아직은 초겨울이라 OO를 쭉 입고 있어요. 후기 읽으며 많이 고민했고 도움을 받아서 저도 후기 남겨봅니다.누군가에겐 도움이 되셨기를 바라는 마음에서요.   OO 패딩 좋은 건 다들 아실테고.. 롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시길요..'

In [306]:
len(total_df)

1423

In [288]:
for s in (pred[:, 0]):
    print(s)

8
1
8
1
8
9
16
5
5
6
9

In [284]:
from itertools import chain
aspect_pred = list(chain.from_iterable(aspect_pred))

In [285]:
aspect_pred

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(17),
 np.int64(17),
 np.int64(9),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(15),
 np.int64(8),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(16),
 np.int64(4),
 np.int64(17),
 np.int64(1),
 np.int64(15),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(16),
 np.int64(9),
 np.int64(0),
 np.int64(8),
 np.int64(1),
 np.int64(1),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(9),
 np.int64(8),
 np.int64(7),
 np.int64(7),
 np.int64(14),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(16),
 np.int64(1),
 np.int64(5),
 np.int64(16),
 np.int64(16),
 np.int64(5),
 np.int64(8),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(10),
 np.int64(15),
 np.int64(15),
 np.int64(1),
 np.int64(13),
 np.int64(16),
 np.int64(5),
 np.int64(1),
 np.int64(5),
 np.int64(5),
 np.int64(17),
 np.int64(4),
 np.int64(1),
 np.int64(4),
 np.int64(1),
 np.int64(4),
 np.int64(8),
 np.int64(4),
 np.int64(9),
 np.int64(17),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(13),
 np.int64(13),
 np.int64(1),
 np.int64(17),
 np.int64(7),
 np.int64(8),
 np.int64(13),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(1),
 np.int64(1),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(1),
 np.int64(9),
 np.int64(16),
 np.int64(5),
 np.int64(17),
 np.int64(16),
 np.int64(9),
 np.int64(13),
 np.int64(7),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(17),
 np.int64(10),
 np.int64(7),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(13),
 np.int64(1),
 np.int64(8),
 np.int64(1),
 np.int64(15),
 np.int64(8),
 np.int64(8),
 np.int64(10),
 np.int64(1),
 np.int64(13),
 np.int64(5),
 np.int64(4),
 np.int64(17),
 np.int64(9),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(9),
 np.int64(1),
 np.int64(13),
 np.int64(16),
 np.int64(1),
 np.int64(5),
 np.int64(5),
 np.int64(0),
 np.int64(17),
 np.int64(17),
 np.int64(17),
 np.int64(2),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(0),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(16),
 np.int64(2),
 np.int64(8),
 np.int64(12),
 np.int64(15),
 np.int64(12),
 np.int64(17),
 np.int64(9),
 np.int64(2),
 np.int64(17),
 np.int64(1),
 np.int64(8),
 np.int64(2),
 np.int64(9),
 np.int64(17),
 np.int64(8),
 np.int64(14),
 np.int64(1),
 np.int64(0),
 np.int64(17),
 np.int64(15),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(10),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(14),
 np.int64(6),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(15),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(9),
 np.int64(10),
 np.int64(5),
 np.int64(8),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(8),
 np.int64(8),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(10),
 np.int64(10),
 np.int64(15),
 np.int64(1),
 np.int64(9),
 np.int64(17),
 np.int64(9),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(4),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(17),
 np.int64(9),
 np.int64(16),
 np.int64(17),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(16),
 np.int64(16),
 np.int64(5),
 np.int64(2),
 np.int64(2),
 np.int64(9),
 np.int64(9),
 np.int64(8),
 np.int64(15),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(15),
 np.int64(17),
 np.int64(1),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(6),
 np.int64(8),
 np.int64(17),
 np.int64(1),
 np.int64(8),
 np.int64(8),
 np.int64(1),
 np.int64(5),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(8),
 np.int64(12),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(12),
 np.int64(17),
 np.int64(9),
 np.int64(16),
 np.int64(0),
 np.int64(9),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(5),
 np.int64(7),
 np.int64(11),
 np.int64(1),
 np.int64(9),
 np.int64(9),
 np.int64(0),
 np.int64(12),
 np.int64(2),
 np.int64(8),
 np.int64(8),
 np.int64(17),
 np.int64(14),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(7),
 np.int64(0),
 np.int64(1),
 np.int64(15),
 np.int64(5),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(6),
 np.int64(8),
 np.int64(0),
 np.int64(16),
 np.int64(17),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(8),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(17),
 np.int64(0),
 np.int64(16),
 np.int64(8),
 np.int64(10),
 np.int64(15),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(8),
 np.int64(8),
 np.int64(15),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(12),
 np.int64(9),
 np.int64(8),
 np.int64(2),
 np.int64(0),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(7),
 np.int64(5),
 np.int64(4),
 np.int64(4),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(2),
 np.int64(1),
 np.int64(0),
 np.int64(7),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(6),
 np.int64(2),
 np.int64(9),
 np.int64(0),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(0),
 np.int64(1),
 np.int64(9),
 np.int64(17),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(15),
 np.int64(4),
 np.int64(5),
 np.int64(0),
 np.int64(1),
 np.int64(5),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(14),
 np.int64(8),
 np.int64(17),
 np.int64(0),
 np.int64(5),
 np.int64(2),
 np.int64(17),
 np.int64(1),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(15),
 np.int64(9),
 np.int64(10),
 np.int64(6),
 np.int64(14),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(9),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(16),
 np.int64(1),
 np.int64(12),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(5),
 np.int64(10),
 np.int64(16),
 np.int64(10),
 np.int64(16),
 np.int64(8),
 np.int64(17),
 np.int64(16),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(14),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(5),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(12),
 np.int64(1),
 np.int64(17),
 np.int64(10),
 np.int64(14),
 np.int64(10),
 np.int64(7),
 np.int64(9),
 np.int64(10),
 np.int64(0),
 np.int64(16),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(17),
 np.int64(16),
 np.int64(12),
 np.int64(7),
 np.int64(10),
 np.int64(5),
 np.int64(0),
 np.int64(5),
 np.int64(5),
 np.int64(2),
 np.int64(1),
 np.int64(17),
 np.int64(9),
 np.int64(10),
 np.int64(17),
 np.int64(9),
 np.int64(17),
 np.int64(10),
 np.int64(12),
 np.int64(15),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(16),
 np.int64(8),
 np.int64(10),
 np.int64(10),
 np.int64(1),
 np.int64(13),
 np.int64(8),
 np.int64(1),
 np.int64(12),
 np.int64(0),
 np.int64(17),
 np.int64(15),
 np.int64(10),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(17),
 np.int64(10),
 np.int64(1),
 np.int64(10),
 np.int64(5),
 np.int64(11),
 np.int64(10),
 np.int64(10),
 np.int64(9),
 np.int64(5),
 np.int64(8),
 np.int64(2),
 np.int64(5),
 np.int64(7),
 np.int64(16),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(17),
 np.int64(17),
 np.int64(16),
 np.int64(12),
 np.int64(0),
 np.int64(5),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(16),
 np.int64(5),
 np.int64(17),
 np.int64(12),
 np.int64(16),
 np.int64(1),
 np.int64(16),
 np.int64(9),
 np.int64(5),
 np.int64(16),
 np.int64(5),
 np.int64(12),
 np.int64(10),
 np.int64(13),
 np.int64(17),
 np.int64(1),
 np.int64(13),
 np.int64(12),
 np.int64(10),
 np.int64(13),
 np.int64(5),
 np.int64(10),
 np.int64(1),
 np.int64(17),
 np.int64(17),
 np.int64(5),
 np.int64(5),
 np.int64(2),
 np.int64(1),
 np.int64(5),
 np.int64(15),
 np.int64(17),
 np.int64(17),
 np.int64(4),
 np.int64(5),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(17),
 np.int64(0),
 np.int64(1),
 np.int64(5),
 np.int64(16),
 np.int64(13),
 np.int64(9),
 np.int64(9),
 np.int64(13),
 np.int64(14),
 np.int64(1),
 np.int64(12),
 np.int64(15),
 np.int64(13),
 np.int64(17),
 np.int64(14),
 np.int64(12),
 np.int64(15),
 np.int64(17),
 np.int64(17),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(17),
 np.int64(17),
 np.int64(17),
 np.int64(17),
 np.int64(10),
 np.int64(14),
 np.int64(11),
 np.int64(5),
 np.int64(17),
 np.int64(5),
 np.int64(16),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(13),
 np.int64(9),
 np.int64(12),
 np.int64(12),
 np.int64(9),
 np.int64(12),
 np.int64(12),
 np.int64(5),
 np.int64(5),
 np.int64(13),
 np.int64(17),
 np.int64(17),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(1),
 np.int64(9),
 np.int64(1),
 np.int64(17),
 np.int64(16),
 np.int64(5),
 np.int64(13),
 np.int64(1),
 np.int64(17),
 np.int64(11),
 np.int64(16),
 np.int64(5),
 np.int64(6),
 np.int64(8),
 np.int64(17),
 np.int64(17),
 np.int64(12),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(5),
 np.int64(13),
 np.int64(17),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(5),
 np.int64(10),
 np.int64(11),
 np.int64(17),
 np.int64(0),
 np.int64(12),
 np.int64(17),
 np.int64(6),
 np.int64(6),
 np.int64(1),
 np.int64(16),
 np.int64(15),
 np.int64(1),
 np.int64(12),
 np.int64(5),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(13),
 np.int64(13),
 np.int64(0),
 np.int64(12),
 np.int64(12),
 np.int64(5),
 np.int64(12),
 np.int64(17),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(12),
 np.int64(17),
 np.int64(13),
 np.int64(11),
 np.int64(17),
 np.int64(17),
 np.int64(0),
 np.int64(14),
 np.int64(1),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(12),
 np.int64(12),
 np.int64(9),
 np.int64(10),
 np.int64(16),
 np.int64(5),
 np.int64(0),
 np.int64(17),
 np.int64(5),
 np.int64(5),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(1),
 np.int64(6),
 np.int64(17),
 np.int64(5),
 np.int64(13),
 np.int64(12),
 np.int64(17),
 np.int64(5),
 np.int64(13),
 np.int64(2),
 np.int64(1),
 np.int64(17),
 np.int64(0),
 np.int64(1),
 np.int64(13),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(1),
 np.int64(10),
 np.int64(9),
 np.int64(8),
 np.int64(8),
 np.int64(2),
 np.int64(13),
 np.int64(17),
 np.int64(4),
 np.int64(5),
 np.int64(12),
 np.int64(8),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(1),
 np.int64(5),
 np.int64(1),
 np.int64(5),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(5),
 np.int64(17),
 np.int64(15),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(0),
 np.int64(14),
 np.int64(13),
 np.int64(16),
 np.int64(10),
 np.int64(1),
 np.int64(5),
 np.int64(16),
 np.int64(17),
 np.int64(2),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(7),
 np.int64(1),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(17),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(5),
 np.int64(16),
 np.int64(10),
 np.int64(9),
 np.int64(0),
 np.int64(16),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(5),
 np.int64(16),
 np.int64(16),
 np.int64(9),
 np.int64(1),
 np.int64(8),
 np.int64(4),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(17),
 np.int64(4),
 np.int64(8),
 np.int64(6),
 np.int64(5),
 np.int64(12),
 np.int64(16),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(15),
 np.int64(13),
 np.int64(10),
 np.int64(8),
 np.int64(0),
 np.int64(5),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(8),
 np.int64(8),
 np.int64(16),
 np.int64(5),
 np.int64(2),
 np.int64(1),
 np.int64(16),
 np.int64(5),
 np.int64(12),
 np.int64(17),
 np.int64(11),
 np.int64(14),
 np.int64(6),
 np.int64(10),
 np.int64(0),
 np.int64(1),
 np.int64(8),
 np.int64(0),
 np.int64(13),
 np.int64(2),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(0),
 np.int64(7),
 np.int64(7),
 np.int64(5),
 np.int64(7),
 np.int64(8),
 np.int64(14),
 np.int64(8),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(1),
 np.int64(10),
 np.int64(16),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(8),
 np.int64(10),
 np.int64(1),
 np.int64(17),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(15),
 np.int64(9),
 np.int64(9),
 np.int64(4),
 np.int64(1),
 np.int64(5),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(13),
 np.int64(13),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(1),
 np.int64(2),
 np.int64(14),
 np.int64(5),
 np.int64(16),
 np.int64(15),
 np.int64(1),
 np.int64(16),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(16),
 np.int64(1),
 np.int64(8),
 np.int64(10),
 np.int64(10),
 np.int64(17),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(10),
 np.int64(11),
 np.int64(1),
 np.int64(16),
 np.int64(16),
 np.int64(10),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(12),
 np.int64(16),
 np.int64(8),
 np.int64(16),
 np.int64(10),
 np.int64(16),
 np.int64(8),
 np.int64(4),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(14),
 np.int64(14),
 np.int64(13),
 np.int64(10),
 np.int64(9),
 np.int64(13),
 ...]

In [326]:
print(len(aspect_pred))
print(len(pola_pred))
print(len(raw))

12883
12883
1423

In [313]:
len(raw)

1423

In [55]:
pred_df = pd.DataFrame(
    {
        'RawText' : raw_l,
        'Aspect_pred' : aspect_pred,
        'Pola_pred' : pola_pred
    }
)

pred_df

,RawText,Aspect_pred,Pola_pred
0,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
1,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
2,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
3,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,17,1
4,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,5,0
...,...,...,...
12878,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,16,-1
12879,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,5,1
12880,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,5,1
12881,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,6,1
12882,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,9,1

In [50]:
pred_df

,RawText,Aspect_pred,Pola_pred
0,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
1,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
2,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,1,1
3,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,17,1
4,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,5,1
...,...,...,...
12878,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,16,9
12879,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,5,9
12880,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,5,9
12881,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,6,9
12882,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,9,9

In [56]:
ddf = pred_df.groupby(['RawText','Aspect_pred']).mean()

In [57]:
ddf

                                                                Pola_pred
RawText                                            Aspect_pred
130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 믿... 0                  1.0
                                                   1                  0.0
                                                   8                 -0.5
                                                   10                 1.0
                                                   13                 1.0
...                                                                   ...
히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요. ... 1                  1.0
                                                   5                  1.0
                                                   13                 1.0
                                                   16                 1.0
                                                   17                 1.0

[8362 rows x 1 columns]

In [203]:
X

[['안녕 하세요 이웃님 들 반갑습니다.',
  '요즘 날씨가 많이 쌀쌀 해졌죠?',
  '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.',
  '다 함께 go go go~~ 제가 입어 보고 좋아서 엄마께도 구매해 드렸네요.',
  '딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해 보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.',
  '엄마도 제가 입은 것 보시더니 탐내셔서 주문해 드렸어요.',
  '영하로 내려가는 날씨에는 이것만 입 기엔 얇지만 초겨울 까지는 운동 갈 때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.',
  '색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈 때 코디하기도 좋아요.',
  '앞으로 코트를 입거나 할 때 안에 내피로 활용하기도 딱 일 듯요!',
  '맘 같아선 색깔 별로 쟁이고 싶습니다.',
  '20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~',
  '설명 끝! 좀 도움이 되셨나요?',
  '그러면 좋아요',
  '꾹 눌러 주시고 전 이만 총총 총~~ 항상 여러 이웃님 들께',
  '감사 드립니다.'],
 ['드디어 겨울이 찾아왔네요.',
  '이제부터 슬슬 겨울 패딩 장만하셔야지요?',
  '패딩 소개해 드릴게요.',
  '작년부터 눈여겨 보던',
  'OO 입니다.',
  '저는 블랙 90 사이즈 구매했는데 딱 잘 맞네요.',
  '작년에 비해 저렴하게 구매해서 아주 만족해요.',
  '신제품은 경량 패딩으로 되 서 3in1 기능이더라',
  '구요.',
  '경량 패딩 구매 따로 하셔야 하는 분들에 겐 신제품 매장에서 확인하시라 고 권하고 싶네요.',
  '저는 경량이 있는 관계로 이 제품 구매했는데 슬림 핏이라 날씬해 보여요.',
  '하지만 안에 두껍게 입 기엔 좀 불편하더라구요.',
  '간편하게 니트 티셔츠에 입기에는 딱입니다.',
  '아직은 초겨울이라 OO를 쭉 입고 있어요.',
  '후기 읽으며 많이 고민했고 도움을 받아서 저도 후기 남겨 봅니다.',
  '누군가에 겐 도움이 되셨기를 바라는 마음에서요. OO 패딩 좋은 건 다들 아실 테고.. 롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시 길 요..'],
 ['오늘도 정말 춥네요...',
  '롱 패딩 찾고 계신 분을 위한 후기 공유합니다.',
  '키 158 센티로에 48 키로 마른 체형인데 90 사이즈가 여유가 별로 없이 딱 맞습니다.',
  '저는 딱 맞게 입기를 좋아해서 아주 만족해요.',
  '와 인색이 정말 특이하게 다운된 색인데 정말 고급스러워서 더욱 마음에 듭니다.',
  '가격도 아주 저렴한 편이라 부담 없이 사서 입게 되었답니다.',
  '핏 되게 나온 옷이라 넉넉하게 입기를 좋아하시는 분은 한 사이즈 올려 입으셔도 좋을 것 같아요.',
  '저는 이 패딩으로 올겨울 아주 따뜻하게 잘 지내게 될 것 같습니다.',
  '새로운 패딩 장만하고 올 겨울 따스하게 보내시길 요...'],
 ['이웃님 들 오늘도 안녕하신가요?',
  '오늘은 따끈한 신상 패딩 후기 올려봅니다~~',
  '겨울이 얼마 남지 않아 고민하다가 눈에 딱 띄는 패딩이 있어 구매했어요.',
  '저는 유난히 흰색을 좋아하는데 이 흰색 패딩이 너무나 고급진 느낌이라 만족스럽습니다.',
  '평소 55 입는데 이 옷도 90 사이즈가 아주 잘 맞네요.',
  '소재가 구김도 없어 좋고 엄청 가벼워서 입은 것 같지도 않은 느낌이 아주 좋아요.',
  '전 요즘은 무거운 패딩은 아주 질색이랍니다.',
  '입었을 때 포근하게 감싸는 느낌도 엄청 만족스럽네요.',
  '강추입니다.',
  '백색의 아름다움을 추구하는 후기~~ 다 들 공감하시지요?',
  'ㅎㅎ'],
 ['OOO 구스로 소문난 OO의 롱 패딩~ 한 번 구경 가봐요.',
  '일단 보는 순간 고급스럽다는 생각이 탁 드는 소재였습니다.',
  '입어 보니 핏이 너무도 예뻐요.',
  '입는 순간 느끼는 따스함은 어떤 패딩보다 훌륭했습니다.',
  '보통의 패딩같이 스포 티한 디자인이 아니라서 회사에 입고 다니기에도 아주 좋을 것 같습니다.',
  'OOO 모델로 텔레비전 광고를 많이 봐서 이 옷을 입으면 나도 그녀처럼 아름다운 여인이 될 것 같은 환상을 갖게 하는 패딩이네요.',
  '우리 모두를 모델로 만들어 줄 패딩 ㅎㅎ ~~ 이웃님 들 생각은 어떠신지요?'],
 ['심플한 디자인에 따뜻한 기능성 패딩을 찾으시는 분들께 소개합니다.',
  '보통 95 사이즈 입는데 후기에 작다는 평이 있어서 100으로 주문했더니 잘 맞네요.',
  '입었을 때 따뜻함이 정말 좋습니다.',
  '혹시 눈이 올 때 방수 기능이 있으면 했는데 정말 눈 맞아도 젖지 않아 참 마음에 드는 패딩이네요.',
  '바람도 잘 들어오지 않으니 보온 효과도 좋은 거 같고요.',
  '저는 개인적으로 롱한 패딩을 좋아하는데 아주 딱 맘에 드는 길이입니다.',
  '아주 오래도록 봉투에 쌓여 있어서 그런지 지금은 털이 죽어 있네요.',
  '시간이 지나면 살아나겠지만 기대했던 것만큼 풍성하지는 않아서 그게 좀 아쉬워요.',
  '그래도 가격 대비 품질은 굿입니다.',
  '후기 잘 읽어 보셨지요?',
  '롱 패딩 찾으시는 분들께 참고가 되기를 바라는 마음에서 후기 공유했습니다 .'],
 ['편안하면서도 뭔 가 좀 색다른 티셔츠가 없을까',
  '검색하던 중 뜻밖에 달달 하고 러 블 리한 핏의 맨투맨을 발견했어요.',
  '러 블 리하게 퍼프 소매로 소매 셔링 디테일을 더해 볼 룸 감 있고 또 더 사랑스럽게 보이는 스타일이더라',
  '구요.',
  '바로 퍼프 맨투맨으로 샀는데 할랑한 루즈 핏의 러 블 리한 맨투맨 제가 딱 찾고 있던 스타일이라 너무 좋았습니다.',
  '엉덩이는 가려 주고 다리는 더 길어 보이게 해 주는 최상의 디자인인 것 같아요.',
  '레깅스와 함께 매칭하면 더욱 더 잘 어울리더라구요.',
  '너무 두껍지도 않고 얇지도 않은 적당한 두께 감이라 좋고 원단도 부드러워서 자꾸 손이 가서 데일리로 입기에 딱 좋은 옷인 것 같습니다.'],
 ['오늘 따뜻한 커피 한 잔 생각나는 날씨네요.',
  '향긋 한 커피 한 잔 하시면서 오늘 소식 시작할까요?',
  '그럼 Go Go Go~~~ 요즘 날씨가 엄청 추웠다 또 괜찮았다 트렌치 코트를 입자니 춥고 코트를 입자니 덥고 그렇더라구요.',
  '그래서 가볍게 걸칠 경량 패딩 알아보다가 OOOO 퀼팅 경량 다운 자켓이 유명하길래 저도 사 봤어요.',
  '워낙 넉넉하게 나왔다는 후기가 많아서 사이즈 고민을 많이 했는데 고민하는 사이에 s가 품절되어서 어쩔 수 없이 xs을 샀어요.',
  '코트 안에도 입을 생각이고 추워 지기 전엔 안에 목 티나 적당히 두께 있는 옷 입고 외투로도 걸칠 생각이어서 받자마자 입어 봤는데 사이즈가 딱 맘에 듭니다!',
  '얼마나 차이가 있을지는 모르겠지만 s로 샀으면 컷을 것 같네요.',
  '가볍고 웬만한 옷엔 다 어울려서 요즘 매일 입어요.',
  '타 브랜드 제품과 비교했을 때 가격 재질 충전재 모두 탁월하고 착용시 가볍고 따뜻합니다.',
  '핏도 예쁘고 디자인도 깔끔하고 가 성비 진짜 좋습니다!!',
  '이런 커피가 다 식었네요.',
  '오늘도 제 소식이 도움이 됐다면 좋아요',
  '꾹~ 부탁 드리며 커피 향처럼 향긋 한 하루가 되 시 길 바 래요~~'],
 ['겨울이 다가오는 요즘 여러분들의 헛헛한 마음을 채울 따끈한 정보 대령했사옵니다~~',
  '오늘 소개해 드릴 아이템은 OOOO 퀄팅 경량 다운 자켓 인데요.',
  '착용 감 좋고 너무 가볍습니다.',
  '크게 나온 거 같아서 S 구매했는데 ( 평소 사이즈는 M) 조금 넉넉하게 잘 맞는 거 같아요.',
  '움직임이 둔하지 않고 활동하는데 크게 무리가 없어요.',
  '다른 옷들 중에 착용 시 습한 느낌이 드는 것도 있는데 재질이 좋아서 그런지 상쾌한 느낌입니다.',
  '가격이 비싼 편이 아닌가 생각이 들었는데 입는 순간 다른 제품에 비해서 퀄리티가 좋아서 가격이 비싼 느낌이 안 들었습니다.',
  '퀼팅이 조잡스럽지 않아서 타제품에 비해 고급스러워요.',
  '컬러에 대해 말씀 드리자면 이 옷은 단연 화이트 죠. 색감이 밝고 깨끗해서 모든 옷에 잘 어울립니다.',
  '화이트야 말로 이 제품의 시 그니 처 컬러입니다.',
  '지금 날씨에는 사무실에서 이거 하나만 입고 있어도 따뜻하네요',
  '지금까지 제가 느꼈던 부분을 솔직하게 알려 드렸습니다.',
  '오늘 저의 소식이 도움이 됐다면 좋아요',
  '잊지 마 세요~~'],
 ['안녕하세요?',
  '우리 이웃님 들, 동물 사랑에 패딩에 손이 잘 안 가셨던',
  '우리 이웃님 들께',
  '희소식 가져왔어요!!!',
  '바로 가 보실까요?',
  'OOOO 퀼팅 다운 자켓은 수조류의 사육과정부터 우 모의 채취 가공 봉제 등 복지 프로그램을 준수했다는 공인 인증까지 안심하고 입을 수 있는 제품이에요.',
  '전에 다운 패딩을 위해 오리털 뽑는 영상 봤는데 정말 학대에 가깝더라고요.',
  '그래서 패딩류 지양했는데 이젠 마음 놓고 구매할 수 있어요.',
  '디자인은 예쁘고 퀄리티 좋고 봉 제 깔끔하고 따뜻해요.',
  '실용적인 면에서는 그 어떤 아이템도 따라갈 수가 없어서 늦가을부터 잘 입고 있습니다.',
  '왜 그렇게 몇 년 전부터 입소문이 나고 베스트셀러인지 입어 보니 알겠더라구요.',
  '이 옷은 단연 화이트 이어야 하는데.... 평 상시 아이 옷만으로도 감당이 안되는지라 차선책인 그레이 구매했네요.',
  '색상이 튀거나 확 예쁘다는 느낌은 없으나 착용감 편안하고 따스하고 어디에 나 잘 어울려요.',
  '무엇보다 놀랍도록 가볍고 따뜻하네요',
  '오늘은 여기까지~~ 좀 도움이 되셨나요?',
  '그러면 좋아요',
  '잊지 마세요!',
  '여러분의 지지와 격려가 제 겐 큰 힘이 됩니다.'],
 ['쌀쌀 해진 요즘 휘 뚜 르 마 뚜 르 걸칠 수 있는 옷 어디 없나',
  '하다가 발견한 제 인생 퀼팅 경량 다운 자켓!! 자 만나러 가실까요~~ 재질도 좋고 충전 재도 구스인데 이 가격이라니!!',
  '놀라도록 혜 자스럽습니다.',
  '가볍고 따뜻하고 디자인도 깔끔합니다.',
  '핏도 예뻐서 치마나 바지에 둘 다 잘 어울려요.',
  '다른 브랜드에서도 비슷한 옷들을 많이 볼 수 있는데 재질도 충전재도 좋고 무엇보다 마음에 들었던 점은 동물복지 시스템 적용해서 다운 솜털 채취한 게 마음에 듭니다!',
  '다른 경량 패딩과 비교했을 때 디테일에서 차이가 있고 무게 감도 확실히 달라요.',
  '가벼우면서 스타일까지 살아 있어요.',
  '퀼팅도 편안해 보이고 간격도 딱 알맞게 봉제되어 있어 고급스럽고 간 절기 아우터로 너무 편 해서 데일리로 늘 착용하는 제 인생 아이템입니다.',
  '한 겨울에는 못 입을 거 같지만 가벼운 옷을 입고 그 위에 살짝 걸치고 코트까지 입으면 정말 따뜻하게 겨울을 보낼 수 있을 거 같아요.',
  '제 소식 어떠셨나요?',
  '도움이 되셨다면 좋아요',
  '꾹 눌러 주시고 오늘도 좋은 하루 행복한 하루 되시길 진심으로 기원합니다.',
  '항상 감사 드려요~~'],
 ['치마나 원피스를 좋아하는 저는, 추워 진다고 해서 원피스를 포기할 수는 없죠',
  'ㅎㅎ 여러분도 저와 같지 않나요?',
  '오늘도 제 맘에 쏙 드는 원피스를 소개해 드릴게요.',
  '제가 S 사이즈를 입는데, 편안하게 입을 수 있는 사이즈네요.',
  '55-66을 걸쳐서 중간 사이즈를 입는데, 이번 S 사이즈 선택은 정확했네요.',
  '상의 하의 소재가 어울리면서 다른 소재라',
  '좋았어요.',
  '니트 부분은 촘촘 해서 입었을 때 착용감이 좋구요.',
  '스커트 부분은 플레어 라 걸을 때 여성스러워 보여요.',
  '스커트의 천이 답답하지 않고 세련된 느낌이 들어요.',
  '두 벌을 레이어 드한 느낌으로 더 스타일 리 쉬하구요.',
  '블랙이라 신경 쓰지 않고 더 편하게 입을 수 있어요.',
  '어떠셨나요?',
  '여러분도 저처럼 추워 질수록 더 예쁘고 분위기 있게 차려입고 멋진 가을을 보내세요~'],
 ['계절이 바뀌는 요즘, 약속에 입고 나갈 옷을 찾고 있나요.',
  '데이트룩은 물론, 데일리룩으로도 입기 좋은 원피스를 소개 해봅니다.',
  '가장 마음에 드는 부분인 브이넥 디자인은 세련되면서도 여성스러워요.',
  '그리고 자칫 단순해 보일 수 있는 옷이 상의 하의 부분이 다른 소재 라 더 멋스러움을 연출해 줘요.',
  '4개의 단추는 포인트를 줘서 더 스타일을 빛 내주구요.',
  '색도 어두운 블랙 계열이면서도 밝게 보여 고급스러워요.',
  '요즘 날씨에도 하나만 입기 딱 좋겠어요.',
  '제가 키가 작은 편인데도 길이 감은 너무 길지 않고 딱 좋네요',
  '오히려 단정해 보여요',
  '여러분들의 멋스러운 가을 쇼핑에 도움되시길 바랄게요~'],
 ['기본 스타일의 롱 니트라고 생각하고 구입을 했는데 다양한 스타일로 연출이 가능한 티셔츠를 득 템 해서 소개를 하려고 합니다.',
  '가격도 저렴하고 디자인도 제가 원하던 스탈이라 세 가지 색상을 다 질렀습니다.',
  '배송을 받고 다 구매한 것이 이렇게 만족스러웠던 적은 없었던 것 같아요.',
  '가로로 길게 립라인으로 된 넥이 탄탄하게 잘 짜여 있어서 오프 솔 더 로도 활용이 가능해서 좋아요.',
  '하나의 니트로 기분과 상황에 따라 때론 청순하게 때론 섹 쉬하게 입을 수 있어 좋은 것 같아요.',
  '간만의 득 템으로 기분 전환이 된 것 같아 너무 만족스럽습니다.'],
 ['이렇게 달달 한 맨투맨을 보신적이 있나요?',
  '전 이 맨투맨을 보는 순간 달달 함에 이끌려 나도 모르게 주문을 하고 있더라구요.',
  '디자인이 러 블 리한 이 맨투맨, 사랑스러움보다 더 놀라운 것은 너무나도 저렴한 가격이었습니다.',
  '소매와 밑단에 풍성하게 주름을 넣어서 사랑스럽기가 이루 말로 다 할 수 가 없는데요. 길이까지 길어서 엉덩이는 덮어 주고 앞라인은 또 살짝 짧아서 다리가 엄청 길어 보이게 하는 효과까지 있어서 너무 맘에 듭니다.',
  '이렇게 저렴한 가격에 이렇게 풍성한 주름이 있는 사랑스러운 맨투맨을 구입할 수 있으리라',
  '정말 상상도 못했었네요.'],
 ['저는 레깅스를 즐겨 입어요.',
  '근데 요즘 살이 좀 찌는 것 같아 레깅스 좀 편하게 입기 위해 엉덩이를 덮을 수 있는 길이 감의 티셔츠를 찾고 있었는데 굿 템을 발견했어요.',
  '바로 루즈 핏 맨투맨입니다.',
  '앞 뒤의 길이가 언 발란스로 되어 엉덩이를 푹 덮어 주는 길이라 제 맘에 쏙 들었습니다.',
  '그리고 넉넉한 사이즈 라 조금씩 오른 제 살들을 잘 감쳐 줘서 더 좋았고 다리까지 길어 보이게 해 주니 이게 왠 일인가 했네요~',
  '무엇보다 가격이 저렴한 데 세 가지 색상을 다 주니 올가을은 다른 옷이 필요 없을 듯하네요.',
  '살이 쪄서 속상했는데 굿 템을 발견해서 마음이 행복 해졌어요.',
  '올가을은 또 이렇게 잘 보낼 수 있게 되어 행복합니다.'],
 ['오늘은 어떤 옷과 입어도, 언제 입어도 깔끔하고 예쁜 바지 하나 소개할게요.',
  '색상이 무난해서 다 좋아요.',
  '발목 위로 살짝 올라가는 기장으로 키도 커 보이고 날씬해 보입니다.',
  '코디할 때도 어떤 상의랑 입어도 잘 어울리네요.',
  '너무 얇지도 않아서 한 여름 되기 전 까지는 문제 없을 것 같아요.',
  '흠을 하나 잡자면 그레 이색은 약간 색이 바랜 것처럼 보여서 좀 그래요. 나머지는 다 좋습니다.',
  '오는 주말에는 이런 바지에 운동화 신고 북촌에 나들이 가는 건 어 떠세요'],
 ['올해는 아이보리나 화이트 색상이 겨울 컬러를 주도한다고 하더군요.',
  '이런 코트 어 떠세요?',
  '정 사이즈로 주문했는데 입어 보니 품이 너무 넓네요.',
  '겉감은 부들부들 좋습니다.',
  '울이 60퍼센트밖에 안 돼서 한 겨울에는 추울 것 같아요.',
  '가성 비는 충분히 좋습니다.',
  '안에 어두운 목 티 입고 아래 스커트랑 받쳐 입으면 겨울 멋쟁이 될 것 같네요.',
  '그런 데 소매나 밑단 같은 데 실밥 처리는 좀 신경 써서 보내주세요.',
  '늘 무채색 옷만 입지 마시고 가끔 씩은 이런 밝은 색 톤으로 이미지 메이킹 다시 해보는 건 어떠신가요??'],
 ['깊어 가는 가을, 이제 슬슬 겨울옷을 꺼내야 할 것 같아요.',
  '요즘 입기 좋은 모직 코드 하나 보여 드릴게요.',
  '그냥 유행 타지 않은 베이 직한 디자인입니다.',
  '저는 개인적으로 이런 디자인 맘에 들어요.',
  '사이즈도 넉넉해서 안에 얇은 패딩 조 키 입고 입으면 딱 일 것 같아요.',
  '옷감 재질이 적당히 부드러워서 더 좋네요.',
  '올 겨울 멋스럽게 입고 다녀야겠어요. 감사합니다.',
  '그 동안 수십년 사 입은 제 옷은 다 어디로 갔을까요?',
  '계절과 함께 다 사라져 버리나 봐요.'],
 ['날씨가 갑자기 추워 졌죠?',
  '올 겨울 따뜻하고 멋스럽게 입을 만한 모직 코트 한번 둘러봤네요.',
  '소개해 드릴게요.',
  '가성 비 완전 좋습니다.',
  '촉감이 많이 부드럽지는 않지만 입으니 따뜻하고 너무 마음에 듭니다.',
  '마감도 잘 되어 있어요.',
  '밝은 카 멜 이라',
  '쫌 그랬는대 막상 입 어보 닌 나쁘지 않네요.',
  '올 겨울 출퇴근할 때 멋스럽게 잘 입을 것 같아요.',
  '추천합니다.',
  '패팅이 따뜻 함의 지존이라 아무리 해도 겨울 멋 내기에는 모직 코트만한 게 없죠?',
  '끝까지 읽어 주셔서 감사해요.'],
 ['올겨울 많이 춥다네요.',
  '이웃님 들 월동 준비 하셨나요?',
  'ㅎㅎ 저는 겨울 나기의 가장 큰 숙제인 김장을 끝내고 나서 겨울 옷을 정리 중입니다.',
  '올겨울은 롱패딩을 입어 볼까 하고 주문한 옷 후기 적어 봅니다.',
  '^^ 일 다 되게 따뜻합니다.',
  '무겁지 않고 색도 예뻐서 맘에 듭니다.',
  '다만 후드 퍼가 풍성하지 않아서 아쉽습니다.',
  '일자 디자인의 롱패딩은 여성스러움을 포기해야 할 것 같아서 이 제품 구매한 건데 생각했던 것보다 많이 예쁘진 않습니다.',
  '사이즈도 고민 많이 했는데 55 반이나 66 입는데 95 사이즈 전혀 안 작고 오히려 크단 느낌입니다.',
  '오히려 90을 샀어',
  '야 더 예뻤겠네요.',
  '이 글 쓴 후에 교환 신청하려구요. ㅎㅎ 이웃님 들 올겨울 감기 조심하시고 건강하게 보내세요.',
  '` ^^ 또 새로운 이야기로 돌아오겠습니다.'],
 ['계절이 바뀔 때마다 옷장을 정리 하다 보면 왜 매번 입을 옷이 없을까요.',
  'ㅠㅠ 요즘 같은 애매한(?) 날씨에 입을 만한 겉옷이 없어서 열심히 서 칭해서 구매했습니다.',
  '경량 패딩 필요하신 분들 모여 주세요.',
  'ㅎㅎ 밝은 색을 사고 싶긴 했는데 너무 튀는 게 아닌가 싶었는데 걱정과 달리 쨍한 화이트가 아니고 차분한 화이트 라 옷을 받쳐 입기도 좋았고 사이즈는 후기에서 사이즈가 크다고',
  '해서 s 사이즈 주문했는데 넉넉하니 여유있고 날씬해 보여서 좋습니다.',
  '경량 패딩 잘못 사면 나이 들어 보이구 안 예쁜데 디자인이 예뻐서 좋고 퀄리티도 만족스럽습니다.',
  '올 겨울 많이 춥다는 데 건강 유의하시고 다음에 들려 드릴 제 이야기를 또 기다려 주세요.',
  '^^'],
 ['두꺼운 패딩은 많은데 요즘 같은 날씨에 가볍게 입을 패딩이 없길래 필요해서 구매했습니다.',
  '입어 본 후기 알려 드릴게요.',
  '^^ 사이즈가 고민돼서 백화점에서 입어 보고 사이즈 정했네요.',
  '작년에 OOO 홈페이지에서 똑같은 어니 언 패딩 구매했었는데 그 옷은 핏도 별로였고 털 비침도 심해서 배송 비 물고 반품했었습니다.',
  '올해는 리 뉴 얼된 건지 핏도 이쁘고 화이트인데도 비침이 거의 없어서 좋습니다.',
  '개인적인 판단일 수 있지만 확실히 올해 제품이 좋습니다.',
  '그리고 무엇보다 마음에 들었던 점은 동물복지 시스템 적용해서 다운 솜털 채취한 게 마음에 드네요.',
  '예전에 다운 패딩을 위해 오리털 뽑는 영상을 봤었는데 정말 학대에 가까워서 패딩 류를 지양했는데 마음 놓고 구매했습니다.',
  '치마랑 바지에 다 잘 어울려서 좋습니다.',
  '맘놓고 동물복지 지향하는 패딩 하나 골라 보세요.',
  '만족하실 거예요.',
  '^^'],
 ['요즘 옷 입기 참 애매하죠?!',
  '날씨가 쌀쌀 해지면서 가볍게 걸칠 수 있는 경량 패딩이 필요하더라구요.',
  '도움 되 시라고 퀼팅 경량 다운 자켓 후기 올립니다.',
  '이 제품은 재질도 좋고 충전 재도 구스입니다.',
  '가격대비 짱이지요.',
  '가볍고 따뜻하고 디자인도 깔끔하네요.',
  '핏도 예쁘고 치마나 바지에 둘 다 예쁘게 착용 가능할 수 있어서 좋습니다.',
  'OOO에서 직접 입어 보고 아이보리 사고 블랙은 현장 구매로 판매하지 않아서 사이트에서 구매했습니다.',
  '여러모로 믿을 수 있고 충전재 확실하고 입었을 때 편하고 핏 예뻐서 강추입니다.',
  '간 절기 아우터로 서 데일리로 착용할 수 있는 제품이라서 만족합니다.',
  '어떠셨나요?',
  '도움이 되셨다면 좋겠네요.',
  '^^ 궁금하신 점은 댓 글 문의 주세요.'],
 ['옷장에 옷은 넘쳐나는데 입을 건 없고 그렁다고',
  '버리 진 못하고 한숨이 나와서 다시는 옷 사지 말아야지',
  '하고는 또 쇼핑 사이트를 뒤고 있는 저를 발견합니다.',
  '진짜 이번이 마지막 쇼핑 ( ㅋㅋ 이번 달) 이니 마지막 후기 올립니다.',
  '이 제품은 경량 점퍼보다 도톰하고 길이가 엉덩이도 덮어서 아주 좋습니다.',
  '작년에 나온 아이보리 색상이 가장 사고 팠는데 그건 품절이라 대신 검정색을 샀습니다.',
  '무광이고 쿨 톤 피부를 화사하게 만들어 줘서 좋습니다.',
  '사이즈를 무척 고민했었는데 s 사이즈 소매는 길어서 살짝 접어 입고 허리부분을 슽링으로 조절하니 적당한 오버 핏으로 아주 맘에 듭니다.',
  '여러분 후기 맘에 드셨나요?',
  '당분간 저의 쇼핑 후기는 못 보시는 거 아시죠?!',
  'ㅎㅎ 담 달에 만 나요.',
  '^^'],
 ['아침에 남편 출근 시키고 애들 밥 먹이고 등교 시키려면 혼이 빠지는 것처럼 정신이 없네요.',
  '이 제품은 아이들 등교시킬 때 휘뚜루마뚜루 템으로 구매했습니다.',
  '얘기 들어 보실래요?',
  '저는 172/62 이고 사실 여자치고 큰 키 라 아우터 살 때 사이즈 때문에 엄청 고민을 많이 합니다.',
  '가벼운 게 좋고 일단 또 봄이니 좀 밝은 색으로 구매했는데 제가 컬러를 잘못 선택했네요.',
  'ㅠㅠ ㅋ 아이보리 같은 흰색을 구매한다는 게 세이지가 그 색인 줄 알고 주문해서 받아 보니 초록빛이 도네요.',
  '가까운 OOO 매장이 문의하니 교환가능하다고',
  '하셔서 가서 아이보리 색으로 교환해서 너무 맘에 들고 약간 오버 핏을 좋아해서 사이즈도 M으로 바꿔서 딱 좋습니다.',
  '평소 후드 티 자주 입어서 아주 잘 입고 있네요.',
  '이웃님 들 도 간 절기 가볍게 걸칠 수 있는 아우터를 찾으신다면 고려해 보셔도 좋을 듯 합니다.'],
 ['평소에 편한 옷을 좋아해서 운동복 브랜드에서 나오는 옷을 많이 구매하는 편입니다.',
  '후드 티를 사고 싶었는데 최 애 브랜드에서 찾았습니다.',
  '지금부터 알려 드릴게요.',
  '적당한 두께라서 좋고 자수 디자인 훌륭합니다.',
  '안쪽이 면 소재라서 좋고 입으면 아주 힙하고 멋스러워서 맘에 듭니다.',
  '세일할 때 사서 가격도 좋습니다.',
  '기본 중의 기본 디자인이라서 편안합니다.',
  '사이즈는 정 사이즈 사시면 딱 맞고 오버 핏을 원하시면 한 사이즈 업하시는 면 좋을 것 같습니다.',
  '맘에 들어서 흰색으로 위 아래 세트로 한 벌 더 살까 고민 중입니다.',
  'ㅎㅎ 여러분도 맘에 드는 옷이나 잘 입으시는 브랜드 알려 주세요.',
  '우리 서로 정보 교환해서 쇼핑 실수 줄여 보자 구요.',
  '화 이 팅!!'],
 ['저는 데님을 참 좋아합니다.',
  '10 여벌 정도를 번갈아 입고 있네요.',
  '그리고 청 자켓은 유행도 없지만 시간이 지나면 더 멋 스로워 지는 느낌이 있어서 몇 년에 한번씩은 구매를 하게 됩니다.',
  '그래서 오늘은 얼마 전 구입한 데님 자켓 보여 드리려고 가져 왔습니다.',
  '기존에 가지고 있는 데님 자켓이 낡아서 새로 구매하려고 백화점에 가서 입어도 보고 인터넷으로 서 칭도 열심히 해서 구입했습니다.',
  '재질이 부드럽고 색상도 좋아하는 컬러 라 자주 입을 수 있어서 좋습니다.',
  '색상도 예쁘고 디자인도 아주 기본 템이라 좋습니다.',
  '원피스나 후드 티 입고 입을 꺼라서 코디하기도 좋습니다.',
  '특히 봄, 가을에 아주 잘 입을 꺼 같습니다.',
  '어떠셨나요?',
  '제 글을 보시고 나니 데님 자켓 하나 정도 소장하고 싶지 않으세요?!',
  '구매하셔서 휘뚜루마뚜루 활용하세요.',
  '^^'],
 ['진하면 떠오르는 대명사 OOO 죠.~ ^^ 오랜만에 예전 감성의 데님 자켓 후기 올릴게요.',
  '일단 면과 레이온 혼방으로 두껍지 않고 무겁지 않습니다.',
  '약간의 신축성이 있어서 편하고 가벼운 데님 자켓입니다.',
  '여름에 입어도 부담스럽지 않을 거 같아서 좋습니다.',
  '사진보다 실물 색깔이 훨씬 예뻐서 맘에 듭니다.',
  '모델 컷 보고 색깔 고민 많이 했는데 다행입니다.',
  '백화점에서보다 휠씬 저렴하게 살 수 있어서 더욱 좋습니다.',
  '여러분 간만에 데님 어 떠세요?',
  '이웃님 들 도 요즘 유행하는 레트로 감성에 합류해 보시 길...'],
 ['가볍고 간단하게 입을 게 필요해서 찾고 살펴 보고 며칠을 고민 하다 짜 잔~~ 구매 후기 올립니다.',
  '일단 사이즈는 정 사이즈입니다.',
  '실용성과 활용도가 정말 좋습니다.',
  '플리스로 입으니 보들보들 부드러워 촉감이 굿이네요.',
  '패딩으로 입으면 탄탄한 게 보온성도 좋습니다.',
  '양말도 사은품으로 넣어 주셔서 좋습니다.',
  '사실 남편 거 먼저 구입했는데 맘에 들어서 제 것도 하나 더 구매했지요.',
  '조금 무게는 있는 편인데 따뜻하고 뒤집어 입어도 좋으니 남편도 마음에 들어 합니다.',
  '이웃님 들 도 커플 템으로 구매하셔서 패션 센스 뽐 내 보세요.~',
  '^^'],
 ['이웃님 들 과 같이 한 세월이 꽤 오래 됐네요.',
  '이젠 저의 감성, 스타일 다 아시죠?',
  'ㅎㅎ 나이에 맞지 않는 소녀 감성 ㅋ~ 오늘은 새로 구매한 패딩 이야기입니다.',
  '워낙 러 블 리한 걸 좋아하는데 유독 겨울엔 어둡고 칙칙한 색상들이 많으니 패딩 하나 사는 것도 맘에 드는 게 없더라구요.',
  '이 제품은 색감이 맘에 들어서 구매했네요.',
  '밝은 핑크가 아니고 인디언 핑크 라 차분하면서 겉옷 색감으로 너무 이쁘네요.',
  '옷 마무리까지 아주 고급스러운 느낌이라 맘에 듭니다.',
  '모르고 샀는데 OOO 패딩이라는 데 ㅎㅎ 사이즈는 살짝 작게 나온 거 같습니다.',
  '신 상은 벨트가 있고 모자에 달린 퍼가 맘에 안 드는 색이라서 과감하게 작년 상품으로 구매했는데 가격까지 저렴하니 너무 좋습니다.',
  '이제 저는 꼬까옷 입고 친구 만나러 나갑니다.',
  'ㅋㅋ 오늘도 행복하세요.'],
 ['여름에는 부담스럽지 않은 가격으로 쇼핑을 할 수 있는데 겨울 의류들은 가격들이 있으니 쉽게 구매하기는 힘드네요.',
  '오늘은 정말 간만에 구입한 겨울 패딩 후기입니다.',
  '작년부터 눈여겨 보던 제품입니다.',
  '저는 정 55 사이즈에 블랙 90 사이즈 구매했네요.',
  '좀 더 롱한 길이 감을 원했지만 올해 신제품에는 있는데 작년 제품에는 없네요.',
  'ㅠㅠ 그래도 작년에 비해 저렴하게 구매해서 만족합니다.',
  '신제품은 경량 패딩으로 되 서 3in1 기능이네요.',
  '경량 패딩 구매 따로 하셔야 하는 분들에 겐 신제품 매장에서 확인하시라 고 권하고 싶습니다.',
  '저는 경량이 있는 관계로 그냥 작년 제품 구매했습니다.',
  '슬림 핏이라서 안에 두껍게 입 기엔 불편합니다.',
  '두껍게 입기 위해 선 한 사이즈 업하셔야 합니다.',
  '원단은 탄탄한 원단으로 되어 있어서 살짝 무겁습니다.',
  '후기 잘 보셨나요?',
  '^^ 도움이 되셨음 좋겠습니다.',
  '따뜻한 겨울 보내세요.'],
 ['안녕 하세요 이웃님 들~~ 벌써 12월이 코앞이에요.',
  '월동 준비 다 하셨나요?',
  '전 부지런히 하고 있답니다.',
  '옛날 70년대처럼 겨울이라고 연탄을 수백 장 들여 놓을 일은 없지만 김장도 벌써 다 했고 롱패딩도 사 놨어요.',
  '제가 산 롱 패딩 구경해 보실래요?',
  '제가 산 패딩은 OO 에요. 일반 롱 패딩보다 길 긴 길어요.',
  '그래서 그런지 두툼한 방한 용으로 최고에요. 그리고 뒷쪽에 지퍼가 있으니 길어도 움직일 때 불편하진 않아요.',
  '다른 브랜드에 비해 치수가 조금 큰 편입니다.',
  '사이즈 선택하실 때 참고 하세요.',
  '모자 털 조금 빠져서 그게 좀 아쉽습니다.',
  '하지만 그 외 장점이 더 많은 패딩입니다.',
  '모자 털은 탈부착이 되니 큰 문제는 되지 않을 듯 하네요.',
  '올 겨울 엄청난 한파가 찾아 올 거라고 기상청이 발표 했어요.',
  '이웃님 들 도 월동 준비 잘 하셔서 올 겨울 건강하고 따뜻하게 보내',
  '세요~~ 제 블 로그 찾아 주셔서 감사합니다.'],
 ['안녕 하세요 이웃님 들~~ 오늘 월동 준비 완료했어요.',
  '무슨 월동 준비냐',
  '고요? 궁금하시면 저랑 같이 가볼까요?',
  '지금 바로 렛츠 고~~ 바로 바로 오늘 OO 가 왔답니다.',
  '깨끗한 하양이라 일단 색상은 합격입니다.',
  '사이즈 약간 오버 핏 사이즈로 정말 괜찮아요.',
  '길이도 좋습니다.',
  '가격은 매장보다 더 저렴하게 구입해서 만족도가 큽니다.',
  '단, 주머니가 조금 불편해서 아쉽습니다.',
  '옆으로 넣는 일반 주머니였으면 더 좋았을 것 같네요.',
  '무게감 또한 아쉬워요.',
  '조금 무거운 감이 있네요.',
  '모자 탈부착이 안되는 것 또한 아쉽습니다.',
  '두께 감 또한 아쉬워요.',
  '좀 더 두께 감 있는 패딩을 원했는데... OO 에 대한 저의 솔직한 평가 어떠셨나요?',
  '도움이 되셨다면 좋아요',
  '잊지 마시고 궁금한 점 댓 글로 남겨 주세요~~'],
 ['이웃님 들 주말 즐겁게 보내고 계신가요?',
  '11 월말인데 이렇게 따뜻한 날씨 레 알인가요?',
  '그래도 유비 무 환이라고 갑자기 찾아 올 한파에 대비, 롱 패딩 구매해 봤습니다.',
  '지금 바로 소개해 드릴게요.',
  'OO 구매했습니다.',
  '제가 핑크 매니아인데 핑크 롱 패딩은 보기 힘들더라구요.',
  '핑크 롱 패딩 옛날부터 사고 싶었는데 이번에 살 수 있게 되 서 너무 좋아요.',
  '혹시나 안 예쁜 핑크일까 봐 노심초사했는데 사진이랑 완전 같은 핑크색이라 정말 기뻤어요.',
  '길이도 사이즈도 참 좋습니다.',
  '안에 구스도 적당히 들어 있어서 올겨울이 벌써 기다려 집니다.',
  '가격대비 완전 대만족이에요.',
  '단 약간 무게감은 있으니 무거운 거 싫어하시는 분들은 참고 하세요~~ 얼른 겨울이 왔으면 좋겠어요.',
  '오늘은 여기까지입니다.',
  '제 소식이 도움이 되셨다면 좋아요',
  '잊지 마 세요~~ 여러 분의 지지와 격려는 저에게 큰 힘이 됩니다.'],
 ['안녕 하세요 이웃님 들~~ 벌써 11월이 저물고 있어요.',
  '2022년도 이제 한 달 가량 남았는데 마무리 잘하시고 겨울 맞이로 제가 산 롱 패딩 구경하러 가실까요?',
  '지금 바로 고 고고~~~ 제가 산 롱 패딩은 OO 입니다.',
  '새하얀 눈 같은 하얀색이라 너무 예쁩니다.',
  '가격도 너무 좋아요.',
  '두께도 생각보다 두꺼워요.',
  '그런 데 두께가 가격에 비해 두꺼운 거지 엄청 두껍지는 않아요.',
  '엄청 두꺼운 패딩 원하시면 실망하실 수 있어요.',
  '품질이 최고 라고는 말할 수 없지만 가 성비는 최고에요. 겨울철 막 입기는 정말 좋을 것 같아요.',
  '내 돈 내산 솔 직 리얼 후기 어떠셨나요?',
  '패딩 선택에 도움이 되셨다면 좋아요',
  '꾹 잊지 마시고 언제나 건강하고 행복하세요~~'],
 ['안녕 하세요 이웃님 들~~ 오늘 날씨가 무척 쌀쌀하네요.',
  '겨울이 성큼 다가왔어요.',
  '올 겨울은 엄청 춥다는 데 겨울이 오기 전 롱 패딩 준비하셔 야죠. 그래서 가져와 봤어요.',
  'OO , 지금 바로 출발하시죠~',
  '렛츠 고~~ 가격 너무 좋아서 미리 구매했는데 품질도 너무 좋아요.',
  '두께도 생각보다 두꺼워서 겨울철 정말 잘 입어 질 것 같습니다.',
  '모자 탈부착이 안되는 게 좀 아쉽긴 하지만 이 가격에 구스 패딩이라 니... 정말 믿을 수가 없네요.',
  '동네에 서 마트 갈 때만 입어도 이 가격 뽕 뽑을 듯 합니다.',
  '휘 뚜 르 마 뚜 르 여기 저기 올겨울 잘 입고 다닐 듯요.',
  '디자인 색상 다 예쁘고 가격도 저렴해서 대만족입니다.',
  '제가 오늘 준비한 소식은 여기까지입니다.',
  '날씨 쌀쌀하니 감기 조심 하시고 내일 또 봬 요~~ 제발~~'],
 ['이웃님 들 지금 입으면 딱 좋을 가 디 건 하나 가져 왔어요.',
  '지금 바로 구경 가시죠~~',
  '울 소재가 부들부들 하고 지금 시기에 입고 다니기 딱 좋습니다.',
  '그리고 사이즈도 알맞게 잘 맞아요.',
  '여우 로고도 참 이쁘고 모임할 때 자주 입고 다닐 예정입니다.',
  '색깔 별로 다 구입하고 싶지만 워낙 가격이 후 덜덜 해서요 ㅠㅠ 약간 얇은 듯 하나 코트 안 이너로 입기에 좋은 두께 감이고 아주 추운 날 빼곤 가을 까지는 충분히 겉옷으로 가능할 것 같습니다.',
  '옆 트임 있어 허리선 타이트하지 않아요.',
  '제가 팔이 좀 긴 편인데도 전혀 짧지 않습니다.',
  '어떤 하의와도 찰떡 매치가 되 서 코디하기 쉬워요.',
  '가 디건 맘에 드셨나요?',
  '오늘도 제 블 로그 찾아 주셔서 감사 드리고 내일은 더 좋은 소식으로 찾아뵐게요.',
  '항상 감사 드립니다.',
  '우리 이웃님 들~~'],
 ['이웃님 들 안녕 하세요~~ 요즘 여우 한 마리 키우는 게 유행이더라',
  '구요.',
  '무슨 말이냐',
  '구요?',
  '가슴팍에 여우 한 마리 딱 있으면 뭔 가 고급 져 보이네요.',
  'OOO 가 디 건 이야기입니다.',
  '이 제품 직접 입어 봤습니다.',
  '색감이 너무 예뻐요.',
  '보는 것 보다 소재가 부드럽진 않네요.',
  '그렇다고',
  '까 끌 거리지도 않아요.',
  '오히려 너무 얇지 않아 따뜻해서 좋습니다.',
  '밑단이 트여 있어서 다리도 길어 보이고 예쁩니다.',
  '여우 자수는 역시 사랑스럽구요.',
  '사이즈도 좋고 핏도 이쁘고 색도 고급스럽습니다.',
  '하지만 이 가격 실화입니까?',
  '여우 한마리 가슴팍에 키우는 댓가 치곤 너무 비쌉니다.',
  '패션을 추구하는 분께는 추천, 가성 비를 추구하는 분께는 비추입니다.',
  '제 소식 어떠셨나요?',
  '도움이 되셨으면 좋겠습니다.',
  '지금 바로 좋아요',
  '잊지 마시고 오늘도 즐겁고 건강한 하루 되 세요~~ 그럼 전 이만 총총~~'],
 ['이웃님 들 안녕 하세요~~ 날씨가 너무 따뜻하네요.',
  '11월 날씨라',
  '믿겨 지지 않아요.',
  '가 디 건 하나만 걸쳐도 딱 좋은 날씨입니다.',
  '이런 날 입으면 좋을 가 디 건 하나 소개해 드릴게요.',
  '지금 바로 고 고고~~ 디자인 클래식해서 좋고요.',
  '가 디건만 입기에도 핏이 좋고, 셔츠에 걸쳐도 핏이 부해 보이지 않게 각 잡아 줘서 좋고, 소재 또한 시간이 지 나도 보풀 안 생길 울 소재라',
  '마음에 듭니다.',
  '소재가 매끄러우면서도 톡톡 하고 특유의 광택 감이 살짝 있어 좋습니다.',
  '착용 시 핏이 깔끔하고 날씬해 보입니다.',
  '다만 팔이 슬림하게 나와서 팔뚝이 좀 굵거나 한 이웃님 들은 꼭 입어 보시거나 실측을 보고 꼭 팔 둘레를 재 어서 구매하세요!!',
  '검은 바지 짙은 회색 바지 구분 없이 여기저기 다 잘 어울립니다.',
  '와이드 핏 부츠 컷 핏 다 좋아요~~',
  '오늘 소식은 여기까지입니다.',
  '햇살 좋을 때 많이 걸으시고 건강한 겨울 맞이하시기 바랍니다.',
  '전 이만 여기서 인사 드립니다.',
  '안녕~~'],
 ['안녕 하세요 이웃님 들~~ 좋은 하루 보내고 계시죠?',
  '오늘은 연예인 OO가 입어 화제였던',
  'OOO 가 디건 가지고 왔습니다.',
  '내 돈 내산 솔 직 후기 지금 바로 시작합니다.',
  '렛츠 고~~ 소재가 정말 좋아요.',
  '입었을 때 전혀 까 끌 거리 지 않고, 원단이 탄탄해서 오래오래 예쁘게 입을 것 같아요.',
  '입고 나가니 친구들이 핏이 너무 예쁘다고',
  '해 줘서 입을 때마다 기분 좋아지는 옷입니다.',
  '이제 날씨가 추워 지니 자켓이나 코트, 패딩 안에 입기에도 딱입니다.',
  '치마에도 잘 어울리고 청바지에도 좋고 코디하기 좋아요.',
  '화면 이랑 같긴 한데 실제로 봤을 때 디자인이 더 예뻐요.',
  '옷감도 좋아서 날씬해 보이는 것 같고 디자인이 예뻐서 가 디건만 입어도 예쁜 것 같습니다.',
  '단 가격은 사악합니다.',
  '그래도 OOO 가 디 건 강추합니다.',
  '좀 도움이 되셨나요?',
  '도움이 되셨다면 좋아요',
  '꾹~ 잊지 마시고 궁금한 점 있으시면 댓 글 남겨 주세요~~'],
 ['안녕 하세요 이웃님 들~~ 코트 자락 휘날리며 걷고 싶은 초겨울 오후입니다.',
  '이웃님 들 도 아직 햇살 좋을 때 많이 걸으세요.',
  '전 멋진 코트 소개해 드리는 역할 맡을게요~~',
  '자 코트 보러 가시죠~~',
  'OO 캐시미어 코트는 이태리 콜롬보 캐시미어를 사용해 소재가 좋습니다.',
  '입으면 몸에 감싸는 감촉이 좋아요.',
  '캐시미어 코트 특유의 지 블 링도 맘에 들어요.',
  '무거 우면 잘 안 입게 되는데 가볍고 따뜻해서 잘 입을 듯요.',
  '색상도 기본 블랙부터 OO 코트의 시 그니 처 컬러인 네이비, 카 멜, 그레이, 베이지, 애 쉬라 여기저기 매치하기 좋은데 그중에서 저는 카 멜 색상이 가장 맘에 들어 선택했습니다.',
  '무엇보다도 소재의 고급스러움이 여러분의 겨울을 더욱 따뜻하게 만들 거예요.',
  '물론 가격은 착하지 않아요.',
  '제 소개 마음에 드셨나요?',
  '도움이 되셨다면 좋아요~',
  '잊지 마시고 오늘 따뜻하고 행복하세요~~'],
 ['쌀쌀한 오후입니다.',
  '멋진 코트 입고 걷고 싶은 오후네요.',
  '이웃님 들 감기 조심하시고 제가 산 코트 구경하러 오세요.',
  '지금 바로 고 고고~~ OO 캐시미어 코트입니다.',
  '가볍고 따뜻하구요.',
  '소재가 정말 고급진 옷입니다.',
  '클래식한 기본 스타일인데 오버 핏이라서 너무 마음에 들어요.',
  '타 브랜드 캐시미어 코트 입어 보고 선 구입하고 싶다는 생각을 해본 적이 없는데 이제품은 입어 보자 마자 한 벌은 갖고 있어야 겠다는 생각이 들어 구매했습니다.',
  '구매하시고 보면 디자인이 더 예쁘고 고급 져요.',
  '지 블 링이 대단하고 옷 디자인도 좋습니다.',
  '길이는 종아리 중간 아래 정도라',
  '딱 좋습니다.',
  '겨울 코트 산다 하시면 강추합니다.',
  '환하게 입고 싶어 베이지 샀는데 좋습니다.',
  '참고로 베이지는 헤링본 처리 된 캐시미어 소재입니다.',
  '제 코트 멋지죠?',
  '이웃님 들 도 멋진 코트 구매하실 때 제가 도움이 되길 바래봅니다. 그럼 저는 이만 총총~~'],
 ['안녕 하세요 이웃님 들~~ 겨울엔 코트 하나 걸치면 패션 걱정 없지 않나요?',
  '그러니까 코트는 고급스러운 소재를 선택해야 하는 것 같아요.',
  '오늘 바로 이 코트 이웃님 들께',
  '추천합니다.',
  '카 멜 색도 너무 예뻤는데 카 멜 색 코트가 이미 있어서 네이비로 했습니다.OO',
  '코트의 시 그니 처 컬러이기도 하고요.',
  '캐시미어 결 결 느낌이 살아 있어서 너무너무 예뻐요.',
  '핏도 무심하게 딱 떨어져서 너무 좋습니다.',
  '평소 55~66 을 입는데 오버 핏이라 도톰한 가 디 건 입고도 XS 사이즈가 맞더라구요.',

In [58]:
group_df = pred_df.groupby(['RawText', 'Aspect_pred']).mean()

In [60]:
dddf = group_df.reset_index()

In [62]:
dddf['Aspect_pred'] = le.inverse_transform(dddf['Aspect_pred'])

In [63]:
dddf

                                                RawText Aspect_pred  Pola_pred
0     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          가격        1.0
1     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          기능        0.0
2     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...         사이즈       -0.5
3     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          소재        1.0
4     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...         착용감        1.0
...                                                 ...         ...        ...
8357  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....          기능        1.0
8358  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         디자인        1.0
8359  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         착용감        1.0
8360  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....           핏        1.0
8361  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         활용성        1.0

[8362 rows x 3 columns]

In [ ]:
################     답    #########################################################################

In [214]:
from konlpy.tag import Kkma

In [347]:
total_df

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1024338,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,SNS,패션,여성의류,OO 경량 다운 자켓,513,121,1.0,"[{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인..."
1,1024477,드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드...,SNS,패션,여성의류,OO 아** 구스코트,464,105,1.0,"[{'Aspect': '사이즈', 'SentimentText': '저는 블랙90 사..."
2,1025044,오늘도 정말 춥네요... 롱패딩 찾고 계신 분을 위한 후기 공유합니다. 키 158...,SNS,패션,여성의류,OO 아** 구스코트,314,78,1.0,"[{'Aspect': '사이즈', 'SentimentText': '키 158센티로에..."
3,1025046,이웃님들 오늘도 안녕하신가요? 오늘은 따끈한 신상 패딩 후기 올려봅니다~~ 겨울이...,SNS,패션,여성의류,OO 아** 구스코트,307,74,1.0,"[{'Aspect': '색상', 'SentimentText': '흰색 패딩이 너무나..."
4,1025071,OOO 구스로 소문난 OO의 롱패딩~ 한번 구경 가봐요. 일단 보는 순간 고급스럽...,SNS,패션,여성의류,OO 아** 구스코트,279,68,1.0,"[{'Aspect': '소재', 'SentimentText': ' 일단 보는 순간 ..."
...,...,...,...,...,...,...,...,...,...,...
1418,1038072,안녕하세요~ 점점 추워지는 날씨에 감기 안걸리고 잘 지내고 계신가요? 오늘은 후드 ...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,303,72,1.0,"[{'Aspect': '가격', 'SentimentText': '이번에 적당한 가격..."
1419,1038073,겨울에 패딩만 입고 다니셨나요? 그렇다면 올해는 밍크자켓 하나 구입하시는 거 어떠신...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,296,64,1.0,"[{'Aspect': '디자인', 'SentimentText': '디자인이 너무너무..."
1420,1038074,밍크가 너무 비싸서 못 사고 계셨다면 이번에 겟해보세요! 적당한 밍크 후드 자켓이예...,SNS,패션,여성의류,OO 코** 밍크 후드 하프자켓,273,69,1.0,"[{'Aspect': '가격', 'SentimentText': '가격 대비 가성비 ..."
1421,1038075,플리츠 디자인 좋아하시나요? 저는 치마도 플리츠 치마가 많아요~ 플리츠 디자인 좋아...,SNS,패션,여성의류,OO 클** 후드 하프 자켓,294,64,1.0,"[{'Aspect': '무게', 'SentimentText': ' 이 옷은 무게가 ..."
1422,1038076,홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~ 봄 가...,SNS,패션,여성의류,OO 클** 후드 하프 자켓,317,76,1.0,"[{'Aspect': '사이즈', 'SentimentText': '입어보니 후드가 ..."

In [348]:
kkma = Kkma()
# raw_list에는 리뷰 문단을 문장으로 나눈 리스트를 담기 위한 공간
raw_list = []
# raw_dict 리뷰 문단마다 index를 키 값으로 value는 리뷰 문단
raw_dict = {}
for i in range(len(total_df)):
    # print(kkma.sentences(total_df.loc[i, 'RawText]))
    # break
    raw_list.append(kkma.sentences(total_df.loc[i, 'RawText']))
    # print(total_df.loc[i, 'RawText'])
    # break
    raw_dict[i] = total_df.loc[i, 'RawText']

In [349]:
len(raw_list)

1423

In [350]:
raw_list

[['안녕 하세요 이웃님 들 반갑습니다.',
  '요즘 날씨가 많이 쌀쌀 해졌죠?',
  '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.',
  '다 함께 go go go~~ 제가 입어 보고 좋아서 엄마께도 구매해 드렸네요.',
  '딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해 보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.',
  '엄마도 제가 입은 것 보시더니 탐내셔서 주문해 드렸어요.',
  '영하로 내려가는 날씨에는 이것만 입 기엔 얇지만 초겨울 까지는 운동 갈 때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.',
  '색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈 때 코디하기도 좋아요.',
  '앞으로 코트를 입거나 할 때 안에 내피로 활용하기도 딱 일 듯요!',
  '맘 같아선 색깔 별로 쟁이고 싶습니다.',
  '20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~',
  '설명 끝! 좀 도움이 되셨나요?',
  '그러면 좋아요',
  '꾹 눌러 주시고 전 이만 총총 총~~ 항상 여러 이웃님 들께',
  '감사 드립니다.'],
 ['드디어 겨울이 찾아왔네요.',
  '이제부터 슬슬 겨울 패딩 장만하셔야지요?',
  '패딩 소개해 드릴게요.',
  '작년부터 눈여겨 보던',
  'OO 입니다.',
  '저는 블랙 90 사이즈 구매했는데 딱 잘 맞네요.',
  '작년에 비해 저렴하게 구매해서 아주 만족해요.',
  '신제품은 경량 패딩으로 되 서 3in1 기능이더라',
  '구요.',
  '경량 패딩 구매 따로 하셔야 하는 분들에 겐 신제품 매장에서 확인하시라 고 권하고 싶네요.',
  '저는 경량이 있는 관계로 이 제품 구매했는데 슬림 핏이라 날씬해 보여요.',
  '하지만 안에 두껍게 입 기엔 좀 불편하더라구요.',
  '간편하게 니트 티셔츠에 입기에는 딱입니다.',
  '아직은 초겨울이라 OO를 쭉 입고 있어요.',
  '후기 읽으며 많이 고민했고 도움을 받아서 저도 후기 남겨 봅니다.',
  '누군가에 겐 도움이 되셨기를 바라는 마음에서요. OO 패딩 좋은 건 다들 아실 테고.. 롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시 길 요..'],
 ['오늘도 정말 춥네요...',
  '롱 패딩 찾고 계신 분을 위한 후기 공유합니다.',
  '키 158 센티로에 48 키로 마른 체형인데 90 사이즈가 여유가 별로 없이 딱 맞습니다.',
  '저는 딱 맞게 입기를 좋아해서 아주 만족해요.',
  '와 인색이 정말 특이하게 다운된 색인데 정말 고급스러워서 더욱 마음에 듭니다.',
  '가격도 아주 저렴한 편이라 부담 없이 사서 입게 되었답니다.',
  '핏 되게 나온 옷이라 넉넉하게 입기를 좋아하시는 분은 한 사이즈 올려 입으셔도 좋을 것 같아요.',
  '저는 이 패딩으로 올겨울 아주 따뜻하게 잘 지내게 될 것 같습니다.',
  '새로운 패딩 장만하고 올 겨울 따스하게 보내시길 요...'],
 ['이웃님 들 오늘도 안녕하신가요?',
  '오늘은 따끈한 신상 패딩 후기 올려봅니다~~',
  '겨울이 얼마 남지 않아 고민하다가 눈에 딱 띄는 패딩이 있어 구매했어요.',
  '저는 유난히 흰색을 좋아하는데 이 흰색 패딩이 너무나 고급진 느낌이라 만족스럽습니다.',
  '평소 55 입는데 이 옷도 90 사이즈가 아주 잘 맞네요.',
  '소재가 구김도 없어 좋고 엄청 가벼워서 입은 것 같지도 않은 느낌이 아주 좋아요.',
  '전 요즘은 무거운 패딩은 아주 질색이랍니다.',
  '입었을 때 포근하게 감싸는 느낌도 엄청 만족스럽네요.',
  '강추입니다.',
  '백색의 아름다움을 추구하는 후기~~ 다 들 공감하시지요?',
  'ㅎㅎ'],
 ['OOO 구스로 소문난 OO의 롱 패딩~ 한 번 구경 가봐요.',
  '일단 보는 순간 고급스럽다는 생각이 탁 드는 소재였습니다.',
  '입어 보니 핏이 너무도 예뻐요.',
  '입는 순간 느끼는 따스함은 어떤 패딩보다 훌륭했습니다.',
  '보통의 패딩같이 스포 티한 디자인이 아니라서 회사에 입고 다니기에도 아주 좋을 것 같습니다.',
  'OOO 모델로 텔레비전 광고를 많이 봐서 이 옷을 입으면 나도 그녀처럼 아름다운 여인이 될 것 같은 환상을 갖게 하는 패딩이네요.',
  '우리 모두를 모델로 만들어 줄 패딩 ㅎㅎ ~~ 이웃님 들 생각은 어떠신지요?'],
 ['심플한 디자인에 따뜻한 기능성 패딩을 찾으시는 분들께 소개합니다.',
  '보통 95 사이즈 입는데 후기에 작다는 평이 있어서 100으로 주문했더니 잘 맞네요.',
  '입었을 때 따뜻함이 정말 좋습니다.',
  '혹시 눈이 올 때 방수 기능이 있으면 했는데 정말 눈 맞아도 젖지 않아 참 마음에 드는 패딩이네요.',
  '바람도 잘 들어오지 않으니 보온 효과도 좋은 거 같고요.',
  '저는 개인적으로 롱한 패딩을 좋아하는데 아주 딱 맘에 드는 길이입니다.',
  '아주 오래도록 봉투에 쌓여 있어서 그런지 지금은 털이 죽어 있네요.',
  '시간이 지나면 살아나겠지만 기대했던 것만큼 풍성하지는 않아서 그게 좀 아쉬워요.',
  '그래도 가격 대비 품질은 굿입니다.',
  '후기 잘 읽어 보셨지요?',
  '롱 패딩 찾으시는 분들께 참고가 되기를 바라는 마음에서 후기 공유했습니다 .'],
 ['편안하면서도 뭔 가 좀 색다른 티셔츠가 없을까',
  '검색하던 중 뜻밖에 달달 하고 러 블 리한 핏의 맨투맨을 발견했어요.',
  '러 블 리하게 퍼프 소매로 소매 셔링 디테일을 더해 볼 룸 감 있고 또 더 사랑스럽게 보이는 스타일이더라',
  '구요.',
  '바로 퍼프 맨투맨으로 샀는데 할랑한 루즈 핏의 러 블 리한 맨투맨 제가 딱 찾고 있던 스타일이라 너무 좋았습니다.',
  '엉덩이는 가려 주고 다리는 더 길어 보이게 해 주는 최상의 디자인인 것 같아요.',
  '레깅스와 함께 매칭하면 더욱 더 잘 어울리더라구요.',
  '너무 두껍지도 않고 얇지도 않은 적당한 두께 감이라 좋고 원단도 부드러워서 자꾸 손이 가서 데일리로 입기에 딱 좋은 옷인 것 같습니다.'],
 ['오늘 따뜻한 커피 한 잔 생각나는 날씨네요.',
  '향긋 한 커피 한 잔 하시면서 오늘 소식 시작할까요?',
  '그럼 Go Go Go~~~ 요즘 날씨가 엄청 추웠다 또 괜찮았다 트렌치 코트를 입자니 춥고 코트를 입자니 덥고 그렇더라구요.',
  '그래서 가볍게 걸칠 경량 패딩 알아보다가 OOOO 퀼팅 경량 다운 자켓이 유명하길래 저도 사 봤어요.',
  '워낙 넉넉하게 나왔다는 후기가 많아서 사이즈 고민을 많이 했는데 고민하는 사이에 s가 품절되어서 어쩔 수 없이 xs을 샀어요.',
  '코트 안에도 입을 생각이고 추워 지기 전엔 안에 목 티나 적당히 두께 있는 옷 입고 외투로도 걸칠 생각이어서 받자마자 입어 봤는데 사이즈가 딱 맘에 듭니다!',
  '얼마나 차이가 있을지는 모르겠지만 s로 샀으면 컷을 것 같네요.',
  '가볍고 웬만한 옷엔 다 어울려서 요즘 매일 입어요.',
  '타 브랜드 제품과 비교했을 때 가격 재질 충전재 모두 탁월하고 착용시 가볍고 따뜻합니다.',
  '핏도 예쁘고 디자인도 깔끔하고 가 성비 진짜 좋습니다!!',
  '이런 커피가 다 식었네요.',
  '오늘도 제 소식이 도움이 됐다면 좋아요',
  '꾹~ 부탁 드리며 커피 향처럼 향긋 한 하루가 되 시 길 바 래요~~'],
 ['겨울이 다가오는 요즘 여러분들의 헛헛한 마음을 채울 따끈한 정보 대령했사옵니다~~',
  '오늘 소개해 드릴 아이템은 OOOO 퀄팅 경량 다운 자켓 인데요.',
  '착용 감 좋고 너무 가볍습니다.',
  '크게 나온 거 같아서 S 구매했는데 ( 평소 사이즈는 M) 조금 넉넉하게 잘 맞는 거 같아요.',
  '움직임이 둔하지 않고 활동하는데 크게 무리가 없어요.',
  '다른 옷들 중에 착용 시 습한 느낌이 드는 것도 있는데 재질이 좋아서 그런지 상쾌한 느낌입니다.',
  '가격이 비싼 편이 아닌가 생각이 들었는데 입는 순간 다른 제품에 비해서 퀄리티가 좋아서 가격이 비싼 느낌이 안 들었습니다.',
  '퀼팅이 조잡스럽지 않아서 타제품에 비해 고급스러워요.',
  '컬러에 대해 말씀 드리자면 이 옷은 단연 화이트 죠. 색감이 밝고 깨끗해서 모든 옷에 잘 어울립니다.',
  '화이트야 말로 이 제품의 시 그니 처 컬러입니다.',
  '지금 날씨에는 사무실에서 이거 하나만 입고 있어도 따뜻하네요',
  '지금까지 제가 느꼈던 부분을 솔직하게 알려 드렸습니다.',
  '오늘 저의 소식이 도움이 됐다면 좋아요',
  '잊지 마 세요~~'],
 ['안녕하세요?',
  '우리 이웃님 들, 동물 사랑에 패딩에 손이 잘 안 가셨던',
  '우리 이웃님 들께',
  '희소식 가져왔어요!!!',
  '바로 가 보실까요?',
  'OOOO 퀼팅 다운 자켓은 수조류의 사육과정부터 우 모의 채취 가공 봉제 등 복지 프로그램을 준수했다는 공인 인증까지 안심하고 입을 수 있는 제품이에요.',
  '전에 다운 패딩을 위해 오리털 뽑는 영상 봤는데 정말 학대에 가깝더라고요.',
  '그래서 패딩류 지양했는데 이젠 마음 놓고 구매할 수 있어요.',
  '디자인은 예쁘고 퀄리티 좋고 봉 제 깔끔하고 따뜻해요.',
  '실용적인 면에서는 그 어떤 아이템도 따라갈 수가 없어서 늦가을부터 잘 입고 있습니다.',
  '왜 그렇게 몇 년 전부터 입소문이 나고 베스트셀러인지 입어 보니 알겠더라구요.',
  '이 옷은 단연 화이트 이어야 하는데.... 평 상시 아이 옷만으로도 감당이 안되는지라 차선책인 그레이 구매했네요.',
  '색상이 튀거나 확 예쁘다는 느낌은 없으나 착용감 편안하고 따스하고 어디에 나 잘 어울려요.',
  '무엇보다 놀랍도록 가볍고 따뜻하네요',
  '오늘은 여기까지~~ 좀 도움이 되셨나요?',
  '그러면 좋아요',
  '잊지 마세요!',
  '여러분의 지지와 격려가 제 겐 큰 힘이 됩니다.'],
 ['쌀쌀 해진 요즘 휘 뚜 르 마 뚜 르 걸칠 수 있는 옷 어디 없나',
  '하다가 발견한 제 인생 퀼팅 경량 다운 자켓!! 자 만나러 가실까요~~ 재질도 좋고 충전 재도 구스인데 이 가격이라니!!',
  '놀라도록 혜 자스럽습니다.',
  '가볍고 따뜻하고 디자인도 깔끔합니다.',
  '핏도 예뻐서 치마나 바지에 둘 다 잘 어울려요.',
  '다른 브랜드에서도 비슷한 옷들을 많이 볼 수 있는데 재질도 충전재도 좋고 무엇보다 마음에 들었던 점은 동물복지 시스템 적용해서 다운 솜털 채취한 게 마음에 듭니다!',
  '다른 경량 패딩과 비교했을 때 디테일에서 차이가 있고 무게 감도 확실히 달라요.',
  '가벼우면서 스타일까지 살아 있어요.',
  '퀼팅도 편안해 보이고 간격도 딱 알맞게 봉제되어 있어 고급스럽고 간 절기 아우터로 너무 편 해서 데일리로 늘 착용하는 제 인생 아이템입니다.',
  '한 겨울에는 못 입을 거 같지만 가벼운 옷을 입고 그 위에 살짝 걸치고 코트까지 입으면 정말 따뜻하게 겨울을 보낼 수 있을 거 같아요.',
  '제 소식 어떠셨나요?',
  '도움이 되셨다면 좋아요',
  '꾹 눌러 주시고 오늘도 좋은 하루 행복한 하루 되시길 진심으로 기원합니다.',
  '항상 감사 드려요~~'],
 ['치마나 원피스를 좋아하는 저는, 추워 진다고 해서 원피스를 포기할 수는 없죠',
  'ㅎㅎ 여러분도 저와 같지 않나요?',
  '오늘도 제 맘에 쏙 드는 원피스를 소개해 드릴게요.',
  '제가 S 사이즈를 입는데, 편안하게 입을 수 있는 사이즈네요.',
  '55-66을 걸쳐서 중간 사이즈를 입는데, 이번 S 사이즈 선택은 정확했네요.',
  '상의 하의 소재가 어울리면서 다른 소재라',
  '좋았어요.',
  '니트 부분은 촘촘 해서 입었을 때 착용감이 좋구요.',
  '스커트 부분은 플레어 라 걸을 때 여성스러워 보여요.',
  '스커트의 천이 답답하지 않고 세련된 느낌이 들어요.',
  '두 벌을 레이어 드한 느낌으로 더 스타일 리 쉬하구요.',
  '블랙이라 신경 쓰지 않고 더 편하게 입을 수 있어요.',
  '어떠셨나요?',
  '여러분도 저처럼 추워 질수록 더 예쁘고 분위기 있게 차려입고 멋진 가을을 보내세요~'],
 ['계절이 바뀌는 요즘, 약속에 입고 나갈 옷을 찾고 있나요.',
  '데이트룩은 물론, 데일리룩으로도 입기 좋은 원피스를 소개 해봅니다.',
  '가장 마음에 드는 부분인 브이넥 디자인은 세련되면서도 여성스러워요.',
  '그리고 자칫 단순해 보일 수 있는 옷이 상의 하의 부분이 다른 소재 라 더 멋스러움을 연출해 줘요.',
  '4개의 단추는 포인트를 줘서 더 스타일을 빛 내주구요.',
  '색도 어두운 블랙 계열이면서도 밝게 보여 고급스러워요.',
  '요즘 날씨에도 하나만 입기 딱 좋겠어요.',
  '제가 키가 작은 편인데도 길이 감은 너무 길지 않고 딱 좋네요',
  '오히려 단정해 보여요',
  '여러분들의 멋스러운 가을 쇼핑에 도움되시길 바랄게요~'],
 ['기본 스타일의 롱 니트라고 생각하고 구입을 했는데 다양한 스타일로 연출이 가능한 티셔츠를 득 템 해서 소개를 하려고 합니다.',
  '가격도 저렴하고 디자인도 제가 원하던 스탈이라 세 가지 색상을 다 질렀습니다.',
  '배송을 받고 다 구매한 것이 이렇게 만족스러웠던 적은 없었던 것 같아요.',
  '가로로 길게 립라인으로 된 넥이 탄탄하게 잘 짜여 있어서 오프 솔 더 로도 활용이 가능해서 좋아요.',
  '하나의 니트로 기분과 상황에 따라 때론 청순하게 때론 섹 쉬하게 입을 수 있어 좋은 것 같아요.',
  '간만의 득 템으로 기분 전환이 된 것 같아 너무 만족스럽습니다.'],
 ['이렇게 달달 한 맨투맨을 보신적이 있나요?',
  '전 이 맨투맨을 보는 순간 달달 함에 이끌려 나도 모르게 주문을 하고 있더라구요.',
  '디자인이 러 블 리한 이 맨투맨, 사랑스러움보다 더 놀라운 것은 너무나도 저렴한 가격이었습니다.',
  '소매와 밑단에 풍성하게 주름을 넣어서 사랑스럽기가 이루 말로 다 할 수 가 없는데요. 길이까지 길어서 엉덩이는 덮어 주고 앞라인은 또 살짝 짧아서 다리가 엄청 길어 보이게 하는 효과까지 있어서 너무 맘에 듭니다.',
  '이렇게 저렴한 가격에 이렇게 풍성한 주름이 있는 사랑스러운 맨투맨을 구입할 수 있으리라',
  '정말 상상도 못했었네요.'],
 ['저는 레깅스를 즐겨 입어요.',
  '근데 요즘 살이 좀 찌는 것 같아 레깅스 좀 편하게 입기 위해 엉덩이를 덮을 수 있는 길이 감의 티셔츠를 찾고 있었는데 굿 템을 발견했어요.',
  '바로 루즈 핏 맨투맨입니다.',
  '앞 뒤의 길이가 언 발란스로 되어 엉덩이를 푹 덮어 주는 길이라 제 맘에 쏙 들었습니다.',
  '그리고 넉넉한 사이즈 라 조금씩 오른 제 살들을 잘 감쳐 줘서 더 좋았고 다리까지 길어 보이게 해 주니 이게 왠 일인가 했네요~',
  '무엇보다 가격이 저렴한 데 세 가지 색상을 다 주니 올가을은 다른 옷이 필요 없을 듯하네요.',
  '살이 쪄서 속상했는데 굿 템을 발견해서 마음이 행복 해졌어요.',
  '올가을은 또 이렇게 잘 보낼 수 있게 되어 행복합니다.'],
 ['오늘은 어떤 옷과 입어도, 언제 입어도 깔끔하고 예쁜 바지 하나 소개할게요.',
  '색상이 무난해서 다 좋아요.',
  '발목 위로 살짝 올라가는 기장으로 키도 커 보이고 날씬해 보입니다.',
  '코디할 때도 어떤 상의랑 입어도 잘 어울리네요.',
  '너무 얇지도 않아서 한 여름 되기 전 까지는 문제 없을 것 같아요.',
  '흠을 하나 잡자면 그레 이색은 약간 색이 바랜 것처럼 보여서 좀 그래요. 나머지는 다 좋습니다.',
  '오는 주말에는 이런 바지에 운동화 신고 북촌에 나들이 가는 건 어 떠세요'],
 ['올해는 아이보리나 화이트 색상이 겨울 컬러를 주도한다고 하더군요.',
  '이런 코트 어 떠세요?',
  '정 사이즈로 주문했는데 입어 보니 품이 너무 넓네요.',
  '겉감은 부들부들 좋습니다.',
  '울이 60퍼센트밖에 안 돼서 한 겨울에는 추울 것 같아요.',
  '가성 비는 충분히 좋습니다.',
  '안에 어두운 목 티 입고 아래 스커트랑 받쳐 입으면 겨울 멋쟁이 될 것 같네요.',
  '그런 데 소매나 밑단 같은 데 실밥 처리는 좀 신경 써서 보내주세요.',
  '늘 무채색 옷만 입지 마시고 가끔 씩은 이런 밝은 색 톤으로 이미지 메이킹 다시 해보는 건 어떠신가요??'],
 ['깊어 가는 가을, 이제 슬슬 겨울옷을 꺼내야 할 것 같아요.',
  '요즘 입기 좋은 모직 코드 하나 보여 드릴게요.',
  '그냥 유행 타지 않은 베이 직한 디자인입니다.',
  '저는 개인적으로 이런 디자인 맘에 들어요.',
  '사이즈도 넉넉해서 안에 얇은 패딩 조 키 입고 입으면 딱 일 것 같아요.',
  '옷감 재질이 적당히 부드러워서 더 좋네요.',
  '올 겨울 멋스럽게 입고 다녀야겠어요. 감사합니다.',
  '그 동안 수십년 사 입은 제 옷은 다 어디로 갔을까요?',
  '계절과 함께 다 사라져 버리나 봐요.'],
 ['날씨가 갑자기 추워 졌죠?',
  '올 겨울 따뜻하고 멋스럽게 입을 만한 모직 코트 한번 둘러봤네요.',
  '소개해 드릴게요.',
  '가성 비 완전 좋습니다.',
  '촉감이 많이 부드럽지는 않지만 입으니 따뜻하고 너무 마음에 듭니다.',
  '마감도 잘 되어 있어요.',
  '밝은 카 멜 이라',
  '쫌 그랬는대 막상 입 어보 닌 나쁘지 않네요.',
  '올 겨울 출퇴근할 때 멋스럽게 잘 입을 것 같아요.',
  '추천합니다.',
  '패팅이 따뜻 함의 지존이라 아무리 해도 겨울 멋 내기에는 모직 코트만한 게 없죠?',
  '끝까지 읽어 주셔서 감사해요.'],
 ['올겨울 많이 춥다네요.',
  '이웃님 들 월동 준비 하셨나요?',
  'ㅎㅎ 저는 겨울 나기의 가장 큰 숙제인 김장을 끝내고 나서 겨울 옷을 정리 중입니다.',
  '올겨울은 롱패딩을 입어 볼까 하고 주문한 옷 후기 적어 봅니다.',
  '^^ 일 다 되게 따뜻합니다.',
  '무겁지 않고 색도 예뻐서 맘에 듭니다.',
  '다만 후드 퍼가 풍성하지 않아서 아쉽습니다.',
  '일자 디자인의 롱패딩은 여성스러움을 포기해야 할 것 같아서 이 제품 구매한 건데 생각했던 것보다 많이 예쁘진 않습니다.',
  '사이즈도 고민 많이 했는데 55 반이나 66 입는데 95 사이즈 전혀 안 작고 오히려 크단 느낌입니다.',
  '오히려 90을 샀어',
  '야 더 예뻤겠네요.',
  '이 글 쓴 후에 교환 신청하려구요. ㅎㅎ 이웃님 들 올겨울 감기 조심하시고 건강하게 보내세요.',
  '` ^^ 또 새로운 이야기로 돌아오겠습니다.'],
 ['계절이 바뀔 때마다 옷장을 정리 하다 보면 왜 매번 입을 옷이 없을까요.',
  'ㅠㅠ 요즘 같은 애매한(?) 날씨에 입을 만한 겉옷이 없어서 열심히 서 칭해서 구매했습니다.',
  '경량 패딩 필요하신 분들 모여 주세요.',
  'ㅎㅎ 밝은 색을 사고 싶긴 했는데 너무 튀는 게 아닌가 싶었는데 걱정과 달리 쨍한 화이트가 아니고 차분한 화이트 라 옷을 받쳐 입기도 좋았고 사이즈는 후기에서 사이즈가 크다고',
  '해서 s 사이즈 주문했는데 넉넉하니 여유있고 날씬해 보여서 좋습니다.',
  '경량 패딩 잘못 사면 나이 들어 보이구 안 예쁜데 디자인이 예뻐서 좋고 퀄리티도 만족스럽습니다.',
  '올 겨울 많이 춥다는 데 건강 유의하시고 다음에 들려 드릴 제 이야기를 또 기다려 주세요.',
  '^^'],
 ['두꺼운 패딩은 많은데 요즘 같은 날씨에 가볍게 입을 패딩이 없길래 필요해서 구매했습니다.',
  '입어 본 후기 알려 드릴게요.',
  '^^ 사이즈가 고민돼서 백화점에서 입어 보고 사이즈 정했네요.',
  '작년에 OOO 홈페이지에서 똑같은 어니 언 패딩 구매했었는데 그 옷은 핏도 별로였고 털 비침도 심해서 배송 비 물고 반품했었습니다.',
  '올해는 리 뉴 얼된 건지 핏도 이쁘고 화이트인데도 비침이 거의 없어서 좋습니다.',
  '개인적인 판단일 수 있지만 확실히 올해 제품이 좋습니다.',
  '그리고 무엇보다 마음에 들었던 점은 동물복지 시스템 적용해서 다운 솜털 채취한 게 마음에 드네요.',
  '예전에 다운 패딩을 위해 오리털 뽑는 영상을 봤었는데 정말 학대에 가까워서 패딩 류를 지양했는데 마음 놓고 구매했습니다.',
  '치마랑 바지에 다 잘 어울려서 좋습니다.',
  '맘놓고 동물복지 지향하는 패딩 하나 골라 보세요.',
  '만족하실 거예요.',
  '^^'],
 ['요즘 옷 입기 참 애매하죠?!',
  '날씨가 쌀쌀 해지면서 가볍게 걸칠 수 있는 경량 패딩이 필요하더라구요.',
  '도움 되 시라고 퀼팅 경량 다운 자켓 후기 올립니다.',
  '이 제품은 재질도 좋고 충전 재도 구스입니다.',
  '가격대비 짱이지요.',
  '가볍고 따뜻하고 디자인도 깔끔하네요.',
  '핏도 예쁘고 치마나 바지에 둘 다 예쁘게 착용 가능할 수 있어서 좋습니다.',
  'OOO에서 직접 입어 보고 아이보리 사고 블랙은 현장 구매로 판매하지 않아서 사이트에서 구매했습니다.',
  '여러모로 믿을 수 있고 충전재 확실하고 입었을 때 편하고 핏 예뻐서 강추입니다.',
  '간 절기 아우터로 서 데일리로 착용할 수 있는 제품이라서 만족합니다.',
  '어떠셨나요?',
  '도움이 되셨다면 좋겠네요.',
  '^^ 궁금하신 점은 댓 글 문의 주세요.'],
 ['옷장에 옷은 넘쳐나는데 입을 건 없고 그렁다고',
  '버리 진 못하고 한숨이 나와서 다시는 옷 사지 말아야지',
  '하고는 또 쇼핑 사이트를 뒤고 있는 저를 발견합니다.',
  '진짜 이번이 마지막 쇼핑 ( ㅋㅋ 이번 달) 이니 마지막 후기 올립니다.',
  '이 제품은 경량 점퍼보다 도톰하고 길이가 엉덩이도 덮어서 아주 좋습니다.',
  '작년에 나온 아이보리 색상이 가장 사고 팠는데 그건 품절이라 대신 검정색을 샀습니다.',
  '무광이고 쿨 톤 피부를 화사하게 만들어 줘서 좋습니다.',
  '사이즈를 무척 고민했었는데 s 사이즈 소매는 길어서 살짝 접어 입고 허리부분을 슽링으로 조절하니 적당한 오버 핏으로 아주 맘에 듭니다.',
  '여러분 후기 맘에 드셨나요?',
  '당분간 저의 쇼핑 후기는 못 보시는 거 아시죠?!',
  'ㅎㅎ 담 달에 만 나요.',
  '^^'],
 ['아침에 남편 출근 시키고 애들 밥 먹이고 등교 시키려면 혼이 빠지는 것처럼 정신이 없네요.',
  '이 제품은 아이들 등교시킬 때 휘뚜루마뚜루 템으로 구매했습니다.',
  '얘기 들어 보실래요?',
  '저는 172/62 이고 사실 여자치고 큰 키 라 아우터 살 때 사이즈 때문에 엄청 고민을 많이 합니다.',
  '가벼운 게 좋고 일단 또 봄이니 좀 밝은 색으로 구매했는데 제가 컬러를 잘못 선택했네요.',
  'ㅠㅠ ㅋ 아이보리 같은 흰색을 구매한다는 게 세이지가 그 색인 줄 알고 주문해서 받아 보니 초록빛이 도네요.',
  '가까운 OOO 매장이 문의하니 교환가능하다고',
  '하셔서 가서 아이보리 색으로 교환해서 너무 맘에 들고 약간 오버 핏을 좋아해서 사이즈도 M으로 바꿔서 딱 좋습니다.',
  '평소 후드 티 자주 입어서 아주 잘 입고 있네요.',
  '이웃님 들 도 간 절기 가볍게 걸칠 수 있는 아우터를 찾으신다면 고려해 보셔도 좋을 듯 합니다.'],
 ['평소에 편한 옷을 좋아해서 운동복 브랜드에서 나오는 옷을 많이 구매하는 편입니다.',
  '후드 티를 사고 싶었는데 최 애 브랜드에서 찾았습니다.',
  '지금부터 알려 드릴게요.',
  '적당한 두께라서 좋고 자수 디자인 훌륭합니다.',
  '안쪽이 면 소재라서 좋고 입으면 아주 힙하고 멋스러워서 맘에 듭니다.',
  '세일할 때 사서 가격도 좋습니다.',
  '기본 중의 기본 디자인이라서 편안합니다.',
  '사이즈는 정 사이즈 사시면 딱 맞고 오버 핏을 원하시면 한 사이즈 업하시는 면 좋을 것 같습니다.',
  '맘에 들어서 흰색으로 위 아래 세트로 한 벌 더 살까 고민 중입니다.',
  'ㅎㅎ 여러분도 맘에 드는 옷이나 잘 입으시는 브랜드 알려 주세요.',
  '우리 서로 정보 교환해서 쇼핑 실수 줄여 보자 구요.',
  '화 이 팅!!'],
 ['저는 데님을 참 좋아합니다.',
  '10 여벌 정도를 번갈아 입고 있네요.',
  '그리고 청 자켓은 유행도 없지만 시간이 지나면 더 멋 스로워 지는 느낌이 있어서 몇 년에 한번씩은 구매를 하게 됩니다.',
  '그래서 오늘은 얼마 전 구입한 데님 자켓 보여 드리려고 가져 왔습니다.',
  '기존에 가지고 있는 데님 자켓이 낡아서 새로 구매하려고 백화점에 가서 입어도 보고 인터넷으로 서 칭도 열심히 해서 구입했습니다.',
  '재질이 부드럽고 색상도 좋아하는 컬러 라 자주 입을 수 있어서 좋습니다.',
  '색상도 예쁘고 디자인도 아주 기본 템이라 좋습니다.',
  '원피스나 후드 티 입고 입을 꺼라서 코디하기도 좋습니다.',
  '특히 봄, 가을에 아주 잘 입을 꺼 같습니다.',
  '어떠셨나요?',
  '제 글을 보시고 나니 데님 자켓 하나 정도 소장하고 싶지 않으세요?!',
  '구매하셔서 휘뚜루마뚜루 활용하세요.',
  '^^'],
 ['진하면 떠오르는 대명사 OOO 죠.~ ^^ 오랜만에 예전 감성의 데님 자켓 후기 올릴게요.',
  '일단 면과 레이온 혼방으로 두껍지 않고 무겁지 않습니다.',
  '약간의 신축성이 있어서 편하고 가벼운 데님 자켓입니다.',
  '여름에 입어도 부담스럽지 않을 거 같아서 좋습니다.',
  '사진보다 실물 색깔이 훨씬 예뻐서 맘에 듭니다.',
  '모델 컷 보고 색깔 고민 많이 했는데 다행입니다.',
  '백화점에서보다 휠씬 저렴하게 살 수 있어서 더욱 좋습니다.',
  '여러분 간만에 데님 어 떠세요?',
  '이웃님 들 도 요즘 유행하는 레트로 감성에 합류해 보시 길...'],
 ['가볍고 간단하게 입을 게 필요해서 찾고 살펴 보고 며칠을 고민 하다 짜 잔~~ 구매 후기 올립니다.',
  '일단 사이즈는 정 사이즈입니다.',
  '실용성과 활용도가 정말 좋습니다.',
  '플리스로 입으니 보들보들 부드러워 촉감이 굿이네요.',
  '패딩으로 입으면 탄탄한 게 보온성도 좋습니다.',
  '양말도 사은품으로 넣어 주셔서 좋습니다.',
  '사실 남편 거 먼저 구입했는데 맘에 들어서 제 것도 하나 더 구매했지요.',
  '조금 무게는 있는 편인데 따뜻하고 뒤집어 입어도 좋으니 남편도 마음에 들어 합니다.',
  '이웃님 들 도 커플 템으로 구매하셔서 패션 센스 뽐 내 보세요.~',
  '^^'],
 ['이웃님 들 과 같이 한 세월이 꽤 오래 됐네요.',
  '이젠 저의 감성, 스타일 다 아시죠?',
  'ㅎㅎ 나이에 맞지 않는 소녀 감성 ㅋ~ 오늘은 새로 구매한 패딩 이야기입니다.',
  '워낙 러 블 리한 걸 좋아하는데 유독 겨울엔 어둡고 칙칙한 색상들이 많으니 패딩 하나 사는 것도 맘에 드는 게 없더라구요.',
  '이 제품은 색감이 맘에 들어서 구매했네요.',
  '밝은 핑크가 아니고 인디언 핑크 라 차분하면서 겉옷 색감으로 너무 이쁘네요.',
  '옷 마무리까지 아주 고급스러운 느낌이라 맘에 듭니다.',
  '모르고 샀는데 OOO 패딩이라는 데 ㅎㅎ 사이즈는 살짝 작게 나온 거 같습니다.',
  '신 상은 벨트가 있고 모자에 달린 퍼가 맘에 안 드는 색이라서 과감하게 작년 상품으로 구매했는데 가격까지 저렴하니 너무 좋습니다.',
  '이제 저는 꼬까옷 입고 친구 만나러 나갑니다.',
  'ㅋㅋ 오늘도 행복하세요.'],
 ['여름에는 부담스럽지 않은 가격으로 쇼핑을 할 수 있는데 겨울 의류들은 가격들이 있으니 쉽게 구매하기는 힘드네요.',
  '오늘은 정말 간만에 구입한 겨울 패딩 후기입니다.',
  '작년부터 눈여겨 보던 제품입니다.',
  '저는 정 55 사이즈에 블랙 90 사이즈 구매했네요.',
  '좀 더 롱한 길이 감을 원했지만 올해 신제품에는 있는데 작년 제품에는 없네요.',
  'ㅠㅠ 그래도 작년에 비해 저렴하게 구매해서 만족합니다.',
  '신제품은 경량 패딩으로 되 서 3in1 기능이네요.',
  '경량 패딩 구매 따로 하셔야 하는 분들에 겐 신제품 매장에서 확인하시라 고 권하고 싶습니다.',
  '저는 경량이 있는 관계로 그냥 작년 제품 구매했습니다.',
  '슬림 핏이라서 안에 두껍게 입 기엔 불편합니다.',
  '두껍게 입기 위해 선 한 사이즈 업하셔야 합니다.',
  '원단은 탄탄한 원단으로 되어 있어서 살짝 무겁습니다.',
  '후기 잘 보셨나요?',
  '^^ 도움이 되셨음 좋겠습니다.',
  '따뜻한 겨울 보내세요.'],
 ['안녕 하세요 이웃님 들~~ 벌써 12월이 코앞이에요.',
  '월동 준비 다 하셨나요?',
  '전 부지런히 하고 있답니다.',
  '옛날 70년대처럼 겨울이라고 연탄을 수백 장 들여 놓을 일은 없지만 김장도 벌써 다 했고 롱패딩도 사 놨어요.',
  '제가 산 롱 패딩 구경해 보실래요?',
  '제가 산 패딩은 OO 에요. 일반 롱 패딩보다 길 긴 길어요.',
  '그래서 그런지 두툼한 방한 용으로 최고에요. 그리고 뒷쪽에 지퍼가 있으니 길어도 움직일 때 불편하진 않아요.',
  '다른 브랜드에 비해 치수가 조금 큰 편입니다.',
  '사이즈 선택하실 때 참고 하세요.',
  '모자 털 조금 빠져서 그게 좀 아쉽습니다.',
  '하지만 그 외 장점이 더 많은 패딩입니다.',
  '모자 털은 탈부착이 되니 큰 문제는 되지 않을 듯 하네요.',
  '올 겨울 엄청난 한파가 찾아 올 거라고 기상청이 발표 했어요.',
  '이웃님 들 도 월동 준비 잘 하셔서 올 겨울 건강하고 따뜻하게 보내',
  '세요~~ 제 블 로그 찾아 주셔서 감사합니다.'],
 ['안녕 하세요 이웃님 들~~ 오늘 월동 준비 완료했어요.',
  '무슨 월동 준비냐',
  '고요? 궁금하시면 저랑 같이 가볼까요?',
  '지금 바로 렛츠 고~~ 바로 바로 오늘 OO 가 왔답니다.',
  '깨끗한 하양이라 일단 색상은 합격입니다.',
  '사이즈 약간 오버 핏 사이즈로 정말 괜찮아요.',
  '길이도 좋습니다.',
  '가격은 매장보다 더 저렴하게 구입해서 만족도가 큽니다.',
  '단, 주머니가 조금 불편해서 아쉽습니다.',
  '옆으로 넣는 일반 주머니였으면 더 좋았을 것 같네요.',
  '무게감 또한 아쉬워요.',
  '조금 무거운 감이 있네요.',
  '모자 탈부착이 안되는 것 또한 아쉽습니다.',
  '두께 감 또한 아쉬워요.',
  '좀 더 두께 감 있는 패딩을 원했는데... OO 에 대한 저의 솔직한 평가 어떠셨나요?',
  '도움이 되셨다면 좋아요',
  '잊지 마시고 궁금한 점 댓 글로 남겨 주세요~~'],
 ['이웃님 들 주말 즐겁게 보내고 계신가요?',
  '11 월말인데 이렇게 따뜻한 날씨 레 알인가요?',
  '그래도 유비 무 환이라고 갑자기 찾아 올 한파에 대비, 롱 패딩 구매해 봤습니다.',
  '지금 바로 소개해 드릴게요.',
  'OO 구매했습니다.',
  '제가 핑크 매니아인데 핑크 롱 패딩은 보기 힘들더라구요.',
  '핑크 롱 패딩 옛날부터 사고 싶었는데 이번에 살 수 있게 되 서 너무 좋아요.',
  '혹시나 안 예쁜 핑크일까 봐 노심초사했는데 사진이랑 완전 같은 핑크색이라 정말 기뻤어요.',
  '길이도 사이즈도 참 좋습니다.',
  '안에 구스도 적당히 들어 있어서 올겨울이 벌써 기다려 집니다.',
  '가격대비 완전 대만족이에요.',
  '단 약간 무게감은 있으니 무거운 거 싫어하시는 분들은 참고 하세요~~ 얼른 겨울이 왔으면 좋겠어요.',
  '오늘은 여기까지입니다.',
  '제 소식이 도움이 되셨다면 좋아요',
  '잊지 마 세요~~ 여러 분의 지지와 격려는 저에게 큰 힘이 됩니다.'],
 ['안녕 하세요 이웃님 들~~ 벌써 11월이 저물고 있어요.',
  '2022년도 이제 한 달 가량 남았는데 마무리 잘하시고 겨울 맞이로 제가 산 롱 패딩 구경하러 가실까요?',
  '지금 바로 고 고고~~~ 제가 산 롱 패딩은 OO 입니다.',
  '새하얀 눈 같은 하얀색이라 너무 예쁩니다.',
  '가격도 너무 좋아요.',
  '두께도 생각보다 두꺼워요.',
  '그런 데 두께가 가격에 비해 두꺼운 거지 엄청 두껍지는 않아요.',
  '엄청 두꺼운 패딩 원하시면 실망하실 수 있어요.',
  '품질이 최고 라고는 말할 수 없지만 가 성비는 최고에요. 겨울철 막 입기는 정말 좋을 것 같아요.',
  '내 돈 내산 솔 직 리얼 후기 어떠셨나요?',
  '패딩 선택에 도움이 되셨다면 좋아요',
  '꾹 잊지 마시고 언제나 건강하고 행복하세요~~'],
 ['안녕 하세요 이웃님 들~~ 오늘 날씨가 무척 쌀쌀하네요.',
  '겨울이 성큼 다가왔어요.',
  '올 겨울은 엄청 춥다는 데 겨울이 오기 전 롱 패딩 준비하셔 야죠. 그래서 가져와 봤어요.',
  'OO , 지금 바로 출발하시죠~',
  '렛츠 고~~ 가격 너무 좋아서 미리 구매했는데 품질도 너무 좋아요.',
  '두께도 생각보다 두꺼워서 겨울철 정말 잘 입어 질 것 같습니다.',
  '모자 탈부착이 안되는 게 좀 아쉽긴 하지만 이 가격에 구스 패딩이라 니... 정말 믿을 수가 없네요.',
  '동네에 서 마트 갈 때만 입어도 이 가격 뽕 뽑을 듯 합니다.',
  '휘 뚜 르 마 뚜 르 여기 저기 올겨울 잘 입고 다닐 듯요.',
  '디자인 색상 다 예쁘고 가격도 저렴해서 대만족입니다.',
  '제가 오늘 준비한 소식은 여기까지입니다.',
  '날씨 쌀쌀하니 감기 조심 하시고 내일 또 봬 요~~ 제발~~'],
 ['이웃님 들 지금 입으면 딱 좋을 가 디 건 하나 가져 왔어요.',
  '지금 바로 구경 가시죠~~',
  '울 소재가 부들부들 하고 지금 시기에 입고 다니기 딱 좋습니다.',
  '그리고 사이즈도 알맞게 잘 맞아요.',
  '여우 로고도 참 이쁘고 모임할 때 자주 입고 다닐 예정입니다.',
  '색깔 별로 다 구입하고 싶지만 워낙 가격이 후 덜덜 해서요 ㅠㅠ 약간 얇은 듯 하나 코트 안 이너로 입기에 좋은 두께 감이고 아주 추운 날 빼곤 가을 까지는 충분히 겉옷으로 가능할 것 같습니다.',
  '옆 트임 있어 허리선 타이트하지 않아요.',
  '제가 팔이 좀 긴 편인데도 전혀 짧지 않습니다.',
  '어떤 하의와도 찰떡 매치가 되 서 코디하기 쉬워요.',
  '가 디건 맘에 드셨나요?',
  '오늘도 제 블 로그 찾아 주셔서 감사 드리고 내일은 더 좋은 소식으로 찾아뵐게요.',
  '항상 감사 드립니다.',
  '우리 이웃님 들~~'],
 ['이웃님 들 안녕 하세요~~ 요즘 여우 한 마리 키우는 게 유행이더라',
  '구요.',
  '무슨 말이냐',
  '구요?',
  '가슴팍에 여우 한 마리 딱 있으면 뭔 가 고급 져 보이네요.',
  'OOO 가 디 건 이야기입니다.',
  '이 제품 직접 입어 봤습니다.',
  '색감이 너무 예뻐요.',
  '보는 것 보다 소재가 부드럽진 않네요.',
  '그렇다고',
  '까 끌 거리지도 않아요.',
  '오히려 너무 얇지 않아 따뜻해서 좋습니다.',
  '밑단이 트여 있어서 다리도 길어 보이고 예쁩니다.',
  '여우 자수는 역시 사랑스럽구요.',
  '사이즈도 좋고 핏도 이쁘고 색도 고급스럽습니다.',
  '하지만 이 가격 실화입니까?',
  '여우 한마리 가슴팍에 키우는 댓가 치곤 너무 비쌉니다.',
  '패션을 추구하는 분께는 추천, 가성 비를 추구하는 분께는 비추입니다.',
  '제 소식 어떠셨나요?',
  '도움이 되셨으면 좋겠습니다.',
  '지금 바로 좋아요',
  '잊지 마시고 오늘도 즐겁고 건강한 하루 되 세요~~ 그럼 전 이만 총총~~'],
 ['이웃님 들 안녕 하세요~~ 날씨가 너무 따뜻하네요.',
  '11월 날씨라',
  '믿겨 지지 않아요.',
  '가 디 건 하나만 걸쳐도 딱 좋은 날씨입니다.',
  '이런 날 입으면 좋을 가 디 건 하나 소개해 드릴게요.',
  '지금 바로 고 고고~~ 디자인 클래식해서 좋고요.',
  '가 디건만 입기에도 핏이 좋고, 셔츠에 걸쳐도 핏이 부해 보이지 않게 각 잡아 줘서 좋고, 소재 또한 시간이 지 나도 보풀 안 생길 울 소재라',
  '마음에 듭니다.',
  '소재가 매끄러우면서도 톡톡 하고 특유의 광택 감이 살짝 있어 좋습니다.',
  '착용 시 핏이 깔끔하고 날씬해 보입니다.',
  '다만 팔이 슬림하게 나와서 팔뚝이 좀 굵거나 한 이웃님 들은 꼭 입어 보시거나 실측을 보고 꼭 팔 둘레를 재 어서 구매하세요!!',
  '검은 바지 짙은 회색 바지 구분 없이 여기저기 다 잘 어울립니다.',
  '와이드 핏 부츠 컷 핏 다 좋아요~~',
  '오늘 소식은 여기까지입니다.',
  '햇살 좋을 때 많이 걸으시고 건강한 겨울 맞이하시기 바랍니다.',
  '전 이만 여기서 인사 드립니다.',
  '안녕~~'],
 ['안녕 하세요 이웃님 들~~ 좋은 하루 보내고 계시죠?',
  '오늘은 연예인 OO가 입어 화제였던',
  'OOO 가 디건 가지고 왔습니다.',
  '내 돈 내산 솔 직 후기 지금 바로 시작합니다.',
  '렛츠 고~~ 소재가 정말 좋아요.',
  '입었을 때 전혀 까 끌 거리 지 않고, 원단이 탄탄해서 오래오래 예쁘게 입을 것 같아요.',
  '입고 나가니 친구들이 핏이 너무 예쁘다고',
  '해 줘서 입을 때마다 기분 좋아지는 옷입니다.',
  '이제 날씨가 추워 지니 자켓이나 코트, 패딩 안에 입기에도 딱입니다.',
  '치마에도 잘 어울리고 청바지에도 좋고 코디하기 좋아요.',
  '화면 이랑 같긴 한데 실제로 봤을 때 디자인이 더 예뻐요.',
  '옷감도 좋아서 날씬해 보이는 것 같고 디자인이 예뻐서 가 디건만 입어도 예쁜 것 같습니다.',
  '단 가격은 사악합니다.',
  '그래도 OOO 가 디 건 강추합니다.',
  '좀 도움이 되셨나요?',
  '도움이 되셨다면 좋아요',
  '꾹~ 잊지 마시고 궁금한 점 있으시면 댓 글 남겨 주세요~~'],
 ['안녕 하세요 이웃님 들~~ 코트 자락 휘날리며 걷고 싶은 초겨울 오후입니다.',
  '이웃님 들 도 아직 햇살 좋을 때 많이 걸으세요.',
  '전 멋진 코트 소개해 드리는 역할 맡을게요~~',
  '자 코트 보러 가시죠~~',
  'OO 캐시미어 코트는 이태리 콜롬보 캐시미어를 사용해 소재가 좋습니다.',
  '입으면 몸에 감싸는 감촉이 좋아요.',
  '캐시미어 코트 특유의 지 블 링도 맘에 들어요.',
  '무거 우면 잘 안 입게 되는데 가볍고 따뜻해서 잘 입을 듯요.',
  '색상도 기본 블랙부터 OO 코트의 시 그니 처 컬러인 네이비, 카 멜, 그레이, 베이지, 애 쉬라 여기저기 매치하기 좋은데 그중에서 저는 카 멜 색상이 가장 맘에 들어 선택했습니다.',
  '무엇보다도 소재의 고급스러움이 여러분의 겨울을 더욱 따뜻하게 만들 거예요.',
  '물론 가격은 착하지 않아요.',
  '제 소개 마음에 드셨나요?',
  '도움이 되셨다면 좋아요~',
  '잊지 마시고 오늘 따뜻하고 행복하세요~~'],
 ['쌀쌀한 오후입니다.',
  '멋진 코트 입고 걷고 싶은 오후네요.',
  '이웃님 들 감기 조심하시고 제가 산 코트 구경하러 오세요.',
  '지금 바로 고 고고~~ OO 캐시미어 코트입니다.',
  '가볍고 따뜻하구요.',
  '소재가 정말 고급진 옷입니다.',
  '클래식한 기본 스타일인데 오버 핏이라서 너무 마음에 들어요.',
  '타 브랜드 캐시미어 코트 입어 보고 선 구입하고 싶다는 생각을 해본 적이 없는데 이제품은 입어 보자 마자 한 벌은 갖고 있어야 겠다는 생각이 들어 구매했습니다.',
  '구매하시고 보면 디자인이 더 예쁘고 고급 져요.',
  '지 블 링이 대단하고 옷 디자인도 좋습니다.',
  '길이는 종아리 중간 아래 정도라',
  '딱 좋습니다.',
  '겨울 코트 산다 하시면 강추합니다.',
  '환하게 입고 싶어 베이지 샀는데 좋습니다.',
  '참고로 베이지는 헤링본 처리 된 캐시미어 소재입니다.',
  '제 코트 멋지죠?',
  '이웃님 들 도 멋진 코트 구매하실 때 제가 도움이 되길 바래봅니다. 그럼 저는 이만 총총~~'],
 ['안녕 하세요 이웃님 들~~ 겨울엔 코트 하나 걸치면 패션 걱정 없지 않나요?',
  '그러니까 코트는 고급스러운 소재를 선택해야 하는 것 같아요.',
  '오늘 바로 이 코트 이웃님 들께',
  '추천합니다.',
  '카 멜 색도 너무 예뻤는데 카 멜 색 코트가 이미 있어서 네이비로 했습니다.OO',
  '코트의 시 그니 처 컬러이기도 하고요.',
  '캐시미어 결 결 느낌이 살아 있어서 너무너무 예뻐요.',
  '핏도 무심하게 딱 떨어져서 너무 좋습니다.',
  '평소 55~66 을 입는데 오버 핏이라 도톰한 가 디 건 입고도 XS 사이즈가 맞더라구요.',

In [351]:
sentence_df = pd.DataFrame()
for idx, raw in enumerate(raw_list):
    # print(raw)
    # print(idx)
    # break
    pred = best_model.predict(raw)
    # print(pred)
    temp_df = pd.DataFrame(pred, columns = ['Aspect_pred', 'Pola_pred'])
    # print(temp_df)
    # break
    temp_df['RawText'] = raw_dict[idx]
    # print(raw_dict[idx])
    # break
    # display(temp_df)
    sentence_df = pd.concat([sentence_df, temp_df])

In [352]:
len(raw_dict)

1423

In [353]:
len(sum(raw_list, []))

12883

In [354]:
sentence_df

    Aspect_pred  Pola_pred                                            RawText
0             1          1  안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...
1             1          1  안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...
2             1          1  안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...
3            17          1  안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...
4             5          0  안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...
..          ...        ...                                                ...
6            16         -1  홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~  봄 가...
7             5          1  홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~  봄 가...
8             5          1  홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~  봄 가...
9             6          1  홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~  봄 가...
10            9          1  홈쇼핑 보면서 고민고민하다가 구매한 옷인데요~ 어떤 옷인지 소개해드릴께요~  봄 가...

[12883 rows x 3 columns]

In [355]:
sentence_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12883 entries, 0 to 10
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Aspect_pred  12883 non-null  int64
 1   Pola_pred    12883 non-null  int64
 2   RawText      12883 non-null  object
dtypes: int64(2), object(1)
memory usage: 402.6+ KB

In [222]:
group_df = sentence_df.groupby(['RawText', 'Aspect_pred']).mean()

In [223]:
group_df

                                                                Pola_pred
RawText                                            Aspect_pred
130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 믿... 0                  1.0
                                                   1                  0.0
                                                   8                 -0.5
                                                   10                 1.0
                                                   13                 1.0
...                                                                   ...
히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요. ... 1                  1.0
                                                   5                  1.0
                                                   13                 1.0
                                                   16                 1.0
                                                   17                 1.0

[8362 rows x 1 columns]

In [230]:
group_df.reset_index(inplace=True)

In [231]:
group_df['Aspect_pred'] = le.inverse_transform(group_df['Aspect_pred'])

In [232]:
group_df

                                                RawText Aspect_pred  Pola_pred
0     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          가격        1.0
1     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          기능        0.0
2     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...         사이즈       -0.5
3     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...          소재        1.0
4     130년에 가까운 전통 글로벌 스포츠 브랜드인 OO의 트랙수트입니다.  OO이라고 ...         착용감        1.0
...                                                 ...         ...        ...
8357  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....          기능        1.0
8358  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         디자인        1.0
8359  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         착용감        1.0
8360  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....           핏        1.0
8361  히든밴딩과 매끈한 절개라인으로 슬림핏을 연출해 주는 바디라인 레깅스를 소개할려해요....         활용성        1.0

[8362 rows x 3 columns]

In [246]:
group_df.index

RangeIndex(start=0, stop=8362, step=1)

In [245]:
total_df.index

RangeIndex(start=0, stop=1423, step=1)

In [276]:
# total_df와 group_df를 join 결합
review_df = pd.merge(total_df, group_df, on='RawText', how='inner')

In [277]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8362 entries, 0 to 8361
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            8362 non-null   int64
 1   RawText          8362 non-null   object
 2   Source           8362 non-null   object
 3   Domain           8362 non-null   object
 4   MainCategory     8362 non-null   object
 5   ProductName      8362 non-null   object
 6   Syllable         8362 non-null   int64
 7   Word             8362 non-null   int64
 8   GeneralPolarity  8330 non-null   float64
 9   Aspects          8362 non-null   object
 10  Aspect_pred      8362 non-null   object
 11  Pola_pred        8362 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 784.1+ KB

In [280]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8362 entries, 0 to 8361
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            8362 non-null   int64
 1   RawText          8362 non-null   object
 2   Source           8362 non-null   object
 3   Domain           8362 non-null   object
 4   MainCategory     8362 non-null   object
 5   ProductName      8362 non-null   object
 6   Syllable         8362 non-null   int64
 7   Word             8362 non-null   int64
 8   GeneralPolarity  8330 non-null   float64
 9   Aspects          8362 non-null   object
 10  Aspect_pred      8362 non-null   object
 11  Pola_pred        8362 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 784.1+ KB

In [282]:
# ProductNum의 빈도 수 체크
len(review_df['ProductName'].unique())

517

In [290]:
# 제품별 리뷰의 상세 감정 분석이 가능
# 제품 이름 중 가장 많은 리뷰를 가진 제풀믕ㄹ 선택하여 감정 점수의 평균을 확인
review_df.groupby(['ProductName'])['RawText'].count()

ProductName
OO [1+1] 에** 티셔츠          27
OO [3 SET] 에** 오버핏 티셔츠    22
OO 가디건 라운드넥                9
OO 가을 슬랙스 3종               5
OO 가을팬츠 3종                 6
                          ..
OO 호** 양모 베스트             12
OO 홀** 퓨어 캐시미어 니트         19
OO 후리스 리버시블 짚업             5
[1+1] 겨울 여성 OO 바지         24
[1+1] 여성 OO 지퍼 바지          6
Name: RawText, Length: 517, dtype: int64

In [322]:
pd.pivot_table(
    data=review_df.drop_duplicates('RawText'),
    index = 'ProductName',
    values = 'RawText',
    aggfunc = ('count')
).sort_values('RawText', ascending=False).index[0]

'OO 코튼 가디건 '

In [330]:
product_name = 'OO 코튼 가디건 '
# 해당 제품의 리뷰들의 전체적인 감정의 점수를 출력
# case1 -> ProductName에서 필터링을 한 뒤 Aspect_pred를 기준으로 그룹화 -> Pola_pred의 평균
test_df = review_df.loc[review_df['ProductName'] == product_name, ]
test_df

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects,Aspect_pred,Pola_pred
1408,1029890,장마가 시작되었으니 예쁜 가디건 하나 사서 걸치고 다니면 좋을 것 같다는 생각에 구...,SNS,패션,여성의류,OO 코튼 가디건,336,80,1.0,"[{'Aspect': '소재', 'SentimentText': '확실히 면소재라 부...",가격,0.0
1409,1029890,장마가 시작되었으니 예쁜 가디건 하나 사서 걸치고 다니면 좋을 것 같다는 생각에 구...,SNS,패션,여성의류,OO 코튼 가디건,336,80,1.0,"[{'Aspect': '소재', 'SentimentText': '확실히 면소재라 부...",색상,1.0
1410,1029890,장마가 시작되었으니 예쁜 가디건 하나 사서 걸치고 다니면 좋을 것 같다는 생각에 구...,SNS,패션,여성의류,OO 코튼 가디건,336,80,1.0,"[{'Aspect': '소재', 'SentimentText': '확실히 면소재라 부...",소재,1.0
1411,1029890,장마가 시작되었으니 예쁜 가디건 하나 사서 걸치고 다니면 좋을 것 같다는 생각에 구...,SNS,패션,여성의류,OO 코튼 가디건,336,80,1.0,"[{'Aspect': '소재', 'SentimentText': '확실히 면소재라 부...",신축성,1.0
1412,1029890,장마가 시작되었으니 예쁜 가디건 하나 사서 걸치고 다니면 좋을 것 같다는 생각에 구...,SNS,패션,여성의류,OO 코튼 가디건,336,80,1.0,"[{'Aspect': '소재', 'SentimentText': '확실히 면소재라 부...",품질,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5660,1036728,가디건은 역시 여기가 제일 잘 만드는 것 같아요!! 그래서 추천 드리고 싶어 오늘 ...,SNS,패션,여성의류,OO 코튼 가디건,314,77,1.0,"[{'Aspect': '촉감', 'SentimentText': '촉감이 정말 부드러...",착용감,1.0
5661,1036729,가을에 입기 좋은 가디건을 가져 왔습니다!! 이 가디건 만큼 좋은 가디건은 보지 못...,SNS,패션,여성의류,OO 코튼 가디건,310,83,1.0,"[{'Aspect': '기능', 'SentimentText': '가을에 입기 좋은 ...",기능,1.0
5662,1036729,가을에 입기 좋은 가디건을 가져 왔습니다!! 이 가디건 만큼 좋은 가디건은 보지 못...,SNS,패션,여성의류,OO 코튼 가디건,310,83,1.0,"[{'Aspect': '기능', 'SentimentText': '가을에 입기 좋은 ...",두께,1.0
5663,1036729,가을에 입기 좋은 가디건을 가져 왔습니다!! 이 가디건 만큼 좋은 가디건은 보지 못...,SNS,패션,여성의류,OO 코튼 가디건,310,83,1.0,"[{'Aspect': '기능', 'SentimentText': '가을에 입기 좋은 ...",마감,1.0
5664,1036729,가을에 입기 좋은 가디건을 가져 왔습니다!! 이 가디건 만큼 좋은 가디건은 보지 못...,SNS,패션,여성의류,OO 코튼 가디건,310,83,1.0,"[{'Aspect': '기능', 'SentimentText': '가을에 입기 좋은 ...",색상,1.0

In [331]:
test_df.groupby('Aspect_pred')['Pola_pred'].mean()

Aspect_pred
가격      0.875000
기능      0.944444
길이      1.000000
두께      0.875000
디자인     1.000000
마감      1.000000
사이즈     0.300000
색상      0.950000
소재      1.000000
신축성     1.000000
제품구성   -1.000000
착용감     1.000000
촉감      1.000000
품질      0.600000
핏       1.000000
활용성     0.666667
Name: Pola_pred, dtype: float64

In [332]:
# case2 -> review_df에서 ProductName과 Aspect_pred를 기준으로 그룹화
# Pola_pred의 평균을 구한다.
# 원하는 제품명을 선택하여 확인
group_df2 = review_df.groupby(['ProductName', 'Aspect_pred'])['Pola_pred'].mean()

In [334]:
group_df2[product_name]

Aspect_pred
가격      0.875000
기능      0.944444
길이      1.000000
두께      0.875000
디자인     1.000000
마감      1.000000
사이즈     0.300000
색상      0.950000
소재      1.000000
신축성     1.000000
제품구성   -1.000000
착용감     1.000000
촉감      1.000000
품질      0.600000
핏       1.000000
활용성     0.666667
Name: Pola_pred, dtype: float64