### 복습
- ratings_train.txt 데이터 로드
- document 컬럼의 결측치 제외
- 텍스트 정규화(특수문자 제거, 2칸 이상의 공백 제외, 문자열 좌우 공백 제거)
- document의 중복 데이터를 제거
- 데이터프레임에서 상위 1000개만 사용
- texts -> 데이터프레임의 document 컬럼의 values
- labels -> 데이터프레임의 label 컬럼의 values
- 토큰화 -> Komoran
    - 선택하는 품사는 NNP, NNG, VV, VA, MAG, XR
    - 불용어 하다, 되다, 이다
- 단어 사전 생성 (vocab)
    - 단어들 중 최소 출현 횟수가 2회
    - 단어 사전에는 <PAD>, <UNK>을 제일 앞에 지정하여 단어사전 생성
- 토큰화된 문서들을 단어 사전의 위치 값에 맞게 인코딩 (enc_inputs)

In [2]:
import pandas as pd
import re
from konlpy.tag import Komoran
from collections import Counter
# import collections

In [3]:
df = pd.read_csv('../data/ratings_train.txt', sep='\t')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [4]:
# document 컬럼의 결측치를 제거하시오
df.dropna(subset="document", inplace=True)

In [5]:
def normalize(text):
    text = re.sub(r"[^가-힣0-9a-zA-Z\s\.]", " ", str(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [6]:
# document만 텍스트 정규화 -> Series 데이터에서 normalize() 함수를 실행
# 여러 개의 컬럼의 텍스트를 정규화 -> DataFrame 데이터에서 normalize() 함수를 실행

# Series 데이터에서 각각의 values들을 normalize() 대입
df['document'].map(normalize)   # 결과를 어디에 대입? -> df['document']
# DataFrame 데이터에서 각각의 values들을 normalize() 대입
df[['id', 'document']] = df[['id', 'document']].applymap(normalize)

C:\Users\student\AppData\Local\Temp\ipykernel_13680\1068432169.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[['id', 'document']] = df[['id', 'document']].applymap(normalize)

In [7]:
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [8]:
# document 컬럼의 중복 데이터 제거
df.drop_duplicates(subset = 'document', inplace=True)
df

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[144734 rows x 3 columns]

In [9]:
# df = df.head(1000)
df = df[:1000]

In [10]:
df

            id                                           document  label
0      9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1      3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2     10265843                                  너무재밓었다그래서보는것을추천한다      0
3      9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4      6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...        ...                                                ...    ...
996    6473973                                           파괴된 관객들.      0
997    8417568                                  알콜중독자들 덕에 평점이 낮은가      1
998    7126211  중견배우들이 만들어놓은 긴장감이 나름 긴장감있게 싸워보려했던 도술사들에 의해 헛웃음...      0
999    8379556  남자 주인공 늑대 인간으로 변하고 끝나네유. 평점 보고 안 볼까 하다가 봤는디 재밌...      1
1000   9856453          정말 최고의 명작 성인이 되고 본 이집트의 왕자는 또 다른 감동 그자체네요      1

[1000 rows x 3 columns]

In [11]:
# 토큰화 작업
komoran = Komoran()

allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'XR']
stop_word = ['하다', '되다', '이다']

def tokenize(doc):
    tokens = []
    for word, pos in komoran.pos(doc):
        if pos in allow_pos and word not in stop_word:
            tokens.append(word)
    return tokens

In [12]:
# texts, labels 변수 생성 document, label 데이터를 대입
texts, labels = df['document'].values, df['label'].values

In [13]:
# texts들을 이용하여 토큰화
tokens_list = [tokenize(doc) for doc in texts]
tokens_list

[['더빙', '진짜', '짜증', '나', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기', '가볍'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '없', '평점', '조정'],
 ['익살', '연기', '돋보이', '영화', '스파이더맨', '늙', '보이', '하', '커스틴 던스트', '너무나'],
 ['막', '걸음마', '떼', '초등학교', '학년', '용', '영화', '별', '반개', '아깝'],
 ['원작', '긴장감', '제대로', '살리'],
 ['반개',
  '아깝',
  '욕',
  '나오',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '이',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '이',
  '드라마',
  '가족',
  '없',
  '연기',
  '못하',
  '사람',
  '모이'],
 ['액션', '없', '재미', '있', '안', '영화'],
 ['왜', '평점', '낮', '꽤', '보', '헐리우드', '화려', '너무', '길들이', '있'],
 [],
 ['볼', '때', '눈물', '나서', '죽', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'],
 ['울', '손들', '횡단보도', '건너', '때', '뛰쳐나오', '이범수', '연기', '드럽'],
 ['담백', '깔끔', '좋', '신문', '기사', '로만', '보다', '보', '자꾸', '잊어버리', '사람'],
 ['취향',
  '존중',
  '진짜',
  '극장',
  '보',
  '영화',
  '가장',
  '노',
  '재',
  '노',
  '감동',
  '스토리',
  '어거지',
  '감동',
  '어거지'],
 ['매번', '긴장'],
 ['참',
  '사람',
  '웃기',
  '바스코',
  '이기',
  '락스',
  '코',
  '까',
  '고',
  '바비',
  '이기',
  '아이돌',
  '깔',
  '그냥',
  '까',
  '안달',
  '난',
  '보이'],
 ['굿바이 레닌', '표절', '이해', '왜', '뒤', '갈수록', '재미없'],
 ['이건',
  '정말',
  '깨알',
  '캐스팅',
  '질퍽',
  '산뜻',
  '내용',
  '구성',
  '잘',
  '버',
  '러',
  '진',
  '깨알',
  '드'],
 ['약탈', '위하', '변명', '착하', '절대'],
 ['심오', '뜻', '있', '그냥', '학생', '선생', '놀아나', '영화', '절대'],
 ['보', '웃', '가능'],
 ['재미없',
  '지루',
  '같',
  '음식',
  '영화',
  '만찬',
  '넘',
  '만찬',
  '이야기',
  '있',
  '음식',
  '보',
  '재미',
  '있',
  '이건',
  '보',
  '없',
  '음식',
  '별로',
  '안',
  '나오',
  '핀란드',
  '풍경',
  '별로',
  '안',
  '나오'],
 ['절대', '평범', '영화', '수작', '말씀', '드리'],
 ['주제', '좋', '중반', '지루'],
 ['다', '짜르', '납득', '없', '그렇', '꼭', '그렇', '걸', '끄'],
 ['고추', '털', '하'],
 ['카밀라', '벨', '발', '연기'],
 [],
 ['센스', '있', '연출력', '탁월', '캐스팅', '90년대', '향수'],
 ['엄',
  '포스',
  '위력',
  '다시',
  '깨닫',
  '하',
  '남',
  '꽃',
  '검사',
  '연기',
  '정말',
  '좋',
  '완전',
  '명품',
  '드라마'],
 ['졸', '쓰레기', '시간', '아깝'],
 ['재밌', '별점', '왜', '이리', '낮', '은고'],
 ['라도', '기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하', '열정', '안나', '윈', '투어'],
 ['키이라 나이틀리', '연기', '하', '대체', '정신', '장애', '틱', '장애'],
 ['원', '작가', '정신', '나가', '유령', '재미있'],
 ['포스터', '있', '보이', '관객'],
 ['영화', '왜', '이렇', '평가', '받', '모르'],
 ['단순', '은은', '매력', '영화'],
 ['다',
  '알바',
  '내용',
  '없',
  '무섭',
  '거도',
  '없',
  '웃기',
  '거도',
  '없',
  '완전',
  '별',
  '싱겁',
  '영화',
  '시간',
  '넘',
  '아깝',
  '완전',
  '낚이'],
 ['오', '서리', '한', '굶주리'],
 ['정말', '맘', '들', '보', '보', '방법', '없'],
 ['윤제문',
  '멋지',
  '배우',
  '발견',
  '되',
  '소소',
  '일탈',
  '잔잔',
  '미소',
  '머금',
  '음악',
  '조금',
  '아쉽',
  '평점',
  '올리'],
 ['평점', '속지', '마시', '길', '시간', '낭비', '돈', '낭비'],
 ['리얼리티',
  '뛰어나',
  '하',
  '크',
  '공감',
  '안',
  '가',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '일',
  '툭하면',
  '사람',
  '패',
  '욕',
  '물건',
  '파손',
  '조금',
  '오바',
  '극',
  '초반',
  '신선',
  '가',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불가'],
 ['마이너스', '왜', '없', '보', '영화', '수준', '딱', '알', '북한', '만들', '돈', '대'],
 ['나', '영화', '사랑합니다'],
 ['데',
  '리스',
  '타르',
  '가르',
  '용의',
  '주인',
  '되',
  '누',
  '이랑',
  '근친상간',
  '하',
  '다니',
  '소설',
  '속',
  '제일',
  '멋지',
  '자이',
  '메',
  '라',
  '니스',
  '드라마',
  '속',
  '드래곤',
  '용',
  '제일',
  '멋지',
  '웃음',
  '감독',
  '토르',
  '다크 월드',
  '잡수',
  '기본',
  '선방',
  '하'],
 ['영화',
  '사람',
  '영혼',
  '어루만지',
  '있',
  '거치',
  '세상사',
  '잠시',
  '잊',
  '동화',
  '같',
  '영화',
  '행복'],
 ['르', '게이', '작', '고추', '매운맛', '보이', '콩', '진호', '간다'],
 ['이렇', '가슴', '시리', '보', '드라마', '있', '감동', '자체'],
 ['난', '꼬마', '애가', '원한', '깊', '하', '그냥', '혼자', '나대', '걸', '어쩌'],
 ['재미있'],
 ['좋'],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '푹',
  '꺼지',
  '하',
  '느낌',
  '활력',
  '없',
  '너무나',
  '무겁',
  '지독',
  '차갑',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '대단',
  '같',
  '생각',
  '들'],
 ['심심', '영화'],
 ['백봉기', '언제나', '오'],
 ['보', '그대로', '들어맞', '예측', '카리스마', '없', '악역'],
 ['불알', '나오', '당황', '아무튼', '영화', '중간', '끝나', '느낌'],
 ['평범', '함속', '녹', '아든', '평범', '일상', '조금', '밋밋'],
 ['보',
  '계속',
  '보',
  '전개도',
  '느리',
  '주인공',
  '은희',
  '컷',
  '나오',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나',
  '기대',
  '하',
  '전개',
  '좀',
  '빨리빨리'],
 ['사랑', '가슴속', '오', '감정', '헤집', '영화', '예', '요정', '말', '최고'],
 ['많',
  '사람',
  '다',
  '큐',
  '보',
  '우리나라',
  '슬프',
  '현대사',
  '단면',
  '대하',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하',
  '노력',
  '말',
  '듣',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '명백',
  '살인',
  '살인자',
  '다',
  '있'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '먹',
  '내용',
  '산',
  '가',
  '시청률',
  '아예',
  '안',
  '나오',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '불구', '지루', '손예진'],
 ['재밌', '비슷', '영화', '안보', '신', '재미있'],
 ['노래', '실력', '뽑', '맞', '박시환', '가면', '진짜', '망신'],
 ['일본', '영화', '다', '유치'],
 ['이틀',
  '다',
  '보',
  '재밌',
  '안',
  '물건',
  '넣',
  '조작',
  '하',
  '안',
  '열리',
  '집',
  '안',
  '활짝',
  '열리',
  '들어가',
  '문자',
  '조작',
  '비번',
  '안',
  '걸리',
  '억지',
  '내용',
  '자체',
  '좋'],
 ['졸', '작'],
 ['달팽이', '빠르', '더', '재밌'],
 ['어설프', '전개', '어이없', '결말'],
 ['부패', '로마노프 왕조', '기리', '같', '영화', '온몸', '항거', '러시아', '민중', '그저', '폭', '돌'],
 ['내용', '전개', '무난', '편이', '잘', '보'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '계',
  '에',
  '속',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오', '리플릿', '사진', '보', '불안'],
 ['단연', '최고', '하'],
 ['감독', '영화', '만들', '관객', '말', '모르', '엉망진창', '개진', '창'],
 ['이건', '우뢰', '매'],
 ['정말', '쓰레기', '영화'],
 ['진정', '위대', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '막', '문', '좋아하', '가요'],
 ['진짜', '골', '까', '눈', '부라리', '때', '쓰러지'],
 ['성룡', '영화', '최', '악인'],
 ['골', '때리', '걸스데이', '이혜리', '잘', '되'],
 ['서기', '이쁘'],
 ['완전', '재밌', '백인', '공주', '귀여움'],
 ['인상', '영화'],
 ['세', '레', '스티', '완전', '강', '추', '정말', '재밌'],
 ['재미있', '영화'],
 ['클라라', '볼라', '고', '화신', '본'],
 ['진짜', '보', '너무', '슬프', '영화'],
 ['설정', '재밌', '새롭', '에피소드', '메인', '스토리', '차차', '나오', '재밌'],
 ['신카이 마코토', '작화', '미', '유', '카나', '연기', '잘', '더', '대박', '이'],
 ['재미없', '진심', '캐스팅'],
 ['잔잔', '생각', '보', '영화인', '같'],
 ['감독', '고은님', '쓰', '영화', '안', '보'],
 ['무섭', '스토리'],
 ['영화', '속', '억지', '노골적', '술', '광고', '좀', '은은', '센스', '있', '하', '어떻'],
 ['킬링타임'],
 ['크리스마스', '떠오르', '영화'],
 ['재미있', '보', '매력', '행복'],
 ['음악', '완전히', '빠지', '보', '영화', '쪼', '산만', '하'],
 ['태어나', '처음', '영화', '중간', '나오', '불륜', '로맨스', '냐'],
 ['왕', '짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭', '하'],
 ['솔직히', '나', '별루', '덜', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '되', '패널', '가구', '거지', '명작', '드라마', '다', '망치', '다', '서운'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌', '보'],
 ['내용', '전개', '너무나', '느리'],
 ['소재', '흥미', '끌', '이야기', '전개', '투박', '몰입', '안'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '있',
  '보이',
  '안간힘',
  '쓰',
  '노력',
  '가상',
  '고증',
  '현실감',
  '떨어지',
  '설정',
  '거북',
  '도대체',
  '왜',
  '이렇',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡', '영화', '좋', '텐', '우상', '만들', '미국', '따뜻', '설정', '이건'],
 ['2년', '삶', '속', '주인공', '생애', '전부', '드러나'],
 ['별점', '가자'],
 ['별로', '다'],
 ['보', '꽤', '지나', '후', '남기', '재미있'],
 ['아니', '이', '왜', '일'],
 ['지나', '다시', '보', '되', '영화', '다시', '보', '순수', '사랑', '감동', '쇼', '펜', '연기'],
 ['올레',
  '공짜',
  '있',
  '보',
  '허',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리',
  '상대',
  '배우',
  '다',
  '따로',
  '같',
  '이건',
  '연기자',
  '문제',
  '있',
  '보',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들',
  '젤',
  '볼',
  '하'],
 ['너무', '욕심', '많', '영화', '제대로', '보이'],
 ['빵점'],
 ['베', '말', '아주', '잘', '쓰'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '하', '같', '나라', '만들', '믿'],
 ['온몸', '찌릿', '짜릿', '용기', '가지'],
 ['정말', '재미있', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '있', '재밌', '전하', '작품'],
 ['케이블', '그만', '나오'],
 ['다르', '냐', '리', '차이밍량', '안', '섞이', '짬뽕', '그릇', '담기'],
 ['여군', '재', '없', '뭐', '건지', '재', '없', '다', '재', '없', '질리', '다이'],
 ['좋'],
 ['한석규', '김혜수', '연기', '돋보이', '영화', '모르', '많이', '어설프', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '떠들석',
  '보',
  '되',
  '영화',
  '작품',
  '면',
  '여',
  '전',
  '영화',
  '믿',
  '힘들',
  '정도',
  '정말',
  '잘',
  '만들',
  '마지막',
  '후반부',
  '살짝',
  '아쉽',
  '하',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝',
  '영화'],
 ['보', '만해'],
 ['재미있', '허풍', '떨', '마'],
 ['용가리', '진짜', '짱', '짱', '매'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '꼽',
  '있',
  '작품',
  '어떻',
  '살',
  '위하',
  '고민',
  '더',
  '하',
  '되',
  '시간',
  '모건 프리먼',
  '나이',
  '들',
  '여전히',
  '섹시'],
 ['작가',
  '별로',
  '다',
  '내용',
  '이',
  '진짜',
  '맨날',
  '그냥',
  '기대',
  '재방송',
  '혹시나',
  '답',
  '없',
  '진짜'],
 ['명작', '명작', '있', '보', '보', '여운', '남', '영화'],
 ['진짜',
  '조금',
  '더',
  '손',
  '좀',
  '보',
  '왜',
  '하',
  '상업',
  '영화',
  '못하',
  '만들',
  '아쉽',
  '충분히',
  '재미있',
  '개인',
  '조금',
  '더',
  '잔인',
  '더',
  '자극',
  '노출',
  '화끈',
  '하',
  '어떻',
  '하',
  '국산',
  '영화',
  '많이',
  '아끼',
  '보이'],
 ['그만', '좀', '끌', '이제', '끝내', '지겹', '지겹'],
 [],
 ['드니', '연기', '일품', '맥스', '샘', '죽이', '하'],
 ['괜찮', '작품'],
 ['너무', '좋', '영화'],
 ['정말', '실망'],
 ['배우',
  '지',
  '안',
  '뜨',
  '영화',
  '찍',
  '껀',
  '왜',
  '안',
  '뜨',
  '진짜',
  '모르',
  '면상',
  '딱',
  '보',
  '알',
  '왜',
  '자신',
  '모르'],
 ['어린이', '좋아하', '어리', '동심', '멀리', '뜨', '낫'],
 ['무술', '인', '왜', '총', '들'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '유명', '영화'],
 ['오랜만'],
 ['종',
  '방',
  '아쉽',
  '오늘',
  '막',
  '방도',
  '잘',
  '보',
  '방송',
  '대본',
  '꽤',
  '완성도',
  '있',
  '느낌',
  '받',
  '요즘',
  '드라마',
  '막장',
  '지치',
  '향',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하',
  '어이없',
  '화이팅'],
 ['평점',
  '조절',
  '위원회',
  '나오',
  '웃음',
  '김혜선',
  '내일이 오면',
  '의',
  '김',
  '순정',
  '순정',
  '역할',
  '정도',
  '잘',
  '해내',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지',
  '있',
  '대하',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하',
  '장면',
  '같',
  '웃음'],
 ['영화', '끝나', '때', '멍하', '다', '보', '한마디', '나오', '같'],
 ['공유', '존', '잘'],
 ['상쾌', '발랄', '영화', '말', '끌', '성', '소재', '유쾌', '해설'],
 ['소파', '죽', '치', '앉', '지키', '보', '이유', '없', '작품'],
 ['로큰롤'],
 ['주되',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하',
  '알',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없',
  '배경',
  '거슬리'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '남',
  '주',
  '춤',
  '못',
  '추',
  '내용',
  '뻔하',
  '주인공',
  '목소리',
  '너무',
  '안',
  '어울리',
  '어제',
  '뛰',
  '나가',
  '참',
  '진심',
  '말리',
  '영국',
  '예산',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10',
  '안'],
 ['어리', '나이', '보', '꽤', '좋아하', '로맨틱', '코미디'],
 ['게이', '물', '인줄', '모르', '보'],
 ['알바', '끄', '절'],
 ['영화', '왜', '받', '보', '알', '이', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답', '영화', '이'],
 ['자극', '익숙', '현대인', '보', '눈', '떼', '힘들', '연출력'],
 ['뻑', '뻑', '잘', '읽', '당하'],
 ['정말',
  '짜증',
  '극치',
  '보이',
  '영화',
  '굉장히',
  '느낌',
  '뚱뚱',
  '못생기',
  '남자',
  '애',
  '발',
  '연기',
  '시종일관',
  '보',
  '고역',
  '흘러나오',
  '잔잔',
  '클래식',
  '음악',
  '조차',
  '듣',
  '싫',
  '짜증',
  '날',
  '정도',
  '상당히',
  '싫',
  '영화'],
 ['감동', '감동', '정말', '최고'],
 ['별점',
  '아깝',
  '얼마나',
  '내용',
  '진부',
  '욕',
  '밖',
  '안',
  '나오',
  '재밌',
  '하',
  '사람',
  '초딩',
  '죄송',
  '너무',
  '화가',
  '나서',
  '보',
  '없',
  '보',
  '마',
  '그냥',
  '티',
  '비판',
  '짜',
  '집기',
  '같'],
 ['왜', '하', '짜증', '안', '내'],
 ['돼지', '피', '먹', '닭목', '따', '장면', '에선', '무당', '하'],
 [],
 ['유치', '지루', '잠'],
 ['판타지', '가져가'],
 ['윤종신',
  '복귀',
  '좋',
  '이하늘',
  '도대체',
  '왜',
  '뽑히',
  '알',
  '없',
  '참가자',
  '실력',
  '따지',
  '전',
  '심사',
  '위원',
  '인격',
  '실력',
  '쌓',
  '오시',
  '길',
  '어',
  '허',
  '그만',
  '좀',
  '하'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['생', '최고', '영화'],
 ['어리',
  '시절',
  '너무',
  '무섭',
  '재미있',
  '보',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘',
  '짓',
  '금물',
  '지옥',
  '가요'],
 ['기존', '멜로', '영화', '형식', '탈피', '하', '감정', '절제', '지나치', '너무', '담백', '영화'],
 ['나', '사랑비', '서주', '쏙', '빠지', '쏙', '나', '절대', '잊', '후회', '도안', '할거'],
 ['이영화', '보', '교훈', '남은', '인생', '화려', '말', '안', '나오'],
 ['추억', '젖', '좋', '생각', '없이', '가볍', '보', '추천'],
 ['단순', '싸이코', '물', '벗어나'],
 ['이', '만들', '가요', '예전', '만들', '다시', '개봉', '한', '가요', '너무', '허', '접하'],
 ['넘', '사랑', '영화', '보고', '연잇', '보', '넘', '귀여워'],
 ['청춘 영화',
  '있',
  '감성',
  '넘치',
  '순간',
  '지나가',
  '다시',
  '돌아오',
  '테',
  '순간',
  '무한',
  '젊음',
  '있',
  '감성'],
 ['건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '달', '재', '웃음', '이안', '나'],
 ['사다코', '한', '서리', '우물', '펀치', '감동'],
 ['후세',
  '사랑',
  '되',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗',
  '이유',
  '시노',
  '출현',
  '연극',
  '으',
  '로',
  '더',
  '알리',
  '하',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '하',
  '노력',
  '더',
  '보이',
  '좋'],
 ['새벽',
  '시간',
  '하',
  '일본',
  '영화',
  '전부',
  '개',
  '졸',
  '작',
  '일본',
  '영화',
  '원래',
  '다',
  '이러'],
 ['강수연', '나가', '최정원', '신음', '신'],
 ['정말', '김혜성', '너무', '예쁘', '이현진', '웃', '정말'],
 ['가발', '쓰'],
 ['화려', '여', '정', '이인상', '깊', '배두나', '연기', '정말', '잘'],
 ['10대', '위하', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '말', '필요', '없', '그냥', '닥치', '보'],
 ['각기', '사람', '재밌', '멋지', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '알', '수없', '미묘', '사로잡', '최고'],
 ['너무너무', '훈훈'],
 ['응답하라', '은지원', '원도', '스스로', '욕'],
 ['너무', '웃기', '배꼽', '빠지', '컴', '영화', '있'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점', '믿', '없'],
 ['장', '끌', '로드', '몰락', '가져오', '오우삼', '헐리우드', '작품', '가장', '재미없', '졸', '작'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['작',
  '하나에',
  '설레',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '없',
  '드라마'],
 ['진심', '재미', '없', '너무', '평점', '높', '화나'],
 ['더럽', '재미없', '형태', '오', '닿', '허무', '완벽히', '지루', '영화', '영양가', '없', '영화'],
 ['이승기', '정말', '연기', '잘', '조연', '연기', '정말', '잘'],
 ['현실', '꿈', '꿈', '현실'],
 ['오늘', '현충일', '특집', '프로', '보', '되', '매우', '훌륭', '작품'],
 ['판', '의미', '동급'],
 ['제대', '보', '더', '재밌'],
 ['영화',
  '보',
  '마음',
  '휴가',
  '다녀오',
  '느낌',
  '소',
  '박',
  '하지',
  '잔잔',
  '지루',
  '다시',
  '보',
  '영화',
  '햇살',
  '가득',
  '이',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '좋', '짜임새', '너무', '허술'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '없',
  '아직',
  '신현준',
  '황',
  '장군',
  '연기',
  '괜찮',
  '한석규',
  '전성시대',
  '열리',
  '영화',
  '이때',
  '한석규',
  '뿅',
  '가'],
 ['일단', '재생', '괴물', '같', '서스펜스', '귀신', '같', '흡입', '력'],
 ['진짜',
  '댓글',
  '한번쯤',
  '볼',
  '영화인',
  '같',
  '죽기',
  '직전',
  '소원',
  '들어주',
  '보',
  '죽기',
  '직전',
  '막',
  '살',
  '인',
  '같',
  '감동',
  '없',
  '진짜',
  '란',
  '영화',
  '발톱',
  '때',
  '못',
  '따라가',
  '쓰레기',
  '영화',
  '와',
  '존',
  '실망'],
 ['시간',
  '좀',
  '밝',
  '긍정',
  '드라마',
  '보',
  '보기',
  '보',
  '오버',
  '연기',
  '거슬리',
  '연기',
  '인',
  '게',
  '너무',
  '표',
  '요',
  '홍혜정',
  '역',
  '이그',
  '마도',
  '후련',
  '기도',
  '고시원',
  '나머지',
  '들',
  '답답',
  '내',
  '월요일',
  '해피',
  '한',
  '보'],
 ['정치인', '모순', '인가', '정치범', '모순'],
 ['어떻', '상상', '대단'],
 ['좀', '어렵', '하', '전쟁', '대하', '묘사', '잘', '모르'],
 ['일본', '극장판', '만들', '우리나라', '에선', '개봉', '하니', '이건', '좀'],
 ['개그콘서트', '보', '전화', '끊', '개그', '콘서트', '없애'],
 ['한물', '동서양', '배우', '싸움판'],
 ['푸', '하', '하', '하', '기대', '안'],
 ['세계', '최초', '반공', '애니매이션', '역사', '가치'],
 ['감각', '시각', '바라보', '색다르', '느낌', '사랑', '문학'],
 ['엄마', '무고', '딸', '감옥살이', '시키', '시키', '이해', '안'],
 ['이영화', '제발', '책', '을', '보세', '감독', '미치', '이', '만들', '화', '날', '정도'],
 ['신나', '흑인', '음악', '아이스 큐브', '남', '없'],
 ['드럽', '재미없', '시간', '돈', '시간', '어쩌'],
 ['그저', '한마디', '알리'],
 ['진짜', '생생', '느끼'],
 ['재밌', '평점', '이상', '정도', '낮'],
 ['옥소리', '프로필', '사진', '남기', '가', '완전', '대박', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 ['아', '진짜', '너무', '좋', '짱', '짱'],
 ['연기', '굿'],
 ['영화', '다시', '안', '나오', '그때', '시절', '잘', '나타내', '같'],
 ['중간', '정도', '보', '꽤', '대단'],
 ['콩', '까', '제맛', '콩', '까', '제맛'],
 ['소설', '재미없'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['가', '알', '없', '매력', '빠지', '영화'],
 ['모녀',
  '토막',
  '살해',
  '살인자',
  '성애',
  '말이',
  '감동',
  '받',
  '사람',
  '본인',
  '피해자',
  '감동',
  '받',
  '하',
  '진심',
  '묻'],
 ['재밌', '평점', '왜', '이렇', '구리지'],
 ['보', '눈', '아깝', '진짜', '놓', '진짜', '기', '명작'],
 ['필름', '값', '아깝', '재미', '더럽', '없', '점', '수준', '매미'],
 ['보'],
 ['영화', '재미있'],
 ['남주인공',
  '연기력',
  '안',
  '습',
  '혀',
  '짧',
  '소리',
  '듣',
  '너무',
  '힘들',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '좋',
  '생각',
  '들',
  '정도',
  '영화',
  '자체',
  '적당히',
  '보',
  '하'],
 ['딱', '액션', '스릴러', '액션', '스릴', '없'],
 ['완전', '스토리', '엉망', '완전', '추'],
 ['영화', '전달', '모르', '오', '글', '거리'],
 ['좋', '영화'],
 ['더빙', '이상', '할머니', '월래', '익숙'],
 ['이', '나오'],
 ['게', '씩', '다', '부족', '씩'],
 ['정말', '말', '그대로', '쇼', '하', '영화'],
 ['전', '보', '기억', '진개', '천카이거', '감독', '이름', '기억', '두'],
 ['정은지', '언니', '연기', '잘', '노래', '잘', '부르', '마지막', '웃', '즐겁', '보', '트로트의 연인'],
 ['이'],
 ['망하'],
 ['아이', '시선', '보', '전쟁', '보', '내내', '가슴', '먹먹'],
 ['사람',
  '재미없',
  '하',
  '레알',
  '기대',
  '안',
  '생각',
  '보',
  '여자',
  '애',
  '복순이',
  '다투',
  '장면',
  '굳이',
  '없',
  '되',
  '생각',
  '몰입',
  '겁나',
  '없애',
  '어색',
  '보이'],
 ['설정', '연속극', '같', '느낌', '들', '배우', '연기', '뛰어나'],
 ['여주인공', '인터뷰', '때', '지루', '죽', '알', '그냥저냥', '킬링타임', '스릴러'],
 ['미',
  '박스',
  '오피스',
  '그냥',
  '몰아주',
  '하',
  '어떻',
  '영화',
  '하',
  '옛날',
  '90년대',
  '우뢰',
  '매',
  '수준',
  '물',
  '폭탄',
  '싸움',
  '손',
  '빔',
  '가나',
  '손',
  '물',
  '폭탄',
  '나가',
  '다르'],
 ['감독', '여자', '다', '보니', '기량', '많이', '딸리'],
 ['보'],
 ['영화', '개연', '없', '허무', '만들', '조디', '포스터', '이쁘', '모습', '남', '영화'],
 ['굳', '굳'],
 ['스토리',
  '말',
  '안',
  '개막',
  '장',
  '사랑이야',
  '기도',
  '아니',
  '예',
  '보',
  '시간',
  '돈',
  '아끼',
  '예',
  '휴',
  '보',
  '호구'],
 ['살리', '쌀', '아깝', '세기', '대사'],
 ['평점',
  '너무',
  '높',
  '전혀',
  '재미있',
  '쓸데없이',
  '말',
  '많',
  '류',
  '영화',
  '조연',
  '뒷받침',
  '중요',
  '조연',
  '내용',
  '자체',
  '전혀',
  '없',
  '여배우',
  '별로',
  '매력',
  '없',
  '이틀',
  '전',
  '저스트',
  '고위',
  '드',
  '잇',
  '애니',
  '스톤',
  '보',
  '영화',
  '보',
  '그렇',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '인가', '가', '훈련', '때', '나오', '작살'],
 ['이건',
  '시종일관',
  '왜',
  '제목',
  '야경꾼 일지',
  '냐',
  '지금',
  '넘어가',
  '달',
  '넘어가',
  '앞',
  '누',
  '군가',
  '얘기',
  '하',
  '더',
  '그렇',
  '순간',
  '훅',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '들', '이해', '가', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '없',
  '아역',
  '연기',
  '추노',
  '나오',
  '민폐',
  '언',
  '외국',
  '판',
  '인줄',
  '초반',
  '그럴싸',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '예', '결말', '이상'],
 ['딱히', '재미', '없'],
 ['송강호', '정말', '연기', '하', '위하', '태어나', '인하', '즐거움', '느끼', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리', '불후의 명작', '그립'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌',
  '살인',
  '대하',
  '감독',
  '해석',
  '정말',
  '재치',
  '있',
  '배우',
  '여',
  '전',
  '모습',
  '정말',
  '유쾌',
  '재밌'],
 ['누', '미', '라파스', '신봉선', '닮', '안', '보'],
 ['케이블', '그만', '좀', '재탕'],
 ['멋지', '정말', '멋지', '말', '이외', '하', '말', '없'],
 ['어떻', '영화', '만들', '의문', '당대', '최고', '영화', '지금', '보', '결코', '떨어지'],
 ['지금', '티', '비', '돈', '내', '보', '한심'],
 ['쓰레기', '연예인', '재기', '장'],
 ['굿', '좋'],
 ['많', '감동', '드라마'],
 ['발로',
  '만들',
  '영화',
  '지진',
  '나서',
  '주인공',
  '넘어지',
  '뒤',
  '사람',
  '유유히',
  '걷',
  '다니',
  '있',
  '발',
  'CG',
  '발',
  '연기',
  '발',
  '시나리오',
  '내용',
  '정말',
  '같'],
 ['적당히', '하', '언제', '끝나'],
 ['잊', '없', '안개', '끼', '워터', '다리', '마스코트'],
 ['곤',
  '사토시',
  '감독',
  '안타깝',
  '돌아가',
  '가슴',
  '먹먹',
  '정말',
  '천재',
  '감독',
  '암',
  '가',
  '이제',
  '와서',
  '다시',
  '보',
  '작품',
  '대작'],
 ['많', '생각', '하', '되', '예', '뼈', '지', '맘', '과', '독'],
 ['없', '줄'],
 ['어리',
  '때',
  '영화로',
  '알',
  '나이',
  '들',
  '이',
  '인생',
  '하',
  '뭉클',
  '영화',
  '세상',
  '살아가',
  '갈수록',
  '오',
  '닿',
  '많',
  '세상',
  '비정',
  '비정',
  '함마',
  '지',
  '따뜻',
  '친구'],
 ['영상', '너무나', '멋지'],
 ['비디오', '있', '보', '1997년', '도인', '줄', '모르', '정도', '잘', '만들', '긴장감', '있'],
 ['처'],
 ['만들',
  '재밌',
  '영화',
  '길',
  '좀',
  '다듬',
  '소재',
  '좋',
  '몰입',
  '감',
  '기대',
  '이상',
  '매끄럽',
  '부분',
  '있',
  '연기',
  '다',
  '잘'],
 ['철',
  '지나',
  '코미디',
  '뼈대',
  '있',
  '가문',
  '이야기',
  '섞',
  '다',
  '지루',
  '박정아',
  '비롯',
  '배우',
  '보',
  '민망',
  '연기',
  '펼치',
  '기억',
  '남',
  '없'],
 ['군더더기', '없이', '잘', '진행', '재미', '없', '문제'],
 ['심심', '재밌', '탑', '연기', '알', '배우', '포스', '잘'],
 ['다', '미', '괜찮'],
 ['지대', '짜증', '아빠', '보', '앗', '민망', '죽'],
 ['못', '주'],
 ['빠', '순이', '영화'],
 ['최악', '애니메이션', '지루', '재미없', '스토리', '진부'],
 ['좋', '의도', '다르', '불쾌', '표현법'],
 ['줄리아', '로버츠', '귀엽', '연인', '5년', '전'],
 ['신선'],
 ['예술가', '사람', '인생', '당시', '시대', '상황', '느끼', '명작'],
 ['관객', '너무', '아쉽', '영화', '베테랑', '더', '류승완', '감독', '역작', '더', '강하', '악역'],
 ['한창', '핵', '펭귄', '남북', '거짓', '평화로', '전', '국민', '속', '때', '만들', '영화'],
 ['지금', '티', '비', '못', '보'],
 ['여자', '애', '못', '해서', '죽', '답', '없'],
 ['성룡', '단연', '최', '고지'],
 ['안', '습'],
 ['감독', '의도', '전혀', '알아차리'],
 ['하나님',
  '이',
  '가정',
  '을',
  '온전히',
  '만들',
  '진리',

In [14]:
# 최소 등장 횟수 2회인 단어사전을 생성
# 토큰화된 tokens_list에서 단어들의 출현 횟수를 확인
freq = Counter(word for toks in tokens_list for word in toks)
freq

Counter({'영화': 364,
         '보': 262,
         '하': 131,
         '없': 113,
         '있': 86,
         '좋': 73,
         '진짜': 68,
         '정말': 67,
         '안': 66,
         '너무': 61,
         '연기': 58,
         '재밌': 57,
         '같': 56,
         '나오': 52,
         '만들': 51,
         '잘': 47,
         '최고': 47,
         '다': 46,
         '사람': 44,
         '왜': 43,
         '되': 41,
         '알': 38,
         '내용': 36,
         '때': 34,
         '감동': 34,
         '말': 34,
         '더': 33,
         '재미없': 32,
         '재미': 31,
         '아깝': 31,
         '배우': 31,
         '재미있': 30,
         '생각': 30,
         '시간': 29,
         '드라마': 28,
         '그냥': 28,
         '좀': 28,
         '평점': 27,
         '스토리': 27,
         '감독': 27,
         '나': 26,
         '이': 26,
         '쓰레기': 26,
         '작품': 25,
         '모르': 24,
         '완전': 23,
         '지루': 22,
         '들': 22,
         '느낌': 21,
         '보이': 20,
         '남': 20,
         '정도': 20,
         '다시': 19,
         '액션': 18,
         '이렇': 18,
         '주인공': 18,
         '느끼': 18,
         '재': 17,
         '참': 17,
         '작': 17,
         '사랑': 17,
         '마지막': 17,
         '짜증': 16,
         '이건': 16,
         '기대': 16,
         '인생': 16,
         '오': 16,
         '돈': 16,
         '가': 16,
         '속': 16,
         '일본': 16,
         '쓰': 16,
         '넘': 15,
         '그렇': 15,
         '대하': 15,
         '명작': 15,
         '살': 15,
         '이야기': 14,
         '솔직히': 14,
         '죽': 14,
         '받': 14,
         '많': 14,
         '소재': 14,
         '괜찮': 14,
         '남자': 14,
         '별로': 13,
         '무섭': 13,
         '이상': 13,
         '볼': 12,
         '멋지': 12,
         '음악': 12,
         '자체': 12,
         '어떻': 12,
         '장면': 12,
         '최악': 12,
         '기억': 12,
         '이해': 11,
         '걸': 11,
         '아쉽': 11,
         '일': 11,
         '끝나': 11,
         '전개': 11,
         '슬프': 11,
         '몰입': 11,
         '실망': 11,
         '전': 11,
         '애': 11,
         '지금': 11,
         '인간': 11,
         '까': 10,
         '절대': 10,
         '웃': 10,
         '아직': 10,
         '조금': 10,
         '유치': 10,
         '한국': 10,
         '좋아하': 10,
         '처음': 10,
         '끌': 10,
         '허': 10,
         '당시': 10,
         '그만': 10,
         '찍': 10,
         '연출': 10,
         '높': 10,
         '마음': 10,
         '굿': 10,
         '울': 9,
         '캐스팅': 9,
         '매력': 9,
         '웃음': 9,
         '감정': 9,
         '설정': 9,
         '진심': 9,
         '많이': 9,
         '짱': 9,
         '못': 9,
         '물': 9,
         '잇': 9,
         '포스터': 8,
         '막': 8,
         '낮': 8,
         '꽤': 8,
         '위하': 8,
         '졸': 8,
         '한': 8,
         '크': 8,
         '신선': 8,
         '제일': 8,
         '연기력': 8,
         '결말': 8,
         '냐': 8,
         '따뜻': 8,
         '지나': 8,
         '아니': 8,
         '전혀': 8,
         '믿': 8,
         '여운': 8,
         '지': 8,
         '표현': 8,
         '스릴러': 8,
         '내내': 8,
         '여자': 8,
         '귀엽': 8,
         '끝': 8,
         '너무나': 7,
         '욕': 7,
         '가장': 7,
         '정신': 7,
         '알바': 7,
         '기분': 7,
         '노력': 7,
         '먹': 7,
         '시청률': 7,
         '눈': 7,
         '최': 7,
         '인상': 7,
         '미': 7,
         '빠지': 7,
         '아주': 7,
         '힘들': 7,
         '나이': 7,
         '자신': 7,
         '어리': 7,
         '요즘': 7,
         '코미디': 7,
         '이유': 7,
         '아름답': 7,
         '티': 7,
         '필요': 7,
         '책': 7,
         '부족': 7,
         '애니': 7,
         '슬픔': 7,
         '비디오': 7,
         '반전': 7,
         '공포': 7,
         '원작': 6,
         '긴장감': 6,
         '가족': 6,
         '눈물': 6,
         '나서': 6,
         '멜로': 6,
         '노': 6,
         '코': 6,
         '발': 6,
         '나가': 6,
         '단순': 6,
         '잔잔': 6,
         '길': 6,
         '공감': 6,
         '초반': 6,
         '수준': 6,
         '누': 6,
         '이랑': 6,
         '다니': 6,
         '가슴': 6,
         '혼자': 6,
         '대단': 6,
         '이제': 6,
         '가요': 6,
         '로맨스': 6,
         '삶': 6,
         '다르': 6,
         '막장': 6,
         '주': 6,
         '날': 6,
         '짜': 6,
         '시절': 6,
         '시리즈': 6,
         '개': 6,
         '현실': 6,
         '더럽': 6,
         '게': 6,
         '전쟁': 6,
         '제발': 6,
         '시나리오': 6,
         '친구': 6,
         '부분': 6,
         '급': 6,
         '또': 6,
         '모두': 6,
         '키': 6,
         '더빙': 5,
         '살리': 5,
         '화려': 5,
         '자극': 5,
         '웃기': 5,
         '갈수록': 5,
         '구성': 5,
         '수작': 5,
         '꼭': 5,
         '별점': 5,
         '대체': 5,
         '관객': 5,
         '캐릭터': 5,
         '조절': 5,
         '딱': 5,
         '잊': 5,
         '깊': 5,
         '그저': 5,
         '중간': 5,
         '모습': 5,
         '예': 5,
         '큐': 5,
         '살인': 5,
         '노래': 5,
         '맞': 5,
         '어이없': 5,
         '매': 5,
         '추': 5,
         '대박': 5,
         '흥미': 5,
         '현실감': 5,
         '후': 5,
         '남기': 5,
         '뭐': 5,
         '건지': 5,
         '답': 5,
         '손': 5,
         '충분히': 5,
         '어린이': 5,
         '화이팅': 5,
         '예산': 5,
         '읽': 5,
         '내': 5,
         '어': 5,
         '추억': 5,
         '이영화': 5,
         '없이': 5,
         '추천': 5,
         '개봉': 5,
         '접하': 5,
         '순간': 5,
         '으': 5,
         '예쁘': 5,
         '의미': 5,
         '요': 5,
         '세계': 5,
         '을': 5,
         '미치': 5,
         '아': 5,
         '기': 5,
         '보니': 5,
         '돌리': 5,
         '안타깝': 5,
         '결국': 5,
         '싸우': 5,
         '사': 5,
         '이후': 5,
         '완벽': 5,
         '전작': 5,
         '점수': 5,
         '도': 5,
         '좀비': 5,
         '초등학교': 4,
         '드럽': 4,
         '극장': 4,
         '고': 4,
         '이리': 4,
         '작가': 4,
         '방법': 4,
         '낭비': 4,
         '뛰어나': 4,
         '극': 4,
         '소설': 4,
         '라': 4,
         '게이': 4,
         '어쩌': 4,
         '그대로': 4,
         '악역': 4,
         '계속': 4,
         '우리나라': 4,
         '깊이': 4,
         '예전': 4,
         '비슷': 4,
         '안보': 4,
         '억지': 4,
         '어설프': 4,
         '흥행': 4,
         '갈등': 4,
         '에': 4,
         '시작': 4,
         '유': 4,
         '영화인': 4,
         '태어나': 4,
         '짬뽕': 4,
         '거지': 4,
         '망치': 4,
         '보지': 4,
         '마라': 4,
         '특유': 4,
         '전부': 4,
         '쇼': 4,
         '문제': 4,
         '어울리': 4,
         '나라': 4,
         '가지': 4,
         '상황': 4,
         '한석규': 4,
         '잔인': 4,
         '뜨': 4,
         '에선': 4,
         '오랜만': 4,
         '왠지': 4,
         '한마디': 4,
         '존': 4,
         '치': 4,
         '배경': 4,
         '진부': 4,
         '나쁘': 4,
         '짓': 4,
         '달': 4,
         '알리': 4,
         '그때': 4,
         '대사': 4,
         '닿': 4,
         '코믹': 4,
         '색다르': 4,
         '짧': 4,
         '먹먹': 4,
         '개연': 4,
         '제목': 4,
         '군가': 4,
         '얘기': 4,
         '줄': 4,
         '영상': 4,
         '감': 4,
         '탑': 4,
         '사실': 4,
         '떠나': 4,
         '충분': 4,
         '레전드': 4,
         '소피': 4,
         '바라': 4,
         '고의': 4,
         '공부': 4,
         '다운': 4,
         '감사': 4,
         '멀': 4,
         '자막': 4,
         '타': 4,
         '기키': 4,
         '유럽': 4,
         '영상미': 4,
         '특히': 4,
         '예고편': 4,
         '연예': 4,
         '초딩': 3,
         '오버': 3,
         '가볍': 3,
         '돋보이': 3,
         '늙': 3,
         '떼': 3,
         '학년': 3,
         '반개': 3,
         '반복': 3,
         '못하': 3,
         '감성': 3,
         '절제': 3,
         '보다': 3,
         '취향': 3,
         '어거지': 3,
         '이기': 3,
         '난': 3,
         '뒤': 3,
         '드': 3,
         '착하': 3,
         '음식': 3,
         '평범': 3,
         '주제': 3,
         '중반': 3,
         '끄': 3,
         '연출력': 3,
         '90년대': 3,
         '장애': 3,
         '거도': 3,
         '맘': 3,
         '불가': 3,
         '데': 3,
         '메': 3,
         '잠시': 3,
         '동화': 3,
         '행복': 3,
         '콩': 3,
         '충격': 3,
         '완전히': 3,
         '무겁': 3,
         '심심': 3,
         '언제': 3,
         '바로': 3,
         '듣': 3,
         '민간인': 3,
         '학살': 3,
         '이정': 3,
         '에피소드': 3,
         '재탕': 3,
         '신': 3,
         '실력': 3,
         '조작': 3,
         '열리': 3,
         '들어가': 3,
         '걸리': 3,
         '매우': 3,
         '아햏햏': 3,
         '진정': 3,
         '별루': 3,
         '성룡': 3,
         '때리': 3,
         '이쁘': 3,
         '새롭': 3,
         '쪼': 3,
         '불륜': 3,
         '왕': 3,
         '덜': 3,
         '떨어지': 3,
         '도대체': 3,
         '미국': 3,
         '순수': 3,
         '아들': 3,
         '베': 3,
         '리': 3,
         '여': 3,
         '마': 3,
         '개인': 3,
         '국산': 3,
         '아끼': 3,
         '지겹': 3,
         '죽이': 3,
         '낫': 3,
         '인': 3,
         '종': 3,
         '방': 3,
         '오늘': 3,
         '그리': 3,
         '사극': 3,
         '의하': 3,
         '유쾌': 3,
         '엉망': 3,
         '절': 3,
         '시종일관': 3,
         '상당히': 3,
         '얼마나': 3,
         '밖': 3,
         '피': 3,
         '잠': 3,
         '판타지': 3,
         '옛날': 3,
         '후회': 3,
         '생명': 3,
         '너무너무': 3,
         '네이버': 3,
         '장': 3,
         '제로': 3,
         '허무': 3,
         '조연': 3,
         '특집': 3,
         '판': 3,
         '서스펜스': 3,
         '귀신': 3,
         '댓글': 3,
         '한번쯤': 3,
         '답답': 3,
         '묘사': 3,
         '극장판': 3,
         '역사': 3,
         '가치': 3,
         '시키': 3,
         '흑인': 3,
         '범죄': 3,
         '느와르': 3,
         '놓': 3,
         '습': 3,
         '소리': 3,
         '적당히': 3,
         '글': 3,
         '이름': 3,
         '두': 3,
         '망하': 3,
         '아이': 3,
         '시선': 3,
         '겁나': 3,
         '여주인공': 3,
         '중요': 3,
         '여배우': 3,
         '지루함': 3,
         '닮': 3,
         '비': 3,
         '연예인': 3,
         '돌아가': 3,
         '과': 3,
         '세상': 3,
         '아빠': 3,
         '앗': 3,
         '의도': 3,
         '강하': 3,
         '첨': 3,
         '해': 3,
         '탄탄': 3,
         '사회': 3,
         '실제': 3,
         '검술': 3,
         '미스': 3,
         '그러': 3,
         '멋있': 3,
         '빨리': 3,
         '중심': 3,
         '나중': 3,
         '사촌': 3,
         '제가': 3,
         '흐르': 3,
         '실제로': 3,
         '늦': 3,
         '망': 3,
         '도움': 3,
         '장난': 3,
         '보내': 3,
         '서로': 3,
         '잃': 3,
         '유대인': 3,
         '엔': 3,
         '딩': 3,
         '영화관': 3,
         '몰': 3,
         '놀': 3,
         '청춘': 3,
         '복수': 3,
         '해주': 3,
         '평생': 3,
         '생각나': 3,
         '짐승': 3,
         '숨': 3,
         '싸구려': 3,
         '밝히': 3,
         '질질': 3,
         '터지': 3,
         '겨': 3,
         '상영': 3,
         '미화': 3,
         '엉성': 3,
         '싫어하': 3,
         '아저씨': 3,
         '역겹': 3,
         '일찍': 3,
         '얼굴': 3,
         '같이': 3,
         '간만': 3,
         '독립': 3,
         '업': 3,
         '외계인': 3,
         '주온': 3,
         '존재': 3,
         '기억나': 3,
         '차라리': 3,
         '실화': 3,
         '동생': 3,
         '아이들': 3,
         '여성': 3,
         '분위기': 3,
         '비하': 3,
         '궁금': 3,
         '목소리': 2,
         '용': 2,
         '별': 2,
         '제대로': 2,
         '생활': 2,
         '발로': 2,
         '헐리우드': 2,
         '향수': 2,
         '담백': 2,
         '깔끔': 2,
         '기사': 2,
         '자꾸': 2,
         '깔': 2,
         '깨알': 2,
         '러': 2,
         '뜻': 2,
         '가능': 2,
         '만찬': 2,
         '드리': 2,
         '납득': 2,
         '고추': 2,
         '센스': 2,
         '탁월': 2,
         '포스': 2,
         '깨닫': 2,
         '꽃': 2,
         '죄인': 2,
         '열정': 2,
         '안나': 2,
         '평가': 2,
         '은은': 2,
         '서리': 2,
         '일탈': 2,
         '이민기': 2,
         '패': 2,
         '물건': 2,
         '상태': 2,
         '마이너스': 2,
         '가르': 2,
         '르': 2,
         '매운맛': 2,
         '간다': 2,
         '꼬마': 2,
         '일본인': 2,
         '당황': 2,
         '일상': 2,
         '전개도': 2,
         '느리': 2,
         '맨날': 2,
         '빨리빨리': 2,
         '가슴속': 2,
         '살인자': 2,
         '산': 2,
         '이틀': 2,
         '집': 2,
         '온몸': 2,
         '폭': 2,
         '계': 2,
         '뻔하': 2,
         '사진': 2,
         '단연': 2,
         '우뢰': 2,
         '내일': 2,
         '골': 2,
         '공주': 2,
         '강': 2,
         '술': 2,
         '킬링타임': 2,
         '떠오르': 2,
         '허풍': 2,
         '거북': 2,
         '스스로': 2,
         '텐': 2,
         '생애': 2,
         '연기자': 2,
         '상대': 2,
         '따로': 2,
         '젤': 2,
         '교훈': 2,
         '케이블': 2,
         '그릇': 2,
         '면': 2,
         '살짝': 2,
         '떨': 2,
         '이제서야': 2,
         '감히': 2,
         '고민': 2,
         '여전히': 2,
         '섹시': 2,
         '혹시나': 2,
         '상업': 2,
         '노출': 2,
         '화끈': 2,
         '끝내': 2,
         '드니': 2,
         '일품': 2,
         '껀': 2,
         '총': 2,
         '외국': 2,
         '상상': 2,
         '심하': 2,
         '의': 2,
         '순정': 2,
         '앉': 2,
         '일반': 2,
         '통하': 2,
         '게임': 2,
         '거슬리': 2,
         '인줄': 2,
         '익숙': 2,
         '뻑': 2,
         '당하': 2,
         '극치': 2,
         '굉장히': 2,
         '싫': 2,
         '따지': 2,
         '인격': 2,
         '기존': 2,
         '쏙': 2,
         '도안': 2,
         '남은': 2,
         '싸이코': 2,
         '돌아오': 2,
         '무한': 2,
         '후세': 2,
         '시노': 2,
         '출현': 2,
         '새벽': 2,
         '정': 2,
         '미묘': 2,
         '훈훈': 2,
         '가져오': 2,
         '오우삼': 2,
         '인지': 2,
         '꿈': 2,
         '훌륭': 2,
         '동급': 2,
         '소': 2,
         '하지': 2,
         '짜임새': 2,
         '허술': 2,
         '일단': 2,
         '괴물': 2,
         '죽기': 2,
         '직전': 2,
         '란': 2,
         '보기': 2,
         '역': 2,
         '이그': 2,
         '기도': 2,
         '정치인': 2,
         '모순': 2,
         '인가': 2,
         '하니': 2,
         '전화': 2,
         '개그': 2,
         '없애': 2,
         '푸': 2,
         '감각': 2,
         '바라보': 2,
         '엄마': 2,
         '딸': 2,
         '화': 2,
         '생생': 2,
         '제맛': 2,
         '말이': 2,
         '본인': 2,
         '피해자': 2,
         '필름': 2,
         '값': 2,
         '남주인공': 2,
         '혀': 2,
         '분이': 2,
         '스릴': 2,
         '전달': 2,
         '거리': 2,
         '씩': 2,
         '언니': 2,
         '부르': 2,
         '즐겁': 2,
         '레알': 2,
         '어색': 2,
         '폭탄': 2,
         '가나': 2,
         '딸리': 2,
         '굳': 2,
         '호구': 2,
         '세기': 2,
         '쓸데없이': 2,
         '류': 2,
         '고위': 2,
         '넘어가': 2,
         '아역': 2,
         '민폐': 2,
         '그럴싸': 2,
         '딱히': 2,
         '송강호': 2,
         '그립': 2,
         '해석': 2,
         '한심': 2,
         '끼': 2,
         '영화로': 2,
         '비정': 2,
         '다듬': 2,
         '비롯': 2,
         '민망': 2,
         '군더더기': 2,
         '진행': 2,
         '빠': 2,
         '애니메이션': 2,
         '불쾌': 2,
         '연인': 2,
         '5년': 2,
         '국민': 2,
         '해서': 2,
         '하나님': 2,
         '이신': 2,
         '흥미진진': 2,
         '점점': 2,
         '이번': 2,
         '지존파': 2,
         '삼': 2,
         '정당화': 2,
         '정부': 2,
         '탓': 2,
         '중국': 2,
         '하트': 2,
         '평균': 2,
         '슬': 2,
         '하기': 2,
         '자': 2,
         '모으': 2,
         '메세지': 2,
         '영화사': 2,
         '히어로': 2,
         '놀이': 2,
         '사건': 2,
         '인물': 2,
         '빌리': 2,
         '우연히': 2,
         '절망': 2,
         '챙기': 2,
         '거부': 2,
         '맛': 2,
         '어마어마': 2,
         '똥': 2,
         '원주민': 2,
         '일어나': 2,
         '우': 2,
         '견자단': 2,
         '정말로': 2,
         '순위': 2,
         '그런지': 2,
         '여배우들': 2,
         '그래픽': 2,
         '평론가': 2,
         '바꾸': 2,
         '느': 2,
         '밥': 2,
         '악의': 2,
         '엄청': 2,
         '자식': 2,
         '살아오': 2,
         '확실히': 2,
         '생기': 2,
         '사라지': 2,
         '아픔': 2,
         '인형': 2,
         '찌': 2,
         '샤넬': 2,
         '세월': 2,
         '찰나': 2,
         '영원': 2,
         '관하': 2,
         '두근거리': 2,
         '아무리': 2,
         '용서': 2,
         '초가': 2,
         '갑자기': 2,
         '선생님': 2,
         '미안': 2,
         '쥐': 2,
         '무기': 2,
         '약간': 2,
         '빼': 2,
         '녀': 2,
         '끌리': 2,
         '디테일': 2,
         '찡': 2,
         '문화': 2,
         '전반': 2,
         '변화': 2,
         '벤지': 2,
         '막히': 2,
         '곳곳': 2,
         '치밀': 2,
         '안되': 2,
         '봄': 2,
         '라면': 2,
         '폭풍': 2,
         '함부로': 2,
         '남녀': 2,
         '웬만': 2,
         '잘못': 2,
         '차': 2,
         '매니아': 2,
         '이하': 2,
         '오르': 2,
         '공포물': 2,
         '귀': 2,
         '은': 2,
         '벌써': 2,
         '관람': 2,
         '신분': 2,
         '최근': 2,
         '삼류': 2,
         '스타': 2,
         '몸매': 2,
         '심형래': 2,
         '전체': 2,
         '주연': 2,
         '엄청나': 2,
         '초등': 2,
         '근래': 2,
         '제작자': 2,
         '호화': 2,
         '님': 2,
         '제작': 2,
         '원하': 2,
         '평': 2,
         '극장가': 2,
         '머리': 2,
         '묻어나': 2,
         '여정': 2,
         '덕': 2,
         '박수': 2,
         '끼우': 2,
         '맞추': 2,
         '무어': 2,
         '최루': 2,
         '걸작': 2,
         '남편': 2,
         '재밌는 영화': 2,
         '쏘': 2,
         '데리': 2,
         '라이': 2,
         '아련': 2,
         '박사': 2,
         '록': 2,
         '철학': 2,
         '13구역': 2,
         '남성': 2,
         '요소': 2,
         '홍보': 2,
         '팔': 2,
         '열': 2,
         '디': 2,
         '주목': 2,
         '뇌': 2,
         '죽음': 2,
         '우주': 2,
         '맡': 2,
         '예술': 2,
         '보통': 2,
         '고도': 2,
         '겪': 2,
         '쉬': 2,
         '즐기': 2,
         '여주': 2,
         '시점': 2,
         '라이언': 2,
         '일병': 2,
         '참고': 2,
         '자위': 2,
         '이거': 2,
         '차리': 2,
         '선정': 2,
         '솔로': 2,
         '링': 2,
         ...})

In [15]:
freq1 = dict()
for toks in tokens_list:
    for word in toks:
        if word in freq1.keys():
            freq1[word] += 1
        else:
            freq1[word] = 1
freq1

{'더빙': 5,
 '진짜': 68,
 '짜증': 16,
 '나': 26,
 '목소리': 2,
 '포스터': 8,
 '초딩': 3,
 '영화': 364,
 '오버': 3,
 '연기': 58,
 '가볍': 3,
 '교도소': 1,
 '이야기': 14,
 '솔직히': 14,
 '재미': 31,
 '없': 113,
 '평점': 27,
 '조정': 1,
 '익살': 1,
 '돋보이': 3,
 '스파이더맨': 1,
 '늙': 3,
 '보이': 20,
 '하': 131,
 '커스틴 던스트': 1,
 '너무나': 7,
 '막': 8,
 '걸음마': 1,
 '떼': 3,
 '초등학교': 4,
 '학년': 3,
 '용': 2,
 '별': 2,
 '반개': 3,
 '아깝': 31,
 '원작': 6,
 '긴장감': 6,
 '제대로': 2,
 '살리': 5,
 '욕': 7,
 '나오': 52,
 '이응경': 1,
 '길용우': 1,
 '생활': 2,
 '이': 26,
 '정말': 67,
 '발로': 2,
 '납치': 1,
 '감금': 1,
 '반복': 3,
 '드라마': 28,
 '가족': 6,
 '못하': 3,
 '사람': 44,
 '모이': 1,
 '액션': 18,
 '있': 86,
 '안': 66,
 '왜': 43,
 '낮': 8,
 '꽤': 8,
 '보': 262,
 '헐리우드': 2,
 '화려': 5,
 '너무': 61,
 '길들이': 1,
 '볼': 12,
 '때': 34,
 '눈물': 6,
 '나서': 6,
 '죽': 14,
 '향수': 2,
 '자극': 5,
 '허진호': 1,
 '감성': 3,
 '절제': 3,
 '멜로': 6,
 '달인': 1,
 '울': 9,
 '손들': 1,
 '횡단보도': 1,
 '건너': 1,
 '뛰쳐나오': 1,
 '이범수': 1,
 '드럽': 4,
 '담백': 2,
 '깔끔': 2,
 '좋': 73,
 '신문': 1,
 '기사': 2,
 '로만': 1,
 '보다': 3,
 '자꾸': 2,
 '잊어버리': 1,
 '취향': 3,
 '존중': 1,
 '극장': 4,
 '가장': 7,
 '노': 6,
 '재': 17,
 '감동': 34,
 '스토리': 27,
 '어거지': 3,
 '매번': 1,
 '긴장': 1,
 '참': 17,
 '웃기': 5,
 '바스코': 1,
 '이기': 3,
 '락스': 1,
 '코': 6,
 '까': 10,
 '고': 4,
 '바비': 1,
 '아이돌': 1,
 '깔': 2,
 '그냥': 28,
 '안달': 1,
 '난': 3,
 '굿바이 레닌': 1,
 '표절': 1,
 '이해': 11,
 '뒤': 3,
 '갈수록': 5,
 '재미없': 32,
 '이건': 16,
 '깨알': 2,
 '캐스팅': 9,
 '질퍽': 1,
 '산뜻': 1,
 '내용': 36,
 '구성': 5,
 '잘': 47,
 '버': 1,
 '러': 2,
 '진': 1,
 '드': 3,
 '약탈': 1,
 '위하': 8,
 '변명': 1,
 '착하': 3,
 '절대': 10,
 '심오': 1,
 '뜻': 2,
 '학생': 1,
 '선생': 1,
 '놀아나': 1,
 '웃': 10,
 '가능': 2,
 '지루': 22,
 '같': 56,
 '음식': 3,
 '만찬': 2,
 '넘': 15,
 '별로': 13,
 '핀란드': 1,
 '풍경': 1,
 '평범': 3,
 '수작': 5,
 '말씀': 1,
 '드리': 2,
 '주제': 3,
 '중반': 3,
 '다': 46,
 '짜르': 1,
 '납득': 2,
 '그렇': 15,
 '꼭': 5,
 '걸': 11,
 '끄': 3,
 '고추': 2,
 '털': 1,
 '카밀라': 1,
 '벨': 1,
 '발': 6,
 '센스': 2,
 '연출력': 3,
 '탁월': 2,
 '90년대': 3,
 '엄': 1,
 '포스': 2,
 '위력': 1,
 '다시': 19,
 '깨닫': 2,
 '남': 20,
 '꽃': 2,
 '검사': 1,
 '완전': 23,
 '명품': 1,
 '졸': 8,
 '쓰레기': 26,
 '시간': 29,
 '재밌': 57,
 '별점': 5,
 '이리': 4,
 '은고': 1,
 '라도': 1,
 '기대': 16,
 '죄인': 2,
 '아직': 10,
 '인생': 16,
 '최고': 47,
 '패션': 1,
 '대하': 15,
 '열정': 2,
 '안나': 2,
 '윈': 1,
 '투어': 1,
 '키이라 나이틀리': 1,
 '대체': 5,
 '정신': 7,
 '장애': 3,
 '틱': 1,
 '원': 1,
 '작가': 4,
 '나가': 6,
 '유령': 1,
 '재미있': 30,
 '관객': 5,
 '이렇': 18,
 '평가': 2,
 '받': 14,
 '모르': 24,
 '단순': 6,
 '은은': 2,
 '매력': 9,
 '알바': 7,
 '무섭': 13,
 '거도': 3,
 '싱겁': 1,
 '낚이': 1,
 '오': 16,
 '서리': 2,
 '한': 8,
 '굶주리': 1,
 '맘': 3,
 '들': 22,
 '방법': 4,
 '윤제문': 1,
 '멋지': 12,
 '배우': 31,
 '발견': 1,
 '되': 41,
 '소소': 1,
 '일탈': 2,
 '잔잔': 6,
 '미소': 1,
 '머금': 1,
 '음악': 12,
 '조금': 10,
 '아쉽': 11,
 '올리': 1,
 '속지': 1,
 '마시': 1,
 '길': 6,
 '낭비': 4,
 '돈': 16,
 '리얼리티': 1,
 '뛰어나': 4,
 '크': 8,
 '공감': 6,
 '가': 16,
 '이민기': 2,
 '캐릭터': 5,
 '정신의학': 1,
 '분노': 1,
 '조절': 5,
 '초기': 1,
 '증상': 1,
 '일': 11,
 '툭하면': 1,
 '패': 2,
 '물건': 2,
 '파손': 1,
 '오바': 1,
 '극': 4,
 '초반': 6,
 '신선': 8,
 '상태': 2,
 '불가': 3,
 '마이너스': 2,
 '수준': 6,
 '딱': 5,
 '알': 38,
 '북한': 1,
 '만들': 51,
 '대': 1,
 '사랑합니다': 1,
 '데': 3,
 '리스': 1,
 '타르': 1,
 '가르': 2,
 '용의': 1,
 '주인': 1,
 '누': 6,
 '이랑': 6,
 '근친상간': 1,
 '다니': 6,
 '소설': 4,
 '속': 16,
 '제일': 8,
 '자이': 1,
 '메': 3,
 '라': 4,
 '니스': 1,
 '드래곤': 1,
 '웃음': 9,
 '감독': 27,
 '토르': 1,
 '다크 월드': 1,
 '잡수': 1,
 '기본': 1,
 '선방': 1,
 '영혼': 1,
 '어루만지': 1,
 '거치': 1,
 '세상사': 1,
 '잠시': 3,
 '잊': 5,
 '동화': 3,
 '행복': 3,
 '르': 2,
 '게이': 4,
 '작': 17,
 '매운맛': 2,
 '콩': 3,
 '진호': 1,
 '간다': 2,
 '가슴': 6,
 '시리': 1,
 '자체': 12,
 '꼬마': 2,
 '애가': 1,
 '원한': 1,
 '깊': 5,
 '혼자': 6,
 '나대': 1,
 '어쩌': 4,
 '충격': 3,
 '기분': 7,
 '완전히': 3,
 '푹': 1,
 '꺼지': 1,
 '느낌': 21,
 '활력': 1,
 '무겁': 3,
 '지독': 1,
 '차갑': 1,
 '자비': 1,
 '그저': 5,
 '일본인': 2,
 '상상력': 1,
 '대단': 6,
 '생각': 30,
 '심심': 3,
 '백봉기': 1,
 '언제나': 1,
 '그대로': 4,
 '들어맞': 1,
 '예측': 1,
 '카리스마': 1,
 '악역': 4,
 '불알': 1,
 '당황': 2,
 '아무튼': 1,
 '중간': 5,
 '끝나': 11,
 '함속': 1,
 '녹': 1,
 '아든': 1,
 '일상': 2,
 '밋밋': 1,
 '계속': 4,
 '전개도': 2,
 '느리': 2,
 '주인공': 18,
 '은희': 1,
 '컷': 1,
 '소극': 1,
 '모습': 5,
 '맨날': 2,
 '언제': 3,
 '전개': 11,
 '좀': 28,
 '빨리빨리': 2,
 '사랑': 17,
 '가슴속': 2,
 '감정': 9,
 '헤집': 1,
 '예': 5,
 '요정': 1,
 '말': 34,
 '많': 14,
 '큐': 5,
 '우리나라': 4,
 '슬프': 11,
 '현대사': 1,
 '단면': 1,
 '깊이': 4,
 '사죄': 1,
 '바로': 3,
 '잡기': 1,
 '노력': 7,
 '듣': 3,
 '보도': 1,
 '연맹': 1,
 '민간인': 3,
 '학살': 3,
 '이정': 3,
 '명백': 1,
 '살인': 5,
 '살인자': 2,
 '예전': 4,
 '작품': 25,
 '에피소드': 3,
 '재탕': 3,
 '삼탕': 1,
 '사골': 1,
 '우려': 1,
 '먹': 7,
 '산': 2,
 '시청률': 7,
 '아예': 1,
 '이제': 6,
 '김남길': 1,
 '연기력': 8,
 '몰입': 11,
 '불구': 1,
 '손예진': 1,
 '비슷': 4,
 '안보': 4,
 '신': 3,
 '노래': 5,
 '실력': 3,
 '뽑': 1,
 '맞': 5,
 '박시환': 1,
 '가면': 1,
 '망신': 1,
 '일본': 16,
 '유치': 10,
 '이틀': 2,
 '넣': 1,
 '조작': 3,
 '열리': 3,
 '집': 2,
 '활짝': 1,
 '들어가': 3,
 '문자': 1,
 '비번': 1,
 '걸리': 3,
 '억지': 4,
 '달팽이': 1,
 '빠르': 1,
 '더': 33,
 '어설프': 4,
 '어이없': 5,
 '결말': 8,
 '부패': 1,
 '로마노프 왕조': 1,
 '기리': 1,
 '온몸': 2,
 '항거': 1,
 '러시아': 1,
 '민중': 1,
 '폭': 2,
 '돌': 1,
 '무난': 1,
 '편이': 1,
 '매우': 3,
 '실망': 11,
 '한국': 10,
 '흥행': 4,
 '코드': 1,
 '갈등': 4,
 '계': 2,
 '에': 4,
 '화해': 1,
 '남발': 1,
 '뻔하': 2,
 '아햏햏': 3,
 '시작': 4,
 '3분': 1,
 '리플릿': 1,
 '사진': 2,
 '불안': 1,
 '단연': 2,
 '엉망진창': 1,
 '개진': 1,
 '창': 1,
 '우뢰': 2,
 '매': 5,
 '진정': 3,
 '위대': 1,
 '별루': 3,
 '내일': 2,
 '조미': 1,
 '문': 1,
 '좋아하': 10,
 '가요': 6,
 '골': 2,
 '눈': 7,
 '부라리': 1,
 '쓰러지': 1,
 '성룡': 3,
 '최': 7,
 '악인': 1,
 '때리': 3,
 '걸스데이': 1,
 '이혜리': 1,
 '서기': 1,
 '이쁘': 3,
 '백인': 1,
 '공주': 2,
 '귀여움': 1,
 '인상': 7,
 '세': 1,
 '레': 1,
 '스티': 1,
 '강': 2,
 '추': 5,
 '클라라': 1,
 '볼라': 1,
 '화신': 1,
 '본': 1,
 '설정': 9,
 '새롭': 3,
 '메인': 1,
 '차차': 1,
 '신카이 마코토': 1,
 '작화': 1,
 '미': 7,
 '유': 4,
 '카나': 1,
 '대박': 5,
 '진심': 9,
 '영화인': 4,
 '고은님': 1,
 '쓰': 16,
 '노골적': 1,
 '술': 2,
 '광고': 1,
 '어떻': 12,
 '킬링타임': 2,
 '크리스마스': 1,
 '떠오르': 2,
 '빠지': 7,
 '쪼': 3,
 '산만': 1,
 '태어나': 4,
 '처음': 10,
 '불륜': 3,
 '로맨스': 6,
 '냐': 8,
 '왕': 3,
 '아주': 7,
 '짬뽕': 4,
 '믹스': 1,
 '음향': 1,
 '덜': 3,
 '기준': 1,
 '패널': 1,
 '가구': 1,
 '거지': 4,
 '명작': 15,
 '망치': 4,
 '서운': 1,
 '이상해': 1,
 '몬스터 주식회사': 1,
 '3D': 1,
 '소재': 14,
 '흥미': 5,
 '끌': 10,
 '투박': 1,
 '보지': 4,
 '마라': 4,
 '중국인': 1,
 '특유': 4,
 '과장': 1,
 '허풍': 2,
 '안간힘': 1,
 '가상': 1,
 '고증': 1,
 '현실감': 5,
 '떨어지': 3,
 '거북': 2,
 '도대체': 3,
 '스스로': 2,
 '대포': 1,
 '장하': 1,
 '불법체류': 1,
 '때려잡': 1,
 '텐': 2,
 '우상': 1,
 '미국': 3,
 '따뜻': 8,
 '2년': 1,
 '삶': 6,
 '생애': 2,
 '전부': 4,
 '드러나': 1,
 '가자': 1,
 '지나': 8,
 '후': 5,
 '남기': 5,
 '아니': 8,
 '순수': 3,
 '쇼': 4,
 '펜': 1,
 '올레': 1,
 '공짜': 1,
 '허': 10,
 '문제': 4,
 '연기자': 2,
 '전혀': 8,
 '배역': 1,
 '어울리': 4,
 '상대': 2,
 '따로': 2,
 '라미란': 1,
 '아들': 3,
 '젤': 2,
 '욕심': 1,
 '빵점': 1,
 '베': 3,
 '모자': 1,
 '라진': 1,
 '도둑들': 1,
 '뫼비우스': 1,
 '나라': 4,
 '믿': 8,
 '찌릿': 1,
 '짜릿': 1,
 '용기': 1,
 '가지': 4,
 '교훈': 2,
 '당시': 10,
 '상황': 4,
 '주입식': 1,
 '전하': 1,
 '케이블': 2,
 '그만': 10,
 '다르': 6,
 '리': 3,
 '차이밍량': 1,
 '섞이': 1,
 '그릇': 2,
 '담기': 1,
 '여군': 1,
 '뭐': 5,
 '건지': 5,
 '질리': 1,
 '다이': 1,
 '한석규': 4,
 '김혜수': 1,
 '많이': 9,
 '에볼라바이러스': 1,
 '떠들석': 1,
 '면': 2,
 '여': 3,
 '전': 11,
 '힘들': 7,
 '정도': 20,
 '마지막': 17,
 '후반부': 1,
 '살짝': 2,
 '도면': 1,
 '만해': 1,
 '떨': 2,
 '마': 3,
 '용가리': 1,
 '짱': 9,
 '이제서야': 2,
 '감히': 2,
 '하나로': 1,
 '꼽': 1,
 '살': 15,
 '고민': 2,
 '모건 프리먼': 1,
 '나이': 7,
 '여전히': 2,
 '섹시': 2,
 '재방송': 1,
 '혹시나': 2,
 '답': 5,
 '여운': 8,
 '손': 5,
 '상업': 2,
 '충분히': 5,
 '개인': 3,
 '잔인': 4,
 '노출': 2,
 '화끈': 2,
 '국산': 3,
 '아끼': 3,
 '끝내': 2,
 '지겹': 3,
 '드니': 2,
 '일품': 2,
 '맥스': 1,
 '샘': 1,
 '죽이': 3,
 '괜찮': 14,
 '지': 8,
 '뜨': 4,
 '찍': 10,
 '껀': 2,
 '면상': 1,
 '자신': 7,
 '어린이': 5,
 '어리': 7,
 '동심': 1,
 '멀리': 1,
 '낫': 3,
 '무술': 1,
 '인': 3,
 '총': 2,
 '크리스토퍼': 1,
 '왈츠': 1,
 '타란티노': 1,
 '조합': 1,
 '에선': 4,
 '유명한': 1,
 '외국': 2,
 '상상': 2,
 '초월': 1,
 '유명': 1,
 '오랜만': 4,
 '종': 3,
 '방': 3,
 '오늘': 3,
 '방도': 1,
 '방송': 1,
 '대본': 1,
 '완성도': 1,
 '요즘': 7,
 '막장': 6,
 '지치': 1,
 '향': 1,
 '바른': 1,
 '그리': 3,
 '심하': 2,
 '화이팅': 5,
 '위원회': 1,
 '김혜선': 1,
 '내일이 오면': 1,
 '의': 2,
 '김': 1,
 '순정': 2,
 '역할': 1,
 '해내': 1,
 '의외': 1,
 '20년': 1,
 '사극': 3,
 '벌어지': 1,
 '논란': 1,
 '왠지': 4,
 '코미디': 7,
 '의하': 3,
 '장면': 12,
 '멍하': 1,
 '한마디': 4,
 '공유': 1,
 '존': 4,
 '상쾌': 1,
 '발랄': 1,
 '성': 1,
 '유쾌': 3,
 '해설': 1,
 '소파': 1,
 '치': 4,
 '앉': 2,
 '지키': 1,
 '이유': 7,
 '로큰롤': 1,
 '주되': 1,
 '타겟': 1,
 '일반': 2,
 '논리': 1,
 '통하': 2,
 '게임': 2,
 '요원': 1,
 '능력': 1,
 '배경': 4,
 '거슬리': 2,
 '뮤지컬 영화': 1,
 '사운드': 1,
 '녹음': 1,
 '엉망': 3,
 '주': 6,
 '춤': 1,
 '못': 9,
 '어제': 1,
 '뛰': 1,
 '말리': 1,
 '영국': 1,
 '예산': 5,
 '뮤지컬': 1,
 '맘마미아': 1,
 '10': 1,
 '로맨틱': 1,
 '물': 9,
 '인줄': 2,
 '절': 3,
 '스텝': 1,
 '꼭두각시': 1,
 '최악': 12,
 '아름답': 7,
 '익숙': 2,
 '현대인': 1,
 '뻑': 2,
 '읽': 5,
 '당하': 2,
 '극치': 2,
 '굉장히': 2,
 '뚱뚱': 1,
 '못생기': 1,
 '남자': 14,
 '애': 11,
 '시종일관': 3,
 '고역': 1,
 '흘러나오': 1,
 '클래식': 1,
 '조차': 1,
 '싫': 2,
 '날': 6,
 '상당히': 3,
 '얼마나': 3,
 '진부': 4,
 '밖': 3,
 '죄송': 1,
 '화가': 1,
 '티': 7,
 '비판': 1,
 '짜': 6,
 '집기': 1,
 '내': 5,
 '돼지': 1,
 '피': 3,
 '닭목': 1,
 '따': 1,
 '무당': 1,
 '잠': 3,
 '판타지': 3,
 '가져가': 1,
 '윤종신': 1,
 '복귀': 1,
 '이하늘': 1,
 '뽑히': 1,
 '참가자': 1,
 '따지': 2,
 '심사': 1,
 '위원': 1,
 '인격': 2,
 '쌓': 1,
 '오시': 1,
 '어': 5,
 '광장': 1,
 '옛날': 3,
 '보고 싶다': 1,
 '생': 1,
 '시절': 6,
 '추억': 5,
 '나쁘': 4,
 '짓': 4,
 '금물': 1,
 '지옥': 1,
 '기존': 2,
 '형식': 1,
 '탈피': 1,
 '지나치': 1,
 '사랑비': 1,
 '서주': 1,
 '쏙': 2,
 '후회': 3,
 '도안': 2,
 '할거': 1,
 '이영화': 5,
 '남은': 2,
 '젖': 1,
 '없이': 5,
 '추천': 5,
 '싸이코': 2,
 '벗어나': 1,
 '개봉': 5,
 '접하': 5,
 '보고': 1,
 '연잇': 1,
 '귀여워': 1,
 '청춘 영화': 1,
 '넘치': 1,
 '순간': 5,
 '지나가': 1,
 '돌아오': 2,
 '테': 1,
 '무한': 2,
 '젊음': 1,
 '건담': 1,
 '시리즈': 6,
 '최고봉': 1,
 '개코': 1,
 '코너': 1,
 '달': 4,
 '이안': 1,
 '사다코': 1,
 '우물': 1,
 '펀치': 1,
 '후세': 2,
 '결정': 1,
 '계기': 1,
 '표현': 8,
 '생명': 3,
 '빼앗': 1,
 '시노': 2,
 '출현': 2,
 '연극': 1,
 '으': 5,
 '로': 1,
 '알리': 4,
 '시랑': 1,
 '새벽': 2,
 '개': 6,
 '원래': 1,
 '이러': 1,
 '강수연': 1,
 '최정원': 1,
 '신음': 1,
 '김혜성': 1,
 '예쁘': 5,
 '이현진': 1,
 '가발': 1,
 '정': 2,
 '이인상': 1,
 '배두나': 1,
 '10대': 1,
 '성적': 1,
 '호기심': 1,
 '필요': 7,
 '닥치': 1,
 '각기': 1,
 '파워': 1,
 '수없': 1,
 '미묘': 2,
 '사로잡': 1,
 '너무너무': 3,
 '훈훈': 2,
 '응답하라': 1,
 '은지원': 1,
 '원도': 1,
 '배꼽': 1,
 '컴': 1,
 '부실': 1,
 '네이버': 3,
 '장': 3,
 '로드': 1,
 '몰락': 1,
 '가져오': 2,
 '오우삼': 2,
 '영웅본색': 1,
 '연출': 10,
 '인지': 2,
 '현실': 6,
 '제로': 3,
 '하나에': 1,
 '설레': 1,
 '학창': 1,
 '그때': 4,
 '느끼': 18,
 '대사': 4,
 '높': 10,
 '화나': 1,
 '더럽': 6,
 '형태': 1,
 '닿': 4,
 '허무': 3,
 '완벽히': 1,
 '영양가': 1,
 '이승기': 1,
 '조연': 3,
 '꿈': 2,
 '현충일': 1,
 '특집': 3,
 '프로': 1,
 '훌륭': 2,
 '판': 3,
 '의미': 5,
 '동급': 2,
 '제대': 1,
 '마음': 10,
 '휴가': 1,
 '다녀오': 1,
 '소': 2,
 '박': 1,
 '하지': 2,
 '햇살': 1,
 '가득': 1,
 '부엌': 1,
 '요리': 1,
 '코믹': 4,
 '짜임새': 2,
 ...}

In [16]:
# tokens_list에 있는 token들을 하나의 변수에 대입
t_s = []
for toks in tokens_list:
    for word in toks:
        t_s.append(word)
Counter(t_s)

Counter({'영화': 364,
         '보': 262,
         '하': 131,
         '없': 113,
         '있': 86,
         '좋': 73,
         '진짜': 68,
         '정말': 67,
         '안': 66,
         '너무': 61,
         '연기': 58,
         '재밌': 57,
         '같': 56,
         '나오': 52,
         '만들': 51,
         '잘': 47,
         '최고': 47,
         '다': 46,
         '사람': 44,
         '왜': 43,
         '되': 41,
         '알': 38,
         '내용': 36,
         '때': 34,
         '감동': 34,
         '말': 34,
         '더': 33,
         '재미없': 32,
         '재미': 31,
         '아깝': 31,
         '배우': 31,
         '재미있': 30,
         '생각': 30,
         '시간': 29,
         '드라마': 28,
         '그냥': 28,
         '좀': 28,
         '평점': 27,
         '스토리': 27,
         '감독': 27,
         '나': 26,
         '이': 26,
         '쓰레기': 26,
         '작품': 25,
         '모르': 24,
         '완전': 23,
         '지루': 22,
         '들': 22,
         '느낌': 21,
         '보이': 20,
         '남': 20,
         '정도': 20,
         '다시': 19,
         '액션': 18,
         '이렇': 18,
         '주인공': 18,
         '느끼': 18,
         '재': 17,
         '참': 17,
         '작': 17,
         '사랑': 17,
         '마지막': 17,
         '짜증': 16,
         '이건': 16,
         '기대': 16,
         '인생': 16,
         '오': 16,
         '돈': 16,
         '가': 16,
         '속': 16,
         '일본': 16,
         '쓰': 16,
         '넘': 15,
         '그렇': 15,
         '대하': 15,
         '명작': 15,
         '살': 15,
         '이야기': 14,
         '솔직히': 14,
         '죽': 14,
         '받': 14,
         '많': 14,
         '소재': 14,
         '괜찮': 14,
         '남자': 14,
         '별로': 13,
         '무섭': 13,
         '이상': 13,
         '볼': 12,
         '멋지': 12,
         '음악': 12,
         '자체': 12,
         '어떻': 12,
         '장면': 12,
         '최악': 12,
         '기억': 12,
         '이해': 11,
         '걸': 11,
         '아쉽': 11,
         '일': 11,
         '끝나': 11,
         '전개': 11,
         '슬프': 11,
         '몰입': 11,
         '실망': 11,
         '전': 11,
         '애': 11,
         '지금': 11,
         '인간': 11,
         '까': 10,
         '절대': 10,
         '웃': 10,
         '아직': 10,
         '조금': 10,
         '유치': 10,
         '한국': 10,
         '좋아하': 10,
         '처음': 10,
         '끌': 10,
         '허': 10,
         '당시': 10,
         '그만': 10,
         '찍': 10,
         '연출': 10,
         '높': 10,
         '마음': 10,
         '굿': 10,
         '울': 9,
         '캐스팅': 9,
         '매력': 9,
         '웃음': 9,
         '감정': 9,
         '설정': 9,
         '진심': 9,
         '많이': 9,
         '짱': 9,
         '못': 9,
         '물': 9,
         '잇': 9,
         '포스터': 8,
         '막': 8,
         '낮': 8,
         '꽤': 8,
         '위하': 8,
         '졸': 8,
         '한': 8,
         '크': 8,
         '신선': 8,
         '제일': 8,
         '연기력': 8,
         '결말': 8,
         '냐': 8,
         '따뜻': 8,
         '지나': 8,
         '아니': 8,
         '전혀': 8,
         '믿': 8,
         '여운': 8,
         '지': 8,
         '표현': 8,
         '스릴러': 8,
         '내내': 8,
         '여자': 8,
         '귀엽': 8,
         '끝': 8,
         '너무나': 7,
         '욕': 7,
         '가장': 7,
         '정신': 7,
         '알바': 7,
         '기분': 7,
         '노력': 7,
         '먹': 7,
         '시청률': 7,
         '눈': 7,
         '최': 7,
         '인상': 7,
         '미': 7,
         '빠지': 7,
         '아주': 7,
         '힘들': 7,
         '나이': 7,
         '자신': 7,
         '어리': 7,
         '요즘': 7,
         '코미디': 7,
         '이유': 7,
         '아름답': 7,
         '티': 7,
         '필요': 7,
         '책': 7,
         '부족': 7,
         '애니': 7,
         '슬픔': 7,
         '비디오': 7,
         '반전': 7,
         '공포': 7,
         '원작': 6,
         '긴장감': 6,
         '가족': 6,
         '눈물': 6,
         '나서': 6,
         '멜로': 6,
         '노': 6,
         '코': 6,
         '발': 6,
         '나가': 6,
         '단순': 6,
         '잔잔': 6,
         '길': 6,
         '공감': 6,
         '초반': 6,
         '수준': 6,
         '누': 6,
         '이랑': 6,
         '다니': 6,
         '가슴': 6,
         '혼자': 6,
         '대단': 6,
         '이제': 6,
         '가요': 6,
         '로맨스': 6,
         '삶': 6,
         '다르': 6,
         '막장': 6,
         '주': 6,
         '날': 6,
         '짜': 6,
         '시절': 6,
         '시리즈': 6,
         '개': 6,
         '현실': 6,
         '더럽': 6,
         '게': 6,
         '전쟁': 6,
         '제발': 6,
         '시나리오': 6,
         '친구': 6,
         '부분': 6,
         '급': 6,
         '또': 6,
         '모두': 6,
         '키': 6,
         '더빙': 5,
         '살리': 5,
         '화려': 5,
         '자극': 5,
         '웃기': 5,
         '갈수록': 5,
         '구성': 5,
         '수작': 5,
         '꼭': 5,
         '별점': 5,
         '대체': 5,
         '관객': 5,
         '캐릭터': 5,
         '조절': 5,
         '딱': 5,
         '잊': 5,
         '깊': 5,
         '그저': 5,
         '중간': 5,
         '모습': 5,
         '예': 5,
         '큐': 5,
         '살인': 5,
         '노래': 5,
         '맞': 5,
         '어이없': 5,
         '매': 5,
         '추': 5,
         '대박': 5,
         '흥미': 5,
         '현실감': 5,
         '후': 5,
         '남기': 5,
         '뭐': 5,
         '건지': 5,
         '답': 5,
         '손': 5,
         '충분히': 5,
         '어린이': 5,
         '화이팅': 5,
         '예산': 5,
         '읽': 5,
         '내': 5,
         '어': 5,
         '추억': 5,
         '이영화': 5,
         '없이': 5,
         '추천': 5,
         '개봉': 5,
         '접하': 5,
         '순간': 5,
         '으': 5,
         '예쁘': 5,
         '의미': 5,
         '요': 5,
         '세계': 5,
         '을': 5,
         '미치': 5,
         '아': 5,
         '기': 5,
         '보니': 5,
         '돌리': 5,
         '안타깝': 5,
         '결국': 5,
         '싸우': 5,
         '사': 5,
         '이후': 5,
         '완벽': 5,
         '전작': 5,
         '점수': 5,
         '도': 5,
         '좀비': 5,
         '초등학교': 4,
         '드럽': 4,
         '극장': 4,
         '고': 4,
         '이리': 4,
         '작가': 4,
         '방법': 4,
         '낭비': 4,
         '뛰어나': 4,
         '극': 4,
         '소설': 4,
         '라': 4,
         '게이': 4,
         '어쩌': 4,
         '그대로': 4,
         '악역': 4,
         '계속': 4,
         '우리나라': 4,
         '깊이': 4,
         '예전': 4,
         '비슷': 4,
         '안보': 4,
         '억지': 4,
         '어설프': 4,
         '흥행': 4,
         '갈등': 4,
         '에': 4,
         '시작': 4,
         '유': 4,
         '영화인': 4,
         '태어나': 4,
         '짬뽕': 4,
         '거지': 4,
         '망치': 4,
         '보지': 4,
         '마라': 4,
         '특유': 4,
         '전부': 4,
         '쇼': 4,
         '문제': 4,
         '어울리': 4,
         '나라': 4,
         '가지': 4,
         '상황': 4,
         '한석규': 4,
         '잔인': 4,
         '뜨': 4,
         '에선': 4,
         '오랜만': 4,
         '왠지': 4,
         '한마디': 4,
         '존': 4,
         '치': 4,
         '배경': 4,
         '진부': 4,
         '나쁘': 4,
         '짓': 4,
         '달': 4,
         '알리': 4,
         '그때': 4,
         '대사': 4,
         '닿': 4,
         '코믹': 4,
         '색다르': 4,
         '짧': 4,
         '먹먹': 4,
         '개연': 4,
         '제목': 4,
         '군가': 4,
         '얘기': 4,
         '줄': 4,
         '영상': 4,
         '감': 4,
         '탑': 4,
         '사실': 4,
         '떠나': 4,
         '충분': 4,
         '레전드': 4,
         '소피': 4,
         '바라': 4,
         '고의': 4,
         '공부': 4,
         '다운': 4,
         '감사': 4,
         '멀': 4,
         '자막': 4,
         '타': 4,
         '기키': 4,
         '유럽': 4,
         '영상미': 4,
         '특히': 4,
         '예고편': 4,
         '연예': 4,
         '초딩': 3,
         '오버': 3,
         '가볍': 3,
         '돋보이': 3,
         '늙': 3,
         '떼': 3,
         '학년': 3,
         '반개': 3,
         '반복': 3,
         '못하': 3,
         '감성': 3,
         '절제': 3,
         '보다': 3,
         '취향': 3,
         '어거지': 3,
         '이기': 3,
         '난': 3,
         '뒤': 3,
         '드': 3,
         '착하': 3,
         '음식': 3,
         '평범': 3,
         '주제': 3,
         '중반': 3,
         '끄': 3,
         '연출력': 3,
         '90년대': 3,
         '장애': 3,
         '거도': 3,
         '맘': 3,
         '불가': 3,
         '데': 3,
         '메': 3,
         '잠시': 3,
         '동화': 3,
         '행복': 3,
         '콩': 3,
         '충격': 3,
         '완전히': 3,
         '무겁': 3,
         '심심': 3,
         '언제': 3,
         '바로': 3,
         '듣': 3,
         '민간인': 3,
         '학살': 3,
         '이정': 3,
         '에피소드': 3,
         '재탕': 3,
         '신': 3,
         '실력': 3,
         '조작': 3,
         '열리': 3,
         '들어가': 3,
         '걸리': 3,
         '매우': 3,
         '아햏햏': 3,
         '진정': 3,
         '별루': 3,
         '성룡': 3,
         '때리': 3,
         '이쁘': 3,
         '새롭': 3,
         '쪼': 3,
         '불륜': 3,
         '왕': 3,
         '덜': 3,
         '떨어지': 3,
         '도대체': 3,
         '미국': 3,
         '순수': 3,
         '아들': 3,
         '베': 3,
         '리': 3,
         '여': 3,
         '마': 3,
         '개인': 3,
         '국산': 3,
         '아끼': 3,
         '지겹': 3,
         '죽이': 3,
         '낫': 3,
         '인': 3,
         '종': 3,
         '방': 3,
         '오늘': 3,
         '그리': 3,
         '사극': 3,
         '의하': 3,
         '유쾌': 3,
         '엉망': 3,
         '절': 3,
         '시종일관': 3,
         '상당히': 3,
         '얼마나': 3,
         '밖': 3,
         '피': 3,
         '잠': 3,
         '판타지': 3,
         '옛날': 3,
         '후회': 3,
         '생명': 3,
         '너무너무': 3,
         '네이버': 3,
         '장': 3,
         '제로': 3,
         '허무': 3,
         '조연': 3,
         '특집': 3,
         '판': 3,
         '서스펜스': 3,
         '귀신': 3,
         '댓글': 3,
         '한번쯤': 3,
         '답답': 3,
         '묘사': 3,
         '극장판': 3,
         '역사': 3,
         '가치': 3,
         '시키': 3,
         '흑인': 3,
         '범죄': 3,
         '느와르': 3,
         '놓': 3,
         '습': 3,
         '소리': 3,
         '적당히': 3,
         '글': 3,
         '이름': 3,
         '두': 3,
         '망하': 3,
         '아이': 3,
         '시선': 3,
         '겁나': 3,
         '여주인공': 3,
         '중요': 3,
         '여배우': 3,
         '지루함': 3,
         '닮': 3,
         '비': 3,
         '연예인': 3,
         '돌아가': 3,
         '과': 3,
         '세상': 3,
         '아빠': 3,
         '앗': 3,
         '의도': 3,
         '강하': 3,
         '첨': 3,
         '해': 3,
         '탄탄': 3,
         '사회': 3,
         '실제': 3,
         '검술': 3,
         '미스': 3,
         '그러': 3,
         '멋있': 3,
         '빨리': 3,
         '중심': 3,
         '나중': 3,
         '사촌': 3,
         '제가': 3,
         '흐르': 3,
         '실제로': 3,
         '늦': 3,
         '망': 3,
         '도움': 3,
         '장난': 3,
         '보내': 3,
         '서로': 3,
         '잃': 3,
         '유대인': 3,
         '엔': 3,
         '딩': 3,
         '영화관': 3,
         '몰': 3,
         '놀': 3,
         '청춘': 3,
         '복수': 3,
         '해주': 3,
         '평생': 3,
         '생각나': 3,
         '짐승': 3,
         '숨': 3,
         '싸구려': 3,
         '밝히': 3,
         '질질': 3,
         '터지': 3,
         '겨': 3,
         '상영': 3,
         '미화': 3,
         '엉성': 3,
         '싫어하': 3,
         '아저씨': 3,
         '역겹': 3,
         '일찍': 3,
         '얼굴': 3,
         '같이': 3,
         '간만': 3,
         '독립': 3,
         '업': 3,
         '외계인': 3,
         '주온': 3,
         '존재': 3,
         '기억나': 3,
         '차라리': 3,
         '실화': 3,
         '동생': 3,
         '아이들': 3,
         '여성': 3,
         '분위기': 3,
         '비하': 3,
         '궁금': 3,
         '목소리': 2,
         '용': 2,
         '별': 2,
         '제대로': 2,
         '생활': 2,
         '발로': 2,
         '헐리우드': 2,
         '향수': 2,
         '담백': 2,
         '깔끔': 2,
         '기사': 2,
         '자꾸': 2,
         '깔': 2,
         '깨알': 2,
         '러': 2,
         '뜻': 2,
         '가능': 2,
         '만찬': 2,
         '드리': 2,
         '납득': 2,
         '고추': 2,
         '센스': 2,
         '탁월': 2,
         '포스': 2,
         '깨닫': 2,
         '꽃': 2,
         '죄인': 2,
         '열정': 2,
         '안나': 2,
         '평가': 2,
         '은은': 2,
         '서리': 2,
         '일탈': 2,
         '이민기': 2,
         '패': 2,
         '물건': 2,
         '상태': 2,
         '마이너스': 2,
         '가르': 2,
         '르': 2,
         '매운맛': 2,
         '간다': 2,
         '꼬마': 2,
         '일본인': 2,
         '당황': 2,
         '일상': 2,
         '전개도': 2,
         '느리': 2,
         '맨날': 2,
         '빨리빨리': 2,
         '가슴속': 2,
         '살인자': 2,
         '산': 2,
         '이틀': 2,
         '집': 2,
         '온몸': 2,
         '폭': 2,
         '계': 2,
         '뻔하': 2,
         '사진': 2,
         '단연': 2,
         '우뢰': 2,
         '내일': 2,
         '골': 2,
         '공주': 2,
         '강': 2,
         '술': 2,
         '킬링타임': 2,
         '떠오르': 2,
         '허풍': 2,
         '거북': 2,
         '스스로': 2,
         '텐': 2,
         '생애': 2,
         '연기자': 2,
         '상대': 2,
         '따로': 2,
         '젤': 2,
         '교훈': 2,
         '케이블': 2,
         '그릇': 2,
         '면': 2,
         '살짝': 2,
         '떨': 2,
         '이제서야': 2,
         '감히': 2,
         '고민': 2,
         '여전히': 2,
         '섹시': 2,
         '혹시나': 2,
         '상업': 2,
         '노출': 2,
         '화끈': 2,
         '끝내': 2,
         '드니': 2,
         '일품': 2,
         '껀': 2,
         '총': 2,
         '외국': 2,
         '상상': 2,
         '심하': 2,
         '의': 2,
         '순정': 2,
         '앉': 2,
         '일반': 2,
         '통하': 2,
         '게임': 2,
         '거슬리': 2,
         '인줄': 2,
         '익숙': 2,
         '뻑': 2,
         '당하': 2,
         '극치': 2,
         '굉장히': 2,
         '싫': 2,
         '따지': 2,
         '인격': 2,
         '기존': 2,
         '쏙': 2,
         '도안': 2,
         '남은': 2,
         '싸이코': 2,
         '돌아오': 2,
         '무한': 2,
         '후세': 2,
         '시노': 2,
         '출현': 2,
         '새벽': 2,
         '정': 2,
         '미묘': 2,
         '훈훈': 2,
         '가져오': 2,
         '오우삼': 2,
         '인지': 2,
         '꿈': 2,
         '훌륭': 2,
         '동급': 2,
         '소': 2,
         '하지': 2,
         '짜임새': 2,
         '허술': 2,
         '일단': 2,
         '괴물': 2,
         '죽기': 2,
         '직전': 2,
         '란': 2,
         '보기': 2,
         '역': 2,
         '이그': 2,
         '기도': 2,
         '정치인': 2,
         '모순': 2,
         '인가': 2,
         '하니': 2,
         '전화': 2,
         '개그': 2,
         '없애': 2,
         '푸': 2,
         '감각': 2,
         '바라보': 2,
         '엄마': 2,
         '딸': 2,
         '화': 2,
         '생생': 2,
         '제맛': 2,
         '말이': 2,
         '본인': 2,
         '피해자': 2,
         '필름': 2,
         '값': 2,
         '남주인공': 2,
         '혀': 2,
         '분이': 2,
         '스릴': 2,
         '전달': 2,
         '거리': 2,
         '씩': 2,
         '언니': 2,
         '부르': 2,
         '즐겁': 2,
         '레알': 2,
         '어색': 2,
         '폭탄': 2,
         '가나': 2,
         '딸리': 2,
         '굳': 2,
         '호구': 2,
         '세기': 2,
         '쓸데없이': 2,
         '류': 2,
         '고위': 2,
         '넘어가': 2,
         '아역': 2,
         '민폐': 2,
         '그럴싸': 2,
         '딱히': 2,
         '송강호': 2,
         '그립': 2,
         '해석': 2,
         '한심': 2,
         '끼': 2,
         '영화로': 2,
         '비정': 2,
         '다듬': 2,
         '비롯': 2,
         '민망': 2,
         '군더더기': 2,
         '진행': 2,
         '빠': 2,
         '애니메이션': 2,
         '불쾌': 2,
         '연인': 2,
         '5년': 2,
         '국민': 2,
         '해서': 2,
         '하나님': 2,
         '이신': 2,
         '흥미진진': 2,
         '점점': 2,
         '이번': 2,
         '지존파': 2,
         '삼': 2,
         '정당화': 2,
         '정부': 2,
         '탓': 2,
         '중국': 2,
         '하트': 2,
         '평균': 2,
         '슬': 2,
         '하기': 2,
         '자': 2,
         '모으': 2,
         '메세지': 2,
         '영화사': 2,
         '히어로': 2,
         '놀이': 2,
         '사건': 2,
         '인물': 2,
         '빌리': 2,
         '우연히': 2,
         '절망': 2,
         '챙기': 2,
         '거부': 2,
         '맛': 2,
         '어마어마': 2,
         '똥': 2,
         '원주민': 2,
         '일어나': 2,
         '우': 2,
         '견자단': 2,
         '정말로': 2,
         '순위': 2,
         '그런지': 2,
         '여배우들': 2,
         '그래픽': 2,
         '평론가': 2,
         '바꾸': 2,
         '느': 2,
         '밥': 2,
         '악의': 2,
         '엄청': 2,
         '자식': 2,
         '살아오': 2,
         '확실히': 2,
         '생기': 2,
         '사라지': 2,
         '아픔': 2,
         '인형': 2,
         '찌': 2,
         '샤넬': 2,
         '세월': 2,
         '찰나': 2,
         '영원': 2,
         '관하': 2,
         '두근거리': 2,
         '아무리': 2,
         '용서': 2,
         '초가': 2,
         '갑자기': 2,
         '선생님': 2,
         '미안': 2,
         '쥐': 2,
         '무기': 2,
         '약간': 2,
         '빼': 2,
         '녀': 2,
         '끌리': 2,
         '디테일': 2,
         '찡': 2,
         '문화': 2,
         '전반': 2,
         '변화': 2,
         '벤지': 2,
         '막히': 2,
         '곳곳': 2,
         '치밀': 2,
         '안되': 2,
         '봄': 2,
         '라면': 2,
         '폭풍': 2,
         '함부로': 2,
         '남녀': 2,
         '웬만': 2,
         '잘못': 2,
         '차': 2,
         '매니아': 2,
         '이하': 2,
         '오르': 2,
         '공포물': 2,
         '귀': 2,
         '은': 2,
         '벌써': 2,
         '관람': 2,
         '신분': 2,
         '최근': 2,
         '삼류': 2,
         '스타': 2,
         '몸매': 2,
         '심형래': 2,
         '전체': 2,
         '주연': 2,
         '엄청나': 2,
         '초등': 2,
         '근래': 2,
         '제작자': 2,
         '호화': 2,
         '님': 2,
         '제작': 2,
         '원하': 2,
         '평': 2,
         '극장가': 2,
         '머리': 2,
         '묻어나': 2,
         '여정': 2,
         '덕': 2,
         '박수': 2,
         '끼우': 2,
         '맞추': 2,
         '무어': 2,
         '최루': 2,
         '걸작': 2,
         '남편': 2,
         '재밌는 영화': 2,
         '쏘': 2,
         '데리': 2,
         '라이': 2,
         '아련': 2,
         '박사': 2,
         '록': 2,
         '철학': 2,
         '13구역': 2,
         '남성': 2,
         '요소': 2,
         '홍보': 2,
         '팔': 2,
         '열': 2,
         '디': 2,
         '주목': 2,
         '뇌': 2,
         '죽음': 2,
         '우주': 2,
         '맡': 2,
         '예술': 2,
         '보통': 2,
         '고도': 2,
         '겪': 2,
         '쉬': 2,
         '즐기': 2,
         '여주': 2,
         '시점': 2,
         '라이언': 2,
         '일병': 2,
         '참고': 2,
         '자위': 2,
         '이거': 2,
         '차리': 2,
         '선정': 2,
         '솔로': 2,
         '링': 2,
         ...})

In [17]:
# 단어사전 생성
min_count = 2

# 단어사전 처음에는 특수 토큰 2개를 먼저 대입
f_vocab = ['<PAD>', '<UNK>']
b_vocab = []
for word, cnt in freq.items():
    # cnt(출현 횟수)가 min_count(최소 출현 횟수) 보다 크거나 같은 경우
    if cnt >= min_count:
        b_vocab.append(word)

f_vocab + b_vocab

['<PAD>',
 '<UNK>',
 '더빙',
 '진짜',
 '짜증',
 '나',
 '목소리',
 '포스터',
 '초딩',
 '영화',
 '오버',
 '연기',
 '가볍',
 '이야기',
 '솔직히',
 '재미',
 '없',
 '평점',
 '돋보이',
 '늙',
 '보이',
 '하',
 '너무나',
 '막',
 '떼',
 '초등학교',
 '학년',
 '용',
 '별',
 '반개',
 '아깝',
 '원작',
 '긴장감',
 '제대로',
 '살리',
 '욕',
 '나오',
 '생활',
 '이',
 '정말',
 '발로',
 '반복',
 '드라마',
 '가족',
 '못하',
 '사람',
 '액션',
 '있',
 '안',
 '왜',
 '낮',
 '꽤',
 '보',
 '헐리우드',
 '화려',
 '너무',
 '볼',
 '때',
 '눈물',
 '나서',
 '죽',
 '향수',
 '자극',
 '감성',
 '절제',
 '멜로',
 '울',
 '드럽',
 '담백',
 '깔끔',
 '좋',
 '기사',
 '보다',
 '자꾸',
 '취향',
 '극장',
 '가장',
 '노',
 '재',
 '감동',
 '스토리',
 '어거지',
 '참',
 '웃기',
 '이기',
 '코',
 '까',
 '고',
 '깔',
 '그냥',
 '난',
 '이해',
 '뒤',
 '갈수록',
 '재미없',
 '이건',
 '깨알',
 '캐스팅',
 '내용',
 '구성',
 '잘',
 '러',
 '드',
 '위하',
 '착하',
 '절대',
 '뜻',
 '웃',
 '가능',
 '지루',
 '같',
 '음식',
 '만찬',
 '넘',
 '별로',
 '평범',
 '수작',
 '드리',
 '주제',
 '중반',
 '다',
 '납득',
 '그렇',
 '꼭',
 '걸',
 '끄',
 '고추',
 '발',
 '센스',
 '연출력',
 '탁월',
 '90년대',
 '포스',
 '다시',
 '깨닫',
 '남',
 '꽃',
 '완전',
 '졸',
 '쓰레기',
 '시간',
 '재밌',
 '별점',
 '이리',
 '기대',
 '죄인',
 '아직',
 '인생',
 '최고',
 '대하',
 '열정',
 '안나',
 '대체',
 '정신',
 '장애',
 '작가',
 '나가',
 '재미있',
 '관객',
 '이렇',
 '평가',
 '받',
 '모르',
 '단순',
 '은은',
 '매력',
 '알바',
 '무섭',
 '거도',
 '오',
 '서리',
 '한',
 '맘',
 '들',
 '방법',
 '멋지',
 '배우',
 '되',
 '일탈',
 '잔잔',
 '음악',
 '조금',
 '아쉽',
 '길',
 '낭비',
 '돈',
 '뛰어나',
 '크',
 '공감',
 '가',
 '이민기',
 '캐릭터',
 '조절',
 '일',
 '패',
 '물건',
 '극',
 '초반',
 '신선',
 '상태',
 '불가',
 '마이너스',
 '수준',
 '딱',
 '알',
 '만들',
 '데',
 '가르',
 '누',
 '이랑',
 '다니',
 '소설',
 '속',
 '제일',
 '메',
 '라',
 '웃음',
 '감독',
 '잠시',
 '잊',
 '동화',
 '행복',
 '르',
 '게이',
 '작',
 '매운맛',
 '콩',
 '간다',
 '가슴',
 '자체',
 '꼬마',
 '깊',
 '혼자',
 '어쩌',
 '충격',
 '기분',
 '완전히',
 '느낌',
 '무겁',
 '그저',
 '일본인',
 '대단',
 '생각',
 '심심',
 '그대로',
 '악역',
 '당황',
 '중간',
 '끝나',
 '일상',
 '계속',
 '전개도',
 '느리',
 '주인공',
 '모습',
 '맨날',
 '언제',
 '전개',
 '좀',
 '빨리빨리',
 '사랑',
 '가슴속',
 '감정',
 '예',
 '말',
 '많',
 '큐',
 '우리나라',
 '슬프',
 '깊이',
 '바로',
 '노력',
 '듣',
 '민간인',
 '학살',
 '이정',
 '살인',
 '살인자',
 '예전',
 '작품',
 '에피소드',
 '재탕',
 '먹',
 '산',
 '시청률',
 '이제',
 '연기력',
 '몰입',
 '비슷',
 '안보',
 '신',
 '노래',
 '실력',
 '맞',
 '일본',
 '유치',
 '이틀',
 '조작',
 '열리',
 '집',
 '들어가',
 '걸리',
 '억지',
 '더',
 '어설프',
 '어이없',
 '결말',
 '온몸',
 '폭',
 '매우',
 '실망',
 '한국',
 '흥행',
 '갈등',
 '계',
 '에',
 '뻔하',
 '아햏햏',
 '시작',
 '사진',
 '단연',
 '우뢰',
 '매',
 '진정',
 '별루',
 '내일',
 '좋아하',
 '가요',
 '골',
 '눈',
 '성룡',
 '최',
 '때리',
 '이쁘',
 '공주',
 '인상',
 '강',
 '추',
 '설정',
 '새롭',
 '미',
 '유',
 '대박',
 '진심',
 '영화인',
 '쓰',
 '술',
 '어떻',
 '킬링타임',
 '떠오르',
 '빠지',
 '쪼',
 '태어나',
 '처음',
 '불륜',
 '로맨스',
 '냐',
 '왕',
 '아주',
 '짬뽕',
 '덜',
 '거지',
 '명작',
 '망치',
 '소재',
 '흥미',
 '끌',
 '보지',
 '마라',
 '특유',
 '허풍',
 '현실감',
 '떨어지',
 '거북',
 '도대체',
 '스스로',
 '텐',
 '미국',
 '따뜻',
 '삶',
 '생애',
 '전부',
 '지나',
 '후',
 '남기',
 '아니',
 '순수',
 '쇼',
 '허',
 '문제',
 '연기자',
 '전혀',
 '어울리',
 '상대',
 '따로',
 '아들',
 '젤',
 '베',
 '나라',
 '믿',
 '가지',
 '교훈',
 '당시',
 '상황',
 '케이블',
 '그만',
 '다르',
 '리',
 '그릇',
 '뭐',
 '건지',
 '한석규',
 '많이',
 '면',
 '여',
 '전',
 '힘들',
 '정도',
 '마지막',
 '살짝',
 '떨',
 '마',
 '짱',
 '이제서야',
 '감히',
 '살',
 '고민',
 '나이',
 '여전히',
 '섹시',
 '혹시나',
 '답',
 '여운',
 '손',
 '상업',
 '충분히',
 '개인',
 '잔인',
 '노출',
 '화끈',
 '국산',
 '아끼',
 '끝내',
 '지겹',
 '드니',
 '일품',
 '죽이',
 '괜찮',
 '지',
 '뜨',
 '찍',
 '껀',
 '자신',
 '어린이',
 '어리',
 '낫',
 '인',
 '총',
 '에선',
 '외국',
 '상상',
 '오랜만',
 '종',
 '방',
 '오늘',
 '요즘',
 '막장',
 '그리',
 '심하',
 '화이팅',
 '의',
 '순정',
 '사극',
 '왠지',
 '코미디',
 '의하',
 '장면',
 '한마디',
 '존',
 '유쾌',
 '치',
 '앉',
 '이유',
 '일반',
 '통하',
 '게임',
 '배경',
 '거슬리',
 '엉망',
 '주',
 '못',
 '예산',
 '물',
 '인줄',
 '절',
 '최악',
 '아름답',
 '익숙',
 '뻑',
 '읽',
 '당하',
 '극치',
 '굉장히',
 '남자',
 '애',
 '시종일관',
 '싫',
 '날',
 '상당히',
 '얼마나',
 '진부',
 '밖',
 '티',
 '짜',
 '내',
 '피',
 '잠',
 '판타지',
 '따지',
 '인격',
 '어',
 '옛날',
 '시절',
 '추억',
 '나쁘',
 '짓',
 '기존',
 '쏙',
 '후회',
 '도안',
 '이영화',
 '남은',
 '없이',
 '추천',
 '싸이코',
 '개봉',
 '접하',
 '순간',
 '돌아오',
 '무한',
 '시리즈',
 '달',
 '후세',
 '표현',
 '생명',
 '시노',
 '출현',
 '으',
 '알리',
 '새벽',
 '개',
 '예쁘',
 '정',
 '필요',
 '미묘',
 '너무너무',
 '훈훈',
 '네이버',
 '장',
 '가져오',
 '오우삼',
 '연출',
 '인지',
 '현실',
 '제로',
 '그때',
 '느끼',
 '대사',
 '높',
 '더럽',
 '닿',
 '허무',
 '조연',
 '꿈',
 '특집',
 '훌륭',
 '판',
 '의미',
 '동급',
 '마음',
 '소',
 '하지',
 '코믹',
 '짜임새',
 '허술',
 '일단',
 '괴물',
 '서스펜스',
 '귀신',
 '댓글',
 '한번쯤',
 '죽기',
 '직전',
 '란',
 '보기',
 '게',
 '요',
 '역',
 '이그',
 '기도',
 '답답',
 '정치인',
 '모순',
 '인가',
 '전쟁',
 '묘사',
 '극장판',
 '하니',
 '전화',
 '개그',
 '없애',
 '푸',
 '세계',
 '역사',
 '가치',
 '감각',
 '바라보',
 '색다르',
 '엄마',
 '딸',
 '시키',
 '제발',
 '책',
 '을',
 '미치',
 '화',
 '흑인',
 '생생',
 '이상',
 '아',
 '굿',
 '제맛',
 '범죄',
 '느와르',
 '말이',
 '본인',
 '피해자',
 '놓',
 '기',
 '필름',
 '값',
 '남주인공',
 '습',
 '혀',
 '짧',
 '소리',
 '분이',
 '적당히',
 '스릴러',
 '스릴',
 '전달',
 '글',
 '거리',
 '씩',
 '부족',
 '기억',
 '이름',
 '두',
 '언니',
 '부르',
 '즐겁',
 '망하',
 '아이',
 '시선',
 '내내',
 '먹먹',
 '레알',
 '여자',
 '겁나',
 '어색',
 '여주인공',
 '폭탄',
 '가나',
 '보니',
 '딸리',
 '개연',
 '굳',
 '호구',
 '세기',
 '쓸데없이',
 '류',
 '중요',
 '여배우',
 '고위',
 '잇',
 '애니',
 '제목',
 '지금',
 '넘어가',
 '군가',
 '얘기',
 '지루함',
 '슬픔',
 '아역',
 '민폐',
 '그럴싸',
 '딱히',
 '송강호',
 '비디오',
 '돌리',
 '그립',
 '해석',
 '닮',
 '비',
 '한심',
 '연예인',
 '시나리오',
 '끼',
 '안타깝',
 '돌아가',
 '과',
 '줄',
 '영화로',
 '세상',
 '비정',
 '친구',
 '영상',
 '다듬',
 '감',
 '부분',
 '비롯',
 '민망',
 '군더더기',
 '진행',
 '탑',
 '아빠',
 '앗',
 '빠',
 '애니메이션',
 '의도',
 '불쾌',
 '귀엽',
 '연인',
 '5년',
 '강하',
 '국민',
 '해서',
 '하나님',
 '이신',
 '흥미진진',
 '첨',
 '해',
 '탄탄',
 '점점',
 '끝',
 '이번',
 '결국',
 '지존파',
 '삼',
 '정당화',
 '정부',
 '탓',
 '사회',
 '사실',
 '떠나',
 '실제',
 '검술',
 '싸우',
 '중국',
 '하트',
 '미스',
 '평균',
 '충분',
 '급',
 '슬',
 '하기',
 '자',
 '모으',
 '그러',
 '멋있',
 '메세지',
 '빨리',
 '영화사',
 '히어로',
 '놀이',
 '중심',
 '사건',
 '인물',
 '인간',
 '레전드',
 '빌리',
 '나중',
 '우연히',
 '사촌',
 '제가',
 '절망',
 '챙기',
 '거부',
 '흐르',
 '맛',
 '어마어마',
 '소피',
 '똥',
 '원주민',
 '일어나',
 '우',
 '실제로',
 '바라',
 '견자단',
 '정말로',
 '또',
 '순위',
 '늦',
 '그런지',
 '여배우들',
 '그래픽',
 '망',
 '평론가',
 '도움',
 '바꾸',
 '느',
 '밥',
 '장난',
 '악의',
 '보내',
 '엄청',
 '자식',
 '살아오',
 '서로',
 '확실히',
 '잃',
 '고의',
 '생기',
 '사라지',
 '공부',
 '사',
 '이후',
 '아픔',
 '유대인',
 '인형',
 '찌',
 '다운',
 '감사',
 '샤넬',
 '세월',
 '찰나',
 '영원',
 '관하',
 '두근거리',
 '멀',
 '아무리',
 '용서',
 '모두',
 '엔',
 '딩',
 '영화관',
 '몰',
 '초가',
 '갑자기',
 '선생님',
 '미안',
 '놀',
 '쥐',
 '청춘',
 '무기',
 '약간',
 '빼',
 '반전',
 '복수',
 '해주',
 '녀',
 '끌리',
 '디테일',
 '완벽',
 '찡',
 '평생',
 '생각나',
 '짐승',
 '자막',
 '문화',
 '전반',
 '변화',
 '벤지',
 '숨',
 '막히',
 '곳곳',
 '치밀',
 '싸구려',
 '밝히',
 '안되',
 '질질',
 '봄',
 '터지',
 '겨',
 '상영',
 '미화',
 '라면',
 '전작',
 '폭풍',
 '함부로',
 '남녀',
 '웬만',
 '잘못',
 '엉성',
 '차',
 '싫어하',
 '매니아',
 '이하',
 '아저씨',
 '역겹',
 '오르',
 '공포물',
 '귀',
 '타',
 '은',
 '벌써',
 '일찍',
 '관람',
 '신분',
 '최근',
 '점수',
 '삼류',
 '스타',
 '얼굴',
 '몸매',
 '심형래',
 '전체',
 '주연',
 '키',
 '기키',
 '엄청나',
 '초등',
 '근래',
 '제작자',
 '유럽',
 '호화',
 '같이',
 '님',
 '간만',
 '영상미',
 '제작',
 '공포',
 '원하',
 '평',
 '극장가',
 '머리',
 '묻어나',
 '여정',
 '독립',
 '덕',
 '업',
 '박수',
 '끼우',
 '맞추',
 '무어',
 '최루',
 '걸작',
 '남편',
 '외계인',
 '재밌는 영화',
 '주온',
 '쏘',
 '데리',
 '라이',
 '아련',
 '존재',
 '도',
 '기억나',
 '박사',
 '록',
 '철학',
 '13구역',
 '남성',
 '요소',
 '홍보',
 '팔',
 '차라리',
 '열',
 '실화',
 '동생',
 '디',
 '아이들',
 '주목',
 '뇌',
 '죽음',
 '우주',
 '맡',
 '여성',
 '예술',
 '보통',
 '고도',
 '겪',
 '쉬',
 '즐기',
 '분위기',
 '여주',
 '시점',
 '비하',
 '라이언',
 '일병',
 '참고',
 '자위',
 '이거',
 '궁금',
 '차리',
 '선정',
 '솔로',
 '링',
 '스타일',
 '설마',
 ...]

In [18]:
vocab = ['<PAD>', '<UNK>'] + [word for word, cnt in freq.items() if cnt >= min_count]
vocab

['<PAD>',
 '<UNK>',
 '더빙',
 '진짜',
 '짜증',
 '나',
 '목소리',
 '포스터',
 '초딩',
 '영화',
 '오버',
 '연기',
 '가볍',
 '이야기',
 '솔직히',
 '재미',
 '없',
 '평점',
 '돋보이',
 '늙',
 '보이',
 '하',
 '너무나',
 '막',
 '떼',
 '초등학교',
 '학년',
 '용',
 '별',
 '반개',
 '아깝',
 '원작',
 '긴장감',
 '제대로',
 '살리',
 '욕',
 '나오',
 '생활',
 '이',
 '정말',
 '발로',
 '반복',
 '드라마',
 '가족',
 '못하',
 '사람',
 '액션',
 '있',
 '안',
 '왜',
 '낮',
 '꽤',
 '보',
 '헐리우드',
 '화려',
 '너무',
 '볼',
 '때',
 '눈물',
 '나서',
 '죽',
 '향수',
 '자극',
 '감성',
 '절제',
 '멜로',
 '울',
 '드럽',
 '담백',
 '깔끔',
 '좋',
 '기사',
 '보다',
 '자꾸',
 '취향',
 '극장',
 '가장',
 '노',
 '재',
 '감동',
 '스토리',
 '어거지',
 '참',
 '웃기',
 '이기',
 '코',
 '까',
 '고',
 '깔',
 '그냥',
 '난',
 '이해',
 '뒤',
 '갈수록',
 '재미없',
 '이건',
 '깨알',
 '캐스팅',
 '내용',
 '구성',
 '잘',
 '러',
 '드',
 '위하',
 '착하',
 '절대',
 '뜻',
 '웃',
 '가능',
 '지루',
 '같',
 '음식',
 '만찬',
 '넘',
 '별로',
 '평범',
 '수작',
 '드리',
 '주제',
 '중반',
 '다',
 '납득',
 '그렇',
 '꼭',
 '걸',
 '끄',
 '고추',
 '발',
 '센스',
 '연출력',
 '탁월',
 '90년대',
 '포스',
 '다시',
 '깨닫',
 '남',
 '꽃',
 '완전',
 '졸',
 '쓰레기',
 '시간',
 '재밌',
 '별점',
 '이리',
 '기대',
 '죄인',
 '아직',
 '인생',
 '최고',
 '대하',
 '열정',
 '안나',
 '대체',
 '정신',
 '장애',
 '작가',
 '나가',
 '재미있',
 '관객',
 '이렇',
 '평가',
 '받',
 '모르',
 '단순',
 '은은',
 '매력',
 '알바',
 '무섭',
 '거도',
 '오',
 '서리',
 '한',
 '맘',
 '들',
 '방법',
 '멋지',
 '배우',
 '되',
 '일탈',
 '잔잔',
 '음악',
 '조금',
 '아쉽',
 '길',
 '낭비',
 '돈',
 '뛰어나',
 '크',
 '공감',
 '가',
 '이민기',
 '캐릭터',
 '조절',
 '일',
 '패',
 '물건',
 '극',
 '초반',
 '신선',
 '상태',
 '불가',
 '마이너스',
 '수준',
 '딱',
 '알',
 '만들',
 '데',
 '가르',
 '누',
 '이랑',
 '다니',
 '소설',
 '속',
 '제일',
 '메',
 '라',
 '웃음',
 '감독',
 '잠시',
 '잊',
 '동화',
 '행복',
 '르',
 '게이',
 '작',
 '매운맛',
 '콩',
 '간다',
 '가슴',
 '자체',
 '꼬마',
 '깊',
 '혼자',
 '어쩌',
 '충격',
 '기분',
 '완전히',
 '느낌',
 '무겁',
 '그저',
 '일본인',
 '대단',
 '생각',
 '심심',
 '그대로',
 '악역',
 '당황',
 '중간',
 '끝나',
 '일상',
 '계속',
 '전개도',
 '느리',
 '주인공',
 '모습',
 '맨날',
 '언제',
 '전개',
 '좀',
 '빨리빨리',
 '사랑',
 '가슴속',
 '감정',
 '예',
 '말',
 '많',
 '큐',
 '우리나라',
 '슬프',
 '깊이',
 '바로',
 '노력',
 '듣',
 '민간인',
 '학살',
 '이정',
 '살인',
 '살인자',
 '예전',
 '작품',
 '에피소드',
 '재탕',
 '먹',
 '산',
 '시청률',
 '이제',
 '연기력',
 '몰입',
 '비슷',
 '안보',
 '신',
 '노래',
 '실력',
 '맞',
 '일본',
 '유치',
 '이틀',
 '조작',
 '열리',
 '집',
 '들어가',
 '걸리',
 '억지',
 '더',
 '어설프',
 '어이없',
 '결말',
 '온몸',
 '폭',
 '매우',
 '실망',
 '한국',
 '흥행',
 '갈등',
 '계',
 '에',
 '뻔하',
 '아햏햏',
 '시작',
 '사진',
 '단연',
 '우뢰',
 '매',
 '진정',
 '별루',
 '내일',
 '좋아하',
 '가요',
 '골',
 '눈',
 '성룡',
 '최',
 '때리',
 '이쁘',
 '공주',
 '인상',
 '강',
 '추',
 '설정',
 '새롭',
 '미',
 '유',
 '대박',
 '진심',
 '영화인',
 '쓰',
 '술',
 '어떻',
 '킬링타임',
 '떠오르',
 '빠지',
 '쪼',
 '태어나',
 '처음',
 '불륜',
 '로맨스',
 '냐',
 '왕',
 '아주',
 '짬뽕',
 '덜',
 '거지',
 '명작',
 '망치',
 '소재',
 '흥미',
 '끌',
 '보지',
 '마라',
 '특유',
 '허풍',
 '현실감',
 '떨어지',
 '거북',
 '도대체',
 '스스로',
 '텐',
 '미국',
 '따뜻',
 '삶',
 '생애',
 '전부',
 '지나',
 '후',
 '남기',
 '아니',
 '순수',
 '쇼',
 '허',
 '문제',
 '연기자',
 '전혀',
 '어울리',
 '상대',
 '따로',
 '아들',
 '젤',
 '베',
 '나라',
 '믿',
 '가지',
 '교훈',
 '당시',
 '상황',
 '케이블',
 '그만',
 '다르',
 '리',
 '그릇',
 '뭐',
 '건지',
 '한석규',
 '많이',
 '면',
 '여',
 '전',
 '힘들',
 '정도',
 '마지막',
 '살짝',
 '떨',
 '마',
 '짱',
 '이제서야',
 '감히',
 '살',
 '고민',
 '나이',
 '여전히',
 '섹시',
 '혹시나',
 '답',
 '여운',
 '손',
 '상업',
 '충분히',
 '개인',
 '잔인',
 '노출',
 '화끈',
 '국산',
 '아끼',
 '끝내',
 '지겹',
 '드니',
 '일품',
 '죽이',
 '괜찮',
 '지',
 '뜨',
 '찍',
 '껀',
 '자신',
 '어린이',
 '어리',
 '낫',
 '인',
 '총',
 '에선',
 '외국',
 '상상',
 '오랜만',
 '종',
 '방',
 '오늘',
 '요즘',
 '막장',
 '그리',
 '심하',
 '화이팅',
 '의',
 '순정',
 '사극',
 '왠지',
 '코미디',
 '의하',
 '장면',
 '한마디',
 '존',
 '유쾌',
 '치',
 '앉',
 '이유',
 '일반',
 '통하',
 '게임',
 '배경',
 '거슬리',
 '엉망',
 '주',
 '못',
 '예산',
 '물',
 '인줄',
 '절',
 '최악',
 '아름답',
 '익숙',
 '뻑',
 '읽',
 '당하',
 '극치',
 '굉장히',
 '남자',
 '애',
 '시종일관',
 '싫',
 '날',
 '상당히',
 '얼마나',
 '진부',
 '밖',
 '티',
 '짜',
 '내',
 '피',
 '잠',
 '판타지',
 '따지',
 '인격',
 '어',
 '옛날',
 '시절',
 '추억',
 '나쁘',
 '짓',
 '기존',
 '쏙',
 '후회',
 '도안',
 '이영화',
 '남은',
 '없이',
 '추천',
 '싸이코',
 '개봉',
 '접하',
 '순간',
 '돌아오',
 '무한',
 '시리즈',
 '달',
 '후세',
 '표현',
 '생명',
 '시노',
 '출현',
 '으',
 '알리',
 '새벽',
 '개',
 '예쁘',
 '정',
 '필요',
 '미묘',
 '너무너무',
 '훈훈',
 '네이버',
 '장',
 '가져오',
 '오우삼',
 '연출',
 '인지',
 '현실',
 '제로',
 '그때',
 '느끼',
 '대사',
 '높',
 '더럽',
 '닿',
 '허무',
 '조연',
 '꿈',
 '특집',
 '훌륭',
 '판',
 '의미',
 '동급',
 '마음',
 '소',
 '하지',
 '코믹',
 '짜임새',
 '허술',
 '일단',
 '괴물',
 '서스펜스',
 '귀신',
 '댓글',
 '한번쯤',
 '죽기',
 '직전',
 '란',
 '보기',
 '게',
 '요',
 '역',
 '이그',
 '기도',
 '답답',
 '정치인',
 '모순',
 '인가',
 '전쟁',
 '묘사',
 '극장판',
 '하니',
 '전화',
 '개그',
 '없애',
 '푸',
 '세계',
 '역사',
 '가치',
 '감각',
 '바라보',
 '색다르',
 '엄마',
 '딸',
 '시키',
 '제발',
 '책',
 '을',
 '미치',
 '화',
 '흑인',
 '생생',
 '이상',
 '아',
 '굿',
 '제맛',
 '범죄',
 '느와르',
 '말이',
 '본인',
 '피해자',
 '놓',
 '기',
 '필름',
 '값',
 '남주인공',
 '습',
 '혀',
 '짧',
 '소리',
 '분이',
 '적당히',
 '스릴러',
 '스릴',
 '전달',
 '글',
 '거리',
 '씩',
 '부족',
 '기억',
 '이름',
 '두',
 '언니',
 '부르',
 '즐겁',
 '망하',
 '아이',
 '시선',
 '내내',
 '먹먹',
 '레알',
 '여자',
 '겁나',
 '어색',
 '여주인공',
 '폭탄',
 '가나',
 '보니',
 '딸리',
 '개연',
 '굳',
 '호구',
 '세기',
 '쓸데없이',
 '류',
 '중요',
 '여배우',
 '고위',
 '잇',
 '애니',
 '제목',
 '지금',
 '넘어가',
 '군가',
 '얘기',
 '지루함',
 '슬픔',
 '아역',
 '민폐',
 '그럴싸',
 '딱히',
 '송강호',
 '비디오',
 '돌리',
 '그립',
 '해석',
 '닮',
 '비',
 '한심',
 '연예인',
 '시나리오',
 '끼',
 '안타깝',
 '돌아가',
 '과',
 '줄',
 '영화로',
 '세상',
 '비정',
 '친구',
 '영상',
 '다듬',
 '감',
 '부분',
 '비롯',
 '민망',
 '군더더기',
 '진행',
 '탑',
 '아빠',
 '앗',
 '빠',
 '애니메이션',
 '의도',
 '불쾌',
 '귀엽',
 '연인',
 '5년',
 '강하',
 '국민',
 '해서',
 '하나님',
 '이신',
 '흥미진진',
 '첨',
 '해',
 '탄탄',
 '점점',
 '끝',
 '이번',
 '결국',
 '지존파',
 '삼',
 '정당화',
 '정부',
 '탓',
 '사회',
 '사실',
 '떠나',
 '실제',
 '검술',
 '싸우',
 '중국',
 '하트',
 '미스',
 '평균',
 '충분',
 '급',
 '슬',
 '하기',
 '자',
 '모으',
 '그러',
 '멋있',
 '메세지',
 '빨리',
 '영화사',
 '히어로',
 '놀이',
 '중심',
 '사건',
 '인물',
 '인간',
 '레전드',
 '빌리',
 '나중',
 '우연히',
 '사촌',
 '제가',
 '절망',
 '챙기',
 '거부',
 '흐르',
 '맛',
 '어마어마',
 '소피',
 '똥',
 '원주민',
 '일어나',
 '우',
 '실제로',
 '바라',
 '견자단',
 '정말로',
 '또',
 '순위',
 '늦',
 '그런지',
 '여배우들',
 '그래픽',
 '망',
 '평론가',
 '도움',
 '바꾸',
 '느',
 '밥',
 '장난',
 '악의',
 '보내',
 '엄청',
 '자식',
 '살아오',
 '서로',
 '확실히',
 '잃',
 '고의',
 '생기',
 '사라지',
 '공부',
 '사',
 '이후',
 '아픔',
 '유대인',
 '인형',
 '찌',
 '다운',
 '감사',
 '샤넬',
 '세월',
 '찰나',
 '영원',
 '관하',
 '두근거리',
 '멀',
 '아무리',
 '용서',
 '모두',
 '엔',
 '딩',
 '영화관',
 '몰',
 '초가',
 '갑자기',
 '선생님',
 '미안',
 '놀',
 '쥐',
 '청춘',
 '무기',
 '약간',
 '빼',
 '반전',
 '복수',
 '해주',
 '녀',
 '끌리',
 '디테일',
 '완벽',
 '찡',
 '평생',
 '생각나',
 '짐승',
 '자막',
 '문화',
 '전반',
 '변화',
 '벤지',
 '숨',
 '막히',
 '곳곳',
 '치밀',
 '싸구려',
 '밝히',
 '안되',
 '질질',
 '봄',
 '터지',
 '겨',
 '상영',
 '미화',
 '라면',
 '전작',
 '폭풍',
 '함부로',
 '남녀',
 '웬만',
 '잘못',
 '엉성',
 '차',
 '싫어하',
 '매니아',
 '이하',
 '아저씨',
 '역겹',
 '오르',
 '공포물',
 '귀',
 '타',
 '은',
 '벌써',
 '일찍',
 '관람',
 '신분',
 '최근',
 '점수',
 '삼류',
 '스타',
 '얼굴',
 '몸매',
 '심형래',
 '전체',
 '주연',
 '키',
 '기키',
 '엄청나',
 '초등',
 '근래',
 '제작자',
 '유럽',
 '호화',
 '같이',
 '님',
 '간만',
 '영상미',
 '제작',
 '공포',
 '원하',
 '평',
 '극장가',
 '머리',
 '묻어나',
 '여정',
 '독립',
 '덕',
 '업',
 '박수',
 '끼우',
 '맞추',
 '무어',
 '최루',
 '걸작',
 '남편',
 '외계인',
 '재밌는 영화',
 '주온',
 '쏘',
 '데리',
 '라이',
 '아련',
 '존재',
 '도',
 '기억나',
 '박사',
 '록',
 '철학',
 '13구역',
 '남성',
 '요소',
 '홍보',
 '팔',
 '차라리',
 '열',
 '실화',
 '동생',
 '디',
 '아이들',
 '주목',
 '뇌',
 '죽음',
 '우주',
 '맡',
 '여성',
 '예술',
 '보통',
 '고도',
 '겪',
 '쉬',
 '즐기',
 '분위기',
 '여주',
 '시점',
 '비하',
 '라이언',
 '일병',
 '참고',
 '자위',
 '이거',
 '궁금',
 '차리',
 '선정',
 '솔로',
 '링',
 '스타일',
 '설마',
 ...]

In [19]:
# token화 된 문서들을 인코딩
stoi = {word : idx for idx, word in enumerate(vocab)}
stoi

{'<PAD>': 0,
 '<UNK>': 1,
 '더빙': 2,
 '진짜': 3,
 '짜증': 4,
 '나': 5,
 '목소리': 6,
 '포스터': 7,
 '초딩': 8,
 '영화': 9,
 '오버': 10,
 '연기': 11,
 '가볍': 12,
 '이야기': 13,
 '솔직히': 14,
 '재미': 15,
 '없': 16,
 '평점': 17,
 '돋보이': 18,
 '늙': 19,
 '보이': 20,
 '하': 21,
 '너무나': 22,
 '막': 23,
 '떼': 24,
 '초등학교': 25,
 '학년': 26,
 '용': 27,
 '별': 28,
 '반개': 29,
 '아깝': 30,
 '원작': 31,
 '긴장감': 32,
 '제대로': 33,
 '살리': 34,
 '욕': 35,
 '나오': 36,
 '생활': 37,
 '이': 38,
 '정말': 39,
 '발로': 40,
 '반복': 41,
 '드라마': 42,
 '가족': 43,
 '못하': 44,
 '사람': 45,
 '액션': 46,
 '있': 47,
 '안': 48,
 '왜': 49,
 '낮': 50,
 '꽤': 51,
 '보': 52,
 '헐리우드': 53,
 '화려': 54,
 '너무': 55,
 '볼': 56,
 '때': 57,
 '눈물': 58,
 '나서': 59,
 '죽': 60,
 '향수': 61,
 '자극': 62,
 '감성': 63,
 '절제': 64,
 '멜로': 65,
 '울': 66,
 '드럽': 67,
 '담백': 68,
 '깔끔': 69,
 '좋': 70,
 '기사': 71,
 '보다': 72,
 '자꾸': 73,
 '취향': 74,
 '극장': 75,
 '가장': 76,
 '노': 77,
 '재': 78,
 '감동': 79,
 '스토리': 80,
 '어거지': 81,
 '참': 82,
 '웃기': 83,
 '이기': 84,
 '코': 85,
 '까': 86,
 '고': 87,
 '깔': 88,
 '그냥': 89,
 '난': 90,
 '이해': 91,
 '뒤': 92,
 '갈수록': 93,
 '재미없': 94,
 '이건': 95,
 '깨알': 96,
 '캐스팅': 97,
 '내용': 98,
 '구성': 99,
 '잘': 100,
 '러': 101,
 '드': 102,
 '위하': 103,
 '착하': 104,
 '절대': 105,
 '뜻': 106,
 '웃': 107,
 '가능': 108,
 '지루': 109,
 '같': 110,
 '음식': 111,
 '만찬': 112,
 '넘': 113,
 '별로': 114,
 '평범': 115,
 '수작': 116,
 '드리': 117,
 '주제': 118,
 '중반': 119,
 '다': 120,
 '납득': 121,
 '그렇': 122,
 '꼭': 123,
 '걸': 124,
 '끄': 125,
 '고추': 126,
 '발': 127,
 '센스': 128,
 '연출력': 129,
 '탁월': 130,
 '90년대': 131,
 '포스': 132,
 '다시': 133,
 '깨닫': 134,
 '남': 135,
 '꽃': 136,
 '완전': 137,
 '졸': 138,
 '쓰레기': 139,
 '시간': 140,
 '재밌': 141,
 '별점': 142,
 '이리': 143,
 '기대': 144,
 '죄인': 145,
 '아직': 146,
 '인생': 147,
 '최고': 148,
 '대하': 149,
 '열정': 150,
 '안나': 151,
 '대체': 152,
 '정신': 153,
 '장애': 154,
 '작가': 155,
 '나가': 156,
 '재미있': 157,
 '관객': 158,
 '이렇': 159,
 '평가': 160,
 '받': 161,
 '모르': 162,
 '단순': 163,
 '은은': 164,
 '매력': 165,
 '알바': 166,
 '무섭': 167,
 '거도': 168,
 '오': 169,
 '서리': 170,
 '한': 171,
 '맘': 172,
 '들': 173,
 '방법': 174,
 '멋지': 175,
 '배우': 176,
 '되': 177,
 '일탈': 178,
 '잔잔': 179,
 '음악': 180,
 '조금': 181,
 '아쉽': 182,
 '길': 183,
 '낭비': 184,
 '돈': 185,
 '뛰어나': 186,
 '크': 187,
 '공감': 188,
 '가': 189,
 '이민기': 190,
 '캐릭터': 191,
 '조절': 192,
 '일': 193,
 '패': 194,
 '물건': 195,
 '극': 196,
 '초반': 197,
 '신선': 198,
 '상태': 199,
 '불가': 200,
 '마이너스': 201,
 '수준': 202,
 '딱': 203,
 '알': 204,
 '만들': 205,
 '데': 206,
 '가르': 207,
 '누': 208,
 '이랑': 209,
 '다니': 210,
 '소설': 211,
 '속': 212,
 '제일': 213,
 '메': 214,
 '라': 215,
 '웃음': 216,
 '감독': 217,
 '잠시': 218,
 '잊': 219,
 '동화': 220,
 '행복': 221,
 '르': 222,
 '게이': 223,
 '작': 224,
 '매운맛': 225,
 '콩': 226,
 '간다': 227,
 '가슴': 228,
 '자체': 229,
 '꼬마': 230,
 '깊': 231,
 '혼자': 232,
 '어쩌': 233,
 '충격': 234,
 '기분': 235,
 '완전히': 236,
 '느낌': 237,
 '무겁': 238,
 '그저': 239,
 '일본인': 240,
 '대단': 241,
 '생각': 242,
 '심심': 243,
 '그대로': 244,
 '악역': 245,
 '당황': 246,
 '중간': 247,
 '끝나': 248,
 '일상': 249,
 '계속': 250,
 '전개도': 251,
 '느리': 252,
 '주인공': 253,
 '모습': 254,
 '맨날': 255,
 '언제': 256,
 '전개': 257,
 '좀': 258,
 '빨리빨리': 259,
 '사랑': 260,
 '가슴속': 261,
 '감정': 262,
 '예': 263,
 '말': 264,
 '많': 265,
 '큐': 266,
 '우리나라': 267,
 '슬프': 268,
 '깊이': 269,
 '바로': 270,
 '노력': 271,
 '듣': 272,
 '민간인': 273,
 '학살': 274,
 '이정': 275,
 '살인': 276,
 '살인자': 277,
 '예전': 278,
 '작품': 279,
 '에피소드': 280,
 '재탕': 281,
 '먹': 282,
 '산': 283,
 '시청률': 284,
 '이제': 285,
 '연기력': 286,
 '몰입': 287,
 '비슷': 288,
 '안보': 289,
 '신': 290,
 '노래': 291,
 '실력': 292,
 '맞': 293,
 '일본': 294,
 '유치': 295,
 '이틀': 296,
 '조작': 297,
 '열리': 298,
 '집': 299,
 '들어가': 300,
 '걸리': 301,
 '억지': 302,
 '더': 303,
 '어설프': 304,
 '어이없': 305,
 '결말': 306,
 '온몸': 307,
 '폭': 308,
 '매우': 309,
 '실망': 310,
 '한국': 311,
 '흥행': 312,
 '갈등': 313,
 '계': 314,
 '에': 315,
 '뻔하': 316,
 '아햏햏': 317,
 '시작': 318,
 '사진': 319,
 '단연': 320,
 '우뢰': 321,
 '매': 322,
 '진정': 323,
 '별루': 324,
 '내일': 325,
 '좋아하': 326,
 '가요': 327,
 '골': 328,
 '눈': 329,
 '성룡': 330,
 '최': 331,
 '때리': 332,
 '이쁘': 333,
 '공주': 334,
 '인상': 335,
 '강': 336,
 '추': 337,
 '설정': 338,
 '새롭': 339,
 '미': 340,
 '유': 341,
 '대박': 342,
 '진심': 343,
 '영화인': 344,
 '쓰': 345,
 '술': 346,
 '어떻': 347,
 '킬링타임': 348,
 '떠오르': 349,
 '빠지': 350,
 '쪼': 351,
 '태어나': 352,
 '처음': 353,
 '불륜': 354,
 '로맨스': 355,
 '냐': 356,
 '왕': 357,
 '아주': 358,
 '짬뽕': 359,
 '덜': 360,
 '거지': 361,
 '명작': 362,
 '망치': 363,
 '소재': 364,
 '흥미': 365,
 '끌': 366,
 '보지': 367,
 '마라': 368,
 '특유': 369,
 '허풍': 370,
 '현실감': 371,
 '떨어지': 372,
 '거북': 373,
 '도대체': 374,
 '스스로': 375,
 '텐': 376,
 '미국': 377,
 '따뜻': 378,
 '삶': 379,
 '생애': 380,
 '전부': 381,
 '지나': 382,
 '후': 383,
 '남기': 384,
 '아니': 385,
 '순수': 386,
 '쇼': 387,
 '허': 388,
 '문제': 389,
 '연기자': 390,
 '전혀': 391,
 '어울리': 392,
 '상대': 393,
 '따로': 394,
 '아들': 395,
 '젤': 396,
 '베': 397,
 '나라': 398,
 '믿': 399,
 '가지': 400,
 '교훈': 401,
 '당시': 402,
 '상황': 403,
 '케이블': 404,
 '그만': 405,
 '다르': 406,
 '리': 407,
 '그릇': 408,
 '뭐': 409,
 '건지': 410,
 '한석규': 411,
 '많이': 412,
 '면': 413,
 '여': 414,
 '전': 415,
 '힘들': 416,
 '정도': 417,
 '마지막': 418,
 '살짝': 419,
 '떨': 420,
 '마': 421,
 '짱': 422,
 '이제서야': 423,
 '감히': 424,
 '살': 425,
 '고민': 426,
 '나이': 427,
 '여전히': 428,
 '섹시': 429,
 '혹시나': 430,
 '답': 431,
 '여운': 432,
 '손': 433,
 '상업': 434,
 '충분히': 435,
 '개인': 436,
 '잔인': 437,
 '노출': 438,
 '화끈': 439,
 '국산': 440,
 '아끼': 441,
 '끝내': 442,
 '지겹': 443,
 '드니': 444,
 '일품': 445,
 '죽이': 446,
 '괜찮': 447,
 '지': 448,
 '뜨': 449,
 '찍': 450,
 '껀': 451,
 '자신': 452,
 '어린이': 453,
 '어리': 454,
 '낫': 455,
 '인': 456,
 '총': 457,
 '에선': 458,
 '외국': 459,
 '상상': 460,
 '오랜만': 461,
 '종': 462,
 '방': 463,
 '오늘': 464,
 '요즘': 465,
 '막장': 466,
 '그리': 467,
 '심하': 468,
 '화이팅': 469,
 '의': 470,
 '순정': 471,
 '사극': 472,
 '왠지': 473,
 '코미디': 474,
 '의하': 475,
 '장면': 476,
 '한마디': 477,
 '존': 478,
 '유쾌': 479,
 '치': 480,
 '앉': 481,
 '이유': 482,
 '일반': 483,
 '통하': 484,
 '게임': 485,
 '배경': 486,
 '거슬리': 487,
 '엉망': 488,
 '주': 489,
 '못': 490,
 '예산': 491,
 '물': 492,
 '인줄': 493,
 '절': 494,
 '최악': 495,
 '아름답': 496,
 '익숙': 497,
 '뻑': 498,
 '읽': 499,
 '당하': 500,
 '극치': 501,
 '굉장히': 502,
 '남자': 503,
 '애': 504,
 '시종일관': 505,
 '싫': 506,
 '날': 507,
 '상당히': 508,
 '얼마나': 509,
 '진부': 510,
 '밖': 511,
 '티': 512,
 '짜': 513,
 '내': 514,
 '피': 515,
 '잠': 516,
 '판타지': 517,
 '따지': 518,
 '인격': 519,
 '어': 520,
 '옛날': 521,
 '시절': 522,
 '추억': 523,
 '나쁘': 524,
 '짓': 525,
 '기존': 526,
 '쏙': 527,
 '후회': 528,
 '도안': 529,
 '이영화': 530,
 '남은': 531,
 '없이': 532,
 '추천': 533,
 '싸이코': 534,
 '개봉': 535,
 '접하': 536,
 '순간': 537,
 '돌아오': 538,
 '무한': 539,
 '시리즈': 540,
 '달': 541,
 '후세': 542,
 '표현': 543,
 '생명': 544,
 '시노': 545,
 '출현': 546,
 '으': 547,
 '알리': 548,
 '새벽': 549,
 '개': 550,
 '예쁘': 551,
 '정': 552,
 '필요': 553,
 '미묘': 554,
 '너무너무': 555,
 '훈훈': 556,
 '네이버': 557,
 '장': 558,
 '가져오': 559,
 '오우삼': 560,
 '연출': 561,
 '인지': 562,
 '현실': 563,
 '제로': 564,
 '그때': 565,
 '느끼': 566,
 '대사': 567,
 '높': 568,
 '더럽': 569,
 '닿': 570,
 '허무': 571,
 '조연': 572,
 '꿈': 573,
 '특집': 574,
 '훌륭': 575,
 '판': 576,
 '의미': 577,
 '동급': 578,
 '마음': 579,
 '소': 580,
 '하지': 581,
 '코믹': 582,
 '짜임새': 583,
 '허술': 584,
 '일단': 585,
 '괴물': 586,
 '서스펜스': 587,
 '귀신': 588,
 '댓글': 589,
 '한번쯤': 590,
 '죽기': 591,
 '직전': 592,
 '란': 593,
 '보기': 594,
 '게': 595,
 '요': 596,
 '역': 597,
 '이그': 598,
 '기도': 599,
 '답답': 600,
 '정치인': 601,
 '모순': 602,
 '인가': 603,
 '전쟁': 604,
 '묘사': 605,
 '극장판': 606,
 '하니': 607,
 '전화': 608,
 '개그': 609,
 '없애': 610,
 '푸': 611,
 '세계': 612,
 '역사': 613,
 '가치': 614,
 '감각': 615,
 '바라보': 616,
 '색다르': 617,
 '엄마': 618,
 '딸': 619,
 '시키': 620,
 '제발': 621,
 '책': 622,
 '을': 623,
 '미치': 624,
 '화': 625,
 '흑인': 626,
 '생생': 627,
 '이상': 628,
 '아': 629,
 '굿': 630,
 '제맛': 631,
 '범죄': 632,
 '느와르': 633,
 '말이': 634,
 '본인': 635,
 '피해자': 636,
 '놓': 637,
 '기': 638,
 '필름': 639,
 '값': 640,
 '남주인공': 641,
 '습': 642,
 '혀': 643,
 '짧': 644,
 '소리': 645,
 '분이': 646,
 '적당히': 647,
 '스릴러': 648,
 '스릴': 649,
 '전달': 650,
 '글': 651,
 '거리': 652,
 '씩': 653,
 '부족': 654,
 '기억': 655,
 '이름': 656,
 '두': 657,
 '언니': 658,
 '부르': 659,
 '즐겁': 660,
 '망하': 661,
 '아이': 662,
 '시선': 663,
 '내내': 664,
 '먹먹': 665,
 '레알': 666,
 '여자': 667,
 '겁나': 668,
 '어색': 669,
 '여주인공': 670,
 '폭탄': 671,
 '가나': 672,
 '보니': 673,
 '딸리': 674,
 '개연': 675,
 '굳': 676,
 '호구': 677,
 '세기': 678,
 '쓸데없이': 679,
 '류': 680,
 '중요': 681,
 '여배우': 682,
 '고위': 683,
 '잇': 684,
 '애니': 685,
 '제목': 686,
 '지금': 687,
 '넘어가': 688,
 '군가': 689,
 '얘기': 690,
 '지루함': 691,
 '슬픔': 692,
 '아역': 693,
 '민폐': 694,
 '그럴싸': 695,
 '딱히': 696,
 '송강호': 697,
 '비디오': 698,
 '돌리': 699,
 '그립': 700,
 '해석': 701,
 '닮': 702,
 '비': 703,
 '한심': 704,
 '연예인': 705,
 '시나리오': 706,
 '끼': 707,
 '안타깝': 708,
 '돌아가': 709,
 '과': 710,
 '줄': 711,
 '영화로': 712,
 '세상': 713,
 '비정': 714,
 '친구': 715,
 '영상': 716,
 '다듬': 717,
 '감': 718,
 '부분': 719,
 '비롯': 720,
 '민망': 721,
 '군더더기': 722,
 '진행': 723,
 '탑': 724,
 '아빠': 725,
 '앗': 726,
 '빠': 727,
 '애니메이션': 728,
 '의도': 729,
 '불쾌': 730,
 '귀엽': 731,
 '연인': 732,
 '5년': 733,
 '강하': 734,
 '국민': 735,
 '해서': 736,
 '하나님': 737,
 '이신': 738,
 '흥미진진': 739,
 '첨': 740,
 '해': 741,
 '탄탄': 742,
 '점점': 743,
 '끝': 744,
 '이번': 745,
 '결국': 746,
 '지존파': 747,
 '삼': 748,
 '정당화': 749,
 '정부': 750,
 '탓': 751,
 '사회': 752,
 '사실': 753,
 '떠나': 754,
 '실제': 755,
 '검술': 756,
 '싸우': 757,
 '중국': 758,
 '하트': 759,
 '미스': 760,
 '평균': 761,
 '충분': 762,
 '급': 763,
 '슬': 764,
 '하기': 765,
 '자': 766,
 '모으': 767,
 '그러': 768,
 '멋있': 769,
 '메세지': 770,
 '빨리': 771,
 '영화사': 772,
 '히어로': 773,
 '놀이': 774,
 '중심': 775,
 '사건': 776,
 '인물': 777,
 '인간': 778,
 '레전드': 779,
 '빌리': 780,
 '나중': 781,
 '우연히': 782,
 '사촌': 783,
 '제가': 784,
 '절망': 785,
 '챙기': 786,
 '거부': 787,
 '흐르': 788,
 '맛': 789,
 '어마어마': 790,
 '소피': 791,
 '똥': 792,
 '원주민': 793,
 '일어나': 794,
 '우': 795,
 '실제로': 796,
 '바라': 797,
 '견자단': 798,
 '정말로': 799,
 '또': 800,
 '순위': 801,
 '늦': 802,
 '그런지': 803,
 '여배우들': 804,
 '그래픽': 805,
 '망': 806,
 '평론가': 807,
 '도움': 808,
 '바꾸': 809,
 '느': 810,
 '밥': 811,
 '장난': 812,
 '악의': 813,
 '보내': 814,
 '엄청': 815,
 '자식': 816,
 '살아오': 817,
 '서로': 818,
 '확실히': 819,
 '잃': 820,
 '고의': 821,
 '생기': 822,
 '사라지': 823,
 '공부': 824,
 '사': 825,
 '이후': 826,
 '아픔': 827,
 '유대인': 828,
 '인형': 829,
 '찌': 830,
 '다운': 831,
 '감사': 832,
 '샤넬': 833,
 '세월': 834,
 '찰나': 835,
 '영원': 836,
 '관하': 837,
 '두근거리': 838,
 '멀': 839,
 '아무리': 840,
 '용서': 841,
 '모두': 842,
 '엔': 843,
 '딩': 844,
 '영화관': 845,
 '몰': 846,
 '초가': 847,
 '갑자기': 848,
 '선생님': 849,
 '미안': 850,
 '놀': 851,
 '쥐': 852,
 '청춘': 853,
 '무기': 854,
 '약간': 855,
 '빼': 856,
 '반전': 857,
 '복수': 858,
 '해주': 859,
 '녀': 860,
 '끌리': 861,
 '디테일': 862,
 '완벽': 863,
 '찡': 864,
 '평생': 865,
 '생각나': 866,
 '짐승': 867,
 '자막': 868,
 '문화': 869,
 '전반': 870,
 '변화': 871,
 '벤지': 872,
 '숨': 873,
 '막히': 874,
 '곳곳': 875,
 '치밀': 876,
 '싸구려': 877,
 '밝히': 878,
 '안되': 879,
 '질질': 880,
 '봄': 881,
 '터지': 882,
 '겨': 883,
 '상영': 884,
 '미화': 885,
 '라면': 886,
 '전작': 887,
 '폭풍': 888,
 '함부로': 889,
 '남녀': 890,
 '웬만': 891,
 '잘못': 892,
 '엉성': 893,
 '차': 894,
 '싫어하': 895,
 '매니아': 896,
 '이하': 897,
 '아저씨': 898,
 '역겹': 899,
 '오르': 900,
 '공포물': 901,
 '귀': 902,
 '타': 903,
 '은': 904,
 '벌써': 905,
 '일찍': 906,
 '관람': 907,
 '신분': 908,
 '최근': 909,
 '점수': 910,
 '삼류': 911,
 '스타': 912,
 '얼굴': 913,
 '몸매': 914,
 '심형래': 915,
 '전체': 916,
 '주연': 917,
 '키': 918,
 '기키': 919,
 '엄청나': 920,
 '초등': 921,
 '근래': 922,
 '제작자': 923,
 '유럽': 924,
 '호화': 925,
 '같이': 926,
 '님': 927,
 '간만': 928,
 '영상미': 929,
 '제작': 930,
 '공포': 931,
 '원하': 932,
 '평': 933,
 '극장가': 934,
 '머리': 935,
 '묻어나': 936,
 '여정': 937,
 '독립': 938,
 '덕': 939,
 '업': 940,
 '박수': 941,
 '끼우': 942,
 '맞추': 943,
 '무어': 944,
 '최루': 945,
 '걸작': 946,
 '남편': 947,
 '외계인': 948,
 '재밌는 영화': 949,
 '주온': 950,
 '쏘': 951,
 '데리': 952,
 '라이': 953,
 '아련': 954,
 '존재': 955,
 '도': 956,
 '기억나': 957,
 '박사': 958,
 '록': 959,
 '철학': 960,
 '13구역': 961,
 '남성': 962,
 '요소': 963,
 '홍보': 964,
 '팔': 965,
 '차라리': 966,
 '열': 967,
 '실화': 968,
 '동생': 969,
 '디': 970,
 '아이들': 971,
 '주목': 972,
 '뇌': 973,
 '죽음': 974,
 '우주': 975,
 '맡': 976,
 '여성': 977,
 '예술': 978,
 '보통': 979,
 '고도': 980,
 '겪': 981,
 '쉬': 982,
 '즐기': 983,
 '분위기': 984,
 '여주': 985,
 '시점': 986,
 '비하': 987,
 '라이언': 988,
 '일병': 989,
 '참고': 990,
 '자위': 991,
 '이거': 992,
 '궁금': 993,
 '차리': 994,
 '선정': 995,
 '솔로': 996,
 '링': 997,
 '스타일': 998,
 '설마': 999,
 ...}

In [20]:
stoi2 = dict()
for idx, word in enumerate(vocab):
    stoi2[word] = idx
stoi2

{'<PAD>': 0,
 '<UNK>': 1,
 '더빙': 2,
 '진짜': 3,
 '짜증': 4,
 '나': 5,
 '목소리': 6,
 '포스터': 7,
 '초딩': 8,
 '영화': 9,
 '오버': 10,
 '연기': 11,
 '가볍': 12,
 '이야기': 13,
 '솔직히': 14,
 '재미': 15,
 '없': 16,
 '평점': 17,
 '돋보이': 18,
 '늙': 19,
 '보이': 20,
 '하': 21,
 '너무나': 22,
 '막': 23,
 '떼': 24,
 '초등학교': 25,
 '학년': 26,
 '용': 27,
 '별': 28,
 '반개': 29,
 '아깝': 30,
 '원작': 31,
 '긴장감': 32,
 '제대로': 33,
 '살리': 34,
 '욕': 35,
 '나오': 36,
 '생활': 37,
 '이': 38,
 '정말': 39,
 '발로': 40,
 '반복': 41,
 '드라마': 42,
 '가족': 43,
 '못하': 44,
 '사람': 45,
 '액션': 46,
 '있': 47,
 '안': 48,
 '왜': 49,
 '낮': 50,
 '꽤': 51,
 '보': 52,
 '헐리우드': 53,
 '화려': 54,
 '너무': 55,
 '볼': 56,
 '때': 57,
 '눈물': 58,
 '나서': 59,
 '죽': 60,
 '향수': 61,
 '자극': 62,
 '감성': 63,
 '절제': 64,
 '멜로': 65,
 '울': 66,
 '드럽': 67,
 '담백': 68,
 '깔끔': 69,
 '좋': 70,
 '기사': 71,
 '보다': 72,
 '자꾸': 73,
 '취향': 74,
 '극장': 75,
 '가장': 76,
 '노': 77,
 '재': 78,
 '감동': 79,
 '스토리': 80,
 '어거지': 81,
 '참': 82,
 '웃기': 83,
 '이기': 84,
 '코': 85,
 '까': 86,
 '고': 87,
 '깔': 88,
 '그냥': 89,
 '난': 90,
 '이해': 91,
 '뒤': 92,
 '갈수록': 93,
 '재미없': 94,
 '이건': 95,
 '깨알': 96,
 '캐스팅': 97,
 '내용': 98,
 '구성': 99,
 '잘': 100,
 '러': 101,
 '드': 102,
 '위하': 103,
 '착하': 104,
 '절대': 105,
 '뜻': 106,
 '웃': 107,
 '가능': 108,
 '지루': 109,
 '같': 110,
 '음식': 111,
 '만찬': 112,
 '넘': 113,
 '별로': 114,
 '평범': 115,
 '수작': 116,
 '드리': 117,
 '주제': 118,
 '중반': 119,
 '다': 120,
 '납득': 121,
 '그렇': 122,
 '꼭': 123,
 '걸': 124,
 '끄': 125,
 '고추': 126,
 '발': 127,
 '센스': 128,
 '연출력': 129,
 '탁월': 130,
 '90년대': 131,
 '포스': 132,
 '다시': 133,
 '깨닫': 134,
 '남': 135,
 '꽃': 136,
 '완전': 137,
 '졸': 138,
 '쓰레기': 139,
 '시간': 140,
 '재밌': 141,
 '별점': 142,
 '이리': 143,
 '기대': 144,
 '죄인': 145,
 '아직': 146,
 '인생': 147,
 '최고': 148,
 '대하': 149,
 '열정': 150,
 '안나': 151,
 '대체': 152,
 '정신': 153,
 '장애': 154,
 '작가': 155,
 '나가': 156,
 '재미있': 157,
 '관객': 158,
 '이렇': 159,
 '평가': 160,
 '받': 161,
 '모르': 162,
 '단순': 163,
 '은은': 164,
 '매력': 165,
 '알바': 166,
 '무섭': 167,
 '거도': 168,
 '오': 169,
 '서리': 170,
 '한': 171,
 '맘': 172,
 '들': 173,
 '방법': 174,
 '멋지': 175,
 '배우': 176,
 '되': 177,
 '일탈': 178,
 '잔잔': 179,
 '음악': 180,
 '조금': 181,
 '아쉽': 182,
 '길': 183,
 '낭비': 184,
 '돈': 185,
 '뛰어나': 186,
 '크': 187,
 '공감': 188,
 '가': 189,
 '이민기': 190,
 '캐릭터': 191,
 '조절': 192,
 '일': 193,
 '패': 194,
 '물건': 195,
 '극': 196,
 '초반': 197,
 '신선': 198,
 '상태': 199,
 '불가': 200,
 '마이너스': 201,
 '수준': 202,
 '딱': 203,
 '알': 204,
 '만들': 205,
 '데': 206,
 '가르': 207,
 '누': 208,
 '이랑': 209,
 '다니': 210,
 '소설': 211,
 '속': 212,
 '제일': 213,
 '메': 214,
 '라': 215,
 '웃음': 216,
 '감독': 217,
 '잠시': 218,
 '잊': 219,
 '동화': 220,
 '행복': 221,
 '르': 222,
 '게이': 223,
 '작': 224,
 '매운맛': 225,
 '콩': 226,
 '간다': 227,
 '가슴': 228,
 '자체': 229,
 '꼬마': 230,
 '깊': 231,
 '혼자': 232,
 '어쩌': 233,
 '충격': 234,
 '기분': 235,
 '완전히': 236,
 '느낌': 237,
 '무겁': 238,
 '그저': 239,
 '일본인': 240,
 '대단': 241,
 '생각': 242,
 '심심': 243,
 '그대로': 244,
 '악역': 245,
 '당황': 246,
 '중간': 247,
 '끝나': 248,
 '일상': 249,
 '계속': 250,
 '전개도': 251,
 '느리': 252,
 '주인공': 253,
 '모습': 254,
 '맨날': 255,
 '언제': 256,
 '전개': 257,
 '좀': 258,
 '빨리빨리': 259,
 '사랑': 260,
 '가슴속': 261,
 '감정': 262,
 '예': 263,
 '말': 264,
 '많': 265,
 '큐': 266,
 '우리나라': 267,
 '슬프': 268,
 '깊이': 269,
 '바로': 270,
 '노력': 271,
 '듣': 272,
 '민간인': 273,
 '학살': 274,
 '이정': 275,
 '살인': 276,
 '살인자': 277,
 '예전': 278,
 '작품': 279,
 '에피소드': 280,
 '재탕': 281,
 '먹': 282,
 '산': 283,
 '시청률': 284,
 '이제': 285,
 '연기력': 286,
 '몰입': 287,
 '비슷': 288,
 '안보': 289,
 '신': 290,
 '노래': 291,
 '실력': 292,
 '맞': 293,
 '일본': 294,
 '유치': 295,
 '이틀': 296,
 '조작': 297,
 '열리': 298,
 '집': 299,
 '들어가': 300,
 '걸리': 301,
 '억지': 302,
 '더': 303,
 '어설프': 304,
 '어이없': 305,
 '결말': 306,
 '온몸': 307,
 '폭': 308,
 '매우': 309,
 '실망': 310,
 '한국': 311,
 '흥행': 312,
 '갈등': 313,
 '계': 314,
 '에': 315,
 '뻔하': 316,
 '아햏햏': 317,
 '시작': 318,
 '사진': 319,
 '단연': 320,
 '우뢰': 321,
 '매': 322,
 '진정': 323,
 '별루': 324,
 '내일': 325,
 '좋아하': 326,
 '가요': 327,
 '골': 328,
 '눈': 329,
 '성룡': 330,
 '최': 331,
 '때리': 332,
 '이쁘': 333,
 '공주': 334,
 '인상': 335,
 '강': 336,
 '추': 337,
 '설정': 338,
 '새롭': 339,
 '미': 340,
 '유': 341,
 '대박': 342,
 '진심': 343,
 '영화인': 344,
 '쓰': 345,
 '술': 346,
 '어떻': 347,
 '킬링타임': 348,
 '떠오르': 349,
 '빠지': 350,
 '쪼': 351,
 '태어나': 352,
 '처음': 353,
 '불륜': 354,
 '로맨스': 355,
 '냐': 356,
 '왕': 357,
 '아주': 358,
 '짬뽕': 359,
 '덜': 360,
 '거지': 361,
 '명작': 362,
 '망치': 363,
 '소재': 364,
 '흥미': 365,
 '끌': 366,
 '보지': 367,
 '마라': 368,
 '특유': 369,
 '허풍': 370,
 '현실감': 371,
 '떨어지': 372,
 '거북': 373,
 '도대체': 374,
 '스스로': 375,
 '텐': 376,
 '미국': 377,
 '따뜻': 378,
 '삶': 379,
 '생애': 380,
 '전부': 381,
 '지나': 382,
 '후': 383,
 '남기': 384,
 '아니': 385,
 '순수': 386,
 '쇼': 387,
 '허': 388,
 '문제': 389,
 '연기자': 390,
 '전혀': 391,
 '어울리': 392,
 '상대': 393,
 '따로': 394,
 '아들': 395,
 '젤': 396,
 '베': 397,
 '나라': 398,
 '믿': 399,
 '가지': 400,
 '교훈': 401,
 '당시': 402,
 '상황': 403,
 '케이블': 404,
 '그만': 405,
 '다르': 406,
 '리': 407,
 '그릇': 408,
 '뭐': 409,
 '건지': 410,
 '한석규': 411,
 '많이': 412,
 '면': 413,
 '여': 414,
 '전': 415,
 '힘들': 416,
 '정도': 417,
 '마지막': 418,
 '살짝': 419,
 '떨': 420,
 '마': 421,
 '짱': 422,
 '이제서야': 423,
 '감히': 424,
 '살': 425,
 '고민': 426,
 '나이': 427,
 '여전히': 428,
 '섹시': 429,
 '혹시나': 430,
 '답': 431,
 '여운': 432,
 '손': 433,
 '상업': 434,
 '충분히': 435,
 '개인': 436,
 '잔인': 437,
 '노출': 438,
 '화끈': 439,
 '국산': 440,
 '아끼': 441,
 '끝내': 442,
 '지겹': 443,
 '드니': 444,
 '일품': 445,
 '죽이': 446,
 '괜찮': 447,
 '지': 448,
 '뜨': 449,
 '찍': 450,
 '껀': 451,
 '자신': 452,
 '어린이': 453,
 '어리': 454,
 '낫': 455,
 '인': 456,
 '총': 457,
 '에선': 458,
 '외국': 459,
 '상상': 460,
 '오랜만': 461,
 '종': 462,
 '방': 463,
 '오늘': 464,
 '요즘': 465,
 '막장': 466,
 '그리': 467,
 '심하': 468,
 '화이팅': 469,
 '의': 470,
 '순정': 471,
 '사극': 472,
 '왠지': 473,
 '코미디': 474,
 '의하': 475,
 '장면': 476,
 '한마디': 477,
 '존': 478,
 '유쾌': 479,
 '치': 480,
 '앉': 481,
 '이유': 482,
 '일반': 483,
 '통하': 484,
 '게임': 485,
 '배경': 486,
 '거슬리': 487,
 '엉망': 488,
 '주': 489,
 '못': 490,
 '예산': 491,
 '물': 492,
 '인줄': 493,
 '절': 494,
 '최악': 495,
 '아름답': 496,
 '익숙': 497,
 '뻑': 498,
 '읽': 499,
 '당하': 500,
 '극치': 501,
 '굉장히': 502,
 '남자': 503,
 '애': 504,
 '시종일관': 505,
 '싫': 506,
 '날': 507,
 '상당히': 508,
 '얼마나': 509,
 '진부': 510,
 '밖': 511,
 '티': 512,
 '짜': 513,
 '내': 514,
 '피': 515,
 '잠': 516,
 '판타지': 517,
 '따지': 518,
 '인격': 519,
 '어': 520,
 '옛날': 521,
 '시절': 522,
 '추억': 523,
 '나쁘': 524,
 '짓': 525,
 '기존': 526,
 '쏙': 527,
 '후회': 528,
 '도안': 529,
 '이영화': 530,
 '남은': 531,
 '없이': 532,
 '추천': 533,
 '싸이코': 534,
 '개봉': 535,
 '접하': 536,
 '순간': 537,
 '돌아오': 538,
 '무한': 539,
 '시리즈': 540,
 '달': 541,
 '후세': 542,
 '표현': 543,
 '생명': 544,
 '시노': 545,
 '출현': 546,
 '으': 547,
 '알리': 548,
 '새벽': 549,
 '개': 550,
 '예쁘': 551,
 '정': 552,
 '필요': 553,
 '미묘': 554,
 '너무너무': 555,
 '훈훈': 556,
 '네이버': 557,
 '장': 558,
 '가져오': 559,
 '오우삼': 560,
 '연출': 561,
 '인지': 562,
 '현실': 563,
 '제로': 564,
 '그때': 565,
 '느끼': 566,
 '대사': 567,
 '높': 568,
 '더럽': 569,
 '닿': 570,
 '허무': 571,
 '조연': 572,
 '꿈': 573,
 '특집': 574,
 '훌륭': 575,
 '판': 576,
 '의미': 577,
 '동급': 578,
 '마음': 579,
 '소': 580,
 '하지': 581,
 '코믹': 582,
 '짜임새': 583,
 '허술': 584,
 '일단': 585,
 '괴물': 586,
 '서스펜스': 587,
 '귀신': 588,
 '댓글': 589,
 '한번쯤': 590,
 '죽기': 591,
 '직전': 592,
 '란': 593,
 '보기': 594,
 '게': 595,
 '요': 596,
 '역': 597,
 '이그': 598,
 '기도': 599,
 '답답': 600,
 '정치인': 601,
 '모순': 602,
 '인가': 603,
 '전쟁': 604,
 '묘사': 605,
 '극장판': 606,
 '하니': 607,
 '전화': 608,
 '개그': 609,
 '없애': 610,
 '푸': 611,
 '세계': 612,
 '역사': 613,
 '가치': 614,
 '감각': 615,
 '바라보': 616,
 '색다르': 617,
 '엄마': 618,
 '딸': 619,
 '시키': 620,
 '제발': 621,
 '책': 622,
 '을': 623,
 '미치': 624,
 '화': 625,
 '흑인': 626,
 '생생': 627,
 '이상': 628,
 '아': 629,
 '굿': 630,
 '제맛': 631,
 '범죄': 632,
 '느와르': 633,
 '말이': 634,
 '본인': 635,
 '피해자': 636,
 '놓': 637,
 '기': 638,
 '필름': 639,
 '값': 640,
 '남주인공': 641,
 '습': 642,
 '혀': 643,
 '짧': 644,
 '소리': 645,
 '분이': 646,
 '적당히': 647,
 '스릴러': 648,
 '스릴': 649,
 '전달': 650,
 '글': 651,
 '거리': 652,
 '씩': 653,
 '부족': 654,
 '기억': 655,
 '이름': 656,
 '두': 657,
 '언니': 658,
 '부르': 659,
 '즐겁': 660,
 '망하': 661,
 '아이': 662,
 '시선': 663,
 '내내': 664,
 '먹먹': 665,
 '레알': 666,
 '여자': 667,
 '겁나': 668,
 '어색': 669,
 '여주인공': 670,
 '폭탄': 671,
 '가나': 672,
 '보니': 673,
 '딸리': 674,
 '개연': 675,
 '굳': 676,
 '호구': 677,
 '세기': 678,
 '쓸데없이': 679,
 '류': 680,
 '중요': 681,
 '여배우': 682,
 '고위': 683,
 '잇': 684,
 '애니': 685,
 '제목': 686,
 '지금': 687,
 '넘어가': 688,
 '군가': 689,
 '얘기': 690,
 '지루함': 691,
 '슬픔': 692,
 '아역': 693,
 '민폐': 694,
 '그럴싸': 695,
 '딱히': 696,
 '송강호': 697,
 '비디오': 698,
 '돌리': 699,
 '그립': 700,
 '해석': 701,
 '닮': 702,
 '비': 703,
 '한심': 704,
 '연예인': 705,
 '시나리오': 706,
 '끼': 707,
 '안타깝': 708,
 '돌아가': 709,
 '과': 710,
 '줄': 711,
 '영화로': 712,
 '세상': 713,
 '비정': 714,
 '친구': 715,
 '영상': 716,
 '다듬': 717,
 '감': 718,
 '부분': 719,
 '비롯': 720,
 '민망': 721,
 '군더더기': 722,
 '진행': 723,
 '탑': 724,
 '아빠': 725,
 '앗': 726,
 '빠': 727,
 '애니메이션': 728,
 '의도': 729,
 '불쾌': 730,
 '귀엽': 731,
 '연인': 732,
 '5년': 733,
 '강하': 734,
 '국민': 735,
 '해서': 736,
 '하나님': 737,
 '이신': 738,
 '흥미진진': 739,
 '첨': 740,
 '해': 741,
 '탄탄': 742,
 '점점': 743,
 '끝': 744,
 '이번': 745,
 '결국': 746,
 '지존파': 747,
 '삼': 748,
 '정당화': 749,
 '정부': 750,
 '탓': 751,
 '사회': 752,
 '사실': 753,
 '떠나': 754,
 '실제': 755,
 '검술': 756,
 '싸우': 757,
 '중국': 758,
 '하트': 759,
 '미스': 760,
 '평균': 761,
 '충분': 762,
 '급': 763,
 '슬': 764,
 '하기': 765,
 '자': 766,
 '모으': 767,
 '그러': 768,
 '멋있': 769,
 '메세지': 770,
 '빨리': 771,
 '영화사': 772,
 '히어로': 773,
 '놀이': 774,
 '중심': 775,
 '사건': 776,
 '인물': 777,
 '인간': 778,
 '레전드': 779,
 '빌리': 780,
 '나중': 781,
 '우연히': 782,
 '사촌': 783,
 '제가': 784,
 '절망': 785,
 '챙기': 786,
 '거부': 787,
 '흐르': 788,
 '맛': 789,
 '어마어마': 790,
 '소피': 791,
 '똥': 792,
 '원주민': 793,
 '일어나': 794,
 '우': 795,
 '실제로': 796,
 '바라': 797,
 '견자단': 798,
 '정말로': 799,
 '또': 800,
 '순위': 801,
 '늦': 802,
 '그런지': 803,
 '여배우들': 804,
 '그래픽': 805,
 '망': 806,
 '평론가': 807,
 '도움': 808,
 '바꾸': 809,
 '느': 810,
 '밥': 811,
 '장난': 812,
 '악의': 813,
 '보내': 814,
 '엄청': 815,
 '자식': 816,
 '살아오': 817,
 '서로': 818,
 '확실히': 819,
 '잃': 820,
 '고의': 821,
 '생기': 822,
 '사라지': 823,
 '공부': 824,
 '사': 825,
 '이후': 826,
 '아픔': 827,
 '유대인': 828,
 '인형': 829,
 '찌': 830,
 '다운': 831,
 '감사': 832,
 '샤넬': 833,
 '세월': 834,
 '찰나': 835,
 '영원': 836,
 '관하': 837,
 '두근거리': 838,
 '멀': 839,
 '아무리': 840,
 '용서': 841,
 '모두': 842,
 '엔': 843,
 '딩': 844,
 '영화관': 845,
 '몰': 846,
 '초가': 847,
 '갑자기': 848,
 '선생님': 849,
 '미안': 850,
 '놀': 851,
 '쥐': 852,
 '청춘': 853,
 '무기': 854,
 '약간': 855,
 '빼': 856,
 '반전': 857,
 '복수': 858,
 '해주': 859,
 '녀': 860,
 '끌리': 861,
 '디테일': 862,
 '완벽': 863,
 '찡': 864,
 '평생': 865,
 '생각나': 866,
 '짐승': 867,
 '자막': 868,
 '문화': 869,
 '전반': 870,
 '변화': 871,
 '벤지': 872,
 '숨': 873,
 '막히': 874,
 '곳곳': 875,
 '치밀': 876,
 '싸구려': 877,
 '밝히': 878,
 '안되': 879,
 '질질': 880,
 '봄': 881,
 '터지': 882,
 '겨': 883,
 '상영': 884,
 '미화': 885,
 '라면': 886,
 '전작': 887,
 '폭풍': 888,
 '함부로': 889,
 '남녀': 890,
 '웬만': 891,
 '잘못': 892,
 '엉성': 893,
 '차': 894,
 '싫어하': 895,
 '매니아': 896,
 '이하': 897,
 '아저씨': 898,
 '역겹': 899,
 '오르': 900,
 '공포물': 901,
 '귀': 902,
 '타': 903,
 '은': 904,
 '벌써': 905,
 '일찍': 906,
 '관람': 907,
 '신분': 908,
 '최근': 909,
 '점수': 910,
 '삼류': 911,
 '스타': 912,
 '얼굴': 913,
 '몸매': 914,
 '심형래': 915,
 '전체': 916,
 '주연': 917,
 '키': 918,
 '기키': 919,
 '엄청나': 920,
 '초등': 921,
 '근래': 922,
 '제작자': 923,
 '유럽': 924,
 '호화': 925,
 '같이': 926,
 '님': 927,
 '간만': 928,
 '영상미': 929,
 '제작': 930,
 '공포': 931,
 '원하': 932,
 '평': 933,
 '극장가': 934,
 '머리': 935,
 '묻어나': 936,
 '여정': 937,
 '독립': 938,
 '덕': 939,
 '업': 940,
 '박수': 941,
 '끼우': 942,
 '맞추': 943,
 '무어': 944,
 '최루': 945,
 '걸작': 946,
 '남편': 947,
 '외계인': 948,
 '재밌는 영화': 949,
 '주온': 950,
 '쏘': 951,
 '데리': 952,
 '라이': 953,
 '아련': 954,
 '존재': 955,
 '도': 956,
 '기억나': 957,
 '박사': 958,
 '록': 959,
 '철학': 960,
 '13구역': 961,
 '남성': 962,
 '요소': 963,
 '홍보': 964,
 '팔': 965,
 '차라리': 966,
 '열': 967,
 '실화': 968,
 '동생': 969,
 '디': 970,
 '아이들': 971,
 '주목': 972,
 '뇌': 973,
 '죽음': 974,
 '우주': 975,
 '맡': 976,
 '여성': 977,
 '예술': 978,
 '보통': 979,
 '고도': 980,
 '겪': 981,
 '쉬': 982,
 '즐기': 983,
 '분위기': 984,
 '여주': 985,
 '시점': 986,
 '비하': 987,
 '라이언': 988,
 '일병': 989,
 '참고': 990,
 '자위': 991,
 '이거': 992,
 '궁금': 993,
 '차리': 994,
 '선정': 995,
 '솔로': 996,
 '링': 997,
 '스타일': 998,
 '설마': 999,
 ...}

In [21]:
import torch

In [22]:
# 인코딩 함수 정의
def encode(toks):
    result = [stoi.get(word, stoi['<UNK>']) for word in toks]
    return result

enc_inputs = [torch.tensor(encode(toks), dtype=torch.long) for toks in tokens_list]

In [23]:
enc_inputs

[tensor([2, 3, 4, 5, 6]),
 tensor([ 7,  8,  9, 10, 11, 12]),
 tensor([], dtype=torch.int64),
 tensor([ 1, 13, 14, 15, 16, 17,  1]),
 tensor([ 1, 11, 18,  9,  1, 19, 20, 21,  1, 22]),
 tensor([23,  1, 24, 25, 26, 27,  9, 28, 29, 30]),
 tensor([31, 32, 33, 34]),
 tensor([29, 30, 35, 36,  1,  1, 11, 37, 38, 39, 40,  1,  1, 41, 41, 38, 42, 43,
         16, 11, 44, 45,  1]),
 tensor([46, 16, 15, 47, 48,  9]),
 tensor([49, 17, 50, 51, 52, 53, 54, 55,  1, 47]),
 tensor([], dtype=torch.int64),
 tensor([56, 57, 58, 59, 60, 61, 62,  1, 63, 64, 65,  1]),
 tensor([66,  1,  1,  1, 57,  1,  1, 11, 67]),
 tensor([68, 69, 70,  1, 71,  1, 72, 52, 73,  1, 45]),
 tensor([74,  1,  3, 75, 52,  9, 76, 77, 78, 77, 79, 80, 81, 79, 81]),
 tensor([1, 1]),
 tensor([82, 45, 83,  1, 84,  1, 85, 86, 87,  1, 84,  1, 88, 89, 86,  1, 90, 20]),
 tensor([ 1,  1, 91, 49, 92, 93, 94]),
 tensor([ 95,  39,  96,  97,   1,   1,  98,  99, 100,   1, 101,   1,  96, 102]),
 tensor([  1, 103,   1, 104, 105]),
 tensor([  1, 106,  47,  89,   1,   1,   1,   9, 105]),
 tensor([ 52, 107, 108]),
 tensor([ 94, 109, 110, 111,   9, 112, 113, 112,  13,  47, 111,  52,  15,  47,
          95,  52,  16, 111, 114,  48,  36,   1,   1, 114,  48,  36]),
 tensor([105, 115,   9, 116,   1, 117]),
 tensor([118,  70, 119, 109]),
 tensor([120,   1, 121,  16, 122, 123, 122, 124, 125]),
 tensor([126,   1,  21]),
 tensor([  1,   1, 127,  11]),
 tensor([], dtype=torch.int64),
 tensor([128,  47, 129, 130,  97, 131,  61]),
 tensor([  1, 132,   1, 133, 134,  21, 135, 136,   1,  11,  39,  70, 137,   1,
          42]),
 tensor([138, 139, 140,  30]),
 tensor([141, 142,  49, 143,  50,   1]),
 tensor([  1, 144, 145, 145]),
 tensor([146,  42, 147, 148]),
 tensor([  1, 149, 150, 151,   1,   1]),
 tensor([  1,  11,  21, 152, 153, 154,   1, 154]),
 tensor([  1, 155, 153, 156,   1, 157]),
 tensor([  7,  47,  20, 158]),
 tensor([  9,  49, 159, 160, 161, 162]),
 tensor([163, 164, 165,   9]),
 tensor([120, 166,  98,  16, 167, 168,  16,  83, 168,  16, 137,  28,   1,   9,
         140, 113,  30, 137,   1]),
 tensor([169, 170, 171,   1]),
 tensor([ 39, 172, 173,  52,  52, 174,  16]),
 tensor([  1, 175, 176,   1, 177,   1, 178, 179,   1,   1, 180, 181, 182,  17,
           1]),
 tensor([ 17,   1,   1, 183, 140, 184, 185, 184]),
 tensor([  1, 186,  21, 187, 188,  48, 189, 190, 191,   1,   1, 192, 154,   1,
           1, 193,   1,  45, 194,  35, 195,   1, 181,   1, 196, 197, 198, 189,
          93, 190, 153, 199, 188, 200]),
 tensor([201,  49,  16,  52,   9, 202, 203, 204,   1, 205, 185,   1]),
 tensor([5, 9, 1]),
 tensor([206,   1,   1, 207,   1,   1, 177, 208, 209,   1,  21, 210, 211, 212,
         213, 175,   1, 214, 215,   1,  42, 212,   1,  27, 213, 175, 216, 217,
           1,   1,   1,   1,   1,  21]),
 tensor([  9,  45,   1,   1,  47,   1,   1, 218, 219, 220, 110,   9, 221]),
 tensor([222, 223, 224, 126, 225,  20, 226,   1, 227]),
 tensor([159, 228,   1,  52,  42,  47,  79, 229]),
 tensor([ 90, 230,   1,   1, 231,  21,  89, 232,   1, 124, 233]),
 tensor([157]),
 tensor([70]),
 tensor([148]),
 tensor([ 55, 234, 235, 236,   1,   1,  21, 237,   1,  16,  22, 238,   1,   1,
           1, 239, 240,   1,  39, 241, 110, 242, 173]),
 tensor([243,   9]),
 tensor([  1,   1, 169]),
 tensor([ 52, 244,   1,   1,   1,  16, 245]),
 tensor([  1,  36, 246,   1,   9, 247, 248, 237]),
 tensor([115,   1,   1,   1, 115, 249, 181,   1]),
 tensor([ 52, 250,  52, 251, 252, 253,   1,   1,  36,   1, 254,   4, 255, 256,
         248, 144,  21, 257, 258, 259]),
 tensor([260, 261, 169, 262,   1,   9, 263,   1, 264, 148]),
 tensor([265,  45, 120, 266,  52, 267, 268,   1,   1, 149, 269, 242,   1, 270,
           1, 103, 271, 264, 272,   1,   1, 273, 274, 275,  95,   1, 276, 277,
         120,  47]),
 tensor([278, 279, 191, 280, 281,   1,   1,   1, 282,  98, 283, 189, 284,   1,
          48,  36, 285, 119]),
 tensor([  1, 286, 197, 287,   1, 109,   1]),
 tensor([141, 288,   9, 289, 290, 157]),
 tensor([291, 292,   1, 293,   1,   1,   3,   1]),
 tensor([294,   9, 120, 295]),
 tensor([296, 120,  52, 141,  48, 195,   1, 297,  21,  48, 298, 299,  48,   1,
         298, 300,   1, 297,   1,  48, 301, 302,  98, 229,  70]),
 tensor([138, 224]),
 tensor([  1,   1, 303, 141]),
 tensor([304, 257, 305, 306]),
 tensor([  1,   1,   1, 110,   9, 307,   1,   1,   1, 239, 308,   1]),
 tensor([ 98, 257,   1,   1, 100,  52]),
 tensor([309, 310]),
 tensor([311,   9, 312,   1, 313, 313, 314, 315, 212, 313,   1,  79,  17,   1,
         312, 316]),
 tensor([317, 317, 317]),
 tensor([318,   1,  36,   1, 319,  52,   1]),
 tensor([320, 148,  21]),
 tensor([217,   9, 205, 158, 264, 162,   1,   1,   1]),
 tensor([ 95, 321, 322]),
 tensor([ 39, 139,   9]),
 tensor([323,   1,   9, 148]),
 tensor([324]),
 tensor([325, 144]),
 tensor([  1,  23,   1, 326, 327]),
 tensor([  3, 328,  86, 329,   1,  57,   1]),
 tensor([330,   9, 331,   1]),
 tensor([328, 332,   1,   1, 100, 177]),
 tensor([  1, 333]),
 tensor([137, 141,   1, 334,   1]),
 tensor([335,   9]),
 tensor([  1,   1,   1, 137, 336, 337,  39, 141]),
 tensor([157,   9]),
 tensor([ 1,  1, 87,  1,  1]),
 tensor([  3,  52,  55, 268,   9]),
 tensor([338, 141, 339, 280,   1,  80,   1,  36, 141]),
 tensor([  1,   1, 340, 341,   1,  11, 100, 303, 342,  38]),
 tensor([ 94, 343,  97]),
 tensor([179, 242,  52, 344, 110]),
 tensor([217,   1, 345,   9,  48,  52]),
 tensor([167,  80]),
 tensor([  9, 212, 302,   1, 346,   1, 258, 164, 128,  47,  21, 347]),
 tensor([348]),
 tensor([  1, 349,   9]),
 tensor([157,  52, 165, 221]),
 tensor([180, 236, 350,  52,   9, 351,   1,  21]),
 tensor([352, 353,   9, 247,  36, 354, 355, 356]),
 tensor([357,   4, 358, 257, 359,   1,   1, 167,  21]),
 tensor([ 14,   5, 324, 360, 140, 184, 237]),
 tensor([342]),
 tensor([284,   1, 177,   1,   1, 361, 362,  42, 120, 363, 120,   1]),
 tensor([98,  1]),
 tensor([  1,   1, 141,  52]),
 tensor([ 98, 257,  22, 252]),
 tensor([364, 365, 366,  13, 257,   1, 287,  48]),
 tensor([105, 367, 368, 139,   9]),
 tensor([  1, 369,   1, 370,  47,  20,   1, 345, 271,   1,   1, 371, 372, 338,
         373, 374,  49, 159, 375,   1,   1]),
 tensor([ 89,   1,   1,   9,  70, 376,   1, 205, 377, 378, 338,  95]),
 tensor([  1, 379, 212, 253, 380, 381,   1]),
 tensor([142,   1]),
 tensor([114, 120]),
 tensor([ 52,  51, 382, 383, 384, 157]),
 tensor([385,  38,  49, 193]),
 tensor([382, 133,  52, 177,   9, 133,  52, 386, 260,  79, 387,   1,  11]),
 tensor([  1,   1,  47,  52, 388,  80, 389, 390, 391,   1, 209, 392, 393, 176,
         120, 394, 110,  95, 390, 389,  47,  52, 343, 137, 114,   1, 395, 396,
          56,  21]),
 tensor([ 55,   1, 265,   9,  33,  20]),
 tensor([1]),
 tensor([397, 264, 358, 100, 345]),
 tensor([358,   1,   1]),
 tensor([  9,   1,   1,  21, 110, 398, 205, 399]),
 tensor([307,   1,   1,   1, 400]),
 tensor([ 39, 157, 401,   9]),
 tensor([402, 403, 118,   1,  32,  47, 141,   1, 279]),
 tensor([404, 405,  36]),
 tensor([406, 356, 407,   1,  48,   1, 359, 408,   1]),
 tensor([  1,  78,  16, 409, 410,  78,  16, 120,  78,  16,   1,   1]),
 tensor([70]),
 tensor([411,   1,  11,  18,   9, 162, 412, 304,   9]),
 tensor([ 14,   1,   1,  52, 177,   9, 279, 413, 414, 415,   9, 399, 416, 417,
          39, 100, 205, 418,   1, 419, 182,  21, 275,   1, 116, 140,  30,   9]),
 tensor([52,  1]),
 tensor([157, 370, 420, 421]),
 tensor([  1,   3, 422, 422, 322]),
 tensor([  9, 423, 424, 147, 148,   9,   1,   1,  47, 279, 347, 425, 103, 426,
         303,  21, 177, 140,   1, 427, 173, 428, 429]),
 tensor([155, 114, 120,  98,  38,   3, 255,  89, 144,   1, 430, 431,  16,   3]),
 tensor([362, 362,  47,  52,  52, 432, 135,   9]),
 tensor([  3, 181, 303, 433, 258,  52,  49,  21, 434,   9,  44, 205, 182, 435,
         157, 436, 181, 303, 437, 303,  62, 438, 439,  21, 347,  21, 440,   9,
         412, 441,  20]),
 tensor([405, 258, 366, 285, 442, 443, 443]),
 tensor([], dtype=torch.int64),
 tensor([444,  11, 445,   1,   1, 446,  21]),
 tensor([447, 279]),
 tensor([55, 70,  9]),
 tensor([ 39, 310]),
 tensor([176, 448,  48, 449,   9, 450, 451,  49,  48, 449,   3, 162,   1, 203,
          52, 204,  49, 452, 162]),
 tensor([453, 326, 454,   1,   1, 449, 455]),
 tensor([  1, 456,  49, 457, 173]),
 tensor([], dtype=torch.int64),
 tensor([1, 1, 1, 1]),
 tensor([311, 458,   1, 459, 460,   1,   1,   9]),
 tensor([461]),
 tensor([462, 463, 182, 464,  23,   1, 100,  52,   1,   1,  51,   1,  47, 237,
         161, 465,  42, 466,   1,   1,  39,   1,  42, 245, 467, 468, 305, 469]),
 tensor([ 17, 192,   1,  36, 216,   1,   1, 470,   1, 471, 471,   1, 417, 100,
           1,  39,   1,  11,   1,  45, 465, 472,   1,  47, 149,  11,   1, 473,
         474, 475, 476, 110, 216]),
 tensor([  9, 248,  57,   1, 120,  52, 477,  36, 110]),
 tensor([  1, 478, 100]),
 tensor([  1,   1,   9, 264, 366,   1, 364, 479,   1]),
 tensor([  1,  60, 480, 481,   1,  52, 482,  16, 279]),
 tensor([1]),
 tensor([  1,   1, 453, 483,   1, 484, 204, 485, 365,   1, 253,  55,   1, 114,
          94, 486, 487]),
 tensor([  1,   1,   1, 488, 135, 489,   1, 490, 337,  98, 316, 253,   6,  55,
          48, 392,   1,   1, 156,  82, 343,   1,   1, 491,   9,   1,   9,   1,
           1,  48]),
 tensor([454, 427,  52,  51, 326,   1, 474]),
 tensor([223, 492, 493, 162,  52]),
 tensor([166, 125, 494]),
 tensor([  9,  49, 161,  52, 204,  38,   9, 176,   1, 217,   1]),
 tensor([495]),
 tensor([ 39, 496,   9,  38]),
 tensor([ 62, 497,   1,  52, 329,  24, 416, 129]),
 tensor([498, 498, 100, 499, 500]),
 tensor([ 39,   4, 501,  20,   9, 502, 237,   1,   1, 503, 504, 127,  11, 505,
          52,   1,   1, 179,   1, 180,   1, 272, 506,   4, 507, 417, 508, 506,
           9]),
 tensor([ 79,  79,  39, 148]),
 tensor([142,  30, 509,  98, 510,  35, 511,  48,  36, 141,  21,  45,   8,   1,
          55,   1,  59,  52,  16,  52, 421,  89, 512,   1, 513,   1, 110]),
 tensor([ 49,  21,   4,  48, 514]),
 tensor([  1, 515, 282,   1,   1, 476, 458,   1,  21]),
 tensor([], dtype=torch.int64),
 tensor([295, 109, 516]),
 tensor([517,   1]),
 tensor([  1,   1,  70,   1, 374,  49,   1, 204,  16,   1, 292, 518, 415,   1,
           1, 519, 292,   1,   1, 183, 520, 388, 405, 258,  21]),
 tensor([  1, 279, 521,   1]),
 tensor([  1, 148,   9]),
 tensor([454, 522,  55, 167, 157,  52, 523, 517,   9, 105, 524, 525,   1,   1,
         327]),
 tensor([526,  65,   9,   1,   1,  21, 262,  64,   1,  55,  68,   9]),
 tensor([  5,   1,   1, 527, 350, 527,   5, 105, 219, 528, 529,   1]),
 tensor([530,  52, 401, 531, 147,  54, 264,  48,  36]),
 tensor([523,   1,  70, 242, 532,  12,  52, 533]),
 tensor([163, 534, 492,   1]),
 tensor([ 38, 205, 327, 278, 205, 133, 535, 171, 327,  55, 388, 536]),
 tensor([113, 260,   9,   1,   1,  52, 113,   1]),
 tensor([  1,  47,  63,   1, 537,   1, 133, 538,   1, 537, 539,   1,  47,  63]),
 tensor([  1, 540, 146,   1]),
 tensor([  1, 465,  93,   1, 541,  78, 216,   1,   5]),
 tensor([  1, 171, 170,   1,   1,  79]),
 tensor([542, 260, 177,   1,   1, 140, 543, 544,   1, 482, 545, 546,   1, 547,
           1, 303, 548,  21, 242, 545, 509,   1,  21, 271, 303,  20,  70]),
 tensor([549, 140,  21, 294,   9, 381, 550, 138, 224, 294,   9,   1, 120,   1]),
 tensor([  1, 156,   1,   1, 290]),
 tensor([ 39,   1,  55, 551,   1, 107,  39]),
 tensor([  1, 345]),
 tensor([ 54, 414, 552,   1, 231,   1,  11,  39, 100]),
 tensor([  1, 103,   1,   1,   9]),
 tensor([79,  9]),
 tensor([ 95, 264, 553,  16,  89,   1,  52]),
 tensor([  1,  45, 141, 175, 260,   9]),
 tensor([377,  42,   1,  39, 204,   1, 554,   1, 148]),
 tensor([555, 556]),
 tensor([  1,   1,   1, 375,  35]),
 tensor([ 55,  83,   1, 350,   1,   9,  47]),
 tensor([ 99, 508,   1,   9, 557,  17, 399,  16]),
 tensor([558, 366,   1,   1, 559, 560,  53, 279,  76,  94, 138, 224]),
 tensor([  1, 561, 562, 563, 564,   9]),
 tensor([224,   1,   1,   1, 522, 565, 237, 133, 566, 140, 476, 567, 486, 180,
          16,  42]),
 tensor([343,  15,  16,  55,  17, 568,   1]),
 tensor([569,  94,   1, 169, 570, 571,   1, 109,   9,   1,  16,   9]),
 tensor([  1,  39,  11, 100, 572,  11,  39, 100]),
 tensor([563, 573, 573, 563]),
 tensor([464,   1, 574,   1,  52, 177, 309, 575, 279]),
 tensor([576, 577, 578]),
 tensor([  1,  52, 303, 141]),
 tensor([  9,  52, 579,   1,   1, 237, 580,   1, 581, 179, 109, 133,  52,   9,
           1,   1,  38,   1,   1, 335]),
 tensor([582,  70, 583,  55, 584]),
 tensor([565, 402, 398, 517, 355,  16, 146,   1,   1,   1,  11, 447, 411,   1,
         298,   9,   1, 411,   1, 189]),
 tensor([585,   1, 586, 110, 587, 588, 110,   1,   1]),
 tensor([  3, 589, 590,  56, 344, 110, 591, 592,   1,   1,  52, 591, 592,  23,
         425, 456, 110,  79,  16,   3, 593,   9,   1,  57, 490,   1, 139,   9,
           1, 478, 310]),
 tensor([140, 258,   1,   1,  42,  52, 594,  52,  10,  11, 487,  11, 456, 595,
          55,   1, 596,   1, 597, 598,   1,   1, 599,   1,   1, 173, 600, 514,
           1,   1, 171,  52]),
 tensor([601, 602, 603,   1, 602]),
 tensor([347, 460, 241]),
 tensor([258,   1,  21, 604, 149, 605, 100, 162]),
 tensor([294, 606, 205, 267, 458, 535, 607,  95, 258]),
 tensor([  1,  52, 608,   1, 609,   1, 610]),
 tensor([  1,   1, 176,   1]),
 tensor([611,  21,  21,  21, 144,  48]),
 tensor([612,   1,   1,   1, 613, 614]),
 tensor([615,   1, 616, 617, 237, 260,   1]),
 tensor([618,   1, 619,   1, 620, 620,  91,  48]),
 tensor([530, 621, 622, 623,   1, 217, 624,  38, 205, 625, 507, 417]),
 tensor([  1, 626, 180,   1, 135,  16]),
 tensor([ 67,  94, 140, 185, 140, 233]),
 tensor([239, 477, 548]),
 tensor([  3, 627, 566]),
 tensor([141,  17, 628, 417,  50]),
 tensor([  1,   1, 319, 384, 189, 137, 342,   3,   1,   4]),
 tensor([42, 55]),
 tensor([629,   3,  55,  70, 422, 422]),
 tensor([ 11, 630]),
 tensor([  9, 133,  48,  36, 565, 522, 100,   1, 110]),
 tensor([247, 417,  52,  51, 241]),
 tensor([226,  86, 631, 226,  86, 631]),
 tensor([211,  94]),
 tensor([ 46,   9, 632, 633,   9, 632, 633,   9,   1]),
 tensor([189, 204,  16, 165, 350,   9]),
 tensor([  1,   1,   1, 277,   1, 634,  79, 161,  45, 635, 636,  79, 161,  21,
         343,   1]),
 tensor([141,  17,  49, 159,   1]),
 tensor([ 52, 329,  30,   3, 637,   3, 638, 362]),
 tensor([639, 640,  30,  15, 569,  16,   1, 202,   1]),
 tensor([52]),
 tensor([  9, 157]),
 tensor([641, 286,  48, 642, 643, 644, 645, 272,  55, 416,   1,   1, 646, 641,
          70, 242, 173, 417,   9, 229, 647,  52,  21]),
 tensor([203,  46, 648,  46, 649,  16]),
 tensor([137,  80, 488, 137, 337]),
 tensor([  9, 650, 162, 169, 651, 652]),
 tensor([70,  9]),
 tensor([  2, 628,   1,   1, 497]),
 tensor([38, 36]),
 tensor([595, 653, 120, 654, 653]),
 tensor([ 39, 264, 244, 387,  21,   9]),
 tensor([415,  52, 655,   1,   1, 217, 656, 655, 657]),
 tensor([  1, 658,  11, 100, 291, 100, 659, 418, 107, 660,  52,   1]),
 tensor([38]),
 tensor([661]),
 tensor([662, 663,  52, 604,  52, 664, 228, 665]),
 tensor([ 45,  94,  21, 666, 144,  48, 242,  52, 667, 504,   1,   1, 476,   1,
          16, 177, 242, 287, 668, 610, 669,  20]),
 tensor([338,   1, 110, 237, 173, 176,  11, 186]),
 tensor([670,   1,  57, 109,  60, 204,   1, 348, 648]),
 tensor([340,   1,   1,  89,   1,  21, 347,   9,  21, 521, 131, 321, 322, 202,
         492, 671,   1, 433,   1, 672, 433, 492, 671, 156, 406]),
 tensor([217, 667, 120, 673,   1, 412, 674]),
 tensor([52]),
 tensor([  9, 675,  16, 571, 205,   1,   7, 333, 254, 135,   9]),
 tensor([676, 676]),
 tensor([ 80, 264,  48,   1, 558,   1, 599, 385, 263,  52, 140, 185, 441, 263,
           1,  52, 677]),
 tensor([ 34,   1,  30, 678, 567]),
 tensor([ 17,  55, 568, 391, 157, 679, 264, 265, 680,   9, 572,   1, 681, 572,
          98, 229, 391,  16, 682, 114, 165,  16, 296, 415,   1, 683, 102, 684,
         685,   1,  52,   9,  52, 122, 310]),
 tensor([ 1, 42]),
 tensor([  1, 603, 189,   1,  57,  36,   1]),
 tensor([ 95, 505,  49, 686,   1, 356, 687, 688, 541, 688,   1, 208, 689, 690,
          21, 303, 122, 537,   1,   3, 691,   1]),
 tensor([427, 173,  91, 189,   9]),
 tensor([692]),
 tensor([476, 675,  16, 693,  11,   1,  36, 694,   1, 459, 576, 493, 197, 695,
           1,   9]),
 tensor([  9,  39, 324, 263, 306, 628]),
 tensor([696,  15,  16]),
 tensor([697,  39,  11,  21, 103, 352,   1,   1, 566, 697,  11,   1]),
 tensor([294,   9,   1,   1, 522, 698,   1, 699,   1, 700]),
 tensor([276, 364,   9,   1, 141, 276, 149, 217, 701,  39,   1,  47, 176, 414,
         415, 254,  39, 479, 141]),
 tensor([208, 340,   1,   1, 702,  48,  52]),
 tensor([404, 405, 258, 281]),
 tensor([175,  39, 175, 264,   1,  21, 264,  16]),
 tensor([347,   9, 205,   1,   1, 148,   9, 687,  52,   1, 372]),
 tensor([687, 512, 703, 185, 514,  52, 704]),
 tensor([139, 705,   1, 558]),
 tensor([630,  70]),
 tensor([265,  79,  42]),
 tensor([ 40, 205,   9,   1,  59, 253,   1,  92,  45,   1,   1, 210,  47, 127,
           1, 127,  11, 127, 706,  98,  39, 110]),
 tensor([647,  21, 256, 248]),
 tensor([219,  16,   1, 707,   1,   1,   1]),
 tensor([  1,   1, 217, 708, 709, 228, 665,  39,   1, 217,   1, 189, 285,   1,
         133,  52, 279,   1]),
 tensor([265, 242,  21, 177, 263,   1, 448, 172, 710,   1]),
 tensor([ 16, 711]),
 tensor([454,  57, 712, 204, 427, 173,  38, 147,  21,   1,   9, 713,   1,  93,
         169, 570, 265, 713, 714, 714,   1, 448, 378, 715]),
 tensor([716,  22, 175]),
 tensor([698,  47,  52,   1,   1, 711, 162, 417, 100, 205,  32,  47]),
 tensor([1]),
 tensor([205, 141,   9, 183, 258, 717, 364,  70, 287, 718, 144, 628,   1, 719,
          47,  11, 120, 100]),
 tensor([  1, 382, 474,   1,  47,   1,  13,   1, 120, 109,   1, 720, 176,  52,
         721,  11,   1, 655, 135,  16]),
 tensor([722, 532, 100, 723,  15,  16, 389]),
 tensor([243, 141, 724,  11, 204, 176, 132, 100]),
 tensor([120, 340, 447]),
 tensor([  1,   4, 725,  52, 726, 721,  60]),
 tensor([490, 489]),
 tensor([727,   1,   9]),
 tensor([495, 728, 109,  94,  80, 510]),
 tensor([ 70, 729, 406, 730,   1]),
 tensor([  1,   1, 731, 732, 733, 415]),
 tensor([198]),
 tensor([  1,  45, 147, 402,   1, 403, 566, 362]),
 tensor([158,  55, 182,   9,   1, 303,   1, 217,   1, 303, 734, 245]),
 tensor([  1,   1,   1,   1,   1,   1, 415, 735, 212,  57, 205,   9]),
 tensor([687, 512, 703, 490,  52]),
 tensor([667, 504, 490, 736,  60, 431,  16]),
 tensor([330, 320, 331,   1]),
 tensor([ 48, 642]),
 tensor([217, 729, 391,   1]),
 tensor([737,  38,   1, 623,   1, 205,   1, 738, 646, 205,   9, 329,  52, 579,
          52]),
 tensor([739, 515,   1,  60, 258, 182]),
 tensor([440, 474,   9,   5,   1,   1, 213,  70, 409,   1, 378]),
 tensor([495,   9, 516,   1, 740, 109, 741,   1, 623]),
 tensor([742, 176, 177, 124]),
 tensor([  9, 743, 744,   1, 287,   1, 303, 568,   9, 745, 353]),
 tensor([746, 217, 452,  21,   1, 747,   1, 748,  21, 747, 276, 749, 750, 751,
         752, 751]),
 tensor([753,   1, 754, 204,   1,  55,  48, 360,   1,  71, 755, 756, 148,   1,
           1, 204,  47,   1, 757, 756,   1, 758, 756,   1, 514, 110,   1, 755,
           1,   1,  55,   1, 759, 638, 703,   1, 760]),
 tensor([  1,   9, 202, 761,   1, 762, 763,   1]),
 tensor([16]),
 tensor([141]),
 tensor([ 94, 144, 137,  21, 137, 310]),
 tensor([  1,  16, 147,   1,   1, 764,   1,   1]),
 tensor([185, 140,  30,   9]),
 tensor([ 16, 551, 180,   1,   1,   9, 205, 248, 100, 180,   1, 765]),
 tensor([176,  11,  70, 264,  21, 124]),
 tensor([  1,   1,   1, 389, 766, 767,   9, 450,  49, 768, 547,  86,   1, 441,
           1,  21]),
 tensor([14]),
 tensor([137, 157, 504,  52,   1]),
 tensor([437,  21, 167, 724, 769]),
 tensor([167, 235, 524]),
 tensor([722,  16,  69, 734, 770, 650,   1,  82,  70,   9]),
 tensor([  9, 148,  89, 148, 204]),
 tensor([  1, 540, 110,  97,  30]),
 tensor([771,   1,  52,   1, 412, 173, 110, 772, 661]),
 tensor([374, 141, 410, 162,   1, 540, 609,   1,  21, 107, 162,  98, 449,   1,
          16, 773, 774,  49, 159,  17, 568, 162]),
 tensor([ 49, 196,   1, 775,  47, 191,  47,  21, 204, 177,   9,   1,   1, 776,
           1, 777,  16,  49, 418, 120,   1,  21,  59,   1, 446, 500,  91,  16,
         152,   1,   1,  49,  36]),

In [24]:
# label 데이터들도 tensor 형태로 변환
labels_t = torch.tensor(labels, dtype=torch.long)

In [25]:
# 학습데이터, 검증 데이터 셋으로 데이터 분할
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_val, Y_train, Y_val = train_test_split(
    enc_inputs, labels_t, test_size=0.2, random_state=42, stratify=labels_t
)

In [27]:
len(X_train)

800

In [28]:
# 파이토치를 이용해서 1차원 합성곱 학습을 생성
import torch.nn as nn
# 데이터셋, 데이터 로더
from torch.utils.data import Dataset, DataLoader
# 패딩 토큰 -> 토큰의 길이를 채워주기 위한 기능
from torch.nn.utils.rnn import pad_sequence

In [29]:
# 딥러닝에서 사용할 데이터를 파이토치에 맞게 변환
class TextDataset(Dataset):
    def __init__(self, xs, ys):
        # 독립변수를 객체 안에 저장
        self.xs = xs
        # 종속변수를 객체 안에 저장
        self.ys = ys
    def __len__(self):
        return len(self.xs)
    def __getitem__(self, idx):
        return self.xs[idx], self.ys[idx]

In [30]:
# 최대 커널의 개수 -> 몇개까지의 단어들을 묶어서 확인할 것인가? (n_gram의 수)
MAX_K = 5

# collate_fn -> Dataset에서 배치만큼 데이터를 가져온 뒤 데이터의 형태를 변경할 때 사용하는 함수
def collate_fn(batch):
    xs, ys = zip(*batch)
    pad_id = stoi['<PAD>']   # 0

    # batch -> [ [tensor([]), label], [tensor([]), label] ]

    # 패딩 토큰 채우기 1차
    # (MAX_K 보다 xs[i] 길이가 작다면 MAX_K 길이로 패딩 토큰을 채워준다)
    fixed = []
    for x in xs:
        if len(x) < MAX_K:
            # 필요한 패딩 토큰 개수 : MAX_K - len(x)
            need = MAX_K - len(x)
            # tensor 데이터에 <PAD>를 채워준다 -> 결합
            x = torch.cat(
                [
                    x,
                    torch.full((need, ), pad_id, dtype=torch.long)
                ]
            )
        fixed.append(x)

    # 패딩 토큰 채우기 2차
    # (xs에서 가장 긴 길이만큼 나머지 xs[i]로 길이를 맞춰사 패딩 토큰 추가)
    xs_pad = pad_sequence(
        fixed, batch_first=True, padding_value=pad_id
    )
    lengths = torch.tensor([len(x) for x in fixed], dtype=torch.long)

    return xs_pad, torch.stack(ys), lengths


train_loader = DataLoader(
    TextDataset(X_train, Y_train),
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)
val_loader = DataLoader(
    TextDataset(X_val, Y_val),
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

In [31]:
import math

In [32]:
# 학습 모델 생성 (kim CNN)
    # Embedding -> Conv1D(k = 3, 4, 5) -> max-over-time(해당 구간에서 가장 연관이 높은 구간 선택)
    #  -> concat(kernel별 높은 구간) -> Dropout -> Linear

class TextCNN(nn.Module):
    def __init__(
            self, vocab_size, emb_dim, num_classes,
            kernel_size = (3, 4, 5),
            num_channel = 100,
            pad_idx = 0,
            dropout = 0.5
    ):
        # vocab_size -> 단어 사전의 길이
        # emb_dim -> 임베딩 벡터의 차원의 수
        # num_classes -> 분류 class의 개수
        # kernel_size -> 묶이는 단어의 개수 목록
        # num_channel -> 합성곱 작업 후 결과의 차원의 개수
        # pad_idx -> 패딩 토큰의 인덱스
        # dropout -> 소실되는 데이터의 비율
        super().__init__()
        self.emb = nn.Embedding(vocab_size, emb_dim, padding_idx=pad_idx)

        # 1차원 합성곱 모델들
        self.convs = nn.ModuleList(
            [nn.Conv1d(in_channels=emb_dim, out_channels=num_channel, kernel_size=k) for k in kernel_size]
        )

        # 100차원의 모델이 3개가 생성이 되고 출력드를 단순 결합
        # 300차원이 되면서 과적합의 위험
        # 일부의 데이터를 소실 -> 과적합 방지
        self.dropout = nn.Dropout(dropout)
        # 선형 모델에서는 분류의 형태로 0, 1의 확률이 출력
        self.fc = nn.Linear(num_channel * len(kernel_size), num_classes)
        # 초기화
        self._init_weights()

    # 벡터 초기화하는 함수
    def _init_weights(self):
        # 자비에르 초기화
        nn.init.xavier_uniform_(self.emb.weight)
        nn.init.xavier_uniform_(self.fc.weight)
        # 합성곱 모델을 초기화
        for conv in self.convs:
            # 비선형 구조에서 사용하는 다중 퍼셉트론 Relu()를 이용하는 경우
            # 학습이 안정되도록 사용하는 초기화
            nn.init.kaiming_uniform_(conv.weight, a = math.sqrt(5))

    # 순전파
    def forward(self, x):
        # x -> DataLoader를 통해서 들어오는 입력 데이터
        # batch가 된 데이터들을 collate_fn에 대입하여 나온 결과를 순전파에 입력
        x = self.emb(x)
        # 배치 크기, 시퀀스의 길이, 임베딩 벡터의 차원의 수
        x = x.transpose(1, 2)
        # 배치크기, 임베딩 벡터의 차원수, 시퀀스의 길이

        feat_maps = []
        # 다중 구조 -> conv -> relu -> Max
        for conv in self.convs:
            h = torch.relu(conv(x))   # 배치의 크기, relu 차원의 개수, T` : 시퀀스의 길이 - 커널의 사이즈 + 1
            # h 중 T`의 최댓값
            h = torch.max(h, dim=2).values   # 배치의 크기, relu 차원의 개수
            feat_maps.append(h)
        # 열을 기준으로 feat_maps 단순 결합
        z = torch.cat(feat_maps, dim=1)   # 배치의 크기, relu 차원의 개수 * len(self.convs)
        # 과적합 방지를 위해 일부 데이터를 0으로 변경
        z = self.dropout(z)
        # 선형 모델에서 예측
        logits = self.fc(z)

        return logits

In [33]:
# 학습의 루프 생성

# 모델 생성
model = TextCNN(
    vocab_size=len(vocab),
    emb_dim=120,   # 차원의 개수(열의 수)
    num_classes=2,   # 분류 class 종류의 수 (0, 1) -> 2
    kernel_size=(3, 4, 5),   # 몇 개의 단어들을 묶을 것인가
    num_channel=64,   # conv1d에서 output의 차원의 개수
    pad_idx=stoi['<PAD>'],   # 패딩 토큰의 위치
    dropout=0.5   # 고차원 데이터에서 과적합 방지용 손실 데이터의 비율
)

In [34]:
# 옵티마이저 설정
optimizer = torch.optim.Adam(model.parameters(), lr=3e-3)
# 손실 함수 설정(예측값과 실젯값의 차이를 계산하는 객체)
criterion = nn.CrossEntropyLoss()

In [35]:
# 학습, 예측을 하는 함수 정의
def run_epoch(loader, train=True):
    # loader -> model에서 사용할 데이터
    # train -> 학습 모드, 평가 모드
    if train:
        model.train()
    else:
        model.eval()

    total_loss = 0.0
    correct = 0
    total = 0

    for x, y, lengths in loader:
        # train 매개변수에 따라 자동 미분을 활성화할 것인가
        with torch.set_grad_enabled(train):
            logits = model(x)
            loss = criterion(logits, y)
            # 학습 모드라면 -> 옵티마이저, 백워드
            if train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
        total_loss += float(loss.item()) * x.size(0)
        # 예측값 -> [확률, 확률] -> 높은 확률의 위치
        preds = logits.argmax(dim=1)
        correct += int((preds == y).sum().item())
        total = x.size(0)
    mean_loss = total_loss / total
    acc = correct / total

    return mean_loss, acc

In [36]:
for epoch in range(10):
    tr_loss, tr_acc = run_epoch(train_loader, train=True)
    val_loss, val_acc = run_epoch(val_loader, train=False)
    print(f"epoch({epoch}) : train loss({round(tr_loss, 4)}) train acc({round(tr_acc, 4)})")
    print(f"epoch({epoch}) : val loss({round(val_loss, 4)}) val acc({round(val_acc, 4)})")

epoch(0) : train loss(65.6171) train acc(58.375)
epoch(0) : val loss(12.9117) val acc(18.375)
epoch(1) : train loss(39.9253) train acc(82.0)
epoch(1) : val loss(12.9589) val acc(18.5)
epoch(2) : train loss(17.5497) train acc(93.25)
epoch(2) : val loss(16.8439) val acc(18.25)
epoch(3) : train loss(10.5651) train acc(95.5)
epoch(3) : val loss(20.9535) val acc(19.25)
epoch(4) : train loss(7.2795) train acc(96.375)
epoch(4) : val loss(23.3508) val acc(19.25)
epoch(5) : train loss(6.2852) train acc(96.5)
epoch(5) : val loss(24.9082) val acc(18.875)
epoch(6) : train loss(5.0177) train acc(96.75)
epoch(6) : val loss(27.7617) val acc(19.125)
epoch(7) : train loss(5.1761) train acc(97.0)
epoch(7) : val loss(32.8202) val acc(18.5)
epoch(8) : train loss(4.4029) train acc(97.75)
epoch(8) : val loss(32.1502) val acc(18.5)
epoch(9) : train loss(5.8189) train acc(96.75)
epoch(9) : val loss(38.2641) val acc(18.875)

In [37]:
# test 예측 함수

@torch.no_grad()
def predict(text):
    toks = tokenize(text)
    ids = torch.tensor(encode(toks), dtype=torch.long)
    pad_id = stoi['<PAD>']

    # 모델에서 최대 커널의 크기를 확인
    max_k = max([m.kernel_size[0] for m in model.convs])

    if len(ids) < max_k:
        need = max_k - len(ids)
        ids = torch.cat([ids, torch.full((need, ), pad_id, dtype=torch.long)])
    x = ids.unsqueeze(0)
    logits = model(x)
    prob = torch.softmax(logits, dim=1).squeeze(0).tolist()
    pred = int(torch.argmax(logits, dim=1).item())
    return prob, pred

p, yhat = predict("직원의 태도가 별로였고 실망했다")
print(f'예측값 : ', yhat)
print(f'예측 확률 :', p)

예측값 :  0
예측 확률 : [1.0, 8.580386157445649e-15]