## 객실의 사용 여부 관련 데이터
1. 데이터를 로드(hotel_bookings.csv)
2. 데이터에 대한 정보를 확인
3. 해당 데이터에서 문제가 있는 부분을 확인하여 수정

In [1]:
import pandas as pd
import numpy as np

In [10]:
#  data 폴더 안에 hotel_bookings.csv 파일을 로드
hotel = pd.read_csv("../data/hotel_bookings.csv")
# 데이터를 로드하고 문제점(랜덤포레스트 학습)
hotel.head(2)

,is_canceled,deposit_type,lead_time,stays_in_weekend_nights,stays_in_week_nights,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr
0,0,No Deposit,105.0,2,5,NaN,0,0,1,0,131.50
1,0,No Deposit,303.0,2,2,NaN,0,0,0,0,73.95

In [12]:
# 데이터프레임의 정보 확인
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   is_canceled                     20000 non-null  int64
 1   deposit_type                    20000 non-null  object
 2   lead_time                       19995 non-null  float64
 3   stays_in_weekend_nights         20000 non-null  int64
 4   stays_in_week_nights            20000 non-null  int64
 5   is_repeated_guest               19642 non-null  float64
 6   previous_cancellations          20000 non-null  int64
 7   previous_bookings_not_canceled  20000 non-null  int64
 8   booking_changes                 20000 non-null  int64
 9   days_in_waiting_list            20000 non-null  int64
 10  adr                             18937 non-null  float64
dtypes: float64(3), int64(7), object(1)
memory usage: 1.7+ MB

In [6]:
hotel['deposit_type'].value_counts()

deposit_type
No Deposit    19138
Non Refund      834
Refundable       28
Name: count, dtype: int64

In [9]:
hotel.describe()

,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr
count,20000.00000,19995.000000,20000.000000,20000.000000,19642.000000,20000.000000,20000.000000,20000.000000,20000.000000,18937.000000
mean,0.12000,85.978345,0.892550,2.380400,0.038133,0.032900,0.169050,0.269400,1.983950,101.410239
std,0.32497,96.427240,0.952077,1.777345,0.191521,0.455552,1.502426,0.687566,15.927212,49.245097
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000
25%,0.00000,11.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,68.800000
50%,0.00000,51.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,94.500000
75%,0.00000,132.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,126.000000
max,1.00000,629.000000,13.000000,30.000000,1.000000,26.000000,66.000000,17.000000,379.000000,451.500000

### 해당 데이터의 컬럼의 의미
is_canceled : 예약 취소 여부 (0= 취소 안됨, 1=취소)

deposit_type : 보증금 유형(No Deposit, Not Refund, Refundable)

lead_time : 예약일과 실제 도착일 사이의 일수

stays_in_weekend_nights : 주말의 숙박 일수

stays_in_week_nights : 주중의 숙박 일수

is_repeated_guest : 재방문 고객 여부 (0=신규, 1=재방문)

previous_cancellations : 과거 예약 취소 횟수

previous_bookings_not_canceled : 과거 예약 중 취소되지 않은 건수

booking_changes : 예약 후 변경 횟수

days_in_waiting_list : 대기자가 있었던 일수

adr : 평균 일일 객실 요금

In [15]:
# 결측치가 존재하는 것은 확인 -> 실제 결측치의 개수를 확인
# 결측치가 존재 여부 함수 -> bool 타입의 데이터프레임이 생성
# bool의 데이터들을 합산하여 컬럼별로 확인
hotel.isna().sum()

is_canceled                          0
deposit_type                         0
lead_time                            5
stays_in_weekend_nights              0
stays_in_week_nights                 0
is_repeated_guest                  358
previous_cancellations               0
previous_bookings_not_canceled       0
booking_changes                      0
days_in_waiting_list                 0
adr                               1063
dtype: int64

In [18]:
# 결측치의 비율 -> 결측치의 개수 / 데이터프레임의 길이 * 100
print("lead_time 컬럼의 결측치의 비율 ", round(5 / len(hotel) * 100, 2))
print("is_repeated_guest 컬럼의 결측치의 비율 ", round(358 / len(hotel) * 100, 2))
print("adr 컬럼의 결측치의 비율 ", round(1063/ len(hotel) * 100, 2))

lead_time 컬럼의 결측치의 비율  0.03
is_repeated_guest 컬럼의 결측치의 비율  1.79
adr 컬럼의 결측치의 비율  5.32

- lead_time 컬럼의 결측치의 비율은 매우 작기 때문에 제거 -> 결측치인 인덱스를 제외
- is_repeated_guest는 해당 데이터에서 개수가 많은 데이터로 결측치를 채워준다.
- adr 컬럼의 결측치는 해당 데이터들을 확인하고 특정한 조건에 맞춰서 데이터를 채워준다.

In [22]:
# lead_time의 결측치가 존재하는 인덱스를 제외
# 제거한다(drop) + 결측치(na) -> 결측치가 존재하는 행이나 열을 제거하는 함수
hotel.dropna(subset = ['lead_time'], axis = 0, inplace = True)

In [ ]:
# 값들의 빈도수를 체크하는 함수를 사용
hotel['is_repeated_guest'].value_counts()

is_repeated_guest
0.0    18888
1.0      749
Name: count, dtype: int64

In [27]:
hotel['is_repeated_guest'].sum()

np.float64(749.0)

In [29]:
# is_repeated_guest 컬럼의 결측치는 0으로 채워준다.
hotel['is_repeated_guest'].fillna(0, inplace=True)

In [31]:
hotel.isna().sum()

is_canceled                          0
deposit_type                         0
lead_time                            0
stays_in_weekend_nights              0
stays_in_week_nights                 0
is_repeated_guest                    0
previous_cancellations               0
previous_bookings_not_canceled       0
booking_changes                      0
days_in_waiting_list                 0
adr                               1063
dtype: int64

In [34]:
hotel['adr'].describe()

count    18932.000000
mean       101.410702
std         49.241204
min         -6.380000
25%         68.822500
50%         94.500000
75%        126.000000
max        451.500000
Name: adr, dtype: float64

In [46]:
# 통계 정보를 확인하니 객실 요금 평균에 음수가 존재 -> 이상한 데이터가 발견
# 이상치 데이터는 제거
# 인덱스의 조건식을 생성 -> 객실 요금 데이터에서 0보다 작은
flag = hotel['adr'] < 0

hotel = hotel.loc[~flag]

In [58]:
# adr의 결측치들을 deposit_type의 값에 따라 그룹화를 하고 평균의 adr의 값을 채워준다.

# deposit_type에 따른 adr의 평균값을 확인
deposit_adr_mean = hotel.groupby(['deposit_type'])['adr'].mean().to_dict()

In [62]:
# hotel 복사본 생성
test_hotel = hotel.copy()

In [ ]:
null_flag = test_hotel['adr'].isna()
for key in deposit_adr_mean:
    # print(key)
    # print(deposit_adr_mean[key])
    # 인덱스 조건식 -> deposit_type이 key와 같다.
    flag = test_hotel['deposit_type'] == key
    # flag와 null_flag 두 조건식이 모두 만족하는 인덱스 필터
    # 첫번째 반복 시에는 deposit_type이 No Deposit이고 adr이 결측치인 데이터를 선택
    test_hotel.loc[flag & null_flag, 'adr'] = deposit_adr_mean[key]
    # break

In [70]:
test_hotel.isna().sum()

is_canceled                       0
deposit_type                      0
lead_time                         0
stays_in_weekend_nights           0
stays_in_week_nights              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
booking_changes                   0
days_in_waiting_list              0
adr                               0
dtype: int64

In [74]:
# map(), apply()
hotel['adr'].map(
    lambda x : print(x)
)

131.5
73.95
nan
80.3
60.9
88.4
105.9
76.67
84.0
42.0
79.84
nan
88.0
126.0
nan
55.0
158.77
56.0
124.1
126.0
77.5
67.0
58.0
72.25
145.1
157.27
nan
100.0
89.0
170.0
67.0
nan
87.0
nan
90.0
107.1
123.0
85.85
56.1
30.24
62.0
110.88
0.0
nan
nan
42.3
0.0
107.1
283.67
55.0
69.0
105.0
62.0
88.0
77.18
134.14
25.11
150.3
168.3
115.2
108.15
130.0
96.0
48.0
75.0
104.5
111.0
130.0
118.13
98.1
168.3
98.0
74.13
82.24
196.0
58.0
87.0
60.0
144.0
118.8
0.0
nan
97.71
118.0
79.2
90.0
245.0
45.0
65.0
88.0
91.0
120.6
106.0
100.0
91.0
88.2
148.0
106.25
89.0
152.0
30.0
90.0
80.0
176.8
100.0
102.8
144.63
27.0
0.0
80.1
47.0
101.15
130.0
60.98
62.0
159.84
161.1
162.0
91.33
0.0
121.14
97.0
62.0
115.0
62.5
75.0
121.0
94.5
44.5
176.64
173.0
130.0
112.0
141.9
36.0
146.11
nan
90.0
126.0
62.0
100.8
54.6
42.0
82.0
169.0
77.85
50.0
35.0
95.0
177.0
89.4
149.4
73.8
0.0
152.0
90.95
48.0
87.0
119.7
nan
60.0
75.0
35.0
162.33
110.0
122.5
35.46
45.0
96.0
0.0
115.0
89.1
30.0
85.67
100.5
nan
82.35
153.62
164.0
120.0
38.0
170.57
75.0
189.9
0.0
73.95
162.0
115.0
74.25
95.0
80.0
165.0
85.0
55.8
48.43
42.6
65.0
202.0
163.8
211.0
25.0
65.0
67.22
59.0
112.7
52.0
85.33
65.4
75.0
60.0
130.0
112.2
64.0
nan
105.3
146.3
67.15
100.1
77.0
86.47
199.0
131.67
126.9
192.0
97.02
139.8
245.0
90.67
46.0
86.5
114.0
129.2
65.0
117.0
72.5
42.5
99.0
37.0
186.0
70.69
114.9
77.93
66.0
89.25
50.0
165.0
67.0
215.0
216.0
219.6
54.0
100.51
66.3
107.1
59.0
120.0
75.0
nan
123.3
73.37
117.9
62.0
120.24
75.0
159.0
170.0
74.95
52.2
96.0
99.95
75.0
85.0
182.18
146.92
75.0
68.0
127.5
35.0
115.0
112.67
55.5
60.0
102.3
55.0
nan
129.72
92.4
48.0
109.0
51.76
54.0
125.1
37.8
105.0
82.45
39.0
105.0
139.0
66.0
nan
77.0
80.1
152.1
83.3
102.5
65.0
102.6
78.3
92.0
118.58
181.79
64.96
65.0
118.0
103.0
39.0
48.0
87.04
106.2
18.6
177.3
209.29
115.0
108.0
90.1
93.6
108.9
68.0
119.0
115.0
160.0
95.0
152.1
95.0
85.33
126.2
117.65
nan
70.0
72.21
61.02
63.0
98.0
130.5
95.0
102.9
65.0
54.0
45.0
93.0
50.55
75.0
105.0
0.0
49.0
112.67
193.08
80.85
44.56
86.0
161.5
122.4
122.63
88.0
55.33
108.0
152.1
105.0
37.8
133.98
96.33
207.9
90.0
139.0
88.0
277.0
29.0
207.9
66.4
93.0
70.0
0.0
131.8
91.75
96.0
125.1
nan
67.91
nan
101.38
108.0
75.0
72.25
128.0
138.6
150.0
121.0
110.0
221.0
122.4
71.0
45.0
58.5
43.0
26.1
45.0
74.8
198.0
62.0
91.0
75.0
40.0
130.0
125.0
45.0
128.5
nan
81.2
94.35
0.0
49.43
130.05
104.4
45.0
0.0
112.5
85.0
48.0
91.8
226.33
114.0
120.6
198.9
74.49
98.1
201.0
76.5
nan
123.45
70.0
134.1
38.0
74.0
78.0
65.0
65.0
6.0
216.9
128.0
78.3
75.0
180.0
121.5
47.8
38.0
100.62
162.0
132.43
63.5
71.7
109.8
230.0
100.0
nan
65.0
85.25
161.0
65.0
144.0
67.0
126.0
nan
60.0
79.2
155.5
114.4
132.44
66.0
80.0
136.0
90.0
126.33
183.0
80.0
44.5
94.14
68.0
55.65
nan
54.9
159.0
131.0
64.8
204.17
145.0
99.18
115.0
95.0
106.67
68.0
80.75
nan
58.4
45.56
79.2
171.0
141.6
139.0
75.0
168.71
89.1
88.29
81.9
95.69
nan
118.15
106.75
110.0
124.0
80.1
60.0
68.0
163.0
60.0
111.0
102.5
89.74
115.0
54.5
119.0
38.88
112.8
160.0
99.45
60.0
114.4
95.0
80.75
122.0
75.0
152.0
113.4
79.5
136.0
150.0
89.1
nan
147.5
78.0
118.8
97.0
74.8
72.25
166.25
51.0
48.0
98.1
95.0
nan
131.0
6.0
36.0
75.0
60.0
244.0
135.4
283.2
98.0
74.0
100.0
62.0
76.67
121.0
34.0
112.5
75.0
90.0
167.0
144.0
91.0
68.0
85.0
67.5
129.0
nan
212.73
159.0
80.75
68.0
65.02
90.1
78.0
0.0
60.0
46.0
60.0
66.53
99.0
99.0
90.0
38.0
63.9
83.83
168.3
34.0
159.0
121.0
98.12
121.0
130.0
93.6
78.0
43.0
55.8
121.1
145.71
54.0
145.0
115.0
93.56
119.1
148.5
99.0
56.0
193.0
139.5
71.0
35.0
68.0
120.28
115.33
138.0
89.0
36.96
28.5
144.0
103.5
131.31
100.8
85.0
nan
154.0
188.0
nan
85.0
58.2
152.1
63.08
177.5
89.25
75.0
44.0
79.5
75.0
120.0
44.0
37.8
88.8
40.0
121.75
54.5
90.0
125.0
108.9
34.0
90.0
98.0
24.7
12.0
48.0
112.67
72.0
75.76
97.0
104.0
99.45
107.0
135.2
106.2
88.0
59.0
45.0
104.0
47.0
46.0
236.5
99.0
99.9
72.0
88.4
89.0
0.0
197.33
159.0
nan
100.0
209.4
65.0
129.6
66.0
49.0
109.77
99.0
139.33
90.9
138.0
134.1
50.0
140.4
90.0
180.0
111.6
nan
233.0
70.0
65.0
44.0
120.83
68.0
78.3
101.33
176.0
99.9
nan
95.0
60.0
64.0
108.0
195.0
102.0
354.0
171.0
99.0
137.7
63.75
61.28
259.0
79.2
95.0
40.0
112.67
144.0
80.75
98.0
165.04
114.5
170.0
97.2
181.8
124.0
83.16
107.0
66.0
117.0
169.0
209.0
135.9
80.0
35.0
203.0
58.92
68.0
128.0
88.0
100.3
99.0
70.0
139.2
92.0
43.0
179.0
100.0
63.3
157.25
80.3
82.73
162.98
99.0
127.5
159.0
210.0
nan
131.0
99.45
160.0
65.0
91.1
94.5
168.0
188.0
79.5
nan
89.1
52.4
95.0
nan
108.0
nan
81.0
99.0
118.0
44.1
111.0
132.67
106.25
210.0
139.0
99.0
126.0
75.0
122.4
95.0
nan
97.41
75.0
65.0
116.1
97.4
75.0
89.2
146.7
112.2
60.0
44.0
76.58
75.0
104.0
123.3
335.0
110.0
30.0
92.65
99.0
131.75
44.81
108.9
160.0
109.1
164.05
39.0
nan
78.0
139.0
75.0
76.23
117.0
98.0
81.0
156.24
75.0
75.0
42.5
140.4
170.0
74.1
60.0
0.0
130.33
104.0
82.39
136.0
85.0
116.95
30.0
117.75
125.0
125.0
80.0
nan
52.56
111.6
30.0
142.2
69.53
29.0
105.0
147.0
0.0
80.75
0.0
44.0
49.0
55.0
117.0
247.0
26.0
136.5
172.8
65.0
95.0
89.0
78.5
80.1
70.0
75.0
130.0
40.0
119.0
91.48
75.0
171.71
62.0
154.0
110.0
88.01
6.0
89.1
38.0
80.75
35.0
116.67
139.0
79.2
111.5
105.3
93.0
189.0
51.0
135.2
98.1
83.0
71.28
52.2
80.0
106.2
75.44
0.0
98.0
90.0
70.0
138.6
nan
109.8
132.0
78.3
74.8
80.75
110.0
38.0
nan
130.1
96.3
107.41
92.0
77.25
106.0
186.0
115.0
66.0
100.8
65.11
nan
94.5
55.0
85.0
63.76
88.4
60.0
59.5
0.0
129.0
51.85
110.0
152.0
nan
50.1
115.0
101.0
99.8
219.0
48.0
95.0
148.0
85.67
89.1
147.0
140.4
205.2
56.0
35.0
56.0
nan
48.0
88.2
76.67
97.71
75.65
147.0
116.1
70.0
74.57
nan
93.0
65.0
59.07
112.67
87.3
70.0
35.0
184.5
174.95
112.67
105.33
95.2
85.0
93.6
79.2
56.0
119.85
199.15
119.0
156.25
153.0
119.0
69.52
109.0
0.0
44.0
91.8
42.0
32.0
60.0
66.0
189.0
180.0
65.83
209.71
46.4
91.38
110.33
153.0
190.0
106.0
65.43
95.0
299.0
124.0
140.0
65.0
123.0
114.4
111.3
0.0
146.0
66.0
98.0
145.0
136.0
146.0
161.0
71.74
102.0
nan
112.5
104.49
77.03
135.29
55.8
98.1
145.67
65.0
132.0
53.0
118.0
98.05
nan
109.0
85.0
48.0
70.0
78.0
81.25
112.67
89.0
121.5
nan
213.6
142.0
93.6
78.0
60.0
149.0
29.0
80.1
72.0
116.1
124.0
90.0
124.0
51.47
39.0
122.48
91.9
76.5
nan
138.9
101.0
68.0
68.0
76.5
39.0
nan
100.0
115.0
167.23
117.0
178.0
90.0
93.8
30.0
nan
95.57
76.69
112.0
190.0
nan
nan
48.0
140.7
110.0
94.71
90.0
0.0
78.3
42.0
113.75
85.67
76.5
230.0
39.0
95.0
98.0
81.0
nan
95.0
90.0
60.0
169.0
108.0
99.0
58.0
100.3
25.0
25.0
76.0
37.0
42.0
82.5
37.0
124.0
61.0
90.0
108.0
148.5
173.94
93.5
120.0
43.2
79.05
107.67
nan
76.8
195.0
98.0
88.0
140.4
91.0
57.0
73.0
76.5
135.0
65.0
62.0
65.0
261.0
87.0
nan
78.0
48.0
65.0
nan
102.72
89.34
72.76
145.0
95.67
82.0
40.0
115.25
160.0
88.0
127.0
100.8
122.84
80.0
140.0
38.07
30.6
39.0
85.0
115.0
91.0
119.2
75.0
157.2
90.07
nan
109.0
0.0
92.98
nan
105.0
65.0
144.8
126.0
0.0
76.5
141.67
75.0
48.0
65.0
75.0
185.0
170.5
85.0
nan
79.0
110.5
173.0
171.0
112.5
138.0
96.3
126.0
68.0
127.0
141.49
107.95
163.5
81.9
86.0
54.0
115.0
100.3
72.0
123.0
247.09
116.5
99.45
90.0
94.0
45.0
0.0
126.0
180.0
104.0
80.0
144.8
110.0
85.5
62.0
187.85
43.0
159.5
54.0
83.0
121.5
36.0
nan
nan
81.0
95.0
64.22
135.9
151.0
62.0
53.32
41.89
176.9
148.29
65.83
80.0
128.7
100.0
94.5
102.56
90.78
nan
95.0
nan
75.0
0.0
111.0
135.0
40.0
65.0
110.0
79.74
77.25
95.0
87.0
212.0
179.0
nan
131.0
110.0
78.08
80.1
99.0
90.0
89.0
46.17
155.0
189.0
95.65
126.27
97.0
43.2
216.0
99.0
87.32
75.0
35.0
96.0
107.33
112.1
121.5
117.0
89.0
48.0
67.76
55.78
312.5
115.0
205.0
nan
129.92
142.2
42.0
305.0
176.8
94.8
72.0
148.5
73.1
100.0
117.1
29.0
67.5
110.0
98.1
172.0
93.5
50.0
50.0
54.71
139.0
172.0
85.0
139.5
23.7
120.0
103.0
65.0
85.5
61.0
36.0
55.0
86.0
118.8
62.0
nan
110.0
0.0
47.0
29.0
85.0
85.5
75.0
79.2
43.41
65.0
200.5
125.8
76.67
99.0
86.4
85.0
25.0
75.33
152.1
155.6
95.0
34.56
nan
82.44
121.75
239.1
89.0
nan
114.2
68.0
114.0
62.5
136.0
179.0
0.0
100.8
109.0
48.38
38.0
85.0
0.26
38.0
89.25
104.0
nan
150.0
95.0
210.0
144.0
172.0
251.0
65.0
199.63
49.0
114.4
168.3
160.0
115.0
104.0
70.0
75.95
50.0
74.69
134.0
36.0
75.0
79.2
43.0
109.0
118.0
77.0
92.17
123.67
145.0
108.8
65.0
122.0
nan
150.3
85.5
103.5
248.0
149.0
37.6
126.0
65.0
78.0
0.0
105.3
76.58
98.0
64.0
49.74
170.0
99.0
100.0
0.0
95.0
84.33
0.0
194.0
75.6
109.65
107.53
79.2
193.6
175.5
nan
112.0
85.0
170.0
88.65
126.6
nan
86.49
76.5
220.0
111.25
191.25
151.0
35.0
83.0
97.43
79.2
85.0
102.85
65.0
213.43
52.0
159.0
130.0
127.71
77.0
87.85
167.8
131.0
40.0
124.0
80.75
98.2
110.0
108.9
98.0
168.3
130.5
80.3
173.45
79.0
50.0
100.0
nan
94.67
146.0
163.67
67.0
112.5
43.0
113.6
98.0
76.0
85.0
115.0
75.57
111.0
0.0
80.0
92.4
153.0
65.0
nan
44.0
86.0
230.0
85.0
108.0
nan
nan
88.0
121.2
185.33
189.33
75.0
72.0
100.0
67.15
134.0
85.0
17.6
36.0
131.0
159.0
102.6
66.8
65.0
83.7
95.8
132.3
116.0
156.0
244.0
99.0
106.0
0.0
101.52
166.0
62.0
65.0
94.36
160.0
30.0
nan
36.24
230.0
112.67
58.0
66.6
100.3
65.75
91.8
200.1
95.0
67.99
85.0
62.0
85.67
80.75
88.0
59.4
38.0
136.8
107.1
111.0
56.0
191.0
156.0
68.0
60.0
107.1
112.7
80.75
156.6
30.0
216.9
126.0
229.0
66.0
117.0
87.78
112.5
109.0
92.65
96.0
109.38
62.8
nan
78.6
93.6
58.0
116.95
131.0
43.8
80.0
101.72
30.0
122.4
196.0
117.98
108.17
99.0
76.23
37.4
152.0
195.0
37.0
55.0
130.0
217.0
170.0
89.1
52.4
106.0
95.0
0.0
110.8
nan
34.0
62.0
92.0
90.0
120.0
135.9
74.25
nan
105.0
132.5
nan
67.0
158.75
117.0
100.0
186.0
89.0
nan
62.0
48.0
nan
104.5
50.0
38.0
161.0
94.0
99.0
85.5
148.5
130.5
135.0
139.5
70.4
94.5
65.0
134.5
120.0
78.0
105.26
64.0
137.7
80.1
65.0
30.0
80.0
95.67
90.68
58.0
75.0
89.0
62.2
0.0
150.0
30.0
100.75
0.0
65.0
0.0
48.0
112.0
88.56
98.0
99.0
60.87
129.9
135.15
43.0
134.0
nan
164.0
95.0
134.0
141.0
184.0
139.0
130.5
86.4
70.0
91.5
69.0
64.37
142.19
96.3
109.8
106.5
130.0
74.8
124.2
0.0
85.0
185.0
60.0
70.0
212.0
268.0
80.0
137.0
106.0
91.36
111.0
90.0
48.0
86.0
39.0
0.0
0.0
100.0
241.0
56.7
38.5
74.0
122.4
82.13
89.1
52.0
92.0
85.0
142.0
85.0
62.0
66.0
0.0
135.33
195.0
269.3
93.86
71.0
246.0
123.2
130.5
72.0
8.0
44.5
90.0
106.0
78.53
136.0
96.0
149.4
55.0
nan
60.0
95.0
nan
84.0
34.4
160.5
49.0
71.1
39.0
150.0
77.6
76.5
120.0
145.0
72.75
166.5
74.8
30.0
103.5
101.0
79.2
44.8
135.0
78.0
120.0
136.67
155.0
156.3
132.3
40.0
71.1
106.54
207.5
86.0
63.75
62.0
110.0
185.57
128.8
78.4
143.7
115.0
156.75
89.78
90.2
46.8
106.88
70.0
65.0
31.95
48.0
112.67
79.2
nan
214.87
96.0
150.0
59.0
65.0
40.5
80.0
140.0
115.0
70.0
108.0
54.0
79.2
110.0
nan
240.0
168.6
87.4
89.0
75.6
65.0
70.26
89.1
80.8
121.6
162.0
112.67
71.0
95.04
48.0
37.8
149.0
139.4
100.0
87.0
101.5
170.0
nan
94.0
102.6
81.5
96.8
119.0
30.0
135.0
139.0
106.2
128.44
72.0
96.75
74.8
86.0
159.3
94.5
159.0
150.0
217.2
153.0
105.3
215.0
0.0
99.0
147.24
104.0
nan
160.0
98.4
60.0
136.0
250.0
156.6
77.99
90.0
43.0
74.8
104.0
89.0
59.0
100.0
120.0
115.0
79.5
85.0
93.6
nan
126.67
44.5
88.4
126.0
88.0
40.0
88.6
68.5
nan
38.0
96.3
65.0
34.0
65.0
100.0
67.5
0.0
159.0
46.0
68.75
109.0
107.1
110.2
42.0
137.7
56.0
48.0
125.0
0.0
111.0
94.0
65.0
89.1
99.9
134.78
182.0
140.0
70.0
63.0
139.5
65.0
0.0
148.0
60.0
120.0
68.4
177.47
85.0
136.0
124.0
120.0
130.0
153.0
56.0
131.0
85.67
77.0
33.0
100.0
149.4
66.0
109.0
118.58
112.6
0.0
95.0
130.0
124.0
nan
104.8
118.5
156.0
162.0
152.0
97.0
nan
78.0
65.0
107.0
65.0
125.1
136.1
85.0
108.0
76.0
54.05
0.0
107.1
146.4
98.1
50.0
98.0
108.0
nan
127.0
214.0
106.2
276.0
45.0
102.9
96.0
158.0
nan
43.2
nan
91.54
95.0
95.0
58.4
60.0
25.0
62.0
75.0
130.0
32.0
94.0
164.0
67.6
128.0
35.0
110.0
91.0
85.0
73.0
88.0
239.0
169.0
80.33
58.31
nan
106.25
120.8
216.9
108.0
89.0
47.85
129.0
117.5
273.56
99.45
108.0
62.0
112.2
85.0
69.85
115.5
138.0
75.0
108.0
89.1
111.0
98.0
73.37
72.07
112.0
79.0
90.0
53.71
75.0
108.0
93.0
87.04
77.0
75.6
43.0
71.6
132.5
177.3
51.84
76.67
130.35
65.7
80.0
39.0
89.1
89.25
90.0
130.94
91.0
95.0
115.0
74.61
89.0
119.85
84.6
67.5
65.0
36.0
26.1
0.0
80.0
62.0
141.68
43.0
175.0
250.0
57.0
26.0
60.0
81.71
111.6
98.67
140.0
nan
122.4
186.43
102.6
72.25
66.49
119.0
124.0
70.0
66.0
107.1
107.0
nan
135.67
66.0
91.33
86.0
100.0
169.0
200.0
108.0
147.59
117.0
42.0
139.0
87.0
140.05
85.03
48.5
235.0
31.45
75.0
60.0
144.0
125.1
72.25
305.0
95.0
109.8
72.0
75.0
105.74
109.0
64.0
44.5
51.0
97.2
114.0
42.0
nan
112.67
169.0
62.0
173.0
90.0
48.0
61.0
92.0
156.6
55.0
82.35
77.93
58.0
166.0
111.2
68.0
112.36
35.0
114.3
79.2
62.0
97.0
50.0
61.5
140.0
118.8
91.8
87.5
44.88
83.0
159.3
119.0
111.0
50.0
81.0
58.0
149.4
176.42
78.3
85.5
70.67
106.25
nan
164.0
143.0
62.17
133.2
65.0
117.0
137.7
71.0
105.9
140.0
49.43
49.0
159.3
68.83
55.0
41.58
68.0
163.2
nan
6.0
110.0
95.0
122.4
62.0
89.3
105.4
104.0
42.0
0.0
134.5
101.13
115.2
48.0
60.65
133.74
139.5
106.26
77.89
83.75
38.0
90.0
54.0
nan
107.95
137.7
51.21
56.0
89.4
80.75
169.2
76.0
145.5
79.8
117.9
54.0
172.0
132.11
38.55
90.0
64.67
0.0
172.0
119.2
81.0
55.0
106.08
79.2
301.0
86.75
185.0
76.08
129.0
nan
80.0
0.0
39.0
116.85
66.43
104.0
91.13
nan
183.0
nan
43.2
108.0
118.0
59.4
155.0
145.8
nan
126.9
171.0
59.71
70.0
197.61
38.0
nan
109.65
180.0
79.0
44.5
80.0
81.0
70.2
48.0
210.0
140.0
150.0
60.0
65.0
93.6
68.72
110.0
114.5
95.0
42.0
130.5
55.0
54.0
102.3
156.0
104.0
114.0
29.0
80.0
60.0
80.0
127.1
88.83
126.0
122.8
60.0
79.0
60.3
55.0
130.0
80.75
0.0
108.45
126.9
51.37
128.6
59.94
110.12
45.0
91.8
56.0
70.0
68.0
104.4
140.0
115.0
126.0
75.6
102.6
nan
89.25
147.0
85.0
95.0
80.1
nan
127.0
27.5
156.67
0.0
65.0
87.5
81.0
81.0
140.88
80.1
139.0
188.14
128.0
73.0
72.75
110.0
112.0
115.0
nan
71.0
nan
120.0
123.3
28.0
50.0
131.0
205.0
43.0
139.0
95.0
48.0
168.3
124.0
135.0
0.0
80.0
156.67
88.0
139.0
nan
78.0
96.5
75.0
168.0
78.3
84.15
100.93
90.0
52.25
110.0
80.0
60.2
175.43
97.5
115.0
157.1
nan
42.0
60.0
nan
65.0
68.74
259.0
43.2
37.0
112.0
53.2
100.92
67.99
115.0
118.0
65.0
37.7
90.0
38.0
61.0
106.34
140.0
160.0
124.38
96.3
140.0
113.4
0.0
59.0
67.76
127.2
43.0
35.0
126.3
121.5
114.5
123.2
144.0
121.0
70.0
40.0
nan
160.0
89.0
62.0
nan
87.0
18.0
32.0
75.0
79.0
91.8
281.0
72.43
75.0
nan
37.29
58.0
160.0
135.9
129.0
112.95
120.0
90.0
70.0
36.0
78.0
137.7
85.2
154.0
95.0
65.0
139.5
63.75
75.0
109.0
79.85
125.66
103.36
101.0
34.0
67.5
120.0
115.82
35.95
112.67
96.3
130.5
85.0
52.55
41.65
139.0
109.0
80.0
65.0
40.0
101.72
90.95
127.0
90.95
112.2
108.75
117.6
157.0
60.0
95.0
95.0
171.0
68.65
117.0
79.2
112.0
30.24
86.0
140.4
157.0
126.9
85.67
100.0
95.0
95.0
98.33
139.5
126.0
62.5
90.0
73.0
57.5
75.7
60.0
58.5
80.0
126.0
123.5
76.08
66.0
93.6
142.0
129.0
169.0
100.0
27.0
146.36
156.6
135.0
95.4
65.0
101.58
136.0
70.0
159.3
81.25
137.25
200.0
100.1
99.88
57.8
270.0
72.76
78.4
160.0
38.4
65.0
105.0
37.6
170.0
121.0
180.0
169.0
120.0
42.0
112.0
nan
51.0
90.0
nan
82.45
45.0
123.38
128.7
132.3
62.0
89.0
67.0
51.8
75.0
120.0
nan
160.0
76.8
122.4
86.1
nan
37.8
90.0
75.0
158.95
65.0
0.0
115.0
126.9
85.67
nan
73.0
90.1
91.48
110.4
110.0
73.9
133.0
202.0
118.8
85.0
94.8
85.0
90.0
79.2
65.0
29.0
123.3
131.83
87.0
112.67
95.5
166.0
128.0
257.67
119.0
90.0
96.0
85.0
145.0
88.0
57.93
85.0
139.0
38.0
74.8
211.0
286.2
nan
120.0
79.2
141.0
76.5
57.6
140.0
65.0
98.0
95.0
97.0
185.0
94.2
108.8
90.4
247.0
157.0
90.95
135.52
130.5
72.0
0.0
66.5
85.0
44.0
110.7
115.6
120.0
69.29
73.0
54.0
196.0
115.0
63.0
99.0
115.0
88.0
85.0
82.08
195.33
103.0
63.0
62.0
140.0
70.0
81.5
97.3
41.96
169.75
38.25
83.85
113.31
153.0
140.0
144.29
183.0
47.25
80.75
125.0
77.0
nan
115.2
90.9
115.0
31.64
50.2
100.8
130.0
66.0
83.5
35.72
85.0
63.75
110.0
66.0
79.2
98.55
129.0
160.0
80.46
67.0
70.0
109.0
0.0
115.0
65.8
100.3
65.0
131.0
50.0
48.0
91.8
96.9
nan
37.0
78.0
0.0
212.1
35.11
144.0
65.0
115.0
117.33
225.0
70.0
73.92
58.65
44.0
108.8
38.0
56.0
148.5
159.0
192.67
nan
149.4
65.0
97.02
121.1
38.0
90.0
59.93
42.0
95.0
200.0
120.0
nan
112.0
76.16
26.0
62.0
120.0
122.33
239.0
90.95
112.2
72.25
0.0
95.0
89.76
144.5
63.58
70.0
55.0
79.2
109.8
nan
234.33
85.0
79.0
112.57
89.0
nan
65.0
nan
65.0
104.0
72.76
160.0
130.5
101.5
94.32
99.0
43.0
135.9
62.0
49.5
108.5
76.81
nan
108.88
108.0
79.2
48.0
29.0
194.0
90.0
79.2
109.0
75.0
80.39
65.0
86.0
37.8
62.0
121.88
71.0
160.0
75.0
159.0
110.0
180.0
nan
30.0
nan
nan
85.5
261.0
99.17
64.0
75.0
73.0
0.0
97.75
89.0
152.67
104.0
75.0
75.0
160.0
44.5
91.0
107.0
97.02
nan
169.0
122.4
126.0
116.1
0.0
74.0
141.0
148.5
134.0
90.0
199.43
88.2
160.0
75.0
nan
0.0
135.15
188.5
65.0
85.0
72.0
80.26
180.0
150.0
65.0
62.0
160.0
111.0
146.7
95.0
0.0
132.6
85.0
68.0
105.0
138.8
75.0
133.33
58.0
168.38
95.0
nan
56.0
nan
75.0
99.0
120.0
65.0
166.25
113.39
102.0
129.6
186.67
150.0
103.0
163.88
36.0
nan
168.0
95.5
104.0
nan
57.8
97.75
65.0
94.0
198.0
62.0
102.0
83.8
141.0
124.0
121.5
146.22
nan
210.0
80.1
85.5
214.0
0.0
165.23
6.0
112.5
58.37
149.6
0.0
244.0
60.0
134.1
88.0
34.0
72.1
122.1
107.0
40.0
90.0
46.5
nan
67.83
90.0
68.0
97.2
240.0
79.2
83.78
68.0
78.4
166.0
148.5
126.9
134.67
55.0
130.0
nan
85.0
130.0
179.1
103.32
110.0
80.1
79.2
82.8
8.0
63.0
113.31
130.0
156.0
72.0
71.0
194.0
104.85
90.0
162.0
166.0
88.0
112.1
88.0
44.67
78.33
80.0
72.75
95.0
106.2
178.75
204.03
76.5
152.0
106.0
293.5
78.31
nan
6.0
87.0
88.0
89.0
140.0
nan
48.67
86.0
205.0
94.5
138.0
nan
65.0
110.0
55.0
nan
160.0
115.0
117.73
nan
74.0
38.0
80.75
66.0
156.0
nan
190.0
nan
170.0
135.5
nan
43.2
nan
94.5
95.0
79.5
0.0
99.72
322.0
95.4
87.0
128.59
58.47
99.0
70.12
100.0
95.0
91.0
119.0
72.0
48.0
174.6
177.0
91.8
60.06
37.8
60.59
105.3
178.0
94.5
123.2
95.0
85.0
nan
218.0
140.4
216.0
96.0
230.0
109.0
79.2
65.0
150.3
60.0
165.75
180.53
99.45
30.0
135.0
137.7
95.0
76.93
108.0
166.5
122.4
90.0
158.4
115.0
65.0
nan
170.0
0.0
96.0
89.1
85.0
105.0
159.0
140.0
71.0
nan
115.0
48.7
73.0
126.0
96.0
72.0
108.0
41.4
114.4
213.75
109.0
68.0
0.0
92.1
106.2
85.5
109.0
124.16
114.0
85.67
103.7
45.89
115.0
90.0
62.0
265.44
95.0
81.0
84.0
85.0
125.1
47.25
89.0
195.33
85.5
138.0
86.0
119.7
85.5
65.0
nan
38.0
93.6
75.0
150.48
120.0
222.5
128.0
245.0
126.0
147.56
129.0
183.0
30.0
114.0
70.0
78.0
79.0
65.0
112.1
94.5
87.55
87.0
121.6
74.0
225.2
40.0
62.0
nan
68.0
0.0
114.92
124.0
59.0
199.0
53.0
35.33
76.0
139.0
nan
63.5
172.0
126.0
171.0
106.33
96.0
112.05
117.9
30.0
nan
159.0
232.8
179.0
170.0
169.2
115.0
139.0
109.0
nan
42.5
41.4
74.8
58.0
65.0
102.6
nan
230.0
4.0
137.33
95.0
90.95
93.6
98.75
104.0
79.0
350.2
215.27
143.0
62.7
94.07
117.0
65.0
45.0
81.2
41.4
90.0
66.0
98.0
85.0
171.0
154.35
106.25
102.35
170.38
140.0
56.83
135.0
75.0
44.0
nan
51.0
35.0
89.1
155.0
89.25
119.0
143.33
45.0
49.0
79.0
178.0
120.0
82.45
102.0
154.98
61.8
56.0
48.0
81.0
110.7
318.71
95.0
45.0
65.0
75.0
178.5
0.0
102.1
100.0
0.0
112.67
76.0
89.1
86.55
97.5
104.0
191.2
37.0
139.0
105.75
107.0
nan
114.4
100.0
235.0
96.3
89.1
79.05
188.0
113.8
114.0
75.0
120.6
79.2
nan
68.16
71.7
199.0
110.0
nan
94.8
85.0
74.8
115.0
143.1
123.5
nan
62.0
89.83
73.0
50.84
48.0
164.0
74.0
nan
127.4
90.0
75.0
65.8
75.0
80.1
38.4
108.0
153.0
144.0
75.0
155.11
nan
0.0
88.4
62.0
67.0
88.0
68.0
190.0
147.0
211.5
99.9
42.0
30.0
75.0
116.5
146.7
86.5
215.0
99.0
68.0
63.0
99.0
91.12
111.96
48.0
162.0
135.0
99.0
40.0
96.6
65.0
nan
80.0
89.1
203.0
38.0
269.0
75.0
82.0
128.0
43.0
98.0
170.0
87.86
167.74
95.0
129.0
70.0
123.75
120.6
230.0
50.0
63.0
128.2
109.0
92.0
225.9
112.67
123.2
130.0
92.0
154.8
nan
nan
105.3
115.0
86.0
64.0
nan
107.1
82.45
nan
40.0
92.4
90.0
78.0
90.2
74.15
50.8
144.76
190.0
99.45
92.0
154.0
44.36
83.0
153.0
nan
nan
85.0
nan
89.25
nan
115.0
8.0
223.75
100.0
nan
80.0
327.6
52.0
nan
55.43
198.9
124.67
0.0
107.0
134.1
69.0
48.0
161.0
88.5
149.4
179.0
116.1
80.0
89.1
196.5
72.0
115.6
95.0
103.5
83.7
130.0
64.8
nan
0.0
60.0
80.1
93.0
118.8
159.0
137.7
115.0
48.0
86.0
65.0
124.0
105.5
235.0
100.09
89.25
50.0
90.1
119.0
156.67
79.2
144.0
33.3
134.3
160.0
93.82
100.0
47.57
25.0
226.67
87.3
155.68
72.1
85.0
262.6
58.0
nan
137.0
78.8
117.0
87.0
86.0
80.85
56.0
124.7
87.3
126.0
58.0
90.65
77.35
127.8
100.0
154.33
126.0
117.0
139.5
132.5
88.0
97.0
48.6
0.0
88.0
192.0
146.0
148.28
133.14
75.0
65.0
98.67
97.92
73.95
95.2
171.1
177.31
124.53
48.95
35.11
62.0
160.0
60.0
118.0
147.33
95.0
75.08
168.6
134.1
68.0
75.0
129.0
98.6
71.39
144.0
65.0
98.0
170.0
126.9
67.0
45.93
95.0
108.0
53.4
96.0
39.0
117.0
143.0
142.2
nan
98.64
48.25
75.0
59.0
80.0
114.4
102.0
54.56
90.0
nan
84.0
nan
85.0

0        None
1        None
2        None
3        None
4        None
         ...
19995    None
19996    None
19997    None
19998    None
19999    None
Name: adr, Length: 19994, dtype: object

In [73]:
hotel['adr'].apply(
    lambda x : print(x)
)

131.5
73.95
nan
80.3
60.9
88.4
105.9
76.67
84.0
42.0
79.84
nan
88.0
126.0
nan
55.0
158.77
56.0
124.1
126.0
77.5
67.0
58.0
72.25
145.1
157.27
nan
100.0
89.0
170.0
67.0
nan
87.0
nan
90.0
107.1
123.0
85.85
56.1
30.24
62.0
110.88
0.0
nan
nan
42.3
0.0
107.1
283.67
55.0
69.0
105.0
62.0
88.0
77.18
134.14
25.11
150.3
168.3
115.2
108.15
130.0
96.0
48.0
75.0
104.5
111.0
130.0
118.13
98.1
168.3
98.0
74.13
82.24
196.0
58.0
87.0
60.0
144.0
118.8
0.0
nan
97.71
118.0
79.2
90.0
245.0
45.0
65.0
88.0
91.0
120.6
106.0
100.0
91.0
88.2
148.0
106.25
89.0
152.0
30.0
90.0
80.0
176.8
100.0
102.8
144.63
27.0
0.0
80.1
47.0
101.15
130.0
60.98
62.0
159.84
161.1
162.0
91.33
0.0
121.14
97.0
62.0
115.0
62.5
75.0
121.0
94.5
44.5
176.64
173.0
130.0
112.0
141.9
36.0
146.11
nan
90.0
126.0
62.0
100.8
54.6
42.0
82.0
169.0
77.85
50.0
35.0
95.0
177.0
89.4
149.4
73.8
0.0
152.0
90.95
48.0
87.0
119.7
nan
60.0
75.0
35.0
162.33
110.0
122.5
35.46
45.0
96.0
0.0
115.0
89.1
30.0
85.67
100.5
nan
82.35
153.62
164.0
120.0
38.0
170.57
75.0
189.9
0.0
73.95
162.0
115.0
74.25
95.0
80.0
165.0
85.0
55.8
48.43
42.6
65.0
202.0
163.8
211.0
25.0
65.0
67.22
59.0
112.7
52.0
85.33
65.4
75.0
60.0
130.0
112.2
64.0
nan
105.3
146.3
67.15
100.1
77.0
86.47
199.0
131.67
126.9
192.0
97.02
139.8
245.0
90.67
46.0
86.5
114.0
129.2
65.0
117.0
72.5
42.5
99.0
37.0
186.0
70.69
114.9
77.93
66.0
89.25
50.0
165.0
67.0
215.0
216.0
219.6
54.0
100.51
66.3
107.1
59.0
120.0
75.0
nan
123.3
73.37
117.9
62.0
120.24
75.0
159.0
170.0
74.95
52.2
96.0
99.95
75.0
85.0
182.18
146.92
75.0
68.0
127.5
35.0
115.0
112.67
55.5
60.0
102.3
55.0
nan
129.72
92.4
48.0
109.0
51.76
54.0
125.1
37.8
105.0
82.45
39.0
105.0
139.0
66.0
nan
77.0
80.1
152.1
83.3
102.5
65.0
102.6
78.3
92.0
118.58
181.79
64.96
65.0
118.0
103.0
39.0
48.0
87.04
106.2
18.6
177.3
209.29
115.0
108.0
90.1
93.6
108.9
68.0
119.0
115.0
160.0
95.0
152.1
95.0
85.33
126.2
117.65
nan
70.0
72.21
61.02
63.0
98.0
130.5
95.0
102.9
65.0
54.0
45.0
93.0
50.55
75.0
105.0
0.0
49.0
112.67
193.08
80.85
44.56
86.0
161.5
122.4
122.63
88.0
55.33
108.0
152.1
105.0
37.8
133.98
96.33
207.9
90.0
139.0
88.0
277.0
29.0
207.9
66.4
93.0
70.0
0.0
131.8
91.75
96.0
125.1
nan
67.91
nan
101.38
108.0
75.0
72.25
128.0
138.6
150.0
121.0
110.0
221.0
122.4
71.0
45.0
58.5
43.0
26.1
45.0
74.8
198.0
62.0
91.0
75.0
40.0
130.0
125.0
45.0
128.5
nan
81.2
94.35
0.0
49.43
130.05
104.4
45.0
0.0
112.5
85.0
48.0
91.8
226.33
114.0
120.6
198.9
74.49
98.1
201.0
76.5
nan
123.45
70.0
134.1
38.0
74.0
78.0
65.0
65.0
6.0
216.9
128.0
78.3
75.0
180.0
121.5
47.8
38.0
100.62
162.0
132.43
63.5
71.7
109.8
230.0
100.0
nan
65.0
85.25
161.0
65.0
144.0
67.0
126.0
nan
60.0
79.2
155.5
114.4
132.44
66.0
80.0
136.0
90.0
126.33
183.0
80.0
44.5
94.14
68.0
55.65
nan
54.9
159.0
131.0
64.8
204.17
145.0
99.18
115.0
95.0
106.67
68.0
80.75
nan
58.4
45.56
79.2
171.0
141.6
139.0
75.0
168.71
89.1
88.29
81.9
95.69
nan
118.15
106.75
110.0
124.0
80.1
60.0
68.0
163.0
60.0
111.0
102.5
89.74
115.0
54.5
119.0
38.88
112.8
160.0
99.45
60.0
114.4
95.0
80.75
122.0
75.0
152.0
113.4
79.5
136.0
150.0
89.1
nan
147.5
78.0
118.8
97.0
74.8
72.25
166.25
51.0
48.0
98.1
95.0
nan
131.0
6.0
36.0
75.0
60.0
244.0
135.4
283.2
98.0
74.0
100.0
62.0
76.67
121.0
34.0
112.5
75.0
90.0
167.0
144.0
91.0
68.0
85.0
67.5
129.0
nan
212.73
159.0
80.75
68.0
65.02
90.1
78.0
0.0
60.0
46.0
60.0
66.53
99.0
99.0
90.0
38.0
63.9
83.83
168.3
34.0
159.0
121.0
98.12
121.0
130.0
93.6
78.0
43.0
55.8
121.1
145.71
54.0
145.0
115.0
93.56
119.1
148.5
99.0
56.0
193.0
139.5
71.0
35.0
68.0
120.28
115.33
138.0
89.0
36.96
28.5
144.0
103.5
131.31
100.8
85.0
nan
154.0
188.0
nan
85.0
58.2
152.1
63.08
177.5
89.25
75.0
44.0
79.5
75.0
120.0
44.0
37.8
88.8
40.0
121.75
54.5
90.0
125.0
108.9
34.0
90.0
98.0
24.7
12.0
48.0
112.67
72.0
75.76
97.0
104.0
99.45
107.0
135.2
106.2
88.0
59.0
45.0
104.0
47.0
46.0
236.5
99.0
99.9
72.0
88.4
89.0
0.0
197.33
159.0
nan
100.0
209.4
65.0
129.6
66.0
49.0
109.77
99.0
139.33
90.9
138.0
134.1
50.0
140.4
90.0
180.0
111.6
nan
233.0
70.0
65.0
44.0
120.83
68.0
78.3
101.33
176.0
99.9
nan
95.0
60.0
64.0
108.0
195.0
102.0
354.0
171.0
99.0
137.7
63.75
61.28
259.0
79.2
95.0
40.0
112.67
144.0
80.75
98.0
165.04
114.5
170.0
97.2
181.8
124.0
83.16
107.0
66.0
117.0
169.0
209.0
135.9
80.0
35.0
203.0
58.92
68.0
128.0
88.0
100.3
99.0
70.0
139.2
92.0
43.0
179.0
100.0
63.3
157.25
80.3
82.73
162.98
99.0
127.5
159.0
210.0
nan
131.0
99.45
160.0
65.0
91.1
94.5
168.0
188.0
79.5
nan
89.1
52.4
95.0
nan
108.0
nan
81.0
99.0
118.0
44.1
111.0
132.67
106.25
210.0
139.0
99.0
126.0
75.0
122.4
95.0
nan
97.41
75.0
65.0
116.1
97.4
75.0
89.2
146.7
112.2
60.0
44.0
76.58
75.0
104.0
123.3
335.0
110.0
30.0
92.65
99.0
131.75
44.81
108.9
160.0
109.1
164.05
39.0
nan
78.0
139.0
75.0
76.23
117.0
98.0
81.0
156.24
75.0
75.0
42.5
140.4
170.0
74.1
60.0
0.0
130.33
104.0
82.39
136.0
85.0
116.95
30.0
117.75
125.0
125.0
80.0
nan
52.56
111.6
30.0
142.2
69.53
29.0
105.0
147.0
0.0
80.75
0.0
44.0
49.0
55.0
117.0
247.0
26.0
136.5
172.8
65.0
95.0
89.0
78.5
80.1
70.0
75.0
130.0
40.0
119.0
91.48
75.0
171.71
62.0
154.0
110.0
88.01
6.0
89.1
38.0
80.75
35.0
116.67
139.0
79.2
111.5
105.3
93.0
189.0
51.0
135.2
98.1
83.0
71.28
52.2
80.0
106.2
75.44
0.0
98.0
90.0
70.0
138.6
nan
109.8
132.0
78.3
74.8
80.75
110.0
38.0
nan
130.1
96.3
107.41
92.0
77.25
106.0
186.0
115.0
66.0
100.8
65.11
nan
94.5
55.0
85.0
63.76
88.4
60.0
59.5
0.0
129.0
51.85
110.0
152.0
nan
50.1
115.0
101.0
99.8
219.0
48.0
95.0
148.0
85.67
89.1
147.0
140.4
205.2
56.0
35.0
56.0
nan
48.0
88.2
76.67
97.71
75.65
147.0
116.1
70.0
74.57
nan
93.0
65.0
59.07
112.67
87.3
70.0
35.0
184.5
174.95
112.67
105.33
95.2
85.0
93.6
79.2
56.0
119.85
199.15
119.0
156.25
153.0
119.0
69.52
109.0
0.0
44.0
91.8
42.0
32.0
60.0
66.0
189.0
180.0
65.83
209.71
46.4
91.38
110.33
153.0
190.0
106.0
65.43
95.0
299.0
124.0
140.0
65.0
123.0
114.4
111.3
0.0
146.0
66.0
98.0
145.0
136.0
146.0
161.0
71.74
102.0
nan
112.5
104.49
77.03
135.29
55.8
98.1
145.67
65.0
132.0
53.0
118.0
98.05
nan
109.0
85.0
48.0
70.0
78.0
81.25
112.67
89.0
121.5
nan
213.6
142.0
93.6
78.0
60.0
149.0
29.0
80.1
72.0
116.1
124.0
90.0
124.0
51.47
39.0
122.48
91.9
76.5
nan
138.9
101.0
68.0
68.0
76.5
39.0
nan
100.0
115.0
167.23
117.0
178.0
90.0
93.8
30.0
nan
95.57
76.69
112.0
190.0
nan
nan
48.0
140.7
110.0
94.71
90.0
0.0
78.3
42.0
113.75
85.67
76.5
230.0
39.0
95.0
98.0
81.0
nan
95.0
90.0
60.0
169.0
108.0
99.0
58.0
100.3
25.0
25.0
76.0
37.0
42.0
82.5
37.0
124.0
61.0
90.0
108.0
148.5
173.94
93.5
120.0
43.2
79.05
107.67
nan
76.8
195.0
98.0
88.0
140.4
91.0
57.0
73.0
76.5
135.0
65.0
62.0
65.0
261.0
87.0
nan
78.0
48.0
65.0
nan
102.72
89.34
72.76
145.0
95.67
82.0
40.0
115.25
160.0
88.0
127.0
100.8
122.84
80.0
140.0
38.07
30.6
39.0
85.0
115.0
91.0
119.2
75.0
157.2
90.07
nan
109.0
0.0
92.98
nan
105.0
65.0
144.8
126.0
0.0
76.5
141.67
75.0
48.0
65.0
75.0
185.0
170.5
85.0
nan
79.0
110.5
173.0
171.0
112.5
138.0
96.3
126.0
68.0
127.0
141.49
107.95
163.5
81.9
86.0
54.0
115.0
100.3
72.0
123.0
247.09
116.5
99.45
90.0
94.0
45.0
0.0
126.0
180.0
104.0
80.0
144.8
110.0
85.5
62.0
187.85
43.0
159.5
54.0
83.0
121.5
36.0
nan
nan
81.0
95.0
64.22
135.9
151.0
62.0
53.32
41.89
176.9
148.29
65.83
80.0
128.7
100.0
94.5
102.56
90.78
nan
95.0
nan
75.0
0.0
111.0
135.0
40.0
65.0
110.0
79.74
77.25
95.0
87.0
212.0
179.0
nan
131.0
110.0
78.08
80.1
99.0
90.0
89.0
46.17
155.0
189.0
95.65
126.27
97.0
43.2
216.0
99.0
87.32
75.0
35.0
96.0
107.33
112.1
121.5
117.0
89.0
48.0
67.76
55.78
312.5
115.0
205.0
nan
129.92
142.2
42.0
305.0
176.8
94.8
72.0
148.5
73.1
100.0
117.1
29.0
67.5
110.0
98.1
172.0
93.5
50.0
50.0
54.71
139.0
172.0
85.0
139.5
23.7
120.0
103.0
65.0
85.5
61.0
36.0
55.0
86.0
118.8
62.0
nan
110.0
0.0
47.0
29.0
85.0
85.5
75.0
79.2
43.41
65.0
200.5
125.8
76.67
99.0
86.4
85.0
25.0
75.33
152.1
155.6
95.0
34.56
nan
82.44
121.75
239.1
89.0
nan
114.2
68.0
114.0
62.5
136.0
179.0
0.0
100.8
109.0
48.38
38.0
85.0
0.26
38.0
89.25
104.0
nan
150.0
95.0
210.0
144.0
172.0
251.0
65.0
199.63
49.0
114.4
168.3
160.0
115.0
104.0
70.0
75.95
50.0
74.69
134.0
36.0
75.0
79.2
43.0
109.0
118.0
77.0
92.17
123.67
145.0
108.8
65.0
122.0
nan
150.3
85.5
103.5
248.0
149.0
37.6
126.0
65.0
78.0
0.0
105.3
76.58
98.0
64.0
49.74
170.0
99.0
100.0
0.0
95.0
84.33
0.0
194.0
75.6
109.65
107.53
79.2
193.6
175.5
nan
112.0
85.0
170.0
88.65
126.6
nan
86.49
76.5
220.0
111.25
191.25
151.0
35.0
83.0
97.43
79.2
85.0
102.85
65.0
213.43
52.0
159.0
130.0
127.71
77.0
87.85
167.8
131.0
40.0
124.0
80.75
98.2
110.0
108.9
98.0
168.3
130.5
80.3
173.45
79.0
50.0
100.0
nan
94.67
146.0
163.67
67.0
112.5
43.0
113.6
98.0
76.0
85.0
115.0
75.57
111.0
0.0
80.0
92.4
153.0
65.0
nan
44.0
86.0
230.0
85.0
108.0
nan
nan
88.0
121.2
185.33
189.33
75.0
72.0
100.0
67.15
134.0
85.0
17.6
36.0
131.0
159.0
102.6
66.8
65.0
83.7
95.8
132.3
116.0
156.0
244.0
99.0
106.0
0.0
101.52
166.0
62.0
65.0
94.36
160.0
30.0
nan
36.24
230.0
112.67
58.0
66.6
100.3
65.75
91.8
200.1
95.0
67.99
85.0
62.0
85.67
80.75
88.0
59.4
38.0
136.8
107.1
111.0
56.0
191.0
156.0
68.0
60.0
107.1
112.7
80.75
156.6
30.0
216.9
126.0
229.0
66.0
117.0
87.78
112.5
109.0
92.65
96.0
109.38
62.8
nan
78.6
93.6
58.0
116.95
131.0
43.8
80.0
101.72
30.0
122.4
196.0
117.98
108.17
99.0
76.23
37.4
152.0
195.0
37.0
55.0
130.0
217.0
170.0
89.1
52.4
106.0
95.0
0.0
110.8
nan
34.0
62.0
92.0
90.0
120.0
135.9
74.25
nan
105.0
132.5
nan
67.0
158.75
117.0
100.0
186.0
89.0
nan
62.0
48.0
nan
104.5
50.0
38.0
161.0
94.0
99.0
85.5
148.5
130.5
135.0
139.5
70.4
94.5
65.0
134.5
120.0
78.0
105.26
64.0
137.7
80.1
65.0
30.0
80.0
95.67
90.68
58.0
75.0
89.0
62.2
0.0
150.0
30.0
100.75
0.0
65.0
0.0
48.0
112.0
88.56
98.0
99.0
60.87
129.9
135.15
43.0
134.0
nan
164.0
95.0
134.0
141.0
184.0
139.0
130.5
86.4
70.0
91.5
69.0
64.37
142.19
96.3
109.8
106.5
130.0
74.8
124.2
0.0
85.0
185.0
60.0
70.0
212.0
268.0
80.0
137.0
106.0
91.36
111.0
90.0
48.0
86.0
39.0
0.0
0.0
100.0
241.0
56.7
38.5
74.0
122.4
82.13
89.1
52.0
92.0
85.0
142.0
85.0
62.0
66.0
0.0
135.33
195.0
269.3
93.86
71.0
246.0
123.2
130.5
72.0
8.0
44.5
90.0
106.0
78.53
136.0
96.0
149.4
55.0
nan
60.0
95.0
nan
84.0
34.4
160.5
49.0
71.1
39.0
150.0
77.6
76.5
120.0
145.0
72.75
166.5
74.8
30.0
103.5
101.0
79.2
44.8
135.0
78.0
120.0
136.67
155.0
156.3
132.3
40.0
71.1
106.54
207.5
86.0
63.75
62.0
110.0
185.57
128.8
78.4
143.7
115.0
156.75
89.78
90.2
46.8
106.88
70.0
65.0
31.95
48.0
112.67
79.2
nan
214.87
96.0
150.0
59.0
65.0
40.5
80.0
140.0
115.0
70.0
108.0
54.0
79.2
110.0
nan
240.0
168.6
87.4
89.0
75.6
65.0
70.26
89.1
80.8
121.6
162.0
112.67
71.0
95.04
48.0
37.8
149.0
139.4
100.0
87.0
101.5
170.0
nan
94.0
102.6
81.5
96.8
119.0
30.0
135.0
139.0
106.2
128.44
72.0
96.75
74.8
86.0
159.3
94.5
159.0
150.0
217.2
153.0
105.3
215.0
0.0
99.0
147.24
104.0
nan
160.0
98.4
60.0
136.0
250.0
156.6
77.99
90.0
43.0
74.8
104.0
89.0
59.0
100.0
120.0
115.0
79.5
85.0
93.6
nan
126.67
44.5
88.4
126.0
88.0
40.0
88.6
68.5
nan
38.0
96.3
65.0
34.0
65.0
100.0
67.5
0.0
159.0
46.0
68.75
109.0
107.1
110.2
42.0
137.7
56.0
48.0
125.0
0.0
111.0
94.0
65.0
89.1
99.9
134.78
182.0
140.0
70.0
63.0
139.5
65.0
0.0
148.0
60.0
120.0
68.4
177.47
85.0
136.0
124.0
120.0
130.0
153.0
56.0
131.0
85.67
77.0
33.0
100.0
149.4
66.0
109.0
118.58
112.6
0.0
95.0
130.0
124.0
nan
104.8
118.5
156.0
162.0
152.0
97.0
nan
78.0
65.0
107.0
65.0
125.1
136.1
85.0
108.0
76.0
54.05
0.0
107.1
146.4
98.1
50.0
98.0
108.0
nan
127.0
214.0
106.2
276.0
45.0
102.9
96.0
158.0
nan
43.2
nan
91.54
95.0
95.0
58.4
60.0
25.0
62.0
75.0
130.0
32.0
94.0
164.0
67.6
128.0
35.0
110.0
91.0
85.0
73.0
88.0
239.0
169.0
80.33
58.31
nan
106.25
120.8
216.9
108.0
89.0
47.85
129.0
117.5
273.56
99.45
108.0
62.0
112.2
85.0
69.85
115.5
138.0
75.0
108.0
89.1
111.0
98.0
73.37
72.07
112.0
79.0
90.0
53.71
75.0
108.0
93.0
87.04
77.0
75.6
43.0
71.6
132.5
177.3
51.84
76.67
130.35
65.7
80.0
39.0
89.1
89.25
90.0
130.94
91.0
95.0
115.0
74.61
89.0
119.85
84.6
67.5
65.0
36.0
26.1
0.0
80.0
62.0
141.68
43.0
175.0
250.0
57.0
26.0
60.0
81.71
111.6
98.67
140.0
nan
122.4
186.43
102.6
72.25
66.49
119.0
124.0
70.0
66.0
107.1
107.0
nan
135.67
66.0
91.33
86.0
100.0
169.0
200.0
108.0
147.59
117.0
42.0
139.0
87.0
140.05
85.03
48.5
235.0
31.45
75.0
60.0
144.0
125.1
72.25
305.0
95.0
109.8
72.0
75.0
105.74
109.0
64.0
44.5
51.0
97.2
114.0
42.0
nan
112.67
169.0
62.0
173.0
90.0
48.0
61.0
92.0
156.6
55.0
82.35
77.93
58.0
166.0
111.2
68.0
112.36
35.0
114.3
79.2
62.0
97.0
50.0
61.5
140.0
118.8
91.8
87.5
44.88
83.0
159.3
119.0
111.0
50.0
81.0
58.0
149.4
176.42
78.3
85.5
70.67
106.25
nan
164.0
143.0
62.17
133.2
65.0
117.0
137.7
71.0
105.9
140.0
49.43
49.0
159.3
68.83
55.0
41.58
68.0
163.2
nan
6.0
110.0
95.0
122.4
62.0
89.3
105.4
104.0
42.0
0.0
134.5
101.13
115.2
48.0
60.65
133.74
139.5
106.26
77.89
83.75
38.0
90.0
54.0
nan
107.95
137.7
51.21
56.0
89.4
80.75
169.2
76.0
145.5
79.8
117.9
54.0
172.0
132.11
38.55
90.0
64.67
0.0
172.0
119.2
81.0
55.0
106.08
79.2
301.0
86.75
185.0
76.08
129.0
nan
80.0
0.0
39.0
116.85
66.43
104.0
91.13
nan
183.0
nan
43.2
108.0
118.0
59.4
155.0
145.8
nan
126.9
171.0
59.71
70.0
197.61
38.0
nan
109.65
180.0
79.0
44.5
80.0
81.0
70.2
48.0
210.0
140.0
150.0
60.0
65.0
93.6
68.72
110.0
114.5
95.0
42.0
130.5
55.0
54.0
102.3
156.0
104.0
114.0
29.0
80.0
60.0
80.0
127.1
88.83
126.0
122.8
60.0
79.0
60.3
55.0
130.0
80.75
0.0
108.45
126.9
51.37
128.6
59.94
110.12
45.0
91.8
56.0
70.0
68.0
104.4
140.0
115.0
126.0
75.6
102.6
nan
89.25
147.0
85.0
95.0
80.1
nan
127.0
27.5
156.67
0.0
65.0
87.5
81.0
81.0
140.88
80.1
139.0
188.14
128.0
73.0
72.75
110.0
112.0
115.0
nan
71.0
nan
120.0
123.3
28.0
50.0
131.0
205.0
43.0
139.0
95.0
48.0
168.3
124.0
135.0
0.0
80.0
156.67
88.0
139.0
nan
78.0
96.5
75.0
168.0
78.3
84.15
100.93
90.0
52.25
110.0
80.0
60.2
175.43
97.5
115.0
157.1
nan
42.0
60.0
nan
65.0
68.74
259.0
43.2
37.0
112.0
53.2
100.92
67.99
115.0
118.0
65.0
37.7
90.0
38.0
61.0
106.34
140.0
160.0
124.38
96.3
140.0
113.4
0.0
59.0
67.76
127.2
43.0
35.0
126.3
121.5
114.5
123.2
144.0
121.0
70.0
40.0
nan
160.0
89.0
62.0
nan
87.0
18.0
32.0
75.0
79.0
91.8
281.0
72.43
75.0
nan
37.29
58.0
160.0
135.9
129.0
112.95
120.0
90.0
70.0
36.0
78.0
137.7
85.2
154.0
95.0
65.0
139.5
63.75
75.0
109.0
79.85
125.66
103.36
101.0
34.0
67.5
120.0
115.82
35.95
112.67
96.3
130.5
85.0
52.55
41.65
139.0
109.0
80.0
65.0
40.0
101.72
90.95
127.0
90.95
112.2
108.75
117.6
157.0
60.0
95.0
95.0
171.0
68.65
117.0
79.2
112.0
30.24
86.0
140.4
157.0
126.9
85.67
100.0
95.0
95.0
98.33
139.5
126.0
62.5
90.0
73.0
57.5
75.7
60.0
58.5
80.0
126.0
123.5
76.08
66.0
93.6
142.0
129.0
169.0
100.0
27.0
146.36
156.6
135.0
95.4
65.0
101.58
136.0
70.0
159.3
81.25
137.25
200.0
100.1
99.88
57.8
270.0
72.76
78.4
160.0
38.4
65.0
105.0
37.6
170.0
121.0
180.0
169.0
120.0
42.0
112.0
nan
51.0
90.0
nan
82.45
45.0
123.38
128.7
132.3
62.0
89.0
67.0
51.8
75.0
120.0
nan
160.0
76.8
122.4
86.1
nan
37.8
90.0
75.0
158.95
65.0
0.0
115.0
126.9
85.67
nan
73.0
90.1
91.48
110.4
110.0
73.9
133.0
202.0
118.8
85.0
94.8
85.0
90.0
79.2
65.0
29.0
123.3
131.83
87.0
112.67
95.5
166.0
128.0
257.67
119.0
90.0
96.0
85.0
145.0
88.0
57.93
85.0
139.0
38.0
74.8
211.0
286.2
nan
120.0
79.2
141.0
76.5
57.6
140.0
65.0
98.0
95.0
97.0
185.0
94.2
108.8
90.4
247.0
157.0
90.95
135.52
130.5
72.0
0.0
66.5
85.0
44.0
110.7
115.6
120.0
69.29
73.0
54.0
196.0
115.0
63.0
99.0
115.0
88.0
85.0
82.08
195.33
103.0
63.0
62.0
140.0
70.0
81.5
97.3
41.96
169.75
38.25
83.85
113.31
153.0
140.0
144.29
183.0
47.25
80.75
125.0
77.0
nan
115.2
90.9
115.0
31.64
50.2
100.8
130.0
66.0
83.5
35.72
85.0
63.75
110.0
66.0
79.2
98.55
129.0
160.0
80.46
67.0
70.0
109.0
0.0
115.0
65.8
100.3
65.0
131.0
50.0
48.0
91.8
96.9
nan
37.0
78.0
0.0
212.1
35.11
144.0
65.0
115.0
117.33
225.0
70.0
73.92
58.65
44.0
108.8
38.0
56.0
148.5
159.0
192.67
nan
149.4
65.0
97.02
121.1
38.0
90.0
59.93
42.0
95.0
200.0
120.0
nan
112.0
76.16
26.0
62.0
120.0
122.33
239.0
90.95
112.2
72.25
0.0
95.0
89.76
144.5
63.58
70.0
55.0
79.2
109.8
nan
234.33
85.0
79.0
112.57
89.0
nan
65.0
nan
65.0
104.0
72.76
160.0
130.5
101.5
94.32
99.0
43.0
135.9
62.0
49.5
108.5
76.81
nan
108.88
108.0
79.2
48.0
29.0
194.0
90.0
79.2
109.0
75.0
80.39
65.0
86.0
37.8
62.0
121.88
71.0
160.0
75.0
159.0
110.0
180.0
nan
30.0
nan
nan
85.5
261.0
99.17
64.0
75.0
73.0
0.0
97.75
89.0
152.67
104.0
75.0
75.0
160.0
44.5
91.0
107.0
97.02
nan
169.0
122.4
126.0
116.1
0.0
74.0
141.0
148.5
134.0
90.0
199.43
88.2
160.0
75.0
nan
0.0
135.15
188.5
65.0
85.0
72.0
80.26
180.0
150.0
65.0
62.0
160.0
111.0
146.7
95.0
0.0
132.6
85.0
68.0
105.0
138.8
75.0
133.33
58.0
168.38
95.0
nan
56.0
nan
75.0
99.0
120.0
65.0
166.25
113.39
102.0
129.6
186.67
150.0
103.0
163.88
36.0
nan
168.0
95.5
104.0
nan
57.8
97.75
65.0
94.0
198.0
62.0
102.0
83.8
141.0
124.0
121.5
146.22
nan
210.0
80.1
85.5
214.0
0.0
165.23
6.0
112.5
58.37
149.6
0.0
244.0
60.0
134.1
88.0
34.0
72.1
122.1
107.0
40.0
90.0
46.5
nan
67.83
90.0
68.0
97.2
240.0
79.2
83.78
68.0
78.4
166.0
148.5
126.9
134.67
55.0
130.0
nan
85.0
130.0
179.1
103.32
110.0
80.1
79.2
82.8
8.0
63.0
113.31
130.0
156.0
72.0
71.0
194.0
104.85
90.0
162.0
166.0
88.0
112.1
88.0
44.67
78.33
80.0
72.75
95.0
106.2
178.75
204.03
76.5
152.0
106.0
293.5
78.31
nan
6.0
87.0
88.0
89.0
140.0
nan
48.67
86.0
205.0
94.5
138.0
nan
65.0
110.0
55.0
nan
160.0
115.0
117.73
nan
74.0
38.0
80.75
66.0
156.0
nan
190.0
nan
170.0
135.5
nan
43.2
nan
94.5
95.0
79.5
0.0
99.72
322.0
95.4
87.0
128.59
58.47
99.0
70.12
100.0
95.0
91.0
119.0
72.0
48.0
174.6
177.0
91.8
60.06
37.8
60.59
105.3
178.0
94.5
123.2
95.0
85.0
nan
218.0
140.4
216.0
96.0
230.0
109.0
79.2
65.0
150.3
60.0
165.75
180.53
99.45
30.0
135.0
137.7
95.0
76.93
108.0
166.5
122.4
90.0
158.4
115.0
65.0
nan
170.0
0.0
96.0
89.1
85.0
105.0
159.0
140.0
71.0
nan
115.0
48.7
73.0
126.0
96.0
72.0
108.0
41.4
114.4
213.75
109.0
68.0
0.0
92.1
106.2
85.5
109.0
124.16
114.0
85.67
103.7
45.89
115.0
90.0
62.0
265.44
95.0
81.0
84.0
85.0
125.1
47.25
89.0
195.33
85.5
138.0
86.0
119.7
85.5
65.0
nan
38.0
93.6
75.0
150.48
120.0
222.5
128.0
245.0
126.0
147.56
129.0
183.0
30.0
114.0
70.0
78.0
79.0
65.0
112.1
94.5
87.55
87.0
121.6
74.0
225.2
40.0
62.0
nan
68.0
0.0
114.92
124.0
59.0
199.0
53.0
35.33
76.0
139.0
nan
63.5
172.0
126.0
171.0
106.33
96.0
112.05
117.9
30.0
nan
159.0
232.8
179.0
170.0
169.2
115.0
139.0
109.0
nan
42.5
41.4
74.8
58.0
65.0
102.6
nan
230.0
4.0
137.33
95.0
90.95
93.6
98.75
104.0
79.0
350.2
215.27
143.0
62.7
94.07
117.0
65.0
45.0
81.2
41.4
90.0
66.0
98.0
85.0
171.0
154.35
106.25
102.35
170.38
140.0
56.83
135.0
75.0
44.0
nan
51.0
35.0
89.1
155.0
89.25
119.0
143.33
45.0
49.0
79.0
178.0
120.0
82.45
102.0
154.98
61.8
56.0
48.0
81.0
110.7
318.71
95.0
45.0
65.0
75.0
178.5
0.0
102.1
100.0
0.0
112.67
76.0
89.1
86.55
97.5
104.0
191.2
37.0
139.0
105.75
107.0
nan
114.4
100.0
235.0
96.3
89.1
79.05
188.0
113.8
114.0
75.0
120.6
79.2
nan
68.16
71.7
199.0
110.0
nan
94.8
85.0
74.8
115.0
143.1
123.5
nan
62.0
89.83
73.0
50.84
48.0
164.0
74.0
nan
127.4
90.0
75.0
65.8
75.0
80.1
38.4
108.0
153.0
144.0
75.0
155.11
nan
0.0
88.4
62.0
67.0
88.0
68.0
190.0
147.0
211.5
99.9
42.0
30.0
75.0
116.5
146.7
86.5
215.0
99.0
68.0
63.0
99.0
91.12
111.96
48.0
162.0
135.0
99.0
40.0
96.6
65.0
nan
80.0
89.1
203.0
38.0
269.0
75.0
82.0
128.0
43.0
98.0
170.0
87.86
167.74
95.0
129.0
70.0
123.75
120.6
230.0
50.0
63.0
128.2
109.0
92.0
225.9
112.67
123.2
130.0
92.0
154.8
nan
nan
105.3
115.0
86.0
64.0
nan
107.1
82.45
nan
40.0
92.4
90.0
78.0
90.2
74.15
50.8
144.76
190.0
99.45
92.0
154.0
44.36
83.0
153.0
nan
nan
85.0
nan
89.25
nan
115.0
8.0
223.75
100.0
nan
80.0
327.6
52.0
nan
55.43
198.9
124.67
0.0
107.0
134.1
69.0
48.0
161.0
88.5
149.4
179.0
116.1
80.0
89.1
196.5
72.0
115.6
95.0
103.5
83.7
130.0
64.8
nan
0.0
60.0
80.1
93.0
118.8
159.0
137.7
115.0
48.0
86.0
65.0
124.0
105.5
235.0
100.09
89.25
50.0
90.1
119.0
156.67
79.2
144.0
33.3
134.3
160.0
93.82
100.0
47.57
25.0
226.67
87.3
155.68
72.1
85.0
262.6
58.0
nan
137.0
78.8
117.0
87.0
86.0
80.85
56.0
124.7
87.3
126.0
58.0
90.65
77.35
127.8
100.0
154.33
126.0
117.0
139.5
132.5
88.0
97.0
48.6
0.0
88.0
192.0
146.0
148.28
133.14
75.0
65.0
98.67
97.92
73.95
95.2
171.1
177.31
124.53
48.95
35.11
62.0
160.0
60.0
118.0
147.33
95.0
75.08
168.6
134.1
68.0
75.0
129.0
98.6
71.39
144.0
65.0
98.0
170.0
126.9
67.0
45.93
95.0
108.0
53.4
96.0
39.0
117.0
143.0
142.2
nan
98.64
48.25
75.0
59.0
80.0
114.4
102.0
54.56
90.0
nan
84.0
nan
85.0

0        None
1        None
2        None
3        None
4        None
         ...
19995    None
19996    None
19997    None
19998    None
19999    None
Name: adr, Length: 19994, dtype: object

- 1차원 스리즈 데이터에서 map(), apply() 함수는 같은 행동을 한다.

In [ ]:
hotel.map(
    lambda x : print(x)
)
# DataFrame에서 map() 함수는 첫번째 스리즈의 values들을 모두 탐색하고 다음 스리즈의 value로 넘어간다.

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

,is_canceled,deposit_type,lead_time,stays_in_weekend_nights,stays_in_week_nights,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr
0,None,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
19995,None,None,None,None,None,None,None,None,None,None,None
19996,None,None,None,None,None,None,None,None,None,None,None
19997,None,None,None,None,None,None,None,None,None,None,None
19998,None,None,None,None,None,None,None,None,None,None,None
19999,None,None,None,None,None,None,None,None,None,None,None

In [ ]:
hotel.apply(
    lambda x : print(x)
)
# DataFrame에서 apply() 함수는 스리즈 별로 탐색을 하는 함수
# 차원을 한개 축소하여 데이터를 확인

0        0
1        0
2        0
3        0
4        0
        ..
19995    1
19996    1
19997    1
19998    1
19999    1
Name: is_canceled, Length: 19994, dtype: int64
0        No Deposit
1        No Deposit
2        No Deposit
3        No Deposit
4        No Deposit
            ...
19995    Non Refund
19996    Non Refund
19997    Non Refund
19998    No Deposit
19999    Non Refund
Name: deposit_type, Length: 19994, dtype: object
0        105.0
1        303.0
2         33.0
3         48.0
4        216.0
         ...
19995     89.0
19996    101.0
19997    277.0
19998      0.0
19999     40.0
Name: lead_time, Length: 19994, dtype: float64
0        2
1        2
2        2
3        0
4        4
        ..
19995    2
19996    0
19997    1
19998    0
19999    0
Name: stays_in_weekend_nights, Length: 19994, dtype: int64
0        5
1        2
2        3
3        1
4        7
        ..
19995    2
19996    3
19997    2
19998    1
19999    2
Name: stays_in_week_nights, Length: 19994, dtype: int64
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
19995    0.0
19996    0.0
19997    0.0
19998    0.0
19999    0.0
Name: is_repeated_guest, Length: 19994, dtype: float64
0        0
1        0
2        0
3        0
4        0
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: previous_cancellations, Length: 19994, dtype: int64
0        0
1        0
2        0
3        0
4        0
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: previous_bookings_not_canceled, Length: 19994, dtype: int64
0        1
1        0
2        0
3        1
4        2
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: booking_changes, Length: 19994, dtype: int64
0        0
1        0
2        0
3        0
4        0
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: days_in_waiting_list, Length: 19994, dtype: int64
0        131.50
1         73.95
2           NaN
3         80.30
4         60.90
          ...
19995     62.00
19996    130.00
19997    100.00
19998    209.00
19999    130.00
Name: adr, Length: 19994, dtype: float64

is_canceled                       None
deposit_type                      None
lead_time                         None
stays_in_weekend_nights           None
stays_in_week_nights              None
is_repeated_guest                 None
previous_cancellations            None
previous_bookings_not_canceled    None
booking_changes                   None
days_in_waiting_list              None
adr                               None
dtype: object

In [80]:
# groupby() 함수와 apply()를 조합하여 deposit_type에 따라서 adr의 결측치를 평균값으로 대체
adj_hotel = hotel.groupby('deposit_type').apply(
    lambda x : x.fillna(x.mean())
)

In [ ]:
# adj_hotel의 인덱스 중 deposit_type 인덱스를 다시 value값으로 넘겨온다.
adj_hotel.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19994 entries, ('No Deposit', np.int64(0)) to ('Refundable', np.int64(16851))
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   is_canceled                     19994 non-null  int64
 1   lead_time                       19994 non-null  float64
 2   stays_in_weekend_nights         19994 non-null  int64
 3   stays_in_week_nights            19994 non-null  int64
 4   is_repeated_guest               19994 non-null  float64
 5   previous_cancellations          19994 non-null  int64
 6   previous_bookings_not_canceled  19994 non-null  int64
 7   booking_changes                 19994 non-null  int64
 8   days_in_waiting_list            19994 non-null  int64
 9   adr                             19994 non-null  float64
dtypes: float64(3), int64(7)
memory usage: 2.2+ MB

In [87]:
# 멀티인덱스인 경우
# 특정 인덱스만 초기화하고 싶으면 reset_index()에서 level 매개변수 설정 변경
adj_hotel.reset_index(level='deposit_type', inplace=True)

In [89]:
# 종속 변수 -> 취소여부의 데이터 균형 부분 확인
adj_hotel['is_canceled'].value_counts()

is_canceled
0    17594
1     2400
Name: count, dtype: int64

- 종속변수 데이터의 균형 문제가 발생 -> 약 7:1 정도의 불균형이 발생
    - 원본의 데이터를 그대로 유지해서 불균형 문제를 학습이 모델이 처리하도록 실행
    - 오버샘플링을 이용하여 모델에 학습
        - 랜덤오버 샘플링
        - SMOTE

In [90]:
adj_hotel['deposit_type'].unique()

array(['No Deposit', 'Non Refund', 'Refundable'], dtype=object)

In [93]:
# deposit_type이 문자형 데이터이기 때문에 0, 1, 2로 데이터를 변경
adj_hotel['deposit_type'] = adj_hotel['deposit_type'].map(
    {
        'No Deposit' : 0,
        'Non Refund' : 1,
        'Refundable' : 2
    }
)

1. adj_hotel에서 독립 변수와 종속 변수로 데이터를 나눠준다.
2. train, test로 데이터를 분할 (7:3)
    - 종속 변수의 데이터의 비율로 데이터를 분할
3. 랜덤포레스트 분류 모델을 생성
4. train 데이터를 이용하여 학습
5. test 데이터를 이용하여 예측
6. 평가 지표 중 정확도를 확인

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import time

In [123]:
# 시작 타이머 지정
start = time.time()
# 독립, 종속
x = adj_hotel.drop('is_canceled', axis=1).values
y = adj_hotel['is_canceled'].values
# train, test로 데이터 분할
X_train, X_test, Y_train, Y_test = train_test_split(
    x, y,
    test_size=0.3, stratify=y
)
# 모델 생성
clf = RandomForestClassifier()
# 모델 학습
clf.fit(X_train, Y_train)
# 모델 예측
pred = clf.predict(X_test)
end = time.time()
# 평가 지표
print("정확도 :", round(
    accuracy_score(Y_test, pred), 2
))
# 분류 보고서 출력
print(classification_report(Y_test, pred))
# 코드의 실행 시간 출력
print("코드 진행 시간 :", end-start)

정확도 : 0.92
              precision    recall  f1-score   support

           0       0.93      0.99      0.95      5279
           1       0.80      0.42      0.55       720

    accuracy                           0.92      5999
   macro avg       0.86      0.70      0.75      5999
weighted avg       0.91      0.92      0.91      5999

코드 진행 시간 : 1.4807195663452148

In [155]:
# 원데이터에서 랜덤 오버 샘플링 작업을 하여 샘플링이 된 데이터셋을 학습
# 독립 변수와 종속 변수를 이용하여 랜덤 오버 샘플링
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

In [156]:
# 샘플러 생성
ros = RandomOverSampler(random_state=42)
smote = SMOTE(random_state=42)

In [157]:
x_over, y_over = ros.fit_resample(x, y)
x_sm, y_sm = smote.fit_resample(x, y)

In [158]:
# train test 데이터셋 분할
X_train_ros, X_test_ros, Y_train_ros, Y_test_ros = train_test_split(
    x_over, y_over,
    test_size=0.3, random_state=42,
    stratify=y_over
)
X_train_sm, X_test_sm, Y_train_sm, Y_test_sm = train_test_split(
    x_sm, y_sm,
    test_size=0.3, random_state=42,
    stratify=y_sm
)

In [159]:
# Random Over Sampling을 한 데이터를 이용하여 랜덤포레스트의 학습, 검증
start = time.time()
clf_ros = RandomForestClassifier()
clf_ros.fit(X_train_ros, Y_train_ros)
pred_ros = clf_ros.predict(X_test_ros)
end = time.time()
print(classification_report(Y_test_ros, pred_ros))
print("RandomOver 데이터의 소요 시간 : ", end-start)

              precision    recall  f1-score   support

           0       0.99      0.94      0.96      5279
           1       0.94      0.99      0.97      5278

    accuracy                           0.96     10557
   macro avg       0.97      0.96      0.96     10557
weighted avg       0.97      0.96      0.96     10557

RandomOver 데이터의 소요 시간 :  2.331523895263672

In [160]:
# SMOTE을 이용하여 랜덤포레스트에 학습, 검증
start = time.time()
clf_sm = RandomForestClassifier()
clf_sm.fit(X_train_sm, Y_train_sm)
pred_sm = clf_sm.predict(X_test_sm)
end = time.time()
print(classification_report(Y_test_sm, pred_sm))
print("SMOTE 데이터의 소요 시간 : ", end-start)

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      5279
           1       0.98      0.92      0.95      5278

    accuracy                           0.95     10557
   macro avg       0.95      0.95      0.95     10557
weighted avg       0.95      0.95      0.95     10557

SMOTE 데이터의 소요 시간 :  2.6983907222747803