In [99]:
import pandas as pd

In [100]:
df = pd.read_json("1-1.여성의류(196).json")
df.head()

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1024338,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,SNS,패션,여성의류,OO 경량 다운 자켓,513,121,1,"[{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인..."
1,1024477,드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드...,SNS,패션,여성의류,OO 아** 구스코트,464,105,1,"[{'Aspect': '사이즈', 'SentimentText': '저는 블랙90 사..."
2,1025044,오늘도 정말 춥네요... 롱패딩 찾고 계신 분을 위한 후기 공유합니다. 키 158...,SNS,패션,여성의류,OO 아** 구스코트,314,78,1,"[{'Aspect': '사이즈', 'SentimentText': '키 158센티로에..."
3,1025046,이웃님들 오늘도 안녕하신가요? 오늘은 따끈한 신상 패딩 후기 올려봅니다~~ 겨울이...,SNS,패션,여성의류,OO 아** 구스코트,307,74,1,"[{'Aspect': '색상', 'SentimentText': '흰색 패딩이 너무나..."
4,1025071,OOO 구스로 소문난 OO의 롱패딩~ 한번 구경 가봐요. 일단 보는 순간 고급스럽...,SNS,패션,여성의류,OO 아** 구스코트,279,68,1,"[{'Aspect': '소재', 'SentimentText': ' 일단 보는 순간 ..."

## 문제
- 데이터프레임에서 'Aspects'컬럼에 데이터들을 이용하여 분류 모델 생성하려 한다.
- SentimentText 텍스트를 이용하여 'Aspect', 'SentimentPolarity'의 값들을 예측
    1. df에서 'Aspects' 데이터를 추출
    2. SentimentText데이터를 문자형으로 이루어져있으니 학습에 대한 데이터의 형태로 변환(문자의 데이터를 숫자형 데이터) -> 토큰화(Okt), 벡터화(TF-IDF)
    3. 종속 변수는 'Aspect', 'SentimentPolarity'
    4. 분류 모델(LinearSVC) random_state만 42로 고정
    5. 테스트를 이용하여 분류가 잘되고 있는가? 정확도만 확인(197데이터를 로드하여 정확도 계산)
    - 벡터화, 모델링 파이프라인으로 연결해서 사용

In [101]:
import json

In [102]:
# json 파일 리스트의 형태로 받아오기
json.load(open('1-1.여성의류(196).json', 'r', encoding='UTF-8'))

[{'Index': '1024338',
  'RawText': '안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.  다 함께 go go go~~  제가 입어보고 좋아서 엄마께도 구매해드렸네요. 딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.  엄마도 제가 입은 것 보시더니 탐내셔서  주문해드렸어요. 영하로 내려가는 날씨에는 이것만 입기엔 얇지만 초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요. 색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈때 코디하기도 좋아요. 앞으로 코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요! 맘같아선 색깔별로 쟁이고 싶습니다.  20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~  설명 끝! 좀 도움이 되셨나요? 그러면 좋아요 꾹 눌러 주시고 전 이만 총총총~~ 항상 여러 이웃님들께 감사드립니다. ',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 경량 다운 자켓',
  'Syllable': '513',
  'Word': '121',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '디자인',
    'SentimentText': '딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서',
    'SentimentWord': '11',
    'SentimentPolarity': '1'},
   {'Aspect': '두께',
    'SentimentText': '이것만 입기엔 얇지만',
    'SentimentWord': '3',
    'SentimentPolarity': '-1'},
   {'Aspect': '기능',
    'SentimentText': '초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.',
    'SentimentWord': '12',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '색상도 디자인도 무난해서',
    'SentimentWord': '3',
    'SentimentPolarity': '0'},
   {'Aspect': '디자인',
    'SentimentText': '디자인도 무난해서',
    'SentimentWord': '2',
    'SentimentPolarity': '0'},
   {'Aspect': '활용성',
    'SentimentText': '사무실에 두고 입기도 좋고, ',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '평소에 가볍게 나갈때 코디하기도 좋아요. ',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요!',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.',
    'SentimentWord': '11',
    'SentimentPolarity': '1'}]},
 {'Index': '1024477',
  'RawText': '드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드릴게요.   작년부터 눈여겨 보던 OO입니다. 저는 블랙90 사이즈 구매했는데 딱 잘 맞네요. 작년에 비해 저렴하게 구매해서 아주 만족해요. 신제품은 경량패딩으로 되서 3in1기능이더라구요. 경량 패딩 구매 따로 하셔야 하는 분들에겐 신제품 매장에서 확인하시라고 권하고 싶네요. 저는 경량이 있는 관계로 이 제품 구매했는데 슬림핏이라 날씬해 보여요. 하지만 안에 두껍게 입기엔 좀 불편하더라구요. 간편하게 니트 티셔츠에 입기에는 딱입니다. 아직은 초겨울이라 OO를 쭉 입고 있어요. 후기 읽으며 많이 고민했고 도움을 받아서 저도 후기 남겨봅니다.누군가에겐 도움이 되셨기를 바라는 마음에서요.   OO 패딩 좋은 건 다들 아실테고.. 롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시길요..',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 아** 구스코트  ',
  'Syllable': '464',
  'Word': '105',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '사이즈',
    'SentimentText': '저는 블랙90 사이즈 구매했는데 딱 잘 맞네요.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '가격',
    'SentimentText': ' 작년에 비해 저렴하게 구매해서 아주 만족해요',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '핏',
    'SentimentText': '슬림핏이라 날씬해 보여요. ',
    'SentimentWord': '3',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '안에 두껍게 입기엔 좀 불편하더라구요.',
    'SentimentWord': '5',
    'SentimentPolarity': '-1'},
   {'Aspect': '활용성',
    'SentimentText': '간편하게 니트 티셔츠에 입기에는 딱입니다.',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시길요..',
    'SentimentWord': '15',
    'SentimentPolarity': '1'}]},
 {'Index': '1025044',
  'RawText': '오늘도 정말 춥네요... 롱패딩 찾고 계신 분을 위한 후기 공유합니다.  키 158센티로에 48키로 마른 체형인데 90사이즈가 여유가 별로 없이 딱 맞습니다. 저는 딱 맞게 입기를 좋아해서 아주 만족해요. 와인색이 정말 특이하게 다운된 색인데 정말 고급스러워서 더욱 마음에 듭니다. 가격도 아주 저렴한 편이라 부담없이 사서 입게 되었답니다. 핏되게 나온 옷이라 넉넉하게 입기를 좋아하시는 분은 한 사이즈 올려 입으셔도 좋을 것 같아요. 저는 이 패딩으로 올겨울 아주 따뜻하게 잘 지내게 될 것 같습니다.   새로운 패딩 장만하고 올 겨울 따스하게 보내시길요...',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 아** 구스코트  ',
  'Syllable': '314',
  'Word': '78',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '사이즈',
    'SentimentText': '키 158센티로에 48키로 마른 체형인데 90사이즈가 여유가 별로 없이 딱 맞습니다. ',
    'SentimentWord': '11',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': '저는 딱 맞게 입기를 좋아해서 아주 만족해요',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '와인색이 정말 특이하게 다운된 색인데 정말 고급스러워서 더욱 마음에 듭니다',
    'SentimentWord': '10',
    'SentimentPolarity': '1'},
   {'Aspect': '가격',
    'SentimentText': '가격도 아주 저렴한 편이라 부담없이 사서 입게 되었답니다.',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': '핏되게 나온 옷이라 넉넉하게 입기를 좋아하시는 분은 한 사이즈 올려 입으셔도 좋을 것 같아요.',
    'SentimentWord': '14',
    'SentimentPolarity': '0'},
   {'Aspect': '기능',
    'SentimentText': '이 패딩으로 올겨울 아주 따뜻하게 잘 지내게 될 것 같습니다. ',
    'SentimentWord': '10',
    'SentimentPolarity': '1'}]},
 {'Index': '1025046',
  'RawText': '이웃님들 오늘도 안녕하신가요? 오늘은 따끈한 신상 패딩 후기 올려봅니다~~  겨울이 얼마 남지 않아 고민하다가 눈에 딱 띄는 패딩이 있어 구매했어요. 저는 유난히 흰색을 좋아하는데 이 흰색 패딩이 너무나 고급진 느낌이라  만족스럽습니다. 평소 55 입는데 이 옷도 90사이즈가 아주 잘 맞네요. 소재가 구김도 없어 좋고 엄청 가벼워서 입은 것 같지도 않은 느낌이 아주 좋아요. 전 요즘은 무거운 패딩은 아주 질색이랍니다. 입었을 때 포근하게 감싸는 느낌도 엄청 만족스럽네요. 강추입니다.  백색의 아름다움을 추구하는 후기~~ 다들 공감하시지요? ㅎㅎ',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 아** 구스코트  ',
  'Syllable': '307',
  'Word': '74',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '색상',
    'SentimentText': '흰색 패딩이 너무나 고급진 느낌이라  만족스럽습니다',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': ' 평소 55 입는데 이 옷도 90사이즈가 아주 잘 맞네요',
    'SentimentWord': '9',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '소재가 구김도 없어 좋고',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '무게',
    'SentimentText': '엄청 가벼워서 입은 것 같지도 않은 느낌이 아주 좋아요. ',
    'SentimentWord': '9',
    'SentimentPolarity': '1'},
   {'Aspect': '촉감',
    'SentimentText': '입었을 때 포근하게 감싸는 느낌도 엄청 만족스럽네요.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'}]},
 {'Index': '1025071',
  'RawText': 'OOO 구스로 소문난 OO의 롱패딩~ 한번 구경 가봐요.  일단 보는 순간 고급스럽다는 생각이 탁 드는 소재였습니다. 입어보니 핏이 너무도 예뻐요. 입는 순간 느끼는 따스함은 어떤 패딩보다 훌륭했습니다. 보통의 패딩같이 스포티한 디자인이 아니라서 회사에 입고 다니기에도 아주 좋을 것 같습니다. OOO 모델로 텔레비전 광고를 많이 봐서 이 옷을 입으면 나도 그녀처럼 아름다운 여인이 될 것 같은 환상을 갖게 하는 패딩이네요.   우리 모두를 모델로 만들어줄 패딩 ㅎㅎ ~~이웃님들 생각은 어떠신지요?',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 아** 구스코트  ',
  'Syllable': '279',
  'Word': '68',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '소재',
    'SentimentText': ' 일단 보는 순간 고급스럽다는 생각이 탁 드는 소재였습니다',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '핏',
    'SentimentText': '입어보니 핏이 너무도 예뻐요',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '입는 순간 느끼는 따스함은 어떤 패딩보다 훌륭했습니다.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '보통의 패딩같이 스포티한 디자인이 아니라서',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': ' 회사에 입고 다니기에도 아주 좋을 것 같습니다.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'}]},
 {'Index': '1025120',
  'RawText': '심플한 디자인에 따뜻한 기능성 패딩을 찾으시는 분들께 소개합니다.  보통 95 사이즈 입는데 후기에 작다는 평이 있어서 100으로 주문했더니 잘 맞네요. 입었을 때 따뜻함이 정말 좋습니다. 혹시 눈이 올 때 방수 기능이 있으면 했는데 정말 눈 맞아도 젖지 않아 참 마음에 드는 패딩이네요. 바람도 잘 들어오지 않으니 보온 효과도 좋은 거 같고요. 저는 개인적으로 롱한 패딩을 좋아하는데 아주 딱 맘에 드는 길이입니다. 아주 오래도록 봉투에 쌓여 있어서 그런지 지금은  털이 죽어 있네요. 시간이 지나면 살아나겠지만 기대했던 것만큼 풍성하지는 않아서 그게 좀 아쉬워요. 그래도 가격 대비 품질은 굿입니다.   후기 잘 읽어보셨지요? 롱패딩 찾으시는 분들께  참고가 되기를  바라는 마음에서 후기  공유했습니다 .                  ',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 아** 구스코트  ',
  'Syllable': '415',
  'Word': '99',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '사이즈',
    'SentimentText': ' 보통 95 사이즈 입는데 후기에 작다는 평이 있어서 100으로 주문했더니 잘 맞네요',
    'SentimentWord': '12',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '혹시 눈이 올 때 방수 기능이 있으면 했는데 정말 눈 맞아도 젖지 않아 참 마음에 드는 패딩이네요',
    'SentimentWord': '17',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '바람도 잘 들어오지 않으니 보온 효과도 좋은 거 같고요',
    'SentimentWord': '9',
    'SentimentPolarity': '1'},
   {'Aspect': '길이',
    'SentimentText': '저는 개인적으로 롱한 패딩을 좋아하는데 아주 딱 맘에 드는 길이입니다. ',
    'SentimentWord': '10',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '털이 죽어 있네요. 시간이 지나면 살아나겠지만 기대했던 것만큼 풍성하지는 않아서 그게 좀 아쉬워요',
    'SentimentWord': '13',
    'SentimentPolarity': '-1'},
   {'Aspect': '품질',
    'SentimentText': '가격 대비 품질은 굿입니다. ',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '입었을 때 따뜻함이 정말 좋습니다. ',
    'SentimentWord': '5',
    'SentimentPolarity': '1'}]},
 {'Index': '1025132',
  'RawText': '편안하면서도 뭔가 좀 색다른 티셔츠가 없을까 검색하던 중 뜻밖에 달달하고 러블리한 핏의 맨투맨을 발견했어요.  러블리하게 퍼프 소매로 소매 셔링 디테일을 더해 볼룸감있고 또 더 사랑스럽게 보이는 스타일이더라구요. 바로 퍼프 맨투맨으로 샀는데 할랑한 루즈핏의 러블리한 맨투맨 제가 딱 찾고 있던 스타일이라 너무 좋았습니다.  엉덩이는 가려주고 다리는 더 길어보이게 해주는 최상의 디자인인 것 같아요. 레깅스와 함께 매칭하면 더욱 더 잘 어울리더라구요.  너무 두껍지도 않고 얇지도 않은 적당한 두께감이라 좋고 원단도 부드러워서 자꾸 손이 가서 데일리로 입기에 딱 좋은 옷인 것 같습니다.  ',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 퍼** 맨투맨/루즈핏롱니트 2종 택1 ',
  'Syllable': '329',
  'Word': '79',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '디자인',
    'SentimentText': '러블리하게 퍼프 소매로 소매 셔링 디테일을 더해 볼룸감있고 또 더 사랑스럽게 보이는 스타일이더라구요',
    'SentimentWord': '13',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '할랑한 루즈핏의 러블리한 맨투맨 제가 딱 찾고 있던 스타일이라 너무 좋았습니다. ',
    'SentimentWord': '11',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '엉덩이는 가려주고 다리는 더 길어보이게 해주는 최상의 디자인인 것 같아요',
    'SentimentWord': '10',
    'SentimentPolarity': '1'},
   {'Aspect': '두께',
    'SentimentText': '너무 두껍지도 않고 얇지도 않은 적당한 두께감이라 좋고',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '원단도 부드러워서',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '자꾸 손이 가서 데일리로 입기에 딱 좋은 옷인 것 같습니다.',
    'SentimentWord': '10',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '레깅스와 함께 매칭하면 더욱 더 잘 어울리더라구요.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'}]},
 {'Index': '1025162',
  'RawText': '오늘 따뜻한 커피 한 잔 생각나는 날씨네요. 향긋한 커피 한 잔 하시면서 오늘 소식 시작할까요? 그럼  Go Go Go~~~  요즘 날씨가 엄청 추웠다 또 괜찮았다 트렌치코트를 입자니 춥고 코트를 입자니 덥고 그렇더라구요. 그래서 가볍게 걸칠 경량패딩 알아보다가 OOOO 퀼팅 경량 다운 자켓이 유명하길래 저도 사봤어요. 워낙 넉넉하게 나왔다는 후기가 많아서 사이즈고민을 많이 했는데 고민하는 사이에 s가 품절되어서 어쩔 수 없이 xs을 샀어요. 코트안에도 입을 생각이고 추워지기 전엔 안에 목티나 적당히 두께있는 옷 입고 외투로도 걸칠 생각이어서 받자마자 입어 봤는데 사이즈가 딱 맘에 듭니다! 얼마나 차이가 있을지는 모르겠지만 s로 샀으면 컷을 것 같네요. 가볍고 웬만한 옷엔 다 어울려서 요즘 매일 입어요. 타 브랜드 제품과 비교했을 때 가격 재질 충전재 모두 탁월하고 착용시 가볍고 따뜻합니다. 핏도예쁘고 디자인도 깔끔하고 가성비 진짜 좋습니다!!  이런 커피가 다 식었네요. 오늘도 제 소식이 도움이 됐다면 좋아요 꾹~ 부탁 드리며 커피향처럼 향긋한 하루가 되시길 바래요~~',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 경량 다운 자켓',
  'Syllable': '550',
  'Word': '137',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '사이즈',
    'SentimentText': '받자마자 입어 봤는데 사이즈가 딱 맘에 듭니다! ',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': 's로 샀으면 컷을 것 같네요. ',
    'SentimentWord': '5',
    'SentimentPolarity': '-1'},
   {'Aspect': '무게',
    'SentimentText': '가볍고 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '웬만한 옷엔 다 어울려서 요즘 매일 입어요. ',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '가격',
    'SentimentText': '가격 재질 충전재 모두 탁월하고',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '재질 충전재 모두 탁월하고',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '무게',
    'SentimentText': '착용시 가볍고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '따뜻합니다.',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '핏',
    'SentimentText': '핏도예쁘고 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '디자인도 깔끔하고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'}]},
 {'Index': '1025163',
  'RawText': '겨울이 다가오는 요즘 여러분들의 헛헛한 마음을 채울 따끈한 정보 대령했사옵니다~~    오늘 소개해 드릴 아이템은 OOOO 퀄팅 경량 다운 자켓 인데요. 착용감 좋고 너무 가볍습니다. 크게 나온 거 같아서 S구매했는데 (평소 사이즈는 M) 조금 넉넉하게 잘 맞는 거 같아요. 움직임이 둔하지 않고 활동하는데 크게 무리가 없어요. 다른 옷들 중에 착용시 습한 느낌이 드는 것도 있는데 재질이 좋아서 그런지 상쾌한 느낌입니다. 가격이 비싼편이 아닌가 생각이 들었는데 입는 순간 다른 제품에 비해서 퀄리티가 좋아서 가격이 비싼 느낌이 안 들었습니다. 퀼팅이 조잡스럽지 않아서 타제품에 비해 고급스러워요. 컬러에 대해 말씀 드리자면 이 옷은 단연 화이트죠. 색감이 밝고 깨끗해서 모든 옷에 잘 어울립니다. 화이트야 말로 이 제품의 시그니처 컬러입니다. 지금 날씨에는 사무실에서 이거 하나만 입고 있어도 따뜻하네요   지금까지 제가 느꼈던 부분을 솔직하게 알려 드렸습니다. 오늘 저의 소식이 도움이 됐다면 좋아요 잊지 마세요~~',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 경량 다운 자켓',
  'Syllable': '514',
  'Word': '126',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '착용감',
    'SentimentText': '착용감 좋고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '무게',
    'SentimentText': '너무 가볍습니다. ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': '크게 나온 거 같아서 S구매했는데 (평소 사이즈는 M) 조금 넉넉하게 잘 맞는 거 같아요. ',
    'SentimentWord': '14',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '재질이 좋아서 그런지 상쾌한 느낌입니다.',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '가격',
    'SentimentText': '가격이 비싼편이 아닌가 생각이 들었는데',
    'SentimentWord': '5',
    'SentimentPolarity': '-1'},
   {'Aspect': '품질',
    'SentimentText': '입는 순간 다른 제품에 비해서 퀄리티가 좋아서 가격이 비싼 느낌이 안 들었습니다.',
    'SentimentWord': '12',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '퀼팅이 조잡스럽지 않아서 타제품에 비해 고급스러워요. ',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '컬러에 대해 말씀 드리자면 이 옷은 단연 화이트죠.',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '색감이 밝고 깨끗해서 모든 옷에 잘 어울립니다.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '화이트야 말로 이 제품의 시그니처 컬러입니다.',
    'SentimentWord': '6',
    'SentimentPolarity': '1'}]},
 {'Index': '1025164',
  'RawText': '안녕하세요? 우리 이웃님들, 동물 사랑에 패딩에 손이 잘 안가셨던 우리 이웃님들께 희소식 가져왔어요!!!바로 가보실까요?  OOOO 퀼팅 다운 자켓은 수조류의 사육과정부터 우모의 채취 가공봉제등 복지 프로그램을 준수했다는 공인인증까지 안심하고 입을수 있는 제품이에요. 전에 다운패딩을 위해 오리털 뽑는 영상봤는데 정말 학대에 가깝더라고요. 그래서 패딩류 지양했는데 이젠 마음 놓고 구매할 수 있어요. 디자인은 예쁘고 퀄리티 좋고 봉제 깔끔하고 따뜻해요. 실용적인 면에서는 그 어떤 아이템도 따라갈수가 없어서 늦가을부터 잘 입고 있습니다. 왜 그렇게 몇년전부터 입소문이 나고 베스트셀러인지 입어보니 알겠더라구요. 이 옷은 단연 화이트이어야하는데.... 평상시 아이 옷만으로도 감당이 안되는지라 차선책인 그레이 구매했네요. 색상이 튀거나 확 예쁘다는 느낌은 없으나 착용감 편안하고  따스하고 어디에나 잘 어울려요. 무엇보다 놀랍도록 가볍고 따뜻하네요   오늘은 여기까지~~좀 도움이 되셨나요? 그러면 좋아요 잊지 마세요! 여러분의 지지와 격려가 제겐 큰 힘이 됩니다.',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 경량 다운 자켓',
  'Syllable': '539',
  'Word': '118',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '디자인',
    'SentimentText': '디자인은 예쁘고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '품질',
    'SentimentText': '퀄리티 좋고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '마감',
    'SentimentText': '봉제 깔끔하고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '따뜻해요. ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '실용적인 면에서는 그 어떤 아이템도 따라갈수가 없어서',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '늦가을부터 잘 입고 있습니다. ',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '이 옷은 단연 화이트이어야하는데.... ',
    'SentimentWord': '4',
    'SentimentPolarity': '-1'},
   {'Aspect': '색상',
    'SentimentText': '색상이 튀거나 확 예쁘다는 느낌은 없으나 ',
    'SentimentWord': '6',
    'SentimentPolarity': '-1'},
   {'Aspect': '착용감',
    'SentimentText': '착용감 편안하고 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '따스하고 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'}]},
 {'Index': '1025165',
  'RawText': '쌀쌀해진 요즘 휘뚜르 마뚜르 걸칠 수 있는 옷 어디 없나 하다가 발견한 제 인생 퀼팅 경량 다운자켓!! 자 만나러 가실까요~~   재질도 좋고 충전재도 구스인데 이 가격이라니!! 놀라도록 혜자스럽습니다. 가볍고 따뜻하고 디자인도 깔끔합니다. 핏도 예뻐서 치마나 바지에 둘다 잘 어울려요. 다른 브랜드에서도 비슷한 옷들을 많이 볼 수 있는데  재질도 충전재도 좋고 무엇보다 마음에 들었던 점은 동물복지시스템 적용해서 다운솜털 채취한게 마음에 듭니다! 다른 경량 패딩과 비교했을 때  디테일에서 차이가 있고 무게감도 확실히 달라요.  가벼우면서 스타일까지 살아 있어요. 퀼팅도 편안해보이고 간격도 딱 알맞게 봉제되어 있어 고급스럽고 간절기 아우터로 너무 편해서 데일리로 늘 착용하는 제 인생 아이템입니다. 한 겨울에는 못 입을 거 같지만 가벼운 옷을 입고 그 위에 살짝 걸치고 코트까지 입으면 정말 따뜻하게 겨울을 보낼 수 있을 거 같아요.  제 소식 어떠셨나요? 도움이 되셨다면 좋아요 꾹 눌러주시고 오늘도 좋은 하루 행복한 하루 되시길 진심으로 기원합니다. 항상 감사 드려요~~',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 경량 다운 자켓',
  'Syllable': '547',
  'Word': '135',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '소재',
    'SentimentText': '재질도 좋고 충전재도 구스인데 ',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '가격',
    'SentimentText': '이 가격이라니!! 놀라도록 혜자스럽습니다. ',
    'SentimentWord': '4',
    'SentimentPolarity': '1'},
   {'Aspect': '무게',
    'SentimentText': '가볍고 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '기능',
    'SentimentText': '따뜻하고 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '디자인도 깔끔합니다. ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '핏',
    'SentimentText': '핏도 예뻐서 ',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '치마나 바지에 둘다 잘 어울려요. ',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '재질도 충전재도 좋고',
    'SentimentWord': '3',
    'SentimentPolarity': '1'},
   {'Aspect': '무게',
    'SentimentText': '가벼우면서 ',
    'SentimentWord': '1',
    'SentimentPolarity': '1'},
   {'Aspect': '활용성',
    'SentimentText': '데일리로 늘 착용하는 제 인생 아이템입니다',
    'SentimentWord': '6',
    'SentimentPolarity': '1'}]},
 {'Index': '1025241',
  'RawText': '치마나 원피스를 좋아하는 저는, 추워진다고 해서 원피스를 포기할수는 없죠 ㅎㅎ 여러분도 저와 같지 않나요? 오늘도 제 맘에 쏙드는 원피스를 소개해드릴게요.  제가 S사이즈를 입는데, 편안하게 입을수 있는 사이즈네요. 55-66을 걸쳐서 중간사이즈를 입는데, 이번 S사이즈 선택은 정확했네요. 상의 하의 소재가 어울리면서 다른소재라 좋았어요. 니트부분은 촘촘해서 입었을때 착용감이 좋구요. 스커트 부분은 플레어라 걸을때 여성스러워 보여요. 스커트의 천이 답답하지않고 세련된 느낌이 들어요. 두벌을 레이어드한 느낌으로 더 스타일리쉬하구요. 블랙이라 신경쓰지않고 더 편하게 입을수 있어요.  어떠셨나요?  여러분도 저처럼 추워질수록 더 예쁘고 분위기 있게 차려입고 멋진 가을을 보내세요~',
  'Source': 'SNS',
  'Domain': '패션',
  'MainCategory': '여성의류',
  'ProductName': 'OO 블랙배색 니트원피스 ',
  'Syllable': '381',
  'Word': '81',
  'GeneralPolarity': '1',
  'Aspects': [{'Aspect': '사이즈',
    'SentimentText': '제가 S사이즈를 입는데, 편안하게 입을수 있는 사이즈네요.',
    'SentimentWord': '7',
    'SentimentPolarity': '1'},
   {'Aspect': '사이즈',
    'SentimentText': '55-66을 걸쳐서 중간사이즈를 입는데, 이번 S사이즈 선택은 정확했네요.',
    'SentimentWord': '8',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '상의 하의 소재가 어울리면서 다른소재라 좋았어요.',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '니트부분은 촘촘해서',
    'SentimentWord': '2',
    'SentimentPolarity': '1'},
   {'Aspect': '착용감',
    'SentimentText': '입었을때 착용감이 좋구요. ',
    'SentimentWord': '3',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '스커트 부분은 플레어라 걸을때 여성스러워 보여요.',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '소재',
    'SentimentText': '스커트의 천이 답답하지않고 세련된 느낌이 들어요.',
    'SentimentWord': '6',
    'SentimentPolarity': '1'},
   {'Aspect': '디자인',
    'SentimentText': '두벌을 레이어드한 느낌으로 더 스타일리쉬하구요.',
    'SentimentWord': '5',
    'SentimentPolarity': '1'},
   {'Aspect': '색상',
    'SentimentText': '블랙이라 신경쓰지않고 더 편하게 입을수 있어요.',
    'SentimentWord': '6',
    'SentimentPolarity': '1'}]},
 {'Index': '1025242',

In [103]:
test_text = [
    '색상이 마음에 든다',
    '설명에 비해 옷이 두껍진 않다',
    '길이가 너무 길지도 않고 짧지도 않다'
]

In [104]:
df['Aspects']

0      [{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인...
1      [{'Aspect': '사이즈', 'SentimentText': '저는 블랙90 사...
2      [{'Aspect': '사이즈', 'SentimentText': '키 158센티로에...
3      [{'Aspect': '색상', 'SentimentText': '흰색 패딩이 너무나...
4      [{'Aspect': '소재', 'SentimentText': ' 일단 보는 순간 ...
                             ...
118    [{'Aspect': '두께', 'SentimentText': '저는 두께가 얇은 ...
119    [{'Aspect': '기능', 'SentimentText': '겨울에 따뜻하게 입...
120    [{'Aspect': '소재', 'SentimentText': '이 목폴라 티셔츠는...
121    [{'Aspect': '소재', 'SentimentText': '일단 원단이 너무 ...
122    [{'Aspect': '활용성', 'SentimentText': '캐쥬얼 코디를 데...
Name: Aspects, Length: 123, dtype: object

In [105]:
df['Aspects'][0]

[{'Aspect': '디자인',
  'SentimentText': '딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서',
  'SentimentWord': '11',
  'SentimentPolarity': '1'},
 {'Aspect': '두께',
  'SentimentText': '이것만 입기엔 얇지만',
  'SentimentWord': '3',
  'SentimentPolarity': '-1'},
 {'Aspect': '기능',
  'SentimentText': '초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.',
  'SentimentWord': '12',
  'SentimentPolarity': '1'},
 {'Aspect': '색상',
  'SentimentText': '색상도 디자인도 무난해서',
  'SentimentWord': '3',
  'SentimentPolarity': '0'},
 {'Aspect': '디자인',
  'SentimentText': '디자인도 무난해서',
  'SentimentWord': '2',
  'SentimentPolarity': '0'},
 {'Aspect': '활용성',
  'SentimentText': '사무실에 두고 입기도 좋고, ',
  'SentimentWord': '4',
  'SentimentPolarity': '1'},
 {'Aspect': '활용성',
  'SentimentText': '평소에 가볍게 나갈때 코디하기도 좋아요. ',
  'SentimentWord': '5',
  'SentimentPolarity': '1'},
 {'Aspect': '활용성',
  'SentimentText': '코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요!',
  'SentimentWord': '8',
  'SentimentPolarity': '1'},
 {'Aspect': '디자인',
  'SentimentText': '디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~',
  'SentimentWord': '6',
  'SentimentPolarity': '1'},
 {'Aspect': '기능',
  'SentimentText': '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.',
  'SentimentWord': '11',
  'SentimentPolarity': '1'}]

In [106]:
text = []
for i in range(len(df)):
    for j in range(len(df['Aspects'][i])):
        text.append(df['Aspects'][i][j]['SentimentText'])
text

['딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서',
 '이것만 입기엔 얇지만',
 '초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.',
 '색상도 디자인도 무난해서',
 '디자인도 무난해서',
 '사무실에 두고 입기도 좋고, ',
 '평소에 가볍게 나갈때 코디하기도 좋아요. ',
 '코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요!',
 '디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~',
 '요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.',
 '저는 블랙90 사이즈 구매했는데 딱 잘 맞네요.',
 ' 작년에 비해 저렴하게 구매해서 아주 만족해요',
 '슬림핏이라 날씬해 보여요. ',
 '안에 두껍게 입기엔 좀 불편하더라구요.',
 '간편하게 니트 티셔츠에 입기에는 딱입니다.',
 '롱이면서 슬림하니 감추고 싶은 부분 감추고 그러면서도 날씬하게 보이는 패딩으로 이번 겨울 멋쟁이가 되어 보시길요..',
 '키 158센티로에 48키로 마른 체형인데 90사이즈가 여유가 별로 없이 딱 맞습니다. ',
 '저는 딱 맞게 입기를 좋아해서 아주 만족해요',
 '와인색이 정말 특이하게 다운된 색인데 정말 고급스러워서 더욱 마음에 듭니다',
 '가격도 아주 저렴한 편이라 부담없이 사서 입게 되었답니다.',
 '핏되게 나온 옷이라 넉넉하게 입기를 좋아하시는 분은 한 사이즈 올려 입으셔도 좋을 것 같아요.',
 '이 패딩으로 올겨울 아주 따뜻하게 잘 지내게 될 것 같습니다. ',
 '흰색 패딩이 너무나 고급진 느낌이라  만족스럽습니다',
 ' 평소 55 입는데 이 옷도 90사이즈가 아주 잘 맞네요',
 '소재가 구김도 없어 좋고',
 '엄청 가벼워서 입은 것 같지도 않은 느낌이 아주 좋아요. ',
 '입었을 때 포근하게 감싸는 느낌도 엄청 만족스럽네요.',
 ' 일단 보는 순간 고급스럽다는 생각이 탁 드는 소재였습니다',
 '입어보니 핏이 너무도 예뻐요',
 '입는 순간 느끼는 따스함은 어떤 패딩보다 훌륭했습니다.',
 '보통의 패딩같이 스포티한 디자인이 아니라서',
 ' 회사에 입고 다니기에도 아주 좋을 것 같습니다.',
 ' 보통 95 사이즈 입는데 후기에 작다는 평이 있어서 100으로 주문했더니 잘 맞네요',
 '혹시 눈이 올 때 방수 기능이 있으면 했는데 정말 눈 맞아도 젖지 않아 참 마음에 드는 패딩이네요',
 '바람도 잘 들어오지 않으니 보온 효과도 좋은 거 같고요',
 '저는 개인적으로 롱한 패딩을 좋아하는데 아주 딱 맘에 드는 길이입니다. ',
 '털이 죽어 있네요. 시간이 지나면 살아나겠지만 기대했던 것만큼 풍성하지는 않아서 그게 좀 아쉬워요',
 '가격 대비 품질은 굿입니다. ',
 '입었을 때 따뜻함이 정말 좋습니다. ',
 '러블리하게 퍼프 소매로 소매 셔링 디테일을 더해 볼룸감있고 또 더 사랑스럽게 보이는 스타일이더라구요',
 '할랑한 루즈핏의 러블리한 맨투맨 제가 딱 찾고 있던 스타일이라 너무 좋았습니다. ',
 '엉덩이는 가려주고 다리는 더 길어보이게 해주는 최상의 디자인인 것 같아요',
 '너무 두껍지도 않고 얇지도 않은 적당한 두께감이라 좋고',
 '원단도 부드러워서',
 '자꾸 손이 가서 데일리로 입기에 딱 좋은 옷인 것 같습니다.',
 '레깅스와 함께 매칭하면 더욱 더 잘 어울리더라구요.',
 '받자마자 입어 봤는데 사이즈가 딱 맘에 듭니다! ',
 's로 샀으면 컷을 것 같네요. ',
 '가볍고 ',
 '웬만한 옷엔 다 어울려서 요즘 매일 입어요. ',
 '가격 재질 충전재 모두 탁월하고',
 '재질 충전재 모두 탁월하고',
 '착용시 가볍고 ',
 '따뜻합니다.',
 '핏도예쁘고 ',
 '디자인도 깔끔하고 ',
 '착용감 좋고 ',
 '너무 가볍습니다. ',
 '크게 나온 거 같아서 S구매했는데 (평소 사이즈는 M) 조금 넉넉하게 잘 맞는 거 같아요. ',
 '재질이 좋아서 그런지 상쾌한 느낌입니다.',
 '가격이 비싼편이 아닌가 생각이 들었는데',
 '입는 순간 다른 제품에 비해서 퀄리티가 좋아서 가격이 비싼 느낌이 안 들었습니다.',
 '퀼팅이 조잡스럽지 않아서 타제품에 비해 고급스러워요. ',
 '컬러에 대해 말씀 드리자면 이 옷은 단연 화이트죠.',
 '색감이 밝고 깨끗해서 모든 옷에 잘 어울립니다.',
 '화이트야 말로 이 제품의 시그니처 컬러입니다.',
 '디자인은 예쁘고 ',
 '퀄리티 좋고 ',
 '봉제 깔끔하고 ',
 '따뜻해요. ',
 '실용적인 면에서는 그 어떤 아이템도 따라갈수가 없어서',
 '늦가을부터 잘 입고 있습니다. ',
 '이 옷은 단연 화이트이어야하는데.... ',
 '색상이 튀거나 확 예쁘다는 느낌은 없으나 ',
 '착용감 편안하고 ',
 '따스하고 ',
 '재질도 좋고 충전재도 구스인데 ',
 '이 가격이라니!! 놀라도록 혜자스럽습니다. ',
 '가볍고 ',
 '따뜻하고 ',
 '디자인도 깔끔합니다. ',
 '핏도 예뻐서 ',
 '치마나 바지에 둘다 잘 어울려요. ',
 '재질도 충전재도 좋고',
 '가벼우면서 ',
 '데일리로 늘 착용하는 제 인생 아이템입니다',
 '제가 S사이즈를 입는데, 편안하게 입을수 있는 사이즈네요.',
 '55-66을 걸쳐서 중간사이즈를 입는데, 이번 S사이즈 선택은 정확했네요.',
 '상의 하의 소재가 어울리면서 다른소재라 좋았어요.',
 '니트부분은 촘촘해서',
 '입었을때 착용감이 좋구요. ',
 '스커트 부분은 플레어라 걸을때 여성스러워 보여요.',
 '스커트의 천이 답답하지않고 세련된 느낌이 들어요.',
 '두벌을 레이어드한 느낌으로 더 스타일리쉬하구요.',
 '블랙이라 신경쓰지않고 더 편하게 입을수 있어요.',
 '데이트룩은 물론, 데일리룩으로도 입기 좋은 원피스를 소개해봅니다.',
 '가장 마음에 드는 부분인 브이넥 디자인은 세련되면서도 여성스러워요. ',
 '자칫 단순해보일수 있는 옷이  상의 하의부분이 다른소재라 더 멋스러움을 연출해줘요. ',
 '4개의 단추는 포인트를 줘서 더 스타일을 빛내주구요.',
 '색도 어두운 블랙계열이면서도 밝게 보여 고급스러워요. ',
 '요즘날씨에도 하나만 입기 딱좋겠어요. ',
 '제가 키가 작은편인데도 길이감은 너무길지않고 딱좋네요 ',
 '다양한 스타일로 연출이 가능한 티셔츠를 득템해서 ',
 '가격도 저렴하고',
 ' 디자인도 제가 원하던 스탈이라',
 '가로로 길게 립라인으로 된 넥이 탄탄하게 잘 짜여 있어서',
 ' 오프솔더로도 활용이 가능해서 좋아요.',
 '하나의 니트로 기분과 상황에 따라 때론 청순하게 때론 섹쉬하게 입을 수 있어 좋은 것 같아요.',
 '디자인이 러블리한 이 맨투맨,',
 ' 너무나도 저렴한 가격이었습니다.',
 '소매와 밑단에 풍성하게 주름을 넣어서 사랑스럽기가 이루말로 다 할 수 가 없는데요.',
 '길이까지 길어서 엉덩이는 덮어주고',
 '앞라인은 또 살짝 짧아서 다리가 엄청 길어보이게 하는 효과까지 있어서 너무 맘에 듭니다.',
 '저렴한 가격에',
 '풍성한 주름이 있는 사랑스러운 맨투맨을',
 '앞 뒤의 길이가 언발란스로 되어 ',
 ' 엉덩이를 푹 덮어주는 길이라 제 맘에 쏙 들었습니다.',
 '넉넉한 사이즈라',
 ' 살들을 잘 감쳐줘서 더 좋았고',
 ' 다리까지 길어 보이게 해 주니',
 '무엇보다 가격이 저렴한데 ',
 '세 가지 색상을 다 주니',
 '어떤 옷과 입어도, 언제 입어도 깔끔하고 예쁜 바지 하나 소개할게요.',
 '색상이 무난해서 다 좋아요',
 '발목 위로 살짝 올라가는 기장으로',
 ' 키도 커보이고 날씬해 보입니다.',
 '코디할 때도 어떤 상의랑 입어도 잘 어울리네요',
 '너무 얇지도 않아서',
 '한 여름 되기 전까지는 문제 없을 것 같아요',
 '그레이색은 약간 색이 바랜 것처럼 보여서 좀 그래요',
 '정사이즈로 주문했는데 입어보니 품이 너무 넓네요',
 '겉감은 부들부들 좋습니다',
 '울이 60퍼센트밖에 안 돼서',
 '한 겨울에는 추울 것 같아요',
 '가성비는 충분히 좋습니다',
 '안에 어두운 목티 입고 아래 스커트랑 받쳐 입으면 겨울 멋쟁이 될 것 같네요. ',
 '소매나 밑단 같은 데 실밥 처리는 좀 신경써서 보내주세요',
 '요즘 입기 좋은 모직코드 하나 보여 드릴게요',
 '그냥 유행타지 않은 베이직한 디자인입니다.  ',
 '저는 개인적으로 이런 디자인 맘에 들어요',
 '사이즈도 넉넉해서',
 '안에 얇은 패딩조키 입고 입으면 딱일 것 같아요',
 '옷감 재질이 적당히 부드러워서 더 좋네요',
 '가성비 완전 좋습니다. ',
 '촉감이 많이 부드럽지는 않지만',
 '입으니 따뜻하고 너무 마음에 듭니다',
 '마감도 잘 되어 있어요',
 '  밝은 카멜이라 쫌 그랬는대 막상 입어보닌 나쁘지 않네요.',
 '올 겨울 출퇴근할 때 멋스럽게 잘 입을 것 같아요. ',
 '겨울 멋내기에는 모직코트만한 게 없죠?',
 '일다 되게 따뜻합니다. ',
 '무겁지 않고 ',
 '색도 예뻐서 맘에 듭니다. ',
 '후드 퍼가 풍성하지 않아서 아쉽습니다. ',
 '생각했던 것 보다 많이 예쁘진 않습니다.',
 '55반이나 66입는데 95사이즈 전혀 안 작고 오히려 크단 느낌입니다.',
 '오히려 90을 샀어야 더 예뻤겠네요.',
 '걱정과 달리 쨍한 화이트가 아니고 차분한 화이트라 옷을 받쳐 입기도 좋았고',
 's사이즈 주문했는데 넉넉하니 여유있고 ',
 '날씬해 보여서 좋습니다.',
 '디자인이 예뻐서 좋고',
 ' 퀄리티도 만족스럽습니다. ',
 '핏도 이쁘고 ',
 '화이트인데도 비침이 거의 없어서 좋습니다.',
 '치마랑 바지에 다 잘어울려서 좋습니다.',
 '이 제품은 재질도 좋고 충전재도 구스입니다. ',
 '가격대비 짱이지요. ',
 '가볍고',
 ' 따뜻하고 ',
 '디자인도 깔끔하네요.',
 '핏도 예쁘고 ',
 '치마나 바지에 둘다 예쁘게 착용가능할 수 있어서 좋습니다. ',
 '입었을때 편하고 ',
 '간절기 아우터로서 데일리로 착용할 수 있는 제품이라서 만족합니다.',
 '핏 예뻐서 강추입니다. ',
 '이 제품은 경량점퍼보다 도톰하고',
 '길이가 엉덩이도 덮어서 아주 좋습니다.',
 '무광이고 쿨톤피부를 화사하게 만들어줘서 좋습니다.',
 '소매는 길어서 살짝 접어 입고',
 '허리부분을 슽링으로 조절하니 적당한 오버핏으로 아주 맘에 듭니다.',
 '봄이니 좀 밝은색으로 구매했는데 제가 컬러를 잘못 선택했네요.ㅠㅠ',
 '아이보리같은 흰색을 구매한다는게 세이지가 그 색인줄 알고 주문해서 받아보니 초록빛이 도네요.',
 '아이보리색으로 교환해서 너무 맘에 들고 ',
 '약간 오버핏을 좋아해서 사이즈도 M으로 바꿔서 딱 좋습니다. ',
 '평소 후드티 자주 입어서 아주 잘 입고 있네요.',
 '간절기 가볍게 걸칠 수 있는 아우터를 찾으신다면 고려해 보셔도 좋을 듯 합니다.',
 '적당한 두께라서 좋고 ',
 '자수 디자인 훌륭합니다.',
 '안쪽이 면소재라서  좋고 ',
 '입으면 아주 힙하고 멋스러워서 맘에 듭니다.',
 '세일할 때 사서 가격도 좋습니다. ',
 '기본중의 기본 디자인이라서 편안합니다. ',
 '사이즈는 정사이즈 사시면 딱 맞고',
 '오버핏을 원하시면 한사이즈 업하시는면 좋을 것 같습니다. ',
 '재질이 부드럽고 ',
 '색상도 좋아하는 컬러라 자주 입을 수 있어서 좋습니다. ',
 '색상도 예쁘고 ',
 '디자인도 아주 기본템이라 좋습니다.',
 '원피스나 후드티입고 입을꺼라서코디하기도 좋습니다.',
 '특히 봄, 가을에 아주 잘 입을꺼 같습니다.',
 '면과 레이온 혼방으로 두껍지 않고 ',
 '무겁지 않습니다.',
 '약간의 신축성이 있어서 편하고',
 '가벼운 데님자켓입니다. ',
 '여름에 입어도 부담스럽지 않을거 같아서 좋습니다.',
 '사진보다 실물 색깔이 훨씬 예뻐서 맘에 듭니다. ',
 '모델컷 보고 색깔 고민 많이 했는데 다행입니다. ',
 '백화점에서보다 휠씬 저렴하게 살 수 있어서 더욱 좋습니다.',
 '사이즈는 정사이즈입니다.',
 '실용성과 활용도가 정말 좋습니다. ',
 '플리스로 입으니 보들보들 부드러워 촉감이 굿이네요.',
 '패딩으로 입으면 탄탄한게 보온성도 좋습니다.',
 '양말도 사은품으로 넣어 주셔서 좋습니다. ',
 '조금 무게는 있는 편인데',
 '따뜻하고 ',
 '뒤집어 입어도 좋으니 ',
 '밝은 핑크가 아니고 인디언 핑크라 차분하면서 겉옷 색감으로 너무 이쁘네요.',
 '옷 마무리까지 아주 고급스러운 느낌이라 맘에 듭니다.',
 '사이즈는 살짝 작게 나온 거 같습니다. ',
 '가격까지 저렴하니 너무 좋습니다.',
 '좀 더 롱한 길이감을 원했지만 올해 신제품에는 있는데 작년 제품에는 없네요.ㅠㅠ',
 '작년에 비해 저렴하게 구매해서 만족합니다.',
 '슬림핏이라서 안에 두껍게 입기엔 불편합니다.',
 '두껍게 입기 위해선 한사이즈 업하셔야 합니다.',
 '원단은 탄탄한 원단으로 되어있어서 ',
 '살짝 무겁습니다. ',
 '일반 롱패딩보다 길긴 길어요.',
 '두툼한 방한용으로 최고에요.',
 '길어도 움직일 때 불편하진 않아요. ',
 '다른브랜드에 비해 치수가 조금 큰 편입니다. ',
 '모자털 조금 빠져서 그게 좀 아쉽습니다.',
 '모자털은  탈부착이 되니 큰 문제는 되지 않을 듯 하네요.',
 '깨끗한 하양이라 일단 색상은 합격입니다.',
 '사이즈 약간 오버핏 사이즈로 정말 괜찮아요. ',
 '길이도 좋습니다. ',
 '가격은 매장보다 더 저렴하게 구입해서 만족도가 큽니다. ',
 '주머니가 조금 불편해서 아쉽습니다',
 '옆으로 넣는 일반 주머니였으면 더 좋았을 것 같네요.',
 '무게감 또한 아쉬워요. ',
 '조금 무거운 감이 있네요. ',
 '모자 탈부착이 안되는 것 또한 아쉽습니다.',
 '두께감 또한 아쉬워요. ',
 '핑크 롱패딩 옛날부터 사고싶었는데 이번에 살수 있게 되서 너무 좋아요.',
 '사진이랑 완전 같은 핑크색이라 정말 기뻤어요.',
 '길이도 사이즈도 참 좋습니다. ',
 '사이즈도 참 좋습니다. ',
 '안에 구스도 적당히 들어있어서 ',
 '가격대비 완전 대만족이에요. ',
 '무게감은 있으니 무거운 거 싫어하시는 분들은 참고하세요',
 '새하얀 눈같은 하얀색이라 너무 예쁩니다. ',
 '가격도 너무 좋아요.',
 '두께도 생각보다 두꺼워요. ',
 '두께가 가격에 비해 두꺼운 거지 엄청 두껍지는 않아요. ',
 '엄청 두꺼운 패딩 원하시면 실망하실 수 있어요.',
 '품질이 최고라고는 말할 수 없지만',
 '가성비는 최고에요.',
 '겨울철 막 입기는 정말 좋을 것 같아요.',
 '가격 너무 좋아서',
 '품질도 너무 좋아요. ',
 '두께도 생각보다 두꺼워서 ',
 '겨울철 정말 잘 입어 질 것 같습니다.',
 '모자 탈부착이 안되는게 좀 아쉽긴 하지만',
 '이 가격에 구스 패딩이라니...정말 믿을 수가 없네요.',
 '동네에서 마트 갈 때만 입어도 이 가격 뽕 뽑을 듯 합니다. ',
 '휘뚜르 마뚜르 여기 저기 올겨울 잘 입고 다닐 듯요.',
 '디자인 색상 다 예쁘고',
 '색상 다 예쁘고 ',
 '울 소재가 부들부들하고',
 '지금 시기에 입고 다니기 딱 좋습니다.',
 '사이즈도 알맞게 잘 맞아요. ',
 '여우 로고도 참 이쁘고',
 '모임할 때 자주 입고 다닐 예정입니다.',
 '워낙 가격이 후덜덜해서요ㅠㅠ',
 '약간 얇은 듯 하나',
 '코트 안 이너로 입기에 좋은 두께감이고',
 '아주 추운날 빼곤 가을까지는 충분히 겉옷으로 가능할 것 같습니다.',
 '제가 팔이 좀 긴편인데도 전혀 짧지 않습니다',
 '색감이 너무 예뻐요.',
 '보는것 보다 소재가 부드럽진 않네요. 그렇다고 까끌거리지도 않아요. ',
 '너무 얇지 않아 ',
 '따뜻해서 좋습니다. ',
 '밑단이 트여 있어서 다리도 길어보이고 예쁩니다.',
 '여우자수는 역시 사랑스럽구요.',
 '사이즈도 좋고 ',
 '핏도 이쁘고 ',
 '색도 고급스럽습니다.',
 '이 가격 실화입니까? 여우 한마리 가슴팍에 키우는 댓가 치곤 너무 비쌉니다',
 '디자인 클래식해서 좋고요.',
 '가디건만 입기에도 핏이 좋고,',
 '셔츠에 걸쳐도 핏이 부해 보이지 않게 각잡아줘서 좋고, ',
 '소재 또한 시간이 지나도 보풀 안생길 울소재라 마음에 듭니다.',
 '소재가 매끄러우면서도 톡톡하고 특유의 광택감이 살짝 있어 좋습니다.',
 '착용시 핏이 깔끔하고 날씬해 보입니다.',
 '팔이 슬림하게 나와서 팔뚝이 좀 굵거나 한 이웃님들은 꼭 입어 보시거나 실측을 보고 꼭 팔둘레를 재어서 구매하세요!! ',
 '검은 바지 짙은 회색 바지 구분없이 여기저기 다 잘 어울립니다.',
 '와이드핏 부츠컷핏 다 좋아요~~',
 '소재가 정말 좋아요.',
 '입었을때 전혀 까끌거리지 않고, ',
 '원단이 탄탄해서 오래오래 예쁘게 입을 것 같아요.',
 '입고 나가니 친구들이 핏이 너무 예쁘다고 해줘서 입을 때마다 기분 좋아지는 옷입니다. ',
 '이제 날씨가 추워지니 자켓이나 코트, 패딩 안에 입기에도 딱입니다.',
 '치마에도 잘 어울리고 청바지에도 좋고 코디하기 좋아요. ',
 '실제로 봤을때 디자인이 더 예뻐요.',
 '옷감도 좋아서 날씬해 보이는 것 같고',
 '디자인이 예뻐서 가디건만 입어도 예쁜것 같습니다. ',
 '가격은 사악합니다. ',
 '이태리 콜롬보 캐시미어를 사용해 소재가 좋습니다.',
 ' 입으면 몸에 감싸는 감촉이 좋아요.',
 '캐시미어 코트 특유의 지블링도 맘에 들어요.',
 '가볍고 ',
 '따뜻해서 잘 입을 듯요.',
 '저는 카멜 색상이 가장 맘에 들어 선택했습니다. ',
 '소재의 고급스러움이 여러분의 겨울을 더욱 따뜻하게 만들 거예요. ',
 '가격은 착하지 않아요.',
 '가볍고',
 ' 따뜻하구요.',
 '소재가 정말 고급진 옷입니다. ',
 '클래식한 기본스타일인데',
 '오버핏이라서 너무 마음에 들어요. ',
 '디자인이 더 예쁘고 고급져요.',
 '지블링이 대단하고 ',
 '옷 디자인도 좋습니다. ',
 '길이는 종아리 중간 아래 정도라 딱 좋습니다.',
 '환하게 입고 싶어 베이지 샀는데 좋습니다. ',
 '카멜색 코트가 이미 있어서 네이비로 했습니다.OO 코트의 시그니처 컬러이기도 하고요',
 '캐시미어 결결 느낌이 살아있어서 너무너무 예뻐요. ',
 '핏도 무심하게 딱 떨어져서 너무 좋습니다.',
 '오버핏이라 도톰한 가디건 입고도 XS사이즈가 맞더라구요.',
 '딱 기본 스타일이라 오랫동안 스테디로 입을 수 있고,',
 '좋은 원단이라 고급스러움이 흐릅니다.',
 '지블링과 광택감은 보기만 해도 흐뭇합니다.',
 '이 카멜색을 얼마나 기다렸게요!! ',
 '무슨 옷에나 툭 걸쳐도 스타일 멋지고 기품 있어 보이니',
 ' 이너 크게 신경쓰지 않아도 되고 정장, 캐쥬얼 모두 다 잘 어울려요.',
 '캐시미어의 품질을 먼저 생각하는데 OO는 이태리 콜롬보사의  캐시미어라 ',
 '오랫동안 따뜻하게 ',
 '편히 입을 수 있고 ',
 '가벼워서 너무 좋습니다. ',
 '옷감의 광택이 인물을 돋보여 주어 고급스러움이 묻어 납니다.',
 '1. 원단 고급지다 ',
 '2.가볍다 ',
 '3.스타일리쉬하다. ',
 '콜롬보 캐시미어 원단이 정말 너무 좋습니다',
 '코트가 가볍고 ',
 '소재가 윤기가 촤르르 흐르고 매끄러우며 고급진 느낌입니다. ',
 '엔틱실버 칼라 자체가 주는 멋짐도 있구요.',
 '지블링 때문에 입었을 때 그 고급스러움이... 넘 예쁩니다. ',
 '오버핏이라 xs 사이즈 인데도 저한테는 맞춘듯이 딱이었어요.',
 '팔길이도 적당하고 좋았구요.',
 '골프웨어인데 필드에서 뿐만 아니라 다양한 레저 활동을 즐길 때는 물론이고 ',
 '일상 생활에서도 세련된 시티룩을 연출할 수 있는 디자인이라 너무 맘에 들었습니다.',
 '따뜻한 보온력까지 갖추고 있어 꽃샘추위도 느근히 견딜 수 있을 점퍼인 것 같아요.',
 '일상생활 뿐만 아니라 출근, 골프, 레져 등 모든 상황에서 입을 수 있는 활용성 높은 ',
 '간절기의 필수 아이템으로 적극 추천합니다',
 ' 저렴하게 ',
 '저렴해서',
 '구성이 좋은 것 같아 질렀어요. ',
 ' 가격이 워낙 좋았기에',
 '특별한 것 없는 심플한 디자인이지만',
 ' 라인이 이뻐서 핏이 살아보여 맘에 들었어요.',
 ' 따뜻하기까지 해서 더 좋았습니다',
 '이 가격에 조끼 하나여도 충분한데 티셔츠와 자켓까지 있는 구성이니',
 '가성비 정말 짱이죠~~^^',
 '6종인데 입을만 한 것은 베스트와 이 자켓 뿐이네요~',
 '아주 저렴했거든요.',
 ' 베스트는 라인이 이뻐서',
 '이 자켓은 투톤이라 마치 조끼를 입은 듯 한 색감이 좋아서 맘에 들어요.',
 '라운딩용으로 덜 고급스럽긴 하지만',
 '몇 번은 입을 만 한 것 같아요',
 ' 집에서 입으면 OOO 핏은 절대 안나온다는 점 참고하세요~ㅎㅎ',
 '자켓, 베스트, 카라티셔츠 2종과 집업티셔츠, 파우치백까지 다양하게 풀 코디네이션 아이템으로 구성되어 있어 매우 알차더라구요. ',
 'UV차단 기능성 원단 사용으로 야외활동에 너무나도 딱 어울리는 소재인 것 같아요. ',
 '라운딩을 위한 옷이다 보니 편안한 착용감은 덤인 듯 합니다.',
 '이번 가을에는 이 세트 하나로 라운딩 준비 끝입니다~~~^^',
 '편안한 착용감의',
 ' 6종 세트 구성으로 판매하는 옷입니다.',
 '저렴해서 ',
 '부드러운 감촉의 기모 원단으로 ',
 '너무 부드러워서 착용감을 더욱 향상시키는 느낌이였습니다. ',
 '디자인은 그냥 심플한 것 같은데 ',
 '입으니 핏이 이쁘고',
 '색상도 화려하지만 너무 튀지 않아 좋은 것 같아요.',
 '세탁을 하면 좀 보플이 생길 것도 같긴 하네요. ',
 '휘뚜루 마뚜루 즐겨 입을 수 있을 듯 한 티셔츠를 발견해서 기분이 정말 좋으네요.',
 '저렴하기도 하고 ',
 '보기에도 디자인이 엘레강스해 보였거든요',
 '자켓의 넥이 길어 제 목이 이렇게 짧다고 느껴지기도 첨이네요. ',
 '자켓이 넥이 심하게 하이스타일이라 ',
 '지퍼를 닫으면 턱에 닿아 너무 불편하네요. ',
 '디자인이 너무 평범해서 이걸 왜 이 돈을 주고 샀을까 생각이 들었어요. ',
 '왼쪽 팔에 OOO 로고가 없었다면 OOO인 줄 모랐을 것 같아요',
 'OOO의 상징적인 디자인 스타일이나 로고가 너무나도 절제되어 있어 섭섭했네요. ',
 '너무 얇아서 좀 실망했습니다.',
 '딱 바람막이로만 입기 좋은 옷이입니다.',
 '바디에 슬림하게 붙는 라인이 너무 이쁘네요.',
 '슬림하게 붙는 핏임에도 불구하고',
 ' 활동하기도 정말 편안해서 정말 좋습니다.',
 '색상도 너무 밝지도 칙칙하지도 않는 상아처럼 뽀오얀 크림색이라 사랑스러움을 더하네요.',
 '블랙도 있었는데 전 크림색이 더 이쁜 것 같아요',
 '모크넥 티셔츠도 부드러워서 착용감이 너무 좋아요.',
 '가볍고 ',
 ' 부드러워서 ',
 '점프와 티셔츠 둘 다 너무 부드럽고',
 '착용감이 좋아서 완존 만족하고 있어요.',
 ' 점퍼는 어디에나 툭 걸쳐도 잘 어울려서 즐겨 입을수 있어서 좋고',
 ' 보기보다 훨씬 따뜻해서 늦가을까지 걱정없을 것 같아요. ',
 '티셔츠도 부드럽고',
 '따뜻해 만족합니다.',
 '좋은 구성으로 기획상품을 만들어 ',
 '보온성이 좋고,',
 ' 편안한 착용감',
 ' 실용성 높은 구성의 OO 골프 기획상품을 소개하려 해요.',
 ' 폭 넓은 스윙을 하기에 정말 편하고 좋으네요.',
 ' 깔끔하고 심플한 디자인이라 ',
 '평소에 입고 다니기 정말 좋아요. ',
 '골프치기도 좋고 ',
 '평상시에도 입고 다니기 편안해서 ',
 '친구들이 스타일이 이뿌다고 어디서 샀냐고 많이 묻는데 ',
 '원단이 부드럽고',
 '착용감도 편안하더라구요',
 '양쪽으로 다 기모처리가 되어있어서',
 '터치감이 부드럽고',
 '따뜻하기까지 했던거였어요',
 '신축성이 얼마나 좋은지 움직이는데 불편함이 전혀 느껴지지 않았어요. ',
 '모크넥 디자인으로',
 ' 레져용으로 뿐만 아니라 자켓 인너웨어로도 손색이 없더라구요.',
 '따뜻한 티셔츠 한장으로 다용도로 연출 가능한 OO의 모크넥 티셔츠 강추입니다.',
 '신축성과 쫀쫀함은 당연하고 ',
 '색상마다 로고가 있는 곳이나 모양이 조금씩 다른 레깅스는 첨입니다. ',
 '로고 위치를 달리해서 입는 재미를 느끼게 해주니 만족감이 배가 되네요. ',
 '정말 편하고',
 '밴딩도 탄탄해서',
 '색감이 예쁘고 또 잘어울리는 것 같아 맘에 듭니다.  ',
 '넉넉하게 4개가 한 세트로 구성되어 있으니',
 ' 매일 돌려 입기가 좋은 것 같네요.',
 ' OO 레깅스 4종 구성을 적극 추천드려요. ',
 '색상마다 디자인이 조금씩 다 달라서 깜짝 놀랐어요. ',
 '다양한 디자인',
 '다양한 색상으로 입는 재미가 있을 것 같아요. ',
 ' 와이존 프리로 ',
 '민망함 없이 자유로이 활동이 가능하다는 거예요.',
 '핏이 예쁜',
 '조깅도 하고 필라테스를 할 생각을 하니 많이 행복해집니다.',
 '데일리 평상복으로도 잘 입을 수 있을 것 같아 강추합니다.',
 '이렇게 저렴한 가격에',
 '디자인이 예쁜 ',
 '기능성 레깅스를 무려 4종이나 준다니',
 '사랑스러운 이뿐 색감의',
 '4개나 들어 있어 행복합니다. ',
 '흡한속건 기능까지 있다고 하니',
 '핏이 예쁜 이 레깅스를 입고 운동을 열씨미 하려고 합니다.',
 '히든밴딩과 매끈한 절개라인으로',
 '슬림핏을 연출해 주는 ',
 '안쪽에 숨어있는 밴딩이 울퉁불퉁한 군살을 정리해줘서 ',
 '허리라인이 매끈해져서 좋으네요',
 '절개라인이 옆선에서 앞으로 넘어오게 디자인이 되어 있어',
 ' 다리가 더욱 슬림해 보이는 것 같아요. ',
 ' 흡한속건 기능성 원단이라고 하니',
 '운동 시 상쾌한 착용감을 유지할 수 있을 것 같아 기대가 되네요.',
 '자외선 차단 기능도 있다고 하니',
 '일상생활이나 레져 활동시에 피부도 보호가 될 것 같아 다양하게 활용이 가능할 것 같습니다.',
 '입체 패턴과',
 '뛰어난 신축성으로 ',
 '완벽한 핏의 이너티셔츠가',
 ' 5종이나 되네요~^^',
 '입어보니 감기거나 보기싫게 달라 붙지 않아서 정말 좋습니다.',
 '굉장히 얇고',
 ' 시원하게 입을 수 있을 것 같은데 ',
 ' 아래 부분이 약간 타이트하게 나와서 아직 못입고 있네요. ㅋㅋ ',
 '사이즈를 한치수 크게 교환하면 핏이 좀 덜 이쁠 듯 해서',
 '예쁘게 입고 라운딩 갈 생각을 하니 너무 행복해지네요. ',
 '올 가을과 겨울 레포츠 활동과 일상 데일리 웨어 등 라이프 스타일에 맞춰 입을 수 있는',
 '보온성과 디자인적 심미성을 모두 갖춘 ',
 '디자인적 심미성을 모두 갖춘 ',
 '환상적인 두톤의 이 컬러감 어쩔까요~?',
 '저의 원픽은 바로 이 패턴블랙입니다',
 ' 핏감과 색상만으로도 모든 설명이 끝났답니다. ',
 '색상만으로도 모든 설명이 끝났답니다. ',
 '블랙, 레드, 화이트도 있으니 원하시는 색상으로 선택을 하시면 될 듯요.',
 '방수, 방풍 기능이 있는 우븐원단으로 되어 있다고 하니 올해는 추위 걱정이 없을 듯 합니다.',
 '겨울철 야외 레포츠 활동이나 데일리 일상 생활에서도 즐겨 입을 수 있는',
 '스트레치성 기모본딩 원단으로 되어 있어',
 ' 활동성은 물론이고',
 '보온성까지 갖춰진 아주 훌륭한 아이랍니다. ',
 '허리도 밴딩처리가 되어 있어',
 '착용감이 너무너무 편안하네요',
 '핏까지 멋진 트렉바지 였습니다.',
 ' 앞과 뒤 주머니를 모두 지퍼 포켓으로 만들어 안전하게 수납을 할 수 있어서 더 좋았답니다. ',
 '트렉수트의 핏이 어찌 이리 이뿔 수가 있을까요? ',
 '디자인이 심플해 보이지만',
 '어깨는 좁고 허리는 짤록하게 만들어주는 깔끔한 패턴으로 여심을 사로잡아 버렸습니다. ',
 '기모 원단으로 되어 있어 ',
 '진짜 따뜻하답니다.',
 '신축성도 이루 말할 수 없이 좋아서',
 '착용시 불편함이 1도 느껴지지 않아요.',
 '트렉수트지만 겨울까지 일상복으로 손색이 없을 것 같습니다.',
 '바느질도 엉망이고',
 '마무리도 깔끔하지 않아요.ㅜㅜ ',
 '지퍼 있는데는 안감이 더 큰지 밖으로 자꾸 밀려 나오네요.',
 '역시 싼 건 그 이유가 있는 것 같습니다',
 '저렴한 구성이라도',
 '아트핏 테크니컬 수트 2종과 아트핏 라운딩 수트 2종으로 구성되어 있는데',
 ' 좋은 가격으로 나와서',
 ' 입으니 네임처럼 아트핏입니다.',
 '제 살들이 숨을 곳이 없어 좀 민망할 따름입니다.ㅋㅋ  ',
 '활동성이 높은 소재를 사용해서 3D 입 체패턴으로 만들었다고 하니 당연히 너무 편안합니다.',
 '더없이 편안한 OOO 트랙수트로 자유롭게 활동하시길 바랍니다.',
 '가격도 착한 ',
 '좋은 상품의 구성이 5종이나 되니',
 '구성이 좋아서',
 '목이 약간 올라오는 반폴라 타입이 셋, 시원해 보이는 라운드 네크라인이 둘 이렇게 다양하게 구성이 되어 있어서 좋았어요.',
 '소매 중앙선을 따라 편칭도 심플한 디자인의 기본 티셔츠에 포인트가 되어서 만족스러웠어요.',
 ' 좀 더 다양한 색상으로 구성이 되었더라면 좋았을 것 같아요.',
 ' 흡수된 땀을 빠르게 말리는 흡한속건의 기능 뿐 아니라',
 'UV차단 효과까지 있어',
 ' 입으면 냉감까지 있어 더 좋아요.',
 '좀 까칠거리는 느낌이 있긴하지만',
 ' 시원한 이너티셔츠로',
 '자외선으로 부터 피부를 보호하며 ',
 '레져를 즐기자구요.',
 '5종 구성으로 일주일 내내 넉넉하게 입을 수 있는',
 '착한 가격으로 ',
 '땀을 많이 흘려도 쾌적한 착용감을 유지시켜주는',
 '흡한 속건의 기능성까지 갖추고 있어서 더 만족스러워요.',
 '스판이라 신축성도 좋아서 활동하기도 아주 좋답니다.',
 '야외에서 오랜시간 운동을 하거나 레져를 즐길 때 입기 정말 좋을 것 같아요',
 '원 아이템으로 입어도 이쁘고, 이너웨어로 입어도 이뿐 ',
 '착한 가격에 ',
 '구성이 5종이나 되어서 ',
 ' 가성비가 좋은 것 같아 ',
 '입었을 때 약간 까슬거리는 촉감이 처음에는 살짝 거슬렸어요',
 ' 몇 번 입다보니 까슬거림이 청량하게 느껴져 오히려 시원해서 좋아하게 되었네요. ',
 '원단이 땀에 젖어도 빨리 말라서 더 좋았어요. ',
 '너무 붙지도 할랑하지도 않아 핏까지 예뻐서 ',
 '압박감에서 벗어날 수 있는 조임 제로',
 '세가지 색상 밖에 없다는 것이 유일한 흠으로 보여집니다. ',
 '쿨감이 있는 시원한 원단인 것은 기본이고',
 ' 면 터치감의 경쾌함까지 느껴져서 맘에 들어요.',
 '속은 맞춤인 듯 몸에 딱 맞아 안정감이 있고 ',
 '겉은 약간 여유롭지만 헐렁하지 않아 핏도 이뿌네요.',
 '소매와 네크라인에 로고로 포인트를 줘서 디자인의 심플함을 보완해 주는 것 같아요.',
 '좋은 가격에 구매하게 되어 너무 좋았습니다',
 ' 좀 더 다양한 색상으로 제작을 해 주시면 더 바랄 것이 없을 것 같아요.',
 ' 슬림해 보이도록 팔의 군살을 모두 가려주는 5부 소매 길이와',
 ' 완성도 높은 턴 업 디자인의 소매라인이',
 '팔뚝을 더욱 슬림해 보이게 해 준답니다.',
 ' 브라도 타공 몰드로  직접적인 통기성을 강화시켜서',
 ' 답답하지 않아 만족스러워요.',
 '원피스 하나로 간편한 외출이 가능해서 강추합니다.',
 '시원하고  우수한 착용감을 느낄 수 있는 원단을 사용한',
 '기능성 브라 원피스',
 '입어보니 핏이 매끄럽고',
 '정전기 발생도 없는 것 같아 만족하게 되었네요.',
 '무엇보다 브라의 밴드가 안정감이 있어 편안했습니다.',
 '세가지 색상 중 하나를 선택해서 구매하면 똑같은 원피스를 랜덤으로 하나를 더 준다하니',
 '면 소재 같은 캐주얼한 느낌으로',
 '일상복과 홈웨어 등 자유롭게 입을 수 있는 멀티 아이템을 발견한 것 같아요.',
 '과하지 않고 심플한 디자인의 라인이라 ',
 '외출시에도 부담스럽지 않네요. ',
 ' 압박감이 느껴지지 않으면서도 안정감이 있어서 착용시 너무 편안해요',
 '길이도 무릎을 살짝 덮는 기장이라 딱 적당하고',
 '옆트임이 있어',
 ' 활동하는데 불편함이 없습니다.',
 '편안하고',
 '이뿐 핏의 헤드 반팔 원피스로',
 ' 1+1으로',
 '좋은 가격에 ',
 ' 편안한 원피스 두 벌을 받을 수 있어서 좋았어요. ',
 ' 바람이 통하고 시원한 느낌이여서 맘에 듭니다. ',
 ' 하변 밴드가 안정감이 있어 더 좋네요.',
 '치마에 옆트임이 있어',
 ' 활동하기 편안하고',
 '앞 뒤의 길이가 약간 언발스하게 디자인해서 심플함을 보충해 주는 느낌이예요.',
 ' 색상, 디자인, 핏 모두 만족스러워',
 '디자인, 핏 모두 만족스러워',
 ' 산책시 비 올 때 입으려고 구입했는데 정말 기능이 좋네요',
 ' 더위를 좀 타는 편이라 걱정했는데, 원단이 얇어서 괜찮을 것 같아요',
 '일부러 어두운 색상으로 구입했는데 생각보다 너무 탁하지 않아서 맘에 듭니다',
 '사이즈가 크네요',
 '구매하실 때 한 사이즈 작게 사시면 맞으실 거예요.',
 '길이는 종아리까지 와서 비 많이 올 때 좋네요. ',
 '레인코트 디자인이 엄청 귀엽네요',
 '안에 끈 조절 스트링도 있어서 품 조절도 가능하고',
 '보관 가방이 있으니깐 비오는 날에 입고 나가서 비 맞아서 비에 젖어도 가방에 넣으면 되니깐 보관이나 휴대성도 좋습니다',
 '66사이즈인 저에게도 비옷답게 여유 있어 편해요',
 '바스락거리는 소리가 좀 거슬리기는 하지만 소재의 특성으로 비옷이니 할 수 없지요.',
 '가성비 좋은 제품입니다. ',
 ' 디자인 이쁜 건 기본이고',
 '평소 95 사이즈 입는데, M이 낙낙해서 뒤에 가방 멜 수도 있어 편합니다',
 '그냥 입을 때는 뒤에 있는 쪼임 끈으로 조이면 되기 때문에 기능성도 아주 좋아요',
 '지퍼 형식이라 저는 똑딱이보다 한번에 입고 벗을 수 있어 편리하고 더 맘에 드네요. ',
 ' 모자도 달려 있어서  뒷모습도 예뻐요. ',
 '바람 많이 불 때는 바람막이 기능도 하니 정말 일석이조 레인코트랍니다.',
 '레인코트 디자인이 너무 너무 이쁘네요.',
 '진짜 비 하나도 안 들어오네요.  ',
 '비가 아무리 와도 끄떡 없을 것 같고 ',
 '가격도 너무 저렴해서 정말 추천하고 싶은 레인코트입니다. ',
 '이제 옷 젖는 걱정 안하고 강아지와 함께 산책할 수 있어서 행복해요',
 '겨울에 따뜻하게 입을 수 있는 기모 소재라 아주 좋아요',
 '약간 통이 있는 일자 바지라서 편하게 입을 수 있어요',
 '다만 다리에 살이 없으신 분은 헐렁하겠어요.',
 '스키니 주로 입었던 사람은 약간 어색하겠지만 첼시 부츠에 입으면 잘 어울립니다.',
 ' 제 키가 170인데 기장은 길지 않고 복숭아뼈 위로 오는 딱 좋은 길이네요. ',
 ' 이 바지는 보들보들해서',
 '착용감이 참 좋습니다.',
 'xs을 살 수 밖에 없었는데  받자마자 입어봤는데 딱 맘에 드네요.',
 '얇은데 ',
 '되게 따뜻하고',
 '가볍고 ',
 '웬만한 옷엔 다 어울려서 요즘 매일입고있습니다. ',
 '가성비 진짜 좋네요.',
 '전 169센티에 51키로인데  m사이즈 딱입니다',
 ' 재질이 너무  좋아요',
 '은은한 색상도 마음에 쏙 들고',
 ' 박음질도 아주 좋네요',
 '이 정도 저렴한 가격에',
 '이런 퀄리티 자켓, 정말 대만족입니다.',
 '실물 디자인이 더 이쁜 거 같습니다',
 '색상을 고민하다가 가장 화사한 핑크로 골랐는데 탁월한 선택이었던 것 같아요',
 '우산을 써도 바람 불면 어쩔 수 없이 옷자락이 젖을 수밖에 없는데 이제 그 걱정은 안해도 될 것 같아서 완전 만족입니다',
 '사이즈는 좀 크게 나왔으니 참고 하세요. ',
 '활용도가 꽤나 높은 자켓이예요',
 '간절기에 좋아서 봄에 정말 편하게 잘 입고 있습니다.',
 '컬러감도 좋고',
 ' 청바지와도 아주 잘 어울리네요.',
 '간절기에 입기에 적당한 두께의 자켓입니다',
 '저는  66인데 m사이즈 아주 잘 맞네요',
 '마감도 제법 깔끔해서 아주 좋습니다.',
 '단지 어깨뽕이 약간 과하게 들어간 것 같은 느낌이 들긴 해요. ',
 '핏도 예쁘고',
 '옷감 재질이 부드럽고 좋아서 완전 마음에 드네요.',
 '요즘엔 보세에서도 이런 저렴한 가격으로 못 사는데 완전 득템한 기분입니다',
 '착용감이 좋아서 자켓이 몸에 착 붙는 그런 느낌의 옷이네요.',
 '55사이즈이지만 오버핏으로 입고 싶어서 한사이 크게 샀는데 좋네요',
 '치수 재보고 구입한거라 예상했던 핏이 나와 마음에 들어요',
 '두꺼운 어깨 패드 들어가 있어서 ',
 '소매 기장이 조금 길긴 하지만 롤업 해서 입을 거라 크게 문제 되진 않습니다.',
 '총장도 적당히 힙을 덮어주는 길이라 좋네요. ',
 '오버핏 자켓도 디자인이 멋스러워서 충분히 소장가치 있는 것 같아 추천합니다',
 ' 어깨 핏을 멋지게 잡아주네요',
 '이런 오버핏 자켓도 디자인이 멋스러워서 충분히 소장가치 있는 것 같아 추천합니다.',
 '시원한 촉감에다',
 '소재가 후들거리지 않고  쫀쫀해서',
 '핏이 사네요.',
 '마무리도 깔끔하고 ',
 ' 여름에 시원하게 잘 입을 것 같아요 . ',
 '소재가 살에 달라 붙지도 않고 넘 마음에 드네요. ',
 '바지 3개에 이 정도 가격이라니 정말 잘 샀어요',
 '사이즈는 정사이즈입니다',
 '입으니 비싼 바지 못지 않게 핏이 좋네요. ',
 '올해 이월 상품을 저렴한 가격으로 구매했네요.',
 'RDS 구스라니 춥진 않겠지만',
 '패딩쪽은 빵빵한 디자인은 아닙니다.',
 '생각보다 무게감이 있어서 아쉽네요. ',
 '넉넉하게 나온 옷은 아니라서 한사이즈 업해서 구매했더니 크네요. ',
 '후리스면은 부들부들해서 감촉이 좋습니다.',
 '디자인이 진짜 이쁩니다.ㅎㅎ',
 '이 제품은 행사로 저렴하길래 ',
 '사고 싶었던 아이보리로 구매해서 맘에 듭니다. ',
 '사이즈는 정사이즈사야 합니다. ',
 '옷이 구김도 없고 ',
 '퍼도 윤기 있어서 좋습니다.',
 '일단 퍼랑 소재는 맘에 듭니다.',
 ' 안감 털빠짐도 덜한 거 같아서 좋습니다. ',
 '카키색으로 사 드렸는데 화면보다 색이 밝아서 녹색 느낌이 더 많이 납니다. 어두운 카키색이었으면 더 좋았을텐데  살짝 아쉽네요',
 '158정도 되는 키에는 조금 길이감이 있어 조금만 더 짧았으면 좋겠다고 하시네요.',
 '옆트임열고 입으면 괜찮습니다. ',
 '핏도 너무 예쁘고 ',
 '따듯하다고 하시네요.',
 '27이 맞을 것 같아서 시켰더니 진짜 배도 안 쪼이고 그렇다고 크지도 않고 딱 잘 맞았어요.',
 '길이도 발목 가리는 정도까지 딱 떨어져서 넘 마음에 드는 기장이네요',
 '면 느낌이 부드럽고 좋네요',
 '디자인이 스키니와 와이드의 중간이라 부담없이 입기에 딱입니다.',
 '사이즈가 좀 큰 거 같아서 25사이즈로 교환했는데 다행히 잘 맞네요',
 ' 핏이 제가 원하던 거라 아주 맘에 들어요. ',
 '보통 26사이즈 입는데 25 사이즈가 맞으니 타이트하게 입길 원하시면 한 사이즈 작게 구매하시는 게 좋겠네요.',
 '가을 겨울 입기 좋은 도톰한 원단이라 좋아요',
 '패턴 섞이지 않은 단색 옷감이라 촌스럽지 않고 세련되어서 멋스러워요.',
 '바지 원단 자체가 부드럽고 ',
 '겨울에도 따뜻할 거 같아 맘에 듭니다.',
 '신축성 또한 좋아서 굿이네요',
 '겨울용은 두꺼운 겨울 원단을 고려해서  28로 구매했더니 허리가 좀 크네요.',
 '핏은 전체적으로 마음에 듭니다. ',
 '도톰해서 ',
 ' 린넨도 블렌딩 되어 좋고',
 '입어보니 역시 예상대로 완전 시원하네요',
 '66사이즈 주문했는데 아주 잘 맞네요',
 '저는 이런 배기핏을 좋아하는데 딱 제가 원하던 스타일이었어요.',
 '린넨의 소재상 조금 구김은 있어서 다림질은 필수입니다. ',
 '일단 촉감이 매우 좋아요',
 '이 바지는 착용감이 너무 좋아서 그 부분이 제일 맘에 들었어요.',
 '데님이라 입었을 때 젊어 보이니 그것도 기분 좋더라구요. ',
 '색상은 베이지였지만 더워 보이는 색상은 아니라서 괜찮았습니다. ',
 '인디고 색상이 아주 시원하게 보여요. ',
 ' 요즘 핫한 스타일이라서 대학생 딸과 아들이랑 다녀도 뒷모습은 친구 같다고 신랑이 놀리기도 하는데 듣기 싫지 않아요.',
 '사이즈는 반사이즈는 내려 입으셔도 될 정도로 넉넉하게 나왔어요.',
 '저도 평상시 입던 바지보다 반 사이즈 내려 입었는데 아주 잘 맞네요',
 '싼 가격에 ',
 '원단이 너무 좋고',
 '핏도 저한테 딱이었습니다. ',
 '부드러운 촉감의 원단이',
 '정말 따뜻하고 좋습니다. ',
 '핏도 적당히 몸에 적당히 붙고 좋습니다. ',
 '사이즈는 오히려 넉넉한 편이라서 좋네요. ',
 '색상도 무난해서',
 '여기저기 코디해서 입기 좋습니다. ',
 '팔길이 기장 모두 적당합니다. ',

In [107]:
len(text)

917

In [108]:
from konlpy.tag import Okt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [109]:
Y_asp = []
for i in range(len(df)):
    for j in range(len(df['Aspects'][i])):
        Y_asp.append(df['Aspects'][i][j]['Aspect'])
Y_asp

['디자인',
 '두께',
 '기능',
 '색상',
 '디자인',
 '활용성',
 '활용성',
 '활용성',
 '디자인',
 '기능',
 '사이즈',
 '가격',
 '핏',
 '활용성',
 '활용성',
 '디자인',
 '사이즈',
 '사이즈',
 '색상',
 '가격',
 '사이즈',
 '기능',
 '색상',
 '사이즈',
 '소재',
 '무게',
 '촉감',
 '소재',
 '핏',
 '기능',
 '디자인',
 '활용성',
 '사이즈',
 '기능',
 '기능',
 '길이',
 '소재',
 '품질',
 '기능',
 '디자인',
 '디자인',
 '디자인',
 '두께',
 '소재',
 '활용성',
 '활용성',
 '사이즈',
 '사이즈',
 '무게',
 '활용성',
 '가격',
 '소재',
 '무게',
 '기능',
 '핏',
 '디자인',
 '착용감',
 '무게',
 '사이즈',
 '소재',
 '가격',
 '품질',
 '디자인',
 '색상',
 '색상',
 '색상',
 '디자인',
 '품질',
 '마감',
 '기능',
 '활용성',
 '기능',
 '색상',
 '색상',
 '착용감',
 '기능',
 '소재',
 '가격',
 '무게',
 '기능',
 '디자인',
 '핏',
 '활용성',
 '소재',
 '무게',
 '활용성',
 '사이즈',
 '사이즈',
 '소재',
 '소재',
 '착용감',
 '디자인',
 '소재',
 '디자인',
 '색상',
 '활용성',
 '디자인',
 '소재',
 '디자인',
 '색상',
 '기능',
 '길이',
 '활용성',
 '가격',
 '디자인',
 '디자인',
 '활용성',
 '활용성',
 '디자인',
 '가격',
 '디자인',
 '길이',
 '길이',
 '가격',
 '디자인',
 '디자인',
 '길이',
 '사이즈',
 '핏',
 '핏',
 '가격',
 '제품구성',
 '활용성',
 '색상',
 '길이',
 '디자인',
 '활용성',
 '두께',
 '기능',
 '색상',
 '사이즈',
 '소재',
 '소재',
 '기능',
 '가격',
 '활용성',
 '품질',
 '기능',
 '디자인',
 '디자인',
 '사이즈',
 '활용성',
 '소재',
 '가격',
 '촉감',
 '기능',
 '품질',
 '색상',
 '활용성',
 '활용성',
 '기능',
 '무게',
 '색상',
 '소재',
 '디자인',
 '사이즈',
 '사이즈',
 '색상',
 '사이즈',
 '핏',
 '디자인',
 '품질',
 '핏',
 '소재',
 '활용성',
 '소재',
 '가격',
 '무게',
 '기능',
 '디자인',
 '핏',
 '활용성',
 '착용감',
 '활용성',
 '핏',
 '두께',
 '길이',
 '색상',
 '길이',
 '핏',
 '색상',
 '색상',
 '색상',
 '사이즈',
 '활용성',
 '기능',
 '두께',
 '디자인',
 '소재',
 '디자인',
 '가격',
 '디자인',
 '사이즈',
 '사이즈',
 '소재',
 '색상',
 '색상',
 '디자인',
 '활용성',
 '기능',
 '두께',
 '무게',
 '신축성',
 '무게',
 '기능',
 '색상',
 '색상',
 '가격',
 '사이즈',
 '활용성',
 '촉감',
 '기능',
 '제품구성',
 '무게',
 '기능',
 '활용성',
 '색상',
 '마감',
 '사이즈',
 '가격',
 '길이',
 '가격',
 '핏',
 '사이즈',
 '소재',
 '무게',
 '길이',
 '기능',
 '길이',
 '사이즈',
 '품질',
 '디자인',
 '색상',
 '사이즈',
 '길이',
 '가격',
 '디자인',
 '디자인',
 '무게',
 '무게',
 '디자인',
 '두께',
 '색상',
 '색상',
 '길이',
 '사이즈',
 '소재',
 '가격',
 '무게',
 '색상',
 '가격',
 '두께',
 '두께',
 '두께',
 '품질',
 '가격',
 '기능',
 '가격',
 '품질',
 '두께',
 '기능',
 '디자인',
 '소재',
 '가격',
 '활용성',
 '디자인',
 '색상',
 '소재',
 '기능',
 '사이즈',
 '디자인',
 '활용성',
 '가격',
 '두께',
 '두께',
 '기능',
 '길이',
 '색상',
 '소재',
 '두께',
 '기능',
 '디자인',
 '디자인',
 '소재',
 '핏',
 '색상',
 '가격',
 '디자인',
 '핏',
 '핏',
 '소재',
 '소재',
 '핏',
 '사이즈',
 '활용성',
 '활용성',
 '소재',
 '촉감',
 '소재',
 '핏',
 '활용성',
 '활용성',
 '디자인',
 '소재',
 '디자인',
 '가격',
 '소재',
 '촉감',
 '소재',
 '무게',
 '기능',
 '색상',
 '소재',
 '가격',
 '무게',
 '기능',
 '소재',
 '디자인',
 '핏',
 '디자인',
 '소재',
 '디자인',
 '길이',
 '색상',
 '색상',
 '소재',
 '핏',
 '사이즈',
 '디자인',
 '소재',
 '소재',
 '색상',
 '디자인',
 '활용성',
 '품질',
 '기능',
 '착용감',
 '무게',
 '소재',
 '소재',
 '무게',
 '디자인',
 '소재',
 '무게',
 '소재',
 '색상',
 '소재',
 '사이즈',
 '길이',
 '활용성',
 '디자인',
 '기능',
 '활용성',
 '기능',
 '가격',
 '가격',
 '제품구성',
 '가격',
 '디자인',
 '핏',
 '기능',
 '제품구성',
 '가격',
 '제품구성',
 '가격',
 '핏',
 '색상',
 '디자인',
 '활용성',
 '핏',
 '제품구성',
 '소재',
 '착용감',
 '활용성',
 '착용감',
 '제품구성',
 '가격',
 '소재',
 '착용감',
 '디자인',
 '핏',
 '색상',
 '품질',
 '활용성',
 '가격',
 '디자인',
 '길이',
 '디자인',
 '착용감',
 '디자인',
 '디자인',
 '디자인',
 '두께',
 '활용성',
 '핏',
 '핏',
 '착용감',
 '색상',
 '색상',
 '착용감',
 '무게',
 '촉감',
 '촉감',
 '착용감',
 '활용성',
 '기능',
 '촉감',
 '기능',
 '제품구성',
 '기능',
 '착용감',
 '제품구성',
 '착용감',
 '디자인',
 '활용성',
 '활용성',
 '착용감',
 '디자인',
 '소재',
 '착용감',
 '소재',
 '촉감',
 '기능',
 '신축성',
 '디자인',
 '활용성',
 '활용성',
 '신축성',
 '디자인',
 '디자인',
 '착용감',
 '품질',
 '색상',
 '제품구성',
 '활용성',
 '제품구성',
 '디자인',
 '디자인',
 '색상',
 '디자인',
 '착용감',
 '핏',
 '활용성',
 '활용성',
 '가격',
 '디자인',
 '제품구성',
 '색상',
 '제품구성',
 '기능',
 '핏',
 '디자인',
 '핏',
 '기능',
 '핏',
 '디자인',
 '핏',
 '소재',
 '착용감',
 '기능',
 '활용성',
 '디자인',
 '신축성',
 '핏',
 '제품구성',
 '핏',
 '두께',
 '기능',
 '디자인',
 '사이즈',
 '활용성',
 '활용성',
 '기능',
 '디자인',
 '색상',
 '색상',
 '핏',
 '색상',
 '색상',
 '기능',
 '활용성',
 '소재',
 '착용감',
 '기능',
 '디자인',
 '착용감',
 '핏',
 '디자인',
 '핏',
 '디자인',
 '핏',
 '소재',
 '기능',
 '신축성',
 '착용감',
 '기능',
 '마감',
 '마감',
 '마감',
 '품질',
 '가격',
 '제품구성',
 '가격',
 '핏',
 '핏',
 '소재',
 '착용감',
 '가격',
 '제품구성',
 '제품구성',
 '제품구성',
 '디자인',
 '색상',
 '기능',
 '기능',
 '기능',
 '촉감',
 '기능',
 '기능',
 '활용성',
 '제품구성',
 '가격',
 '착용감',
 '기능',
 '신축성',
 '활용성',
 '활용성',
 '가격',
 '제품구성',
 '가격',
 '촉감',
 '기능',
 '기능',
 '핏',
 '착용감',
 '색상',
 '소재',
 '촉감',
 '착용감',
 '핏',
 '디자인',
 '가격',
 '색상',
 '길이',
 '디자인',
 '핏',
 '기능',
 '착용감',
 '활용성',
 '소재',
 '기능',
 '핏',
 '소재',
 '착용감',
 '제품구성',
 '디자인',
 '활용성',
 '디자인',
 '활용성',
 '착용감',
 '길이',
 '디자인',
 '착용감',
 '착용감',
 '핏',
 '제품구성',
 '가격',
 '제품구성',
 '기능',
 '착용감',
 '디자인',
 '착용감',
 '디자인',
 '색상',
 '디자인',
 '기능',
 '소재',
 '색상',
 '사이즈',
 '사이즈',
 '길이',
 '디자인',
 '디자인',
 '제품구성',
 '사이즈',
 '소재',
 '가격',
 '디자인',
 '사이즈',
 '기능',
 '디자인',
 '디자인',
 '기능',
 '디자인',
 '기능',
 '기능',
 '가격',
 '기능',
 '소재',
 '디자인',
 '사이즈',
 '활용성',
 '길이',
 '촉감',
 '착용감',
 '사이즈',
 '두께',
 '기능',
 '무게',
 '활용성',
 '가격',
 '사이즈',
 '소재',
 '색상',
 '마감',
 '가격',
 '품질',
 '디자인',
 '색상',
 '기능',
 '사이즈',
 '활용성',
 '기능',
 '색상',
 '활용성',
 '두께',
 '사이즈',
 '마감',
 '디자인',
 '핏',
 '소재',
 '가격',
 '착용감',
 '사이즈',
 '핏',
 '디자인',
 '길이',
 '길이',
 '디자인',
 '핏',
 '디자인',
 '촉감',
 '소재',
 '핏',
 '품질',
 '기능',
 '소재',
 '가격',
 '사이즈',
 '핏',
 '가격',
 '기능',
 '디자인',
 '무게',
 '사이즈',
 '촉감',
 '디자인',
 '가격',
 '색상',
 '사이즈',
 '소재',
 '소재',
 '소재',
 '품질',
 '색상',
 '길이',
 '디자인',
 '핏',
 '기능',
 '사이즈',
 '길이',
 '촉감',
 '디자인',
 '사이즈',
 '핏',
 '사이즈',
 '소재',
 '소재',
 '소재',
 '기능',
 '신축성',
 '사이즈',
 '핏',
 '두께',
 '소재',
 '기능',
 '사이즈',
 '디자인',
 '소재',
 '촉감',
 '착용감',
 '소재',
 '색상',
 '색상',
 '디자인',
 '사이즈',
 '사이즈',
 '가격',
 '소재',
 '핏',
 '소재',
 '기능',
 '핏',
 '사이즈',
 '색상',
 '활용성',
 '길이',
 '소재',
 '두께',
 '활용성',
 '핏',
 '핏',
 '신축성',
 '가격',
 '촉감',
 '색상',
 '촉감',
 '색상',
 '소재',
 '활용성',
 '사이즈',
 '마감',
 '기능',
 '무게',
 '기능',
 '디자인',
 '핏',
 '길이',
 '착용감',
 '길이',
 '색상',
 '사이즈',
 '착용감',
 '소재',
 '핏',
 '신축성',
 '길이',
 '신축성',
 '소재',
 '품질',
 '촉감',
 '두께',
 '사이즈',
 '색상',
 '두께',
 '소재',
 '색상',
 '소재',
 '활용성',
 '색상',
 '디자인',
 '촉감',
 '활용성',
 '기능',
 '색상',
 '촉감',
 '신축성',
 '마감',
 '기능',
 '색상',
 '활용성',
 '핏',
 '사이즈',
 '두께',
 '품질',
 '활용성',
 '마감',
 '기능',
 '활용성',
 '착용감',
 '소재',
 '신축성',
 '착용감',
 '두께',
 '핏',
 '색상',
 '활용성',
 '활용성',
 '신축성',
 '사이즈',
 '핏',
 '소재',
 '가격',
 '색상',
 '품질',
 '품질',
 '디자인',
 '색상',
 '길이',
 '기능',
 '가격',
 '무게',
 '가격',
 '기능',
 '색상',
 '디자인',
 '무게',
 '기능',
 '착용감',
 '디자인',
 '길이',
 '활용성',
 '착용감',
 '기능',
 '소재',
 '기능',
 '무게',
 '신축성',
 '디자인',
 '촉감',
 '활용성',
 '사이즈',
 '기능',
 '소재',
 '촉감',
 '신축성',
 '핏',
 '기능',
 '무게',
 '품질',
 '품질',
 '신축성',
 '가격',
 '제품구성',
 '색상',
 '디자인',
 '디자인',
 '소재',
 '기능',
 '소재',
 '신축성',
 '기능',
 '소재',
 '기능',
 '기능',
 '사이즈',
 '디자인',
 '신축성',
 '착용감',
 '기능',
 '착용감',
 '색상',
 '두께',
 '기능',
 '길이',
 '핏',
 '사이즈',
 '활용성',
 '마감',
 '품질',
 '활용성',
 '소재',
 '기능',
 '기능',
 '신축성',
 '착용감',
 '소재',
 '신축성',
 '디자인',
 '착용감',
 '활용성',
 '디자인',
 '디자인',
 '디자인',
 '사이즈',
 '길이',
 '기능',
 '두께',
 '디자인',
 '활용성',
 '활용성',
 '두께',
 '색상',
 '소재',
 '핏',
 '사이즈',
 '신축성',
 '착용감',
 '품질',
 '기능',
 '활용성',
 '기능',
 '소재',
 '촉감',
 '디자인',
 '길이',
 '활용성',
 '무게',
 '기능',
 '활용성',
 '소재',
 '촉감',
 '사이즈',
 '활용성',
 '가격',
 '색상',
 '핏',
 '소재',
 '소재',
 '두께',
 '기능',
 '무게',
 '색상',
 '사이즈',
 '디자인',
 '품질',
 '가격',
 '활용성',
 '색상',
 '색상',
 '무게',
 '기능',
 '길이',
 '활용성',
 '디자인',
 '품질',
 '디자인']

In [110]:
Y_sent = []
for i in range(len(df)):
    for j in range(len(df['Aspects'][i])):
        Y_sent.append(df['Aspects'][i][j]['SentimentPolarity'])
Y_sent

['1',
 '-1',
 '1',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '-1',
 '-1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '-1',
 '1',
 '-1',
 '0',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '0',
 '-1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '-1',
 '0',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '-1',
 '-1',
 '-1',
 '0',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '-1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1']

In [111]:
test_data = pd.read_json("1-1.여성의류(197).json")
test_data.head()

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1028158,바지 하나 소개 해 드릴게요. 도시적이고 세련된 스타일의 바지랍니다. 무엇보다 디...,SNS,패션,여성의류,OO 프리미엄 팬츠,312,73,1,"[{'Aspect': '디자인', 'SentimentText': '도시적이고 세련된..."
1,1028159,안녕하세요. 날씨가 점점 추워지고 있는데 오늘은 일명 OO 패딩이라는 OOO 스투키...,SNS,패션,여성의류,OO 스** 다운 숏패딩,318,76,1,"[{'Aspect': '기능', 'SentimentText': '이거 하나만 입어도..."
2,1028160,필라테스를 시작하게 되어서 운동복으로 OOOO 레깅스를 구매 해 보았습니다. 사이...,SNS,패션,여성의류,OO 리** 레깅스,271,60,1,"[{'Aspect': '사이즈', 'SentimentText': '사이즈 M사이즈를..."
3,1028161,작년에 입고 마음에 들어서 올해 재구매한 OOOO 와이드 바지입니다. 정말 편한 바...,SNS,패션,여성의류,OO 브** 와이드 플리츠 팬츠,296,71,1,"[{'Aspect': '착용감', 'SentimentText': '정말 편한 바지 ..."
4,1028162,겨울 코디에 빼 놓을 수 없는 게 코트 아닐까요? 그런데 날씨는 추워지는데 입을 만...,SNS,패션,여성의류,OO 여성용 핸드메이드 더블 코트,320,74,1,"[{'Aspect': '길이', 'SentimentText': '무릎까지 내려오는 ..."

In [122]:
test = []
for i in range(len(test_data)):
    for j in range(len(test_data['Aspects'][i])):
        test.append(test_data['Aspects'][i][j]['SentimentText'])
test

['도시적이고 세련된 스타일의 바지랍니다.',
 '무엇보다 디자인이 많이 고급집니다!',
 '색상도 거의 블랙에 가까운 차콜색이라서 너무 좋습니다.',
 '가격이 좀 사악하게 나와서',
 '어머나 색상 너무 좋고',
 '핏 그리고 감촉까지도 제가 찾던 바지입니다. ',
 '감촉까지도 제가 찾던 바지입니다. ',
 '바지 재질이 부들부들하고',
 '핏도 좋습니다. ',
 '길이감도 딱 좋아서 기장 수선 없이 입을 수 있습니다.',
 '이거 하나만 입어도 따뜻해서 추위 걱정 없을 거 같습니다.',
 '또 무엇보다 가볍고 ',
 '숏패딩이라 기장이 짧아서 활동성이 너무 좋습니다. ',
 '청바지 롱치마에 같이 입어도 어울립니다.',
 '내구성도 뛰어나서 ',
 '이곳 저곳에 주머니가 많은 디자인이라서 수납하기도 편리하고 좋네요. ',
 '보온성이 아주 뛰어난 숏패딩 하나 구입하시고 이번 겨울 따뜻하게 보내시는 건 어떨까요?',
 '등산, 캠핑 등 다양한 활동에도 너무 좋고',
 '사이즈 M사이즈를 선택했는데 적당하게 잘 맞습니다. ',
 '가격대비 재질도 마음에 듭니다.',
 '나름 OOOO 글자가 멋스럽고 좋네요.',
 '운동복으로 일상복으로 입기에 적당합니다.',
 '착용감도 좋고',
 '아랫배도 잘 잡아줍니다.',
 '핏도 나름 이쁘고 좋네요. ',
 '신축성이 좋아서 활동하는데 전혀 불편함이 없고 좋습니다.',
 '착한 이 가격에 ',
 '품질이 너무 좋네요.',
 '정말 편한 바지 리뷰 시작할게요~~~',
 '색상이 고급스럽고 ',
 '가격대비 품질이 너무 좋은 바지입니다. ',
 '캐쥬얼로도 정장으로도 잘 입을 수 있는 바지입니다. ',
 '소재가 도톰해서',
 '정말 따뜻하고 한 겨울에도 잘 입을 수 있는 바지입니다. ',
 '바지통도 적당히 넓어서 편하고 좋습니다. ',
 '길이감도 적당해서 좋아요. ',
 '디자인도 너무 멋지고 예쁩니다.',
 '정말 착용감 편하고',
 '무릎까지 내려오는 기장이 너무 좋습니다. ',
 '라이트 민트 색상이 너무 고급지고 예쁘네요. ',
 '두께도 많이 두껍지도 않고 얇지도 않아서 좋고',
 '무엇보다 따뜻하네요. ',
 '사이즈도 넉넉하니 좋네요.',
 '디자인도 무난하니 ',
 '화려하지는 않지만 심플한 디자인이 너무나도 매력적인 코트입니다.',
 '투피스처럼 보이지만 원피스인게 이 옷 디자인의 매력입니다. ',
 '소매 길이와 치마길이도 적당해서 편하게 입을 수 있습니다. ',
 '색상도 크림색이라서 화사해 보입니다.',
 '사이즈도 정사이즈로 나온 제품이라서 잘 맞았습니다. ',
 '옷의 마감들도 아주 깔끔하게 되어 있는 원피스이고',
 '봄 가을에 입기 좋습니다.',
 '신부의 예복으로도 손색이 없는 이 원피스 괜찮지 않나요? ',
 '입은지 2개월 정도 되었는데 착용감 무지 좋습니다. ',
 '두께가 있는 편이지만 저는 오히려 이 두께감이 더 좋습니다.',
 '배랑 엉덩이를 잘 잡아주고',
 '핏도 좋습니다.',
 '색깔도 무난해서 괜찮습니다.',
 '하제 비만이라서 라지로 구매했는데 잘 맞습니다. ',
 '처음에는 손빨래했는데 물빠짐도 없고 좋았습니다. ',
 '길이감도 적당합니다.',
 '신축성이 좋아서',
 '입고 벗기가 무지 편한 이 레깅스',
 '귀여운 후드가 있는 스타일이 매력적이며',
 '직장인들 정장 위에 장착하셔도 어울리는 옷입니다. ',
 '저는 옷을 좀 박시하게 입는 스타일인데 이 패딩 오버핏이라서 저는 너무 좋습니다. ',
 '입자마자 생각보다 엄청 가벼워서 더 좋았고 ',
 '은은한 오트밀 색상이 너무 좋네요. ',
 '어떤 스타일에도 찰떡이라서 데일리 아우터로 딱인 이 제품',
 '일단 칼라가 있어서 화려하지 않으면서도 적당히 고급스러움을 자아냅니다. ',
 '스커트는 아래로 갈수록 넓어지는 디자인이라서 활동하기가 아주 편합니다. ',
 '상견례나 결혼식 등 중요한 자리에서 입을 수 있는 옷으로 딱입니다.',
 '두껍지도 얇지도 않아서',
 '봄 가을에 입기 좋습니다.',
 '출근복으로도 너무 좋은 이 원피스 어떠셨나요?',
 '일단 원 플러스 원의 구성이 너무 좋고 ',
 '색상도 검정과 곤색이라서 너무 좋습니다. ',
 '스판이라서 신축성도 너무 좋고',
 '두께감도 있어서',
 '따뜻합니다. ',
 '저에게 기장이 조금 짧은 느낌은 있지만 요즘 짧게 입는 추세인지라 괜찮네요.',
 '디자인이 양옆으로 지퍼가 있어서 유용하니 좋고 ',
 '가격도 착하게 구입해서 너무 좋네요.',
 '한 벌의 가격으로 두 벌을 주는데',
 '품질도 너무 좋네요.',
 '여성스러운 스타일이 느껴지는 베이직한 목폴라 니트 하나를 소개 해 드릴께요.',
 '바디를 따라 슬림하게 떨어지는 핏이 여성스럽습니다. ',
 '부드럽고 포근한 소재가 ',
 '착용했을 때 까슬거리거나 따갑지가 않아서 편안하게 입을 수 있는 니트입니다. ',
 '적당한 두께감이 있어서',
 '따뜻하고 좋습니다. ',
 '신축성도 좋아서 답답하지 않고 편안하니 좋네요. ',
 '레이어드로도 연출하기가 좋고',
 '스커트 바지등과도 너무나도 잘 어울리는 아이템입니다.',
 '스판기는 없지만 ',
 '뒷지퍼가 길어서 ',
 '손세탁시 물 빠짐도 거의 없고 옷변형도 없어서 너무 좋습니다. ',
 '사이즈도 정사이즈로 잘 맞고',
 '기장도 무릎 정도 오는 길이라서 딱입니다. ',
 '소매 부분의 디자인도 더 여성스러워 보여서 너무 좋고',
 '색상도 무난해서 더 좋은 원피스입니다.',
 '결혼식 복장으로, 출근복으로, 면접 보러 갈 때도 아주 좋을 듯합니다.',
 '가격대비 품질이 좋은 옷이니 ',
 '입고 벗기 편합니다.',
 '색상이 검정과 곤색으로 이루어져 있어서 무난해서 너무 좋습니다.',
 '두벌을 이 착한 가격에 주니 좋은데 ',
 '품질까지도 너무 좋습니다. ',
 '기모가 있어서 ',
 ' 따뜻하고',
 '무엇보다 신축성이 좋아서 활동하기 너무  좋습니다. ',
 '허리도 밴드로 되어 있어서 편하고',
 '두께도 도톰하고 좋네요.',
 '올 겨울 따뜻하게 잘 보낼거 같습니다. ',
 '일단 초겨울부터 한 겨울까지 쭉 입을 수 있는 아이템입니다.',
 '가볍기는 말할 필요 없이 너무 가볍고 ',
 '따뜻하기도 정말 따뜻하고 좋습니다. ',
 '저는 오트밀 색상으로 샀는데 예쁘네요.',
 '사이즈는 정사이즈이니 참고하세요.',
 '기장이 짧은 패딩이라서 활동하기에 너무 편해서 좋고 ',
 '오버핏이라서 좋습니다.',
 '다양한 패션에 매칭하기도 좋습니다.',
 '착용감이 우수하고',
 '깔끔하고 고급스러운 디자인을 가지고 있습니다. ',
 '세탁시에도 변형이 없어 오래 입을 수 있을 거 같아 좋네요.',
 '착용시 스마트하고 깔끔한 느낌을 주는 스타일입니다.',
 '사이즈는 넉넉해서 몸에 붙지 않아서 좋습니다. ',
 '기본티라서 기대가 없었는데 실물로 보니 디자인이 더 예쁩니다.',
 '아쉬운 점은 생각보다 소재가 살짝 얇습니다. ',
 '일단 핏이 날씬해 보이는  원피스라서 마음에 들었습니다.',
 '허리 벨트가 있는게 날씬해 보이는 효과가 있습니다.',
 '얌전해 보이는 스타일의 원피스라서 어른들이 좋아하실 원피스입니다.',
 '아주 추운 겨울에는 못입을 거 같고 ',
 '요즘 날씨에 입기에 딱입니다. ',
 '신축성이 너무 좋고 ',
 '원단도 고급스러워 보이고',
 '품질도 싼티 나지 않고 좋아 보입니다. ',
 '날씬해 보이는 원피스를 원하신다면 ',
 '디자인이 깔끔한 원피스라서 저는 개인적으로 괜찮고 좋았습니다.',
 '색상이 무난해서 괜찮은 제품이고',
 '허리 라인은 핏이 이쁘게 잘 빠졌습니다. ',
 '디자인 나름 깔끔해서 괜찮습니다. ',
 '소매에 있는 셔링이 더 여성스러워 보이고 좋습니다. ',
 '가격도 저렴해서 좋은데',
 '재질도 괜찮습니다.',
 '봄 가을에 입기 좋은 원피스인데 여름에도 괜찮을 듯 하네요. ',
 '사이즈 정사이즈이니 참고하세요.',
 '핏이 예쁜 원피스를 찾으신다면 구매해서 입어 보세요. ',
 '스판의 함량을 높인 중량감 높은 소재를 사용해서 구김은 적고',
 '텐션과 편안함이 두 배로 증가됐습니다.',
 '여유있는 핏으로 ',
 '착용시 더욱 편안한 느낌을 주고 ',
 '밑단으로 갈수록 좁아져',
 '다리가 더 길어보이게 해주는 것 같아 만족스럽네요. ',
 '색상도 라이트 베이지, 다크 네이비, 라벤더로 하나하나 색감이 다 이쁘네요.',
 'O의 컴포트 팬츠 3종으로 시원한 여름을 보낼수 있을 것 같습니다.',
 '힙과 엉덩이에 적당한 여유가 있어서',
 ' 통풍도 잘 되고',
 '피부에 붙지않아 더 시원한 느낌도 들어요. ',
 '신축성이 얼마나 좋은지 ',
 '활동하기가 너무 편안해서 좋으네요.',
 '핏도 예뻐서',
 '좋은 가격에 데리고 온 ',
 '세 가지 색상이 한 세트인데',
 '색감이 모두 예뻐서 어느것 하나 버릴 것이 없네요~ㅋㅋ',
 '그 중 라벤더 색상이 가장 사랑스러운 것 같아요. ',
 '은은한 연보라빛이 제 맘을 흔들어 놓았네요. ',
 ' 길이가 좀 길어 아쉽습니다. ',
 '다리가 좀 더 길었다면 더 이뿌게 입을 수 있었을텐데요 ㅜㅜ',
 '타이트하지 않고 살짝 여유로운 핏이라 편안하고 ',
 ' 부담없이 즐겨 입을 수 있는 굿템인 것 같아요.',
 '디자인은 한없이 평범하기 그지없는',
 '청바지 3벌이더라구요. ',
 ' 터키 오르타 원단이라고 굉장히 좋은 청바지라고 ',
 ' 다리에 착 감기는 듯한 착용감이 너무 좋더라구요.',
 '스판도 좋아서',
 '활동하기 편해서',
 '데일리로 입기에 너무 좋을 것 같습니다.',
 '시원한 느낌의 폴리원단을 사용해서',
 ' 청량감이 있어서 정말 좋아요.',
 ' 여유로운 핏감과',
 '높은 스판 함양으로 ',
 ' 활동하기도 편안해요.',
 '구김현상도 없어 더 좋았네요.',
 '얇은데도 ',
 '약간의 무게감이 있어',
 ' 실루엣이 착 내려 앉는 느낌이라 ',
 '피부에 감기지 않아서 만족스럽네요.',
 '쿠폰 사용으로 OOO에서 홈쇼핑보다 훨씬 저렴하게 구입하게 되어 좋았습니다.',
 '이렇게 좋은 가격에',
 '  청바지가 세 개라니 ',
 '세가지 색상 모두 색감도 너무 이쁩니다.',
 ' 다크 인디고가 젤로 맘에 드는데요, ',
 '기본 컬러 위에 올 핸드 브러쉬 터치를 이용해 은은한 하이라이트 효과를 줘서',
 ' 입체적으로 날씬해 보이는 핏까지 연출해 줘서 맘에 듭니다. ',
 '디자인은 지극히 평범하지만',
 '입으면 핏으로 살아나는 청바지라 꿀추천합니다~^^',
 '정말 슬림해 보이는 청바지를 발견했어요~',
 '뒤판으로 휘어진 패턴라인을 이용해서 뒷당김 효과를 줘서',
 '원래보다 작아 보이게 인사이즈 슬림라인으로 보이게 하는 것이라는데 정말 신기할 정도네요. ',
 ' 입었더니 다리가 정말 얇아 보여서 순간 제 다리가 아닌 줄 알았네요',
 '고탄성 라이크라 함유로',
 '신축성과 탄성이 좋아서',
 '더 꽉 잡아 주는 듯 해서 만족스러워요.',
 ' 이뿐 9부 라인이라',
 '굽높은 힐 뿐 아니라 운동화에도 잘 어울려서',
 '휘뚜루마뚜루로 즐겨 입을 수 있겠어요.',
 '허리가 짤록하게 보이도록 스트링 처리되어 있어',
 '핏도 너무 이뻐요.',
 ' 딱 맞는 사이즈라 이쁜데',
 '두꺼운 옷을 입으려면 한 치수 업해야 할 듯 합니다.',
 ' 소재가 생각보다 얇아서 좀 아쉽기는 하지만 ',
 '가벼워서 좋기는 해요.',
 '여름에 시원한게 ',
 ' 데일리로 입을 수 있는 린넨 팬츠 3종입니다.',
 '저렴한 가격에 ',
 ' 린넨 바지 3벌을 갖게 되어 너무 좋습니다',
 '전 린넨을 너무 사랑하거든요',
 '좀 부드러운 느낌입니다. ',
 '살짤 와이드핏이라',
 '걸을 때마다 살랑살랑 피부에 닿는 느낌이 부드러워서 기분이 좋네요. ',
 '밑단에 트임이 있는데 저는 갠적으로 이런 트임 디자인은 좀 별루인 것 같아요.',
 '넉넉하게 바지 3개가 한 세트라 이번 여름에는 다른 바지가 필요없을 것 같아요. ',
 '린넨 바지는 속옷이 비치지 않게 힙의 주머니를 소프트한 면으로 만들어서 걱정이 없어 좋았답니다.',
 '이렇게 세심한 디테일까지 신경을 쓰다니 말입니다. ',
 '베이지 컬러 바지에 힐 샌들을 신으면 출근복으로도 손상이 없을 정도로',
 '디자인이 아주 고급져 보여서 너무너무 좋습니다.',
 '허리는 자연스럽게 맞고',
 '힙과 허벅지는 여유로우며',
 ' 발목으로 갈수록 좁아지는 테이퍼드 형태의 보이핏이 정말 멋스러워요.',
 '색상도 라이트 인디고와 미디움 인디고 두 가지 색상 모두 색감이 좋고',
 '구제 느낌을 주기 위해 원단을 덧대고 스티치 한 것도 과하지 않고 딱 적당해 고급스러워 보입니다. ',
 '신축성도 좋아 활동하기가 편안하네요.',
 '좋은 가격에',
 '디자인이 이뿐 ',
 '보이핏 데님을 두 벌이나 갖게 되어서 행복합니다.',
 '가볍고',
 ' 시원한 착용감의 여름 소재로 된 OO 데님 리뷰예요. ',
 '신축성이 좋고',
 '얇아서',
 '더운 여름이어도 데님을 입을 수 있게 되어 너무 반가운 아이템입니다.',
 ' 키가 작은 저는 기장이 길어서 발목이 보이지도 않는다는 겁니다. ',
 '바지를 자르기엔 자체 디자인이 이뻐서 그냥 길게 입고 있어 많이 아쉽네요.',
 '기장 선택 가능하게 만들어 주시면 좋을 것 같아요.',
 '네추럴한 아이보리와 베이지톤으로',
 '잔잔하고 부드러운 체크 린넨 자켓이 이뿌네요.',
 '원단에 스판의 원료인 폴리를 섞어서 직조를 해서 구김이 적고 ',
 '활동하기도 편해서 매력적이네요.',
 '천연섬유의 내추럴함과 시원함에 합성섬유인 폴리를 섞어 실용성을 겸비한',
 '핑크, 베이지, 브라운 핀이 섞인 잔잔한 하운드투스로 여성스러우며 트렌디한 느낌을 주는',
 '레귤러 핏임에도 불구하고 입체패턴을 이용해 상체가 날씬해 보이는 효과가 나서 맘에 들어요',
 '가슴 포켓을 포함한 모든 주머니의 작은 디테일의 완성도가 높아서 고급스럽기까지 해요. ',
 ' 뒷부분 중앙 트임이 있어서 ',
 '더블버튼을 잠그고도 편안하게 활동이 가능하답니다.ㅋㅋ',
 '린넨원단이라 하니 시원한 것은 당연하겠지요.',
 '디자인이 예쁜 체크 린넨 자켓이 ',
 '좋은 가격으로',
 '약간의 폴리가 섞여 있는지',
 '적당한 신축성이 있어서',
 ' 입고 활동하기가 정말 편하네요.',
 '색감도 맘에 들고',
 '약간의 여유로운 핏도 제게 잘 어울리는 것 같아 좋아요. ',
 '바지나 치마 모두 잘 어울릴 것 같아서 코디가 편할 것 같네요.',
 '때와 장소를 가리지 않고 어디에나 잘 어울릴 것 같아서 유용하게 잘 입을 수 있을 것 같아 만족합니다.',
 '여섯가지 다양한 색상으로 구성된 ',
 '아주 저렴해서 사봤어요.',
 '색상도 어느 하나 나무랄것 없이 다 이쁘네요.',
 ' 색상이 다양하게 구성되어 있어',
 '옷에 따라 맞춰입기도 좋을 것 같습니다.',
 ' 신축성도 좋고 쫀쫀하기까지 해서',
 '살들을 잘 잡아주네요. ',
 '허벅지를 반 이상 덮는 롱한 기장에',
 '시원한 소재로 된 ',
 '여유로운 핏으로 하늘하늘하게 떨어지니',
 '밑단 양쪽의 트임도 시원한 청량감을 주네요. ',
 '아주 가벼워서',
 '한여름에도 입기에 부담이 없을 것 같아 실용적입니다. ',
 '색도 쿨감이 느껴지는 블랙이라 더 고급스럽게 느껴지고',
 '지퍼나 단추 같은 것의 여밈이 없는 것도 맘에 듭니다.',
 '착한 가격에',
 '따로 또 같이 가벼운 운동 및 야외활동 시에도 편안하게 착용이 가능한',
 '조거팬츠와 스트릿 무드의 후드 티셔츠가 너무 잘 어울리는 조합입니다.',
 '더운 여름과 아주 추운 겨울날만 제외하면 언제든지 즐겨 입을 수 있을 것 같아요. ',
 ' 세탁기 사용이 가능하다고 하니 어찌나 반갑든지~^^ ',
 '디자인의 트렌디함이 색상을 돗보이게 해주는 듯 합니다.',
 '깔끔한 디자인에',
 '트렌디한 컬러로',
 '아름다운 가격으로 나온',
 '기본컬러인 블랙을 필두로 베이지, 그린, 브릭 이렇게 네가지 색상이 있어 선택의 폭이 넓어 좋아요. ',
 '저의 원픽은 블루느낌이 많이 도는 그린색상이예요.',
 '어딘지 모르게 좀 묘한 느낌이 나서 좋더라구요.',
 '가볍고',
 '따뜻한 다운 코트를 장만하고 나니',
 '어디에나 잘 어울리는 멋진 다운 코트 하나 장만했네요.',
 '다운인데도',
 '가격이 저렴하게 나와서',
 '너무 부해보이지 않고 딱 떨어지는 실루엣이 세련돼 보이더라구요. ',
 '원단에서 나는 바스락 거림이 조금 거슬리기는 하지만 이 정도는 눈감아 줄만 합니다. ',
 '발수, 방풍 가공이 다 되어있어 아주 따뜻할 것 같긴 하지만 ',
 '생각보다 좀 얇아서',
 '아주 추운 날에는 좀 힘들 듯합니다.',
 '무릎 바로 위까지 오는 적당한 길이감까지 만족스러운 ',
 ' 바지가 4가지가 다 색깔이 이쁜데',
 '브릭색상은 튀지도 평범하지도 않는 트렌디한 컬러감과 ',
 '친환경적인 린넨 소재가 만나서 ',
 '너무나도 멋스러운 스타일을 연출하고 있더라구요. ',
 '여름에 입기에 딱 좋은',
 '가장 시원해 보이는 아이스 블루 컬러에 다양한 기법의 수작업 워싱 처리를 해서 프리미엄 데님의 완성도를 보여주는 듯 합니다.',
 '밑단도 자연스럽게 컷팅을 해서 자유분방해 보이면서도 세련되게 보이는 효과가 있어요.',
 ' 밑위도 살짝 업시켜서 더 편안하게 착용할 수 있도록 해주는 것 같아요. ',
 '타이트한 듯 무심하게 툭 떨어지는 일자핏도 맘에 듭니다.',
 '이렇게 핏이 세련돼 보이는 데님을 오랜만에 만나서 기분이 좋습니다.',
 '착용감이 편하고',
 '스타일리쉬하게 연출이 가능한',
 '엉덩이가 큰 제겐 그냥 슬림핏이네요.ㅎㅎ',
 '저 같은 체형이 부담없이 편하게 입을 수 있는 슬림핏 디자인 같아요. ',
 '날씬하신 분들은 너무 루즈하다고 느낄 수도 있을 것 같아요. ',
 '이 가격에 데님 3종이라니 ',
 '흡수성과 통기성까지 좋은 ',
 '면스판 소재라 쾌적하게 입을 수 있다고 하니 ',
 '가성비는 좋은 것 같아요. ',
 '뒤 포켓의 웨이브 자수로 힙업 효과를 낸 ',
 ' 적당한 두께감으로 얇으면서도',
 ' 비치지 않아서 맘에 듭니다.',
 ' 슬림 스트레이트 핏이 흰색과 만나서 정장바지의 느낌도 있어서 ',
 '하이힐과 매치한다면 잘 갖추어 입은 느낌도 나네요.',
 '때론 캐주얼하게 때론 세련되게 연출이 가능해서 다용도로 활용하기 좋고',
 '착시 효과로 인한 보정 효과를 볼 수 있어서 더 좋습니다. ',
 '뛰어난 신축성과 쫀쫀함으로',
 ' 다리 핏을 너무나도 이뻐 보이게 해 줘서 만족스러워요.',
 '6종 모두 색감이 맘에 듭니다. ',
 '기모가 있어서 따뜻해서 좋아요. ',
 '착용감이 좋아서',
 '조금 크게 주문하면 편안하게 홈웨어로도 좋을 것 같아요.',
 '여유있는 실루엣에',
 '좁은 더블버튼여밈으로 오픈시에도 배를 가려주는 디자인이라 좋습니다. ',
 ' 다양한 바지와 코디가 가능하고 ',
 '칼라 체크를 넣어 레드로한 캐주얼 감성을 업시켰는데요,',
 '제가 젤루 맘에 들었던 것이 이 체크였어요',
 ' 세 가지 체크가 다 맘에 들어 하나를 고를는 것이 쉽지 않았어요.',
 '심플한 디자인에',
 ' 은은한 체크로 화려함을 더한',
 '루즈핏 린넨자켓으로 한껏 멋부릴 생각에',
 '잘 어울릴 것 같은 스타일리쉬한 디자인이네요. ',
 '젤루 맘에 들었던 디자인인 그레이체크를 ',
 '전체적으로 그레이 모노톤의 글렌체크로 심심할 수 있는 색감을',
 '핑크와 블루로 포인트를 줘서 생기를 불어넣어 준 것 같아 정말 맘에 쏙 들어왔어요.',
 '가격도 좋아서 ',
 '천연소재의 내추럴한 느낌이',
 '여름철에 시원함을 줄 수 있어 더 없이 좋았어요.',
 '신축성도 좋고',
 '여유핏이라 활동하기가 정말 편한',
 ' 감쪽 같이 원단을 감싼 밴딩 처리로 ',
 '데님의 원형은 유지하면서 탄탄하게 허리를 잡아 주고',
 ' 착용감이 편안해서 좋으네요.',
 ' 착한 가격에',
 '데님 3종을 다 받을 수 있다니 ',
 '가성비가 짱입니다.',
 '슬림 스트레이트 핏으로 다리가 길고 날씬하게 보여서 더 만족스럽네요.',
 '편안해 보이는 핏감과',
 '발목이 보이는 크롭기장이 트렌디하고 보이네요.',
 '본인의 다리 길이에 맞춰서 롤업 사이즈를 조절하면 될 듯해서 길이에 대한 부담감이 없어 좋으네요.',
 ' 탄탄한 고탁성의 라이크라 스판사를 사용해서 신축성이 좋아 ',
 '입고 활동하기에 꺼리낌이 없어 무지 편안해서 좋아요.',
 ' 착용감이 편안하면서도',
 ' 멋스러운 핏의 데님을 내놓았네요.',
 '산뜻한 미디움 톤의 컬러감으로 사계절 내내 입기에 좋은 색상인 것 같아요.',
 ' 디스트로이드 워싱 처리가 과하지 않아서 좋으네요.',
 '아웃심의 네이비 컬러 파이핑이 옆모습을 더 날씬하게 보이게 해 줘서 너무 좋아요.',
 ' 어떤 티셔츠에도 잘어울리는 색상이라 ',
 '스판이 쫀쫀해서 무릎이 튀어나오지 않아 만족스러워요.',
 '단정한 펌프스 힐과 스타일링하여 포멀한 오피스 룩으로도 활용이 가능할 것 같아 ',
 '코디하기도 쉬울 것 같습니다.',
 '어디에나 잘어울리는 보이핏 데님을 득템했어요.',
 'OOOO의 보이핏 데님은 기장 걱정을 하지 않아도 되어서 좋으네요. ',
 ' 롤업 스타일이라 다리길이에 따라 롤업의 정도를 조절하면 되기에 만족스러워요. ',
 ' 발목이 핏 되는 앵글부츠에도 스니커즈에도 잘 어울리고',
 ' 타이트한 티셔츠나 맨투맨이나 자켓 아래에 입어도 잘 어울려서 ',
 '상황에 맞게 다 코디가 가능해 좋으네요. ',
 '하늘거리는 블라우스 같은 쉬폰 자켓입니다.',
 '얇아서 가방에 넣어 다니기도 편하고',
 '뚝 걸치기만 해도 멋스럽네요.',
 '생각보다 많이 비치지도 않아서 ',
 ' 안에 가볍게 나시티를 입고 입기에도 좋으네요.',
 '디자인이 멋스러우면서도',
 '실용적인 자켓을 구매하게 되어 너무 좋으네요.',
 '얇고 가볍게 입을 수 있는',
 '면스판 소재로 편하고',
 '여름에 데님은 좀 무리가 있는 듯 합니다.',
 '일반 데님보다는 얇은 편이긴 한데',
 '한여름에 입기엔 더울 것 같아요. ',
 ' 땀이 나니 슬림핏이 더 덥게 느껴지는 것 같아요. ',
 '신축성이 좋기는 한데',
 '쫀쫀하지는 않은 것 같아요.',
 '몇 번 입었더니 금방 늘어진 느낌입니다. ',
 '입으면 편하긴 한데',
 '넘 편~~하니 뱃살 잡아주지는 못하는거 같아 아쉽습니다.',
 '이 바지는 린넨에 레이온을 혼방해서 구김이 덜 가도록해서 불편함이 조금 감소가 되었네요. ',
 '좀 뻣뻣한 감이 있는 100% 린넨과 달리 약간 하늘거리는 느낌도 있어서 좋은 것 같아요.',
 '시원한 린넨 바지가 ',
 ' 올여름은 시원하게 잘 지낼수 있을 것 같아요.',
 '심플 라이프 스타일을 반영해 착용감이 편안하고',
 '유연한 실루엣의 린넨 팬츠 ',
 '3벌이나 생겨서',
 '아우터 또는 내피로 간절기부터 한겨울까지 활용도 만점인 ',
 '충전재가 덕다운이라 따뜻함을 물론이고',
 '카라가 없는 넥라인이라',
 ' 아우터로는 이너웨어로도 입기 좋아서 얼렁 샀어요',
 '하나씩 털이 삐져나오는 것은 어쩔수가 없나봐요..ㅜㅜ  ',
 '기계세탁도 가능하다고 하니',
 '편안하게 막 입을 수 있겠어요. ',
 '간절기에는 아우터로, 한겨울에는 코트나 점퍼의 이너로 활용할 수 있어 강추합니다.',
 '컬러가 아이보리에 민트 한방울 섞인 느낌이라 맘에 들고',
 '전체적으로 박음질은 좋습니다.',
 '길이는 종아리까지이고 기존 롱 트렌치 코트랑 같아서 수선은 안해도 될 것 같습니다.',
 '뒤가 멋스럽고 ',
 '색상도 너무 예쁩니다. ',
 '허리 벨트를 뺄수있어 좋습니다.',
 '소재가 아주 얇지만은 않아서',
 '가을에도 충분히 입을 듯 합니다.',
 '주름은 좀 가는 편이에요.',
 '디자인이 일단 흔하지 않아서 개성 있어 보여 좋습니다',
 '포인트 스티치 깔끔합니다.',
 '길이가 좀 길어 키가 작지 않은데도 길게 내려옵니다. ',
 '안에 위 아래 핏하게 입고 이 제품 걸치면 드레시할 듯 합니다.',
 '허리끈 한쪽이 고정된 것이 좀 불편하고요. ',
 '소매통이 너무 큽니다.',
 '좋은 가격에 구입했으니 만족입니다.',
 '스타일 납니다. ',
 '라글란 소매로 자연스럽게 떨어지는 어깨라인이 너무 예뻐 눈길을 사로 잡습니다. ',
 '기장도 살짝 길어서 스타일리시하게 연출하기 너무 좋아요.',
 '칼라도 흔하게 보이는 아이보리 칼라가 아니라서 꼭 한번 입어 보시기를 추천드립니다.',
 '오버핏이라 멋스럽게 떨어지는 라인이 예뻐요.',
 '너무 얇지도 두텁지도 않아서',
 '간절기에 활용도 높을 것 같습니다.',
 '구김이 거의 없는 실용적인 소재입니다. ',
 '핏은 오버핏으로 제일 작은 사이즈임에도  큽니다.',
 '소재는 힘있는소재로 툭 걸쳐 입기 멋스럽습니다.',
 '길이가 좀 긴편이라',
 '통바지에는 잘 안어울리는듯 하네요. ',
 ' 찬바람 불때 간절기용으로 활용성 있을듯 합니다.',
 '색상은 그린 컬러를 품고 있는 카키라 가을이 물씬 풍겨서 좋지만 ',
 '검정색 보다 더 어두워 보이는 느낌을 주는게 아쉽네요.',
 '소매는 한번 접어 입어도 예쁘게 단추 디테일이 있어서 마음에 들어요.',
 '허리 사이즈 때문에 한사이즈 크게 주문했더니 바지통이 좀 넓고 전체적으로 넉넉해서',
 '사무실 근무복으로는 손색없이 편하게 입을 것 같아요.',
 '안쪽 이중 잠금 단추가 조금 짧게 연결되어 있고',
 '허리부분이 살짝 두께감이 있어 앉으면 좀 불편합니다.',
 '안쪽기모가 톡톡해서 ',
 '겨울내 따뜻하게 입을것 같아요.',
 '신축성도 좋고 ',
 '기모 바지임에도 불구하고 가볍습니다. ',
 '핏은 사진처럼 너무 좋습니다.',
 '기모 바지라서 그런가 보다 감안하고 입습니다.',
 '블랙에 가까운 진한 네이비 색상 맘에 듭니다.',
 '기존 OOO 가다건이나 원피스의 네이비랑 큰 차이가 없어 코디하기 좋은 가디건이에요.',
 '어깨를 덮는 적당한 두께에',
 '소재도 까끌거림없이 부드럽고',
 '따뜻합니다. ',
 '가볍고 ',
 '따뜻해서 겨울에 아우터안에 입어도 되고',
 '가을에 원피스나 셔츠위에 걸쳐도 되서 활용도가 좋아요.',
 '디자인이 클래식해서 오래 입을 수 있을것 같아 좋습니다.',
 '길이가 약간 짧은듯 하지만',
 '품, 허리 모두 맞춤옷처럼 편해서 좋습니다',
 '스판이라 움직임이 편하고',
 '라인이 예뻐 만족합니다.',
 '기모도 두툼해서 ',
 '보온성이 좋아 겨울에 잘 입을 것 같습니다. ',
 '기모 바지라 무게감은 좀 있습니다.',
 '가격도 그리 나쁘지 않습니다.',
 '여러모로 활용성 높은 바지임에 틀림없습니다.',
 '사진보다는 색상이 밝은편인데',
 '볼 모양 프린트가 귀엽고 활달해 보여서 예쁩니다.',
 '안에 기모라 추운날 라운딩도 문제 없을 듯 하고 ',
 '활동하기 편해서 좋습니다. ',
 '가격도 나쁘지 않은데 ',
 '옷이 두툼하니 ',
 '스몰이 딱 맞는 스몰이 아니고, 그렇다고 또 너무 박시하게 나온 것도 아니라서, 적당하게 잘 나온 것 같아 만족합니다.',
 '겨울철에 입어도 따뜻하네요. ',
 '라운딩 나갈 때 입기 좋아요.',
 '다들 귀염성 있고 예쁘다고 칭찬 많이 하셨어요.',
 '기장이 짧아 더 큐트해 보이고 귀엽습니다.',
 '소재도 탄탄하니 좋고',
 '공 넣을수 있는 주머니도 센스 있게 있더라구요.',
 '오버핏이라 넉넉하게 입기 좋구요. ',
 '길이가 길지 않아서 오버핏이라도 괜찮은 듯 합니다.',
 '기모가 있어서 따뜻하고',
 '평상복으로도 입기 좋아요.',
 '소매가 좀 길지만 불편한 정도는 아니라서 괜찮습니다.',
 '라인 아주 예쁩니다.',
 '붓컷이라도 밑단이 크게 강조되지 않아서 크게 유행 타지 않을 것 같아 좋습니다.',
 '핏이 예뻐서 윗 옷 크게 신경쓰지 않고 티셔츠 하나 걸쳐도 스타일리쉬 하네요. ',
 '기모 안감이라 ',
 '한겨울 따듯하게 잘입을 것 같습니다. ',
 '밑위도 길어서 아주 편안합니다.',
 '진짜 흑검정이어서 더 예쁜듯 하네요.',
 '보온성과 스타일 둘 다 잡을 수 있는 기모 바지 소개해 드릴게요',
 '스타일 둘 다 잡을 수 있는 기모 바지 소개해 드릴게요',
 '스판이라 신축성이 좋아 엄청 편하고',
 '핏도 예쁩니다. ',
 '두꺼운 기모가 아니고 얇은 기모라 활동하기 편합니다.',
 '얇은 기모라 ',
 '맘에 드는 가격에 맘에 드는 바지에요. ',
 '사이즈는 기모 없는 바지보다 조금 작게 나온 듯합니다. ',
 '구매시 최소 한사이즈 업하셔야 할 듯 합니다.',
 '보온성 걱정하실 수도 있는데 충분히 따뜻합니다.',
 '플리스 원단의 집업 베스트는 어떤 이너 위에 입어도 잘 어울립니다.',
 '가벼운 아우터 안에 같이 입으니 핏이 너무 귀엽고',
 '따뜻해서 완전 반한 아이템입니다. ',
 '날 더 추워지면 패딩 안에 입기도 딱 좋은 두께로 ',
 '골프칠 때 말고 등산 갈 때도 잘 입을 것 같습니다.',
 '운동 갈 때도 운동복 위에 바로 입고 나갈 수 있어서 활용도 최고네요.',
 '한겨울에도 코트, 패딩안에 너무 잘 입을 수 있을 것 같은 아이템으로 강추입니다.',
 '지금 입기 딱 좋은',
 '라운딩 가기에도 좋은',
 '실물 디자인이 더 귀여운 옷입니다.',
 '흰색 깔끔하니 컬러감 좋습니다. ',
 '소재도 복실복실 감도 너무 좋고 ',
 '겨울까지 입을수 있을 것 같아요. ',
 '따뜻하고 ',
 '소재도 좋고 ',
 '주머니도 있어서 라운딩할 때 볼 주머니 따로 착용 안해도 되서 너무 편합니다.',
 '넉넉한 핏이어서 좋고 ',
 '방풍 효과 있는데도',
 '생각보다 무겁지 않고 좋습니다. ',
 '트렌디한 야상 아우터라서 편하게 입을 수 있는 점퍼입니다. ',
 '허리 선과 밑단 스트링으로 조절하여 실루엣 연출이 가능해서 좋은데 ',
 '허리선을 조이면 여성스러운 느낌으로 연출 가능하고,',
 '허리 스트링은 풀고 밑단만 조여서 연출하면 둥근 실루엣의 편안한 느낌으로 멋스럽습니다.',
 '카키 색상이 야상에 잘 어울리고 멋지네요.',
 '적당한 길이에 ',
 '봄, 가을에 잘 입을 것 같습니다.',
 '가격도 세일 중이라 나쁘지 않아요.',
 '바지 길이가 길까 살짝 걱정했는데 맞춤한 바지처럼 딱 맞아서 너무 좋았습니다.',
 '운동화 신고 끌리지 않는  길이고',
 '움직임이 편해서 좋습니다. ',
 '디자인이 다리가 길어 보이는 마법같은 팬츠입니다.',
 '길이감이 좋아 바지 안줄여서 얼마나 좋은지 몰라요~~',
 '사이즈도 딱 맞아 더욱 좋았어요.',
 'OO 오버핏 스트링 야상 점퍼 세일하길래 소개해 드리려고요. ',
 '보이는것보다는 얇고 ',
 '안감이 없지만 ',
 '재질 자체가 두께가 있어서 ',
 '따뜻하긴 합니다. ',
 '안감이 없는 건 좀 아쉬워요.',
 '가격 할인을 해도 비싼데',
 '이너 따뜻하게 입으면 늦가을까지 가능하긴 합니다.',
 '사이즈는 M으로 했으면 더 예뻤을 것 같긴 해요',
 '오버핏이라 S로 구매했는데 역시 야상은 크게 입는게 멋스럽네요.',
 '좀 오버핏이라서 모델처럼 예쁜 핏이 나오지는 않네요.',
 '오버핏이라 크긴 한데 그것도 나름 괜찮네요. ',
 '티셔츠나 셔츠 위에 널널하게 걸치는 것도 좋아요. ',
 '기장은 살짝 짧은 편입니다.',
 '소재 도톰하고 ',
 '따뜻해 보여요.',
 '관리만 잘하면 소재가 보풀도 거의 일어나지 않습니다.',
 '네이비 색상 깔끔하고 예뻐요.',
 '깔끔한 컬러감이 돋보이며',
 '와이드한 핏감과',
 '포켓 디테일을 더해 캐주얼한 느낌을 연출할 수 있는 팬츠에요',
 '가벼운 면 혼방 소재로 ',
 '시원해서 ',
 '데일리로 입기 좋은 아이템이네요.',
 '바지 핏이 정말 예뻐요.',
 '바지가 길 것 같아서 고민은 했는데 운동화 신고도 입을만 하네요.',
 '모델처럼 발목이 나와 보이거나 하지는 않지만 줄이지 않고 입을 수 있고',
 '디자인이 멋스럽게 느껴집니다.',
 '디자인이 와이드 팬츠라 다리가 길어보이고',
 '164인 제가 입었을때 기장감도 딱 좋습니다.',
 '약간 도톰해서 ',
 '와이드 팬츠가 너무 잘 빠져 디자인이 참 맘에 듭니다.',
 '포켓 디자인도 귀엽습니다.',
 '착용감 굉장히 편하고',
 '소재도 부드럽고 좋은 것 같습니다.',
 '구두나 스니커즈, 운동화에도 모두 잘 어울립니다. ',
 '늦가을까지 입기 좋을 듯 합니다. ',
 '보기에도 좋고 입어도 예쁜 와이드 팬츠',
 '클래식한 디자인인데 이쁘네요.',
 '일상복으로 입어도 괜찮을 듯 해요.',
 '날씨가 추워져서 지금 입기 좋을 것 같네요.',
 '편한 스타일이고',
 '평상시에도 입을 수 있고',
 '할인되서 가격도 나쁘지 않습니다.',
 '맨투맨에 입어도 얌홀이 커서 불편함 전혀 없을 듯 합니다',
 '넉넉한 핏이다 보니 ',
 '라운딩할 때도 편하게 입을 수 있을 것 같습니다.',
 '포근한 뽀글이가 아니라 약간 거친 느낌이에요.',
 '색상도 이쁘고 ',
 '소재도 부드럽고 좋습니다.',
 '세일할때 구매해서 가격도 나쁘지 않습니다. ',
 '기장이 크롭이라 귀엽고 길이가 짧지도 길지도 않고 적당합니다. ',
 '그래서 어디나 매치하기가 좋네요.',
 '기모 안감이 부드럽고 ',
 '따뜻해서 ',
 '착용시 느낌이 좋습니다.',
 '색상도 화면이랑 똑같아서 좋습니다.',
 '데일리룩으로 자주 입을 것 같네요.',
 '마침 OO 오버핏 스트링 야상 점퍼가 세일을 해서 가져와 봤어요.',
 '은은한 카키색 야상 점퍼라서 색상 멋스럽고 예뻐요. ',
 '소재가 빳빳하지 않아서 ',
 '자연스럽게 코디하기 좋습니다.',
 '할인을 많이 해서 저렴하게 샀네요.',
 'OO 제품이라서 할인을 해도 비싸긴 합니다. ',
 '소재가 좋고 ',
 '디자인 또한 다른 브랜드에 비해 더 멋스러운 것 같아요.',
 '젤 작은 사이즈도 크긴 합니다. ',
 '크게 입는 것 싫어하시는 이웃님들은  핏이 어정쩡하게 느끼실 수도 있습니다.',
 '따뜻하고 ',
 '편하게 막 입을 수 있는 옷입니다.',
 '55반 사이즈 입는데 후드 입고 M 사이즈 입으니 딱 맞네요.',
 '헐렁한 느낌 원하시면 L 입으셔야 해요.',
 '이것 저것 할인해서 저렴하게 구입했습니다.',
 '가격이 29만원 대인데 소재가  그 정도는 아닌 듯 해요.',
 '정상가로 사긴 너무 비싸네요.',
 '색상은 예뻐요.',
 '맨투맨이나 후드에 레이어드하면 포인트로 좋습니다.',
 '무거워요. ',
 'xs했는데 목폴라 입고 이쁘게 맞네요.',
 '제일 직은 사이즈로 선택하길 잘했네요.',
 '요즘 같은 날씨에 입기 딱 좋습니다.',
 '좀 더 날 풀리면 반팔에 입어도 따뜻해서 좋고 ',
 '생각보다 더 가벼워서 안입은 듯 하다네요.',
 '약간 때탄 거 같은 색상이지만 오히려 화이트보다 때 덜탈 거 같아서 좋습니다',
 '안에 받쳐입기에 딱 좋습니다. ',
 '디자인 이쁘네요.',
 '색깔이 팥죽색이라 해야 하나, 뭔가 애매하네요. ',
 '디자인이 웰메이드 느낌이 나서 만족스럽습니다.',
 '이 색상이 좀 더 코코아 빛 돌면 인기폭발이었을거 같네요. ',
 '늦가을부터 초봄까지 이너로 잘 입을 수 있겠어요.',
 '연베이지같은 화이트 색상이라 오히려 좋습니다',
 '쿨톤 하얀 얼굴인데 색상 괜찮네요. ',
 '160, 55~55반인데 S사이즈가 넉넉하네요. ',
 '보기싫게 크지 않고 안에 도톰하게 입을 수 있을 것 같아서 맘에 듭니다.',
 '품은 큰데 ',
 '팔 올렸을 때 겨드랑이, 어깨부분이 끼지 않고 편해서 좋습니다.',
 '똑딱이 단추가 잘못하면 뜯어질 것 같아서 조심해서 입어야겠습니다.',
 '저렴한 다운제품에 ',
 '품질이 괜찮아서  ',
 '경량보다 더 가벼운 거 찾으시는 분들은 만족하실 거예요.',
 '후리스의 따뜻함에 짜증났던 마음이 사르르륵 녹았습니다. ',
 '기대를 저버리지 않게 품질이 좋습니다.',
 '디자인도 귀엽고 ',
 '정말 도톰해서 ',
 '아주 따뜻합니다.',
 '안에 방열내의 껴입고 이거 입으면 한겨울도 거뜬할 거 같네요. ',
 '이 가격에 좋은 물건을 팔다니 역시 이 브랜드 제품은 믿고 사야 된다니까요. ',
 '실제 주된 컬러는 진한 카키에 가까운데 예쁩니다.',
 '옷 디자인은 클래식한 무드로 잘 만들어졌고 ',
 '다양한 컬러의 원사가 어우러져 실제로 보는 색상이 더 예쁘네요. ',
 '소매만 조금  길고',
 '핏은 예쁘네요. ',
 '두께는 약간 도톰해서',
 '원단 정말 좋고 ',
 '색감도 회색 풀색 섞인 느낌인데 피부톤이 예뻐 보여서 완전 좋습니다. ',
 '가벼우면서 ',
 '따뜻해서 좋습니다.',
 '다른 캐시미어100 제품과 비교시 퀄리티 떨어지고',
 '많이 까끌거리네요. ',
 '캐시미어 특유의 솜털 느낌은 전혀 없고그냥 질 좋은 울느낌이라서',
 '가격이 비싼듯 하네요. ',
 '디자인은 이쁘고 ',
 '핏도 날씬해 보여서 구매 결정 했습니다.',
 '몇 번 입고 나니 무릎이 많이 나오고 바지는 금방 핏이 흐트러지고 후줄근해집니다.ㅠㅠ ',
 '가격대비 따뜻하고 좋습니다. ',
 '옷이 너무 하드하고',
 '무겁지만 너무 무거워 못입겠다 정도는 아닙니다.',
 '색감은 약간 베이지 도는 아이보리라서 맘에 듭니다.',
 '모델 OOO씨의 핏과는 많이 다르지만 그래도 이 정도 핏이면 만족입니다. ㅋㅋ',
 '이 가격에 이 정도면 성공이죠.!!',
 '디자인이 너무 예쁘고 ',
 '마감 처리도 깔끔하고 좋습니다.',
 '브라운에 가까운 진한 베이지 같아서 정말 곰같은 색상입니다.ㅠㅠ ',
 '겉옷 55사이즈 입는데 전반적으로 핏도 여유있게 딱 맞고 좋네요.',
 '가격이 다운되었을때 저렴하게 잘 구입해서 더 좋습니다. ',
 '양면이라서 샀는데 한쪽으로만 입을 거 같네요. ',
 '디자인이 드롭 숄더라서 어깨가 조금 좁아 보이는 느낌입니다.^^',
 '핏은 생각보다 루즈합니다.',
 '내가 입을땐 뚱뚱해 보였는데 ',
 '확실히 학생인 딸이 입으니깐 루즈해도 예뻐서 딸아이가 입는다고 가져 갔습니다. ',
 '지금처럼 환절기 교복 위에다 착용하거나 평상복에다도 착용해도 좋습니다.',
 '팔 부분은 차가운 천으로 돼 있어서 아쉽네요.',
 '저렴해서 ',
 '미듐사이즈가 너무 딱 맞아서 라지로 교환 받으니 살짝 크지만',
 '핏이 더 우아해 보이고 ',
 '두터운 이너도 입을 수 있어서 좋습니다.',
 '이런 스타일의 자켓은  클래식하면서 현대적인 미가 공존하는 세련미의 극치라서 맘에 듭니다.',
 '앞으로 더욱 추워지면 자주 입기 어렵겠지만 ',
 '내년 봄과 가을 뿐만 아니라 몇 년이고 오래도록 애용 할 생각이네요.',
 '털이 적어도 너무 적습니다.',
 '안감이 비칠 정도로 적네요. ',
 '털빠짐이 장난 아닙니다. ',
 '검은 스웨터 입으면 빠진 털때문에 난리납니다.',
 '몇번 빨면 털 다 빠져서 구멍이 송송 날 듯 해요.ㅠㅠ',
 'OO 리버시블이고 처음 가격이 19만원대여서 좋을 줄 알았는데 완전 실망이네요',
 '싸이즈는 좀 큰편인데 한치수 작으면 전체 길이가 짧아져서 이상할 듯 합니다. 비추입니다. ㅠㅠ',
 '사진보다 더 이쁜 진보라빛 와인이라 붉은기 없어서 진짜 이쁘고 맘에 드네요. ',
 '이 양면 무스탕 코트는 모가 24% 혼용 돼 있어서 작년겨울 입었을때 휠씬 따뜻했었답니다.',
 '길이도 길어서 좋습니다.',
 '차콜이랑 와인중에 와인을 선택한건데 받고 보니 잘 선택해서 만족합니다.',
 '뒤집어 입었을 때도 디자인이 어색하지 않고 예뻐서 맘에 드네요. ',
 '좋은옷 착한가격에 재구매해서 더 만족스럽습니다.',
 '후드끈 칼라감으로 스포티하고 이쁩니다.',
 '안쪽 면은 안감있어서 교복같이 어두운색 옷을 입더라도 털빠짐이 없습니다.',
 '가격 혜택까지 넘 좋게 잘 샀습니다.',
 '사이즈 85구입했는데 루즈핏이라서 90사이즈로 입더라도 넉넉히 예쁠것 같습니다.',
 '운동할 때 휘뚜루 마뚜루 입기 좋습니다.',
 '체크 패턴이 아주 작아서 촌스럽지 않고 세련된 느낌입니다',
 '가디건에 청바지에 입으면 케주얼하게 어울리고',
 ' 슬랙스랑 입으니 스타일이 더 살아나서 너무너무 만족해요. ',
 '구매시 주의하실 점으로는 팔 부분이 넓지 않다는 사실을 기억해야 하는 부분입니다',
 '  맨투맨이나 후드 입으면 팔 부분이 좀 낄 것 같은 느낌입니다',
 '티나 블라우스, 가디건이랑 입는게 가장 이쁠 것 같네요.',
 ' 저는 55사이즈 입는데 s가 잘 맞았어요',
 '코디에 따라서 캐주얼과 정장을 넘나들 수 있는 실용적인 제품이랍니다',
 ' 완전 슬림핏은 아니고 약간 넉넉한 테이퍼드 핏이라 더욱 맘에 들어요.',
 '에나멜 로퍼랑 매치하니 매니쉬룩 찰떡 완성이라 기분 좋네요',

In [123]:
test_aspect = []
for i in range(len(test_data)):
    for j in range(len(test_data['Aspects'][i])):
        test_aspect.append(test_data['Aspects'][i][j]['Aspect'])
test_aspect

['디자인',
 '디자인',
 '색상',
 '가격',
 '색상',
 '핏',
 '촉감',
 '소재',
 '핏',
 '길이',
 '기능',
 '무게',
 '길이',
 '활용성',
 '품질',
 '디자인',
 '기능',
 '활용성',
 '사이즈',
 '소재',
 '디자인',
 '활용성',
 '착용감',
 '기능',
 '핏',
 '신축성',
 '가격',
 '품질',
 '착용감',
 '색상',
 '품질',
 '활용성',
 '소재',
 '기능',
 '사이즈',
 '길이',
 '디자인',
 '착용감',
 '길이',
 '색상',
 '두께',
 '기능',
 '사이즈',
 '디자인',
 '디자인',
 '디자인',
 '길이',
 '색상',
 '사이즈',
 '마감',
 '기능',
 '활용성',
 '착용감',
 '두께',
 '기능',
 '핏',
 '색상',
 '사이즈',
 '품질',
 '길이',
 '신축성',
 '착용감',
 '디자인',
 '활용성',
 '디자인',
 '무게',
 '색상',
 '활용성',
 '디자인',
 '디자인',
 '활용성',
 '두께',
 '기능',
 '활용성',
 '제품구성',
 '색상',
 '신축성',
 '두께',
 '기능',
 '길이',
 '디자인',
 '가격',
 '가격',
 '품질',
 '디자인',
 '핏',
 '소재',
 '촉감',
 '두께',
 '기능',
 '신축성',
 '활용성',
 '활용성',
 '신축성',
 '길이',
 '품질',
 '사이즈',
 '길이',
 '디자인',
 '색상',
 '활용성',
 '품질',
 '착용감',
 '색상',
 '가격',
 '품질',
 '소재',
 '기능',
 '신축성',
 '디자인',
 '두께',
 '기능',
 '기능',
 '무게',
 '기능',
 '색상',
 '사이즈',
 '길이',
 '디자인',
 '활용성',
 '착용감',
 '디자인',
 '품질',
 '디자인',
 '사이즈',
 '디자인',
 '두께',
 '핏',
 '디자인',
 '디자인',
 '기능',
 '기능',
 '신축성',
 '소재',
 '품질',
 '핏',
 '디자인',
 '색상',
 '핏',
 '디자인',
 '디자인',
 '가격',
 '소재',
 '기능',
 '사이즈',
 '핏',
 '소재',
 '착용감',
 '핏',
 '착용감',
 '디자인',
 '핏',
 '색상',
 '기능',
 '핏',
 '기능',
 '기능',
 '신축성',
 '활용성',
 '핏',
 '가격',
 '제품구성',
 '색상',
 '색상',
 '색상',
 '길이',
 '길이',
 '핏',
 '활용성',
 '디자인',
 '제품구성',
 '소재',
 '착용감',
 '신축성',
 '착용감',
 '활용성',
 '소재',
 '기능',
 '핏',
 '소재',
 '착용감',
 '소재',
 '두께',
 '무게',
 '핏',
 '착용감',
 '가격',
 '가격',
 '제품구성',
 '색상',
 '색상',
 '색상',
 '핏',
 '디자인',
 '핏',
 '핏',
 '기능',
 '핏',
 '핏',
 '소재',
 '신축성',
 '착용감',
 '길이',
 '활용성',
 '활용성',
 '디자인',
 '핏',
 '사이즈',
 '사이즈',
 '두께',
 '무게',
 '기능',
 '활용성',
 '가격',
 '제품구성',
 '소재',
 '촉감',
 '디자인',
 '촉감',
 '디자인',
 '제품구성',
 '디자인',
 '디자인',
 '활용성',
 '디자인',
 '사이즈',
 '사이즈',
 '디자인',
 '색상',
 '디자인',
 '신축성',
 '가격',
 '디자인',
 '제품구성',
 '무게',
 '소재',
 '신축성',
 '두께',
 '기능',
 '길이',
 '길이',
 '길이',
 '색상',
 '디자인',
 '소재',
 '활용성',
 '소재',
 '디자인',
 '핏',
 '디자인',
 '디자인',
 '착용감',
 '소재',
 '디자인',
 '가격',
 '소재',
 '신축성',
 '착용감',
 '색상',
 '핏',
 '활용성',
 '활용성',
 '제품구성',
 '가격',
 '색상',
 '제품구성',
 '활용성',
 '신축성',
 '기능',
 '길이',
 '소재',
 '핏',
 '디자인',
 '무게',
 '활용성',
 '색상',
 '디자인',
 '가격',
 '활용성',
 '제품구성',
 '기능',
 '소재',
 '디자인',
 '디자인',
 '색상',
 '가격',
 '색상',
 '색상',
 '색상',
 '무게',
 '기능',
 '활용성',
 '소재',
 '가격',
 '핏',
 '소재',
 '기능',
 '두께',
 '기능',
 '길이',
 '색상',
 '색상',
 '소재',
 '디자인',
 '기능',
 '색상',
 '디자인',
 '착용감',
 '핏',
 '핏',
 '착용감',
 '디자인',
 '핏',
 '디자인',
 '핏',
 '제품구성',
 '기능',
 '소재',
 '가격',
 '디자인',
 '두께',
 '소재',
 '핏',
 '활용성',
 '활용성',
 '기능',
 '신축성',
 '핏',
 '색상',
 '소재',
 '착용감',
 '활용성',
 '핏',
 '디자인',
 '활용성',
 '디자인',
 '색상',
 '색상',
 '디자인',
 '색상',
 '핏',
 '디자인',
 '디자인',
 '색상',
 '색상',
 '가격',
 '소재',
 '기능',
 '신축성',
 '핏',
 '디자인',
 '기능',
 '착용감',
 '가격',
 '제품구성',
 '가격',
 '핏',
 '핏',
 '길이',
 '길이',
 '신축성',
 '착용감',
 '착용감',
 '핏',
 '색상',
 '색상',
 '디자인',
 '색상',
 '신축성',
 '활용성',
 '활용성',
 '활용성',
 '길이',
 '디자인',
 '활용성',
 '활용성',
 '활용성',
 '디자인',
 '두께',
 '핏',
 '소재',
 '활용성',
 '디자인',
 '활용성',
 '두께',
 '소재',
 '기능',
 '두께',
 '기능',
 '기능',
 '신축성',
 '품질',
 '품질',
 '착용감',
 '기능',
 '소재',
 '소재',
 '기능',
 '기능',
 '착용감',
 '디자인',
 '제품구성',
 '활용성',
 '소재',
 '디자인',
 '활용성',
 '품질',
 '소재',
 '착용감',
 '활용성',
 '색상',
 '마감',
 '길이',
 '디자인',
 '색상',
 '디자인',
 '소재',
 '기능',
 '소재',
 '디자인',
 '디자인',
 '길이',
 '활용성',
 '디자인',
 '사이즈',
 '가격',
 '디자인',
 '디자인',
 '길이',
 '색상',
 '핏',
 '두께',
 '기능',
 '소재',
 '사이즈',
 '소재',
 '길이',
 '활용성',
 '기능',
 '색상',
 '색상',
 '디자인',
 '사이즈',
 '활용성',
 '디자인',
 '두께',
 '소재',
 '기능',
 '신축성',
 '무게',
 '핏',
 '소재',
 '색상',
 '색상',
 '두께',
 '소재',
 '기능',
 '무게',
 '기능',
 '활용성',
 '디자인',
 '길이',
 '사이즈',
 '신축성',
 '핏',
 '소재',
 '기능',
 '무게',
 '가격',
 '활용성',
 '색상',
 '디자인',
 '소재',
 '착용감',
 '가격',
 '두께',
 '사이즈',
 '기능',
 '활용성',
 '디자인',
 '길이',
 '소재',
 '디자인',
 '핏',
 '길이',
 '소재',
 '활용성',
 '길이',
 '핏',
 '디자인',
 '핏',
 '소재',
 '기능',
 '길이',
 '색상',
 '기능',
 '디자인',
 '신축성',
 '핏',
 '두께',
 '소재',
 '가격',
 '사이즈',
 '사이즈',
 '기능',
 '소재',
 '핏',
 '기능',
 '두께',
 '활용성',
 '활용성',
 '기능',
 '기능',
 '활용성',
 '디자인',
 '색상',
 '소재',
 '기능',
 '기능',
 '소재',
 '디자인',
 '핏',
 '기능',
 '무게',
 '착용감',
 '디자인',
 '디자인',
 '디자인',
 '색상',
 '길이',
 '기능',
 '가격',
 '길이',
 '길이',
 '착용감',
 '디자인',
 '길이',
 '사이즈',
 '가격',
 '두께',
 '디자인',
 '소재',
 '기능',
 '디자인',
 '가격',
 '기능',
 '사이즈',
 '사이즈',
 '핏',
 '사이즈',
 '활용성',
 '길이',
 '소재',
 '기능',
 '소재',
 '색상',
 '색상',
 '핏',
 '디자인',
 '소재',
 '기능',
 '활용성',
 '핏',
 '길이',
 '길이',
 '디자인',
 '디자인',
 '길이',
 '두께',
 '디자인',
 '디자인',
 '착용감',
 '소재',
 '활용성',
 '기능',
 '디자인',
 '디자인',
 '활용성',
 '기능',
 '디자인',
 '활용성',
 '가격',
 '사이즈',
 '핏',
 '착용감',
 '소재',
 '색상',
 '소재',
 '가격',
 '길이',
 '활용성',
 '소재',
 '기능',
 '촉감',
 '색상',
 '활용성',
 '가격',
 '색상',
 '소재',
 '활용성',
 '가격',
 '가격',
 '소재',
 '디자인',
 '사이즈',
 '핏',
 '기능',
 '착용감',
 '사이즈',
 '사이즈',
 '가격',
 '소재',
 '가격',
 '색상',
 '활용성',
 '무게',
 '사이즈',
 '사이즈',
 '기능',
 '기능',
 '무게',
 '색상',
 '활용성',
 '디자인',
 '색상',
 '디자인',
 '색상',
 '기능',
 '색상',
 '색상',
 '사이즈',
 '사이즈',
 '사이즈',
 '사이즈',
 '마감',
 '가격',
 '품질',
 '무게',
 '기능',
 '품질',
 '디자인',
 '두께',
 '기능',
 '기능',
 '가격',
 '색상',
 '디자인',
 '색상',
 '길이',
 '핏',
 '두께',
 '소재',
 '색상',
 '무게',
 '기능',
 '품질',
 '촉감',
 '소재',
 '가격',
 '디자인',
 '핏',
 '품질',
 '기능',
 '소재',
 '무게',
 '색상',
 '핏',
 '가격',
 '디자인',
 '마감',
 '색상',
 '사이즈',
 '가격',
 '디자인',
 '디자인',
 '핏',
 '핏',
 '핏',
 '활용성',
 '소재',
 '가격',
 '사이즈',
 '핏',
 '활용성',
 '디자인',
 '기능',
 '활용성',
 '소재',
 '소재',
 '품질',
 '품질',
 '품질',
 '품질',
 '사이즈',
 '색상',
 '기능',
 '길이',
 '색상',
 '디자인',
 '가격',
 '색상',
 '품질',
 '가격',
 '사이즈',
 '활용성',
 '디자인',
 '활용성',
 '활용성',
 '사이즈',
 '사이즈',
 '활용성',
 '사이즈',
 '활용성',
 '디자인',
 '활용성',
 '사이즈',
 '길이',
 '소재',
 '소재',
 '사이즈',
 '소재',
 '기능',
 '소재',
 '기능',
 '핏',
 '신축성',
 '핏',
 '착용감',
 '기능',
 '색상',
 '가격',
 '색상',
 '색상',
 '활용성',
 '착용감',
 '색상',
 '색상',
 '품질',
 '소재',
 '핏',
 '디자인',
 '핏',
 '가격',
 '소재',
 '착용감',
 '기능',
 '소재',
 '길이',
 '착용감',
 '핏',
 '신축성',
 '착용감',
 '기능',
 '활용성',
 '색상',
 '디자인',
 '가격',
 '착용감',
 '두께',
 '착용감',
 '촉감',
 '디자인',
 '두께',
 '소재',
 '기능',
 '가격',
 '착용감',
 '기능',
 '기능',
 '가격',
 '착용감',
 '활용성',
 '활용성',
 '기능',
 '두께',
 '디자인',
 '품질',
 '사이즈',
 '사이즈',
 '사이즈',
 '활용성',
 '소재',
 '신축성',
 '핏',
 '디자인']

In [ ]:
okt = Okt()

def okt_tokenize(text):
    return okt.morphs(text)

vectorizer_okt = TfidfVectorizer(
    tokenizer = okt_tokenize,   
    ngram_range = (1, 2),   
    min_df = 1,   
    lowercase = False    
)

le = LabelEncoder()

Y_asp_le = le.fit_transform(Y_asp)

In [ ]:
model = LinearSVC(random_state=42)

pipe_aspect = Pipeline(
    [
        ('vector', vectorizer_okt),
        ('clf', model)
    ]
)
pipe_aspect.fit(text, Y_asp)
pred_aspect = pipe_aspect.predict(test)
accuracy_score(test_aspect, pred_aspect)

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

0.7439490445859872

In [128]:
model = LinearSVC(random_state=42)

pipe_aspect = Pipeline(
    [
        ('vector', vectorizer_okt),
        ('clf', model)
    ]
)
pipe_aspect.fit(text, Y_asp_le)
pred_aspect = pipe_aspect.predict(test_text)

le.inverse_transform(pred_aspect)
print("예측된 Aspect:", le.inverse_transform(pred_aspect))

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

예측된 Aspect: ['색상' '디자인' '길이']

In [ ]:
test_sentiment = []
for i in range(len(test_data)):
    for j in range(len(test_data['Aspects'][i])):
        test_sentiment.append(test_data['Aspects'][i][j]['SentimentPolarity'])
test_sentiment

{'-1', '0', '1'}

In [133]:
okt = Okt()

def okt_tokenize(text):
    return okt.morphs(text)

vectorizer_okt = TfidfVectorizer(
    tokenizer = okt_tokenize,   
    ngram_range = (1, 2),   
    min_df = 1,   
    lowercase = False    
)

In [134]:
pipe_sentiment = Pipeline(
    [
        ('vector', vectorizer_okt),
        ('clf', model)
    ]
)
pipe_sentiment.fit(text, Y_sent)
pred_sentiment = pipe_sentiment.predict(test)
accuracy_score(test_sentiment, pred_sentiment)

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

0.8840764331210191

In [ ]:
pipe_sentiment = Pipeline(
    [
        ('vector', vectorizer_okt),
        ('clf', model)
    ]
)
pipe_sentiment.fit(text, Y_sent)

pred_sentiment = pipe_sentiment.predict(test_text)

In [118]:
print("예측된 Sentiment:", pred_sentiment)

예측된 Sentiment: ['1' '1' '1']

In [ ]:
y_combined = [f"{a}_{s}" for a, s in zip(Y_asp, Y_sent)]

pipe = Pipeline([
    ('tfidf', TfidfVectorizer(tokenizer=okt_tokenize, ngram_range=(1,2))),
    ('clf', LinearSVC(random_state=42))
])

pipe.fit(text, y_combined)

pred_combined = pipe.predict(test_text)
pred_aspect = [p.split('_')[0] for p in pred_combined]
pred_sentiment = [int(p.split('_')[1]) for p in pred_combined]

for t, a, s in zip(test_text, pred_aspect, pred_sentiment):
    print(f"문장: {t}, Aspect: {a}, Sentiment: {s}")

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

문장: 색상이 마음에 든다, Aspect: 색상, Sentiment: 1
문장: 설명에 비해 옷이 두껍진 않다, Aspect: 소재, Sentiment: 1
문장: 길이가 너무 길지도 않고 짧지도 않다, Aspect: 길이, Sentiment: 1

In [145]:
df['RawText'][0]

'안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 딱 좋을 인생 경량 패딩 하나 소개해 드릴게요.  다 함께 go go go~~  제가 입어보고 좋아서 엄마께도 구매해드렸네요. 딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서 어디서 샀냐고 많이들 물어보는 옷입니다.  엄마도 제가 입은 것 보시더니 탐내셔서  주문해드렸어요. 영하로 내려가는 날씨에는 이것만 입기엔 얇지만 초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요. 색상도 디자인도 무난해서 사무실에 두고 입기도 좋고, 평소에 가볍게 나갈때 코디하기도 좋아요. 앞으로 코트를 입거나 할때 안에 내피로 활용하기도 딱일 듯요! 맘같아선 색깔별로 쟁이고 싶습니다.  20대와 50대 모두 아우르는 디자인이 무난하고 깔끔하면서 고급스러운 옷 추천합니다~~~  설명 끝! 좀 도움이 되셨나요? 그러면 좋아요 꾹 눌러 주시고 전 이만 총총총~~ 항상 여러 이웃님들께 감사드립니다. '