In [1]:
import pandas as pd

In [3]:
df = pd.read_json('../data/인터뷰/ckmk_d_bm_f_n_169087.json')
df

,version,dataSet,rawDataInfo
info,1,"{'date': '20230116', 'occupation': 'BM', 'chan...",NaN
question,1,{'raw': {'text': '지원자님께서 가지고 계신 나만의 스트레스 해소법이 ...,"{'fileFormat': 'wav', 'fileSize': 664398, 'dur..."
answer,1,{'raw': {'text': '저는 저 혼자 시간을 보내는 것을 우선적으로 하고요...,"{'fileFormat': 'wav', 'fileSize': 1900238, 'du..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, info to answer
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   version      3 non-null      int64
 1   dataSet      3 non-null      object
 2   rawDataInfo  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [5]:
# read_json을 통해 json파일을 로드했는데? 데이터 형태가 데이터프레임에 최적화x
# 답변의 데이터, 답변의 요약데이터를 추출 -> kobart 모델을 이용해서 요약 학습
# json 파일을 dict형태로 변환 -> 데이터 추출
import json

In [6]:
# 파일을 로드해서 dict형태로 변환
with open('../data/인터뷰/ckmk_d_bm_f_n_169087.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [8]:
type(data)

dict

In [9]:
from pprint import pprint

In [11]:
pprint(data)

{'dataSet': {'answer': {'emotion': [],
                        'intent': [{'category': 'attitude',
                                    'expression': '',
                                    'text': ''}],
                        'raw': {'text': '저는 저 혼자 시간을 보내는 것을 우선적으로 하고요. 예를 들어서 '
                                        '혼자 산책을 한다든지 아니면 혼자 카페를 간다든지 아니면 혼자 코인 '
                                        '노래방을 간다든지 해서 스트레스를 해소하는 편입니다. 물론 남들과 '
                                        '만나면서 시간을 보내는 것도 굉장히 좋아하지만요. 아무래도 내 '
                                        '혼자만의 시간이 있어야 어느 정도 생각 정리도 되고 그러면서 내 '
                                        '안에 있던 응어리도 절로 풀러지는 그런 것을 경험하게 되었습니다. '
                                        '그리고 코인 노래방이나 이런 곳에 가면은 아무래도 제가 노래 부르는 '
                                        '것도 좋아하고 그리고 노래를 부르면서 그런 소리가 웅웅거리고 또 '
                                        '소리를 지른다는 거에 대해서 해소감도 있는 것 같고요. 그래서 저는 '
                                        '일단 혼자만의 시간을 보내는데 뭐 혼자서 노래방을 가거나 아니면 '
                                        '혼자서 카페를 가거나 그런 식으로 스트레스를 해소한다 라고 말씀을 '
                                        '드릴 수 있을 것 같습니다.',
                                'wordCount': 107},
                        'summary': {'text': '저는 혼자 시간을 보내는 것을 우선적으로 하며, 혼자 산책을 '
                                            '하거나 혼자 카페를 간다든지 또는 혼자 노래방을 간다든지 '
                                            '해서 스트레스를 해소하는 편입니다. 혼자의 시간이 있으면 '
                                            '생각 정리도 되고 제 안에 있던 응어리도 저절로 풀러지는 '
                                            '것을 경험하게 되었습니다.',
                                    'wordCount': 36}},
             'info': {'ageRange': '-34',
                      'channel': 'MOCK',
                      'date': '20230116',
                      'experience': 'NEW',
                      'gender': 'FEMALE',
                      'occupation': 'BM',
                      'place': 'ONLINE'},
             'question': {'emotion': [],
                          'intent': [],
                          'raw': {'text': '지원자님께서 가지고 계신 나만의 스트레스 해소법이 있으신지 '
                                          '있으시다고 한다면 왜 그러한 방법으로 스트레스를 해소하려고 '
                                          '하셨는지 이야기해 주실 수 있으실까요',
                                  'wordCount': 19}}},
 'rawDataInfo': {'answer': {'audioPath': '/Mock/01.Management/Female/New/ckmk_a_bm_f_n_169087.wav',
                            'channelCount': 1,
                            'duration': 59380,
                            'fileFormat': 'wav',
                            'fileSize': 1900238,
                            'samplingBit': 16,
                            'samplingRate': '16kHz'},
                 'question': {'audioPath': '/Mock/01.Management/Female/New/ckmk_q_bm_f_n_169087.wav',
                              'channelCount': 1,
                              'duration': 20760,
                              'fileFormat': 'wav',
                              'fileSize': 664398,
                              'samplingBit': 16,
                              'samplingRate': '16kHz'}},
 'version': '1.0'}

In [25]:
data['dataSet']['answer']['raw']['text']

'저는 저 혼자 시간을 보내는 것을 우선적으로 하고요. 예를 들어서 혼자 산책을 한다든지 아니면 혼자 카페를 간다든지 아니면 혼자 코인 노래방을 간다든지 해서 스트레스를 해소하는 편입니다. 물론 남들과 만나면서 시간을 보내는 것도 굉장히 좋아하지만요. 아무래도 내 혼자만의 시간이 있어야 어느 정도 생각 정리도 되고 그러면서 내 안에 있던 응어리도 절로 풀러지는 그런 것을 경험하게 되었습니다. 그리고 코인 노래방이나 이런 곳에 가면은 아무래도 제가 노래 부르는 것도 좋아하고 그리고 노래를 부르면서 그런 소리가 웅웅거리고 또 소리를 지른다는 거에 대해서 해소감도 있는 것 같고요. 그래서 저는 일단 혼자만의 시간을 보내는데 뭐 혼자서 노래방을 가거나 아니면 혼자서 카페를 가거나 그런 식으로 스트레스를 해소한다 라고 말씀을 드릴 수 있을 것 같습니다.'

### kobart 복습
1. 인터뷰 폴더 안에 있는 json 파일들을 로드
    - 답변에 대한 데이터들을 하나의 리스트로 생성
    - 답변 요약에 대한 데이터들을 하나의 리스트로 생성
2. 위에서 생성된 데이터들 중 train 데이터는 처음부터 100번째 데이터까지
3. 마지막에서 10번째부터 마지막까지의 데이터를 validation 데이터로 사용
4. train, test 데이터를 DatasetDict 형태로 변환
5. tokenizer와 model을 로드하여 데이터를 학습하고 검증
    - input의 최대 사이즈 : 512
    - output의 최대 사이즈 : 256
6. test 데이터를 생성 : 원본의 리스트에서 200번째의 데이터를 이용하여 요약을 생성

In [14]:
from glob import glob

In [46]:
import numpy as np
from datasets import Dataset, DatasetDict
# 문장 간의 검증 지표를 만들어주는 라이브러리
import evaluate
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
glob('../data/인터뷰/*.json')

['../data/인터뷰\\ckmk_d_bm_f_n_169087.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169088.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169393.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169394.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169395.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169443.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169453.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169454.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169455.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169456.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169513.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169553.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169554.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169555.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169556.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169557.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169559.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169560.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169561.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_169562.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170083.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170084.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170085.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170086.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170087.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170088.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170089.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170090.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170091.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170092.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170403.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170404.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170405.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170406.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170407.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170408.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170409.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170410.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170411.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170412.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_170422.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171753.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171754.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171756.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171757.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171758.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171759.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171760.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171761.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171762.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171843.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171844.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171845.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171846.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171847.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171848.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171849.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171850.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171851.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171852.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171993.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171995.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171997.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171998.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_171999.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172001.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172002.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172613.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172614.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172615.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172616.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172617.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172618.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172619.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172620.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_172621.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173653.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173763.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173764.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173765.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173766.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173767.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173768.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173769.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173770.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173771.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_173772.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174133.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174135.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174136.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174137.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174139.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174140.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174141.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174213.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174214.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174215.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174216.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174217.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174218.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174219.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174221.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174222.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174343.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174345.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174346.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174347.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174349.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174351.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174353.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174355.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174357.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174358.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174359.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174361.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174362.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174653.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174654.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174753.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174754.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174755.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174756.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174757.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174903.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174904.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174905.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174906.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174907.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174963.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174964.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174965.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174966.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174967.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174973.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174974.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_174975.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175013.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175014.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175015.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175016.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175017.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175018.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175019.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175020.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175021.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175022.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175083.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175084.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175093.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175094.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175095.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175096.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175097.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175099.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175100.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175101.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175102.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175123.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175124.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175193.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175194.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175195.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175197.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175198.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175200.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175201.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175202.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175263.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175264.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175265.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175266.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175267.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175268.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175269.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175270.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175271.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175272.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175293.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175294.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175295.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175296.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175297.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175298.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175363.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175364.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175365.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175366.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175367.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175368.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175369.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175370.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175371.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175372.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175744.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175745.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175746.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175747.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175748.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175750.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175751.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175923.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175924.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175925.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175926.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175927.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175929.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175931.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_175932.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176203.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176205.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176206.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176207.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176208.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176209.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176210.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176211.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176212.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176393.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176394.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176396.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176397.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176399.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176400.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176401.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_176402.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177763.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177764.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177765.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177766.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177767.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177770.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177771.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_177772.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178053.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178054.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178055.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178056.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178057.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178058.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178059.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178060.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178061.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178062.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178194.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178195.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178196.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178197.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178198.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178200.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178201.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178202.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178334.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178335.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178336.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178337.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178338.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178339.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178340.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178341.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178342.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178383.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178384.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178385.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178386.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178387.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178388.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178389.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178390.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178391.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178392.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178463.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178464.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178465.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178466.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178467.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178468.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178469.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178470.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178471.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178472.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178523.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178524.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178525.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178526.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178527.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178528.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178529.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178530.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178531.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178532.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178703.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178704.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178705.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178707.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178708.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178709.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178710.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178711.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178843.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178844.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178845.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178846.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178847.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178848.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178849.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178850.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178851.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_178852.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180093.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180095.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180096.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180133.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180223.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180224.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180226.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180863.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180864.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180865.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180866.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180867.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180868.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180869.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_180871.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181173.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181174.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181175.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181176.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181177.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181178.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181179.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181180.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181181.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181182.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181433.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181434.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181435.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181437.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181438.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181439.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181440.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181441.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181442.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181553.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181554.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181555.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181556.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181557.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181558.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181559.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181560.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181561.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181562.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181763.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181764.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181765.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181766.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181767.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181768.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181769.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181770.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181771.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_181772.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182033.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182034.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182035.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182036.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182037.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182038.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182039.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182040.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182041.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182042.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182163.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182164.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182165.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182166.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182167.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182168.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182169.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182170.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182171.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182172.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182663.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182664.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182666.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182667.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182668.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182669.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182670.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182671.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182672.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182833.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182834.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182836.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182837.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182838.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182841.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_182842.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183023.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183024.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183025.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183026.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183027.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183028.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183029.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183031.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183032.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183613.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183614.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183615.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183616.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183617.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183618.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_183724.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184143.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184144.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184145.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184146.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184147.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184148.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184173.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184223.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184224.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184225.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184226.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184227.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184228.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184229.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184563.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184564.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184565.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184566.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184567.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184568.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184569.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184570.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184571.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184572.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184904.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184905.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184906.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184907.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184908.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184909.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184910.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184911.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184912.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184963.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_184964.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185323.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185373.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185374.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185375.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185633.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185634.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185635.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185643.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185653.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185703.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185704.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185823.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_185883.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_187553.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_187554.json',
 '../data/인터뷰\\ckmk_d_bm_f_n_187555.json',

In [16]:
file_list = glob('../data/인터뷰/*.json')

In [34]:
texts = []
summary = []

for file_name in file_list:
    with open(file_name, 'r', encoding='utf-8') as f:
        data2 = json.load(f, strict=False)
        text = data2['dataSet']['answer']['raw']['text']
        summ = data2['dataSet']['answer']['raw']['text']
        texts.append(text)
        summary.append(summ)

In [35]:
texts

['저는 저 혼자 시간을 보내는 것을 우선적으로 하고요. 예를 들어서 혼자 산책을 한다든지 아니면 혼자 카페를 간다든지 아니면 혼자 코인 노래방을 간다든지 해서 스트레스를 해소하는 편입니다. 물론 남들과 만나면서 시간을 보내는 것도 굉장히 좋아하지만요. 아무래도 내 혼자만의 시간이 있어야 어느 정도 생각 정리도 되고 그러면서 내 안에 있던 응어리도 절로 풀러지는 그런 것을 경험하게 되었습니다. 그리고 코인 노래방이나 이런 곳에 가면은 아무래도 제가 노래 부르는 것도 좋아하고 그리고 노래를 부르면서 그런 소리가 웅웅거리고 또 소리를 지른다는 거에 대해서 해소감도 있는 것 같고요. 그래서 저는 일단 혼자만의 시간을 보내는데 뭐 혼자서 노래방을 가거나 아니면 혼자서 카페를 가거나 그런 식으로 스트레스를 해소한다 라고 말씀을 드릴 수 있을 것 같습니다.',
 '네 여러 관계자와 협력을 해서 네 성공적으로 일정을 수행해 본 적이 있었고요. 아무래도 사람이 많다 보니까 저의 생각을 먼저 고수하는 것보다는 그들의 의견을 먼저 듣는 것에서 부터 시작했습니다. 아무래도 서로가 뭐라고 해야 될까요. 각자 보이는 생각이 다 맞다고 우기면은 거기서 더 잘 나아갈 수가 없더라고요. 그래서 들어봤을 때 이 사람의 이야기를 먼저 듣고 만약에 이게 아니다 라는 느낌이 들었을 때는 제가 이 사람 말에 우선 이해와 공감을 먼저 했습니다. 이러한 상황에서 당신의 말은 이렇군요 저도 그럴 것 같습니다 하지만 저희는 이런 결과물로 내야 되는데 여기에서 이 상황만 생각하면 조금은 어려울 것 같아요. 그래서 우리가 이런 비 상황도 함께 고려해서 좋게 결과를 만들어 봅시다 라는 식으로 조금은 애둘러서 하지만 강하게 말을 했었고 그로 인해서 협력이 잘 되었던 기억이 납니다. 네 그런 식으로 진행을 해서 굉장히 잘 수행되었다고 말씀드릴 수 있을 것 같습니다.',
 '대부분은 왠지 전사나 마법사를 고를 것 같은데요. 저는 조금은 독특하게 힐러 역할을 해보고 싶습니다. 힐러는 어떻게 보면은 굉장히 소위 게임하는 사람들 사이에서는 게임을 굉장히 못하는 그러니까 너는 내 피나 채워줘라 약간 이런 역할로 볼 수 있는데요. 사실 어떻게 보면은 없어서는 안 될 가장 중요한 역할이라고 생각하거든요. 이 캐릭터에 체력이 따르기 전에 채워 넣어야 되는 그런 센스도 있어야 되고요. 그러면서 이 사람들이 안전한 위치에 내가 또 봐 놓고 들어가야 됩니다. 또 그러한 순발력도 있어야 되고 그리고 아무래도 아까 전에 제가 이야기한 것처럼 없으면 안 될 존재라서 그래도 누군가는 해야 되는 일이잖아요. 네 그래서 저는 힐러 역할을 해서 다른 전사라던지 마법사들의 그런 피를 채워주는 그런 없어서는 안 될 존재가 되고 싶습니다.',
 '네 소통 능력을 키우기 위해서는 저는 일단 말을 많이 해야 된다 라고 생각을 하는데요. 동아리에 가입을 하거나 어떤 커뮤니티에 등록을 하는 게 가장 효과적이라고 말씀드릴 수 있을 것 같습니다. 하지만 우리가 요즘 코로나시대다 보니까 뭐 쉽게 할 수 없는 것들도 있잖아요. 거기에서는 아마 제가 하는 방법으로는요. 어떠한 상황을 가정하고 거기에 맞게 이야기하는 혼잣말 하는 거를 약간 저는 연습을 했었습니다. 예를 들어서 내가 어디에 가서 이 물건을 사야 되는데 직원이 없다. 그래서 이 직원을 찾기 위해서 나는 또 다른 누군가에게 물어봐서 길을 찾아가야 된다. 뭐 대략적으로 어 그 조금은 엉뚱하게 제가 말씀을 드렸는데요. 그런 식으로 제가 어떠한 상황을 가정하고 거기에 맞게 대처하는 것을 여러 번 연습했습니다. 그러다 보니까 소통 능력도 덩달아 좋아지구요. 단어 선택이라든지 아니면 또 거기에 따른 뭐 추임새라고 할까요. 네 그런 것도 넣는 게 조금 늘어서요. 저는 방금 제가 말한 이 방법을 네 많이 사용을 했었고 추천을 하는 바입니다.',
 '네 과거에 프로젝트를 수행했던 경험이 있구요. 저는 리더보다는 주변 사람들을 챙기고 그 사람들의 의견을 듣는 그런 조언 역할을 했습니다. 이렇게 들으면은 굉장히 어 저기 어떤 그 상황에 사람일까 라는 생각이 드는데요. 예를 들어서 사람은 다양하게 있고요 그 사람들의 생각도 다 다양합니다. 그래서 간혹 그들이 충돌하는 경우도 있는데요. 그런 상황에서 저는 중재자의 역할을 했었고 어떻게 하면 이 상황을 해결할지 그리고 어떻게 하면 이걸 잘 해결해서 우리가 좋은 결과를 이끌어낼 수 있을지 고민하는 역할에 있었다 라고 보면 좋을 것 같고요. 실제로 두 팀원들이 싸워서 사이가 굉장히 안 좋아질 뻔한 적이 있었는데 제가 직접 그 두 분의 이야기를 듣고 그 두 분의 입장에서 그 상황을 고려해서 이야기를 전해 줬더니 잘 해결됐던 경험도 있습니다. 예를 들어 아 너는 지금 이 상황에서 에이 라고 생각했구나 너희 입장에서는 그럴 수 있어 그런데 비는 지금 이런 입장이라서 그렇게 이야기를 했대 어찌 보면 둘 다 잘못한 게 아니고 말이 그냥 조금 다르게 나온 거잖아 그러니까 함께 이거를 잘 풀어나갔으면 좋겠다. 뭐 이런 식으로 약간 어떻게 보면 중재하는 그런 역할을 담당해줬습니다.',
 '최근 경험해 본 서비스들 중에 가장 인상 깊게 본 서비스는 무엇인가요 왜 인상 깊었었는지 설명해 주세요 라는 질문에 대한 저의 답변입니다. 얼마 전 제가 아르바이트 하는 곳에 청소가 필요해서 청소 업체에 의뢰했던 건이 있었습니다. 보통 일반적인 보이는 곳만 청소하는 것이 보통인데 그 업체는 우리가 생각하지 못한 곳까지 꼼꼼하게 복도 틈새마다 찌든 때와 흠집으로 인한 오염물을 미세하게 흡입되어 있어 정밀 관리가 필요했었는데 계단과 유리창 등 특별 서비스를 받아 모든 분이 만족한 서비스를 받는 기분이 들었습니다. 단순한 청소도 최선을 다하는 모습을 보고 저도 모든 일에 대충하려는 마음이 바뀌었었습니다. 어떠한 일이 주어지더라도 서비스 서비스 정신을 발휘하여 최선을 다할 것입니다. 그분의 정성 어린 본인의 일에 최선을 다하는 모습이 꽤 인상적이었습니다.',
 '네 저는 팀장보다는 팀원에 더 잘 맞을 것 같고요. 이렇게 이야기하는 이유는 제가 조별 과제라던지 아니면은 그런 커뮤니티 상황에서 그런 조별 조별의 조장보다는 조원 역할을 많이 했었습니다. 하지만 제가 다른 분들과 차별화된 것은 어떠한 의견들이 있을 때 그것을 조율하고 다른 사람들의 의견을 듣고 거기에 맞춰서 조장님께 이야기해서 함께 나아가는 그런 역할을 했었는데요. 때로는 서로의 생각이 강한 팀원들이 있다면 그것을 중재하는 중재자 역할을 하기도 했습니다. 그리고 실제로 그것은 팀장님과 여기서는 팀장님이고 이제 뭐 조원 조장님들과 제가 그런 식으로 협엽을 했었을 때는 더 긍정적으로 잘 끝났던 경험들이 많은데요. 그래서 저는 모든 이 것들을 이것들 이것이라면 조금 웃기네요. 네 이 팀원들을 끌고 가는 자기 주장이 강한 팀장보다는 그 안에서 사람들과 대화를 많이 나누고 상황을 조율하는 그런 팀원이 잘 맞다 라고 말씀해 드릴 수 있을 것 같습니다.',
 '네 저는 경영이나 사무 쪽에서 더 중요한 것은 팀워크라고 생각이 듭니다. 창의성이라는 것은 만약에 예술가 였다면 제가 창의성이라고 대답을 했을 것 같습니다. 왜냐하면 작가들은 자신의 생각과 자신의 지식이 굉장히 뚜렷하게 빛이 나는 직종 중에 하나 인데요. 저희는 어떻게 보면 하나의 회사이고 이 회사는 거대한 팀이라고 생각이 듭니다. 그래서 이를 수행하기 위해서는 내 근처에 있는 팀원들과 네 입을 맞추어야 잘 나갈 수 있고 회사의 발전을 위해서는 우리들이 열심히 한 마음 한 뜻이 되어야 더 성장할 수 있다 라고 생각하기 때문입니다. 그래서 저는 창의성보다는 팀워크가 더 중요하다고 말씀드릴 수 있을 것 같습니다.',
 '네 저는 가장 기억에 남는 거짓말은 괜찮지 않으면서 괜찮아 라고 이야기했던 것 같습니다. 내가 힘든 걸 남한테 알리고 싶지 않고 굳이 나의 부정적인 에너지를 전달해 주기 싫어서 괜찮아 라는 말을 입에 달고 살았었는데요. 요즘에는 네 마냥 괜찮다고 말하지만은 않습니다. 왜냐하면 실제로 이 상대가 내가 괜찮은 줄 알았는데 내가 너무 힘들어 하는 모습을 보고 아 얘가 진짜로 괜찮아서 괜찮은 게 아니었구나 하고 미안해하면서 힘들어 하는 모습을 봤거든요. 어떻게 보면은 나는 이 사람이 위해서 거짓말을 했는데 그 거짓말 때문에 상처받는 걸 보니 저도 마음이 안 좋더라고요. 그래서 지금은 예전처럼 뭐 뭐든지 힘들어도 아 괜찮아 이러지는 않고 솔직함과 그리고 어느 정도의 거짓말을 섞어서 괜찮다 라고 이야기하는 편입니다.',
 '네 우선은 이 면접은 끝까지 다 봐야겠죠. 왜냐하면은 이것은 우리의 하나의 시간이고 그리고 이 시간에 정말 중요한 약속이고 일정이니까요. 저는 이 일정을 잘 끝내고 거창한 것은 하지 않을 것 같습니다. 그냥 소소하게 일상 속에서 뭐 행복을 느낄 것 같은데요. 예를 들어서 가족들과 밥 맛있는 밥을 먹으러 간다든지 아니면 영화를 본다든지 아니면 밤 산책을 한다든지 그런 식으로 소소하게 하루를 마무리 지을 것 같습니다. 거창하게 무언가를 하는 것보다는 때로는 소소한 일상에서 오는 행복을 찾는 걸 저는 더 중요하게 생각을 해서요. 그리고 거창하게 뭘 할려고 하면은 오히려 기억에 남는 것도 없을 것 같습니다. 그래서 저는 당장 뭐 할 거 라는 라는 답변에는 일단은 면접을 아주 멋있게 마무리 짓도록 하겠습니다 라고 답변해 드릴 수 있을 것 같습니다.',
 '네 십 년 후에 이 회사에서 저를 계속 써주고 계신다면 저는 계속 다니고 있을 것 같고요. 아무래도 저는 그때쯤 되면은 몸에 근육이 굉장히 많이 있을 것 같습니다. 제가 틈틈이 시간 날 때마다 홈트레이닝을 하거든요. 눈에는 바로 보여지지 않아도 그래도 이것들이 쌓이면서 몸에 라인이 잡히고 내가 더 건강해진다는 느낌이 들어서 아무래도 저는 계속해서 운동을 하고 있을 것 같거든요. 그래서 조금 더 건강하고 근육이 많은 제가 되어 있을 것 같고 그리고 현재 다닌 회사에서는 어느 정도의 위치 위치 안정된 위치에 있지 않을까 라는 생각이 듭니다. 그리고 그 위치에 되면 제 밑으로 들어 오는 다른 분들을 위해서 많은 이야기들도 해주고 그리고 너무 나 때에 만의 이야기 하지 않는 소위 꼰대 같지 않는 그런 상사로 남아서 있을 것 같다는 생각이 듭니다.',
 '저는 협업을 할 때 사교성이 굉장히 좋은 편 중에 한 명입니다. 저는 업무를 하는 데 있어서 같이 동료와 융화되는 그런 능력들을 가장 중요하게 생각을 하는데요. 그 이유는 저희가 근무를 할 때 혼자 하는 업무들이 아니고 대부분의 업무들이 다른 동료 혹은 선배들과 함께하는 근무이기 때문에 때로는 우리가 갈등이 있을 수도 있지만 그러한 갈등들을 잘 해결하는 능력들이 어 우리가 업무를 하는 데 있어서 굉장히 중요하다 라고 생각합니다. 저 같은 경우에는 사교성을 키우기 위해서 조금 처음에는 어색하더라도 먼저 사근사근하게 다른 동료들에게 말을 거는 편입니다. 그 이유는 제가 말을 걸면 사소한 것이라도 서로 정보 교환을 하게 되고 그 정보 교환 속에서 우리가 어떤 사람이라는 걸 서로 알게 되고 그리 그리고 나아가서 아이스 브레이킹 할 수 있는 그런 어 시간들을 가질 수 있기 때문에 저는 조직 융화를 위해서 먼저 동료나 혹은 선배들에게 좀 자세하게 말을 걸면서 친해지려고 노력하는 편입니다.',
 '제가 대학을 다닐 때 어떤 마케팅 회사에서 인터을 한 경험이 있는데요. 그 인턴 경험을 하면서 여러 가지 실무들을 익힐 수도 있었지만 저는 컴퓨터 활용 쪽을 공부하기로 마음먹었습니다. 그 이유는 제가 현업에서 근무를 하다 보니까 엑셀 프로그램을 정말 많이 활용한다 라는 생각을 했습니다. 그래서 기존에는 컴퓨터 활용이라는 자격증을 꼭 왜 해야 하는지 그 부분에 대해서 중요도를 깨닫지 못했었는데요. 실제로 인턴을 하다 보니까 현업에서는 이러한 자격증이 있으면 너무 잘 활용할 수 있겠다. 어 꼭 일일이 수기로 붙여 놓는 데이터가 있더라도 내가 쿼리나 혹은 음 피봇 테이블들을 활용할 수 있는 엑셀 기능을 잘 활용하면 업무에 도움이 되겠다 라는 생각이 들어서 그때 당시에 인턴을 했던 경험을 바탕으로 컴퓨터 학원에 등록을 하고 또 나아가서 컴퓨터 활용 이급 자격증을 땄구요. 지금은 더 추가로 공부를 해고 해보고자 싶어서 일 등급을 딸려고 지금 현재 공부 중에 있습니다.',
 '제가 일을 하면서 가장 어려울 것으로 지금 현재 예상되는 부분은 다른 음 동료들과 빠르게 친해질 수 있을까에 대한 부분입니다. 사실 제가 어 다른 어 졸업 이후에 다른 일들을 여러 가지 했었는데요. 그 과정에 있어서 지금 직무와는 연관된 부분이 아니기 때문에 신입으로 지원을 하게 되었습니다. 그래서 물론 저보다 나이가 많으신 분들도 있을 수도 있고 혹은 적으신 분들도 있을 수도 있지만 어 신입의 입장으로서 저보다 분명히 업무 내용에 대해서 많이 알고 있을 선배들이 있기 때문에 그런 선배들을 항상 존중하는 자세 그리고 항상 낮은 자세로 배우려는 자 마음가짐을 가지고 제가 잘 모르는 부분이 있다면 많이 물어보고 혹에 제가 도움 드릴 수 있는 부분이 있다 라면 정말 성심성의껏 도움을 드리는 자세로 다른 동료들과 함께 융합하고 또 다른 부서와 함께 협업하는 자세로 근무하는 근무를 진행하고 싶습니다.',
 '회사에 들어와서 제가 꼭 만나 뵙고 싶은 선배는 저에게 잔소리를 많이 해줄 수 있는 선배입니다. 그 이유는 저는 잔소리도 후배에 대한 관심에서 주는 그런 큰 관심과 그리고 시간을 투자하는 부분이라고 생각을 합니다. 만약 후배에게 전혀 관심이 없다 라면은 자기 업무를 나눠주거나 혹은 옆에 앉혀서 가르칠 그럴 의지도 없을 것이라고 생각합니다. 그렇지만 만약에 정말 후배를 아끼는 마음이 있다라면 그 후배가 지금 어떤 업무들을 하고 있는지 잘 살펴보고 만약에 자기가 도움 줄 수 있는 부분이 있다 라면은 여러 가지 도움 주기 위해서 아마 그 과정에서 잔소리들을 굉장히 많이 하실 수도 있는데요. 저는 그렇게 잔소리를 하는 과정이 자기 후배에 대한 굉장히 큰 관심이라고 생각하기 때문에 저는 저를 많이 지켜봐 줄 수 있고 그리고 저에 대해서 많은 피드백과 가끔 기분이 나쁠 수도 있지만 어 냉철한 비판 있는 그런 의견들을 제시해 줄 수 있는 선배를 선호합니다.',
 '네 제가 현재 지원한 곳에 의 본사 말고도 여러 가지 다양한 계열사가 있다는 것에 대해서는 잘 알고 있습니다. 그렇지만 제가 지주사인 본사에 지원을 하게 된 이유는 지주사만이 가지고 있는 음 여러 가지 경험과 노하우에 대해서 배우고자 하는 의지가 있기 때문입니다. 저 같은 경우에는 신입이기 때문에 아직 여러 가지 실무 경험은 없지만 다양한 분야에서 한 어 굉장히 밑바닥부터 배우고자 하는 의지가 강합니다. 그래서 지금 지주사의 경우에는 여러 가지 계열사가 진행하고 있는 프로젝트에 대해서도 음 현황 파악을 잘 할 수가 있고 또 나아가서 그룹 전체에 공감이 되는 그런 미션이라든지 혹은 방향성에 대해서 제시를 하는 곳이기 때문에 제가 신입으로서 배울 수 있는 그런 업무들이 훨씬 더 많다 라고 생각이 되었습니다. 그래서 저는 여러 가지 분야에 대해서 배워볼 수 있는 기회야말로 저에게 가장 큰 어 보상이라고 생각하기 때문에 지원하게 되었습니다.',
 '입사 후에 쉬운 일 그리고 어려운 일이 분명히 닥칠 텐데요. 저는 그렇게 여러 가지 일들이 쏟아질 때 우선순위를 분배할 수 있는 능력이 업무 능력 중에 정말 중요하다 라고 생각합니다. 그 이유는 우리가 업무들이 쏟아지게 되면 여러 가지 역할들을 음 동시 다발적으로 시행해야 될 수가 있는데요. 그럴 때 지금 당장 처리해야 될 긴급한 일 혹은 장기적으로 아직 시간을 좀 두고 처리해야 될 아직 덜 중요한 일들이 있을 수 있기 때문에 이런 여러 가지 업무들이 닥칠 때 우선순위를 분류를 해서 진행을 할 수 있는 부분이 어 한정된 시와 시간을 가장 잘 활용할 수 있는 부분이라고 생각합니다. 그렇기 때문에 저는 처음에 신입으로 들어가게 된다면 지금 현재 흘러가는 일의 방향성이 어떻게 흘러가는지 먼저 전체적인 방향을 파악해 본 이후에 제 업무들을 하나하나 시행해 보도록 하겠습니다. 그리고 그 내용들은 스케줄표로 정리를 하면은 놓치는 부분이 하나도 없을 것이라고 생각하고 있습니다.',
 '제가 해보았던 다양한 커뮤니케이션 중에서는 제가 경험해보지 않 않은 그런 어플이나 경험 내용을 바탕으로 고객을 설득하는 게 가장 힘들었었습니다. 제가 대학 시절에 아르바이트를 한 적이 있었는데요. 당시에 어느 날 장애인분이 오셔서 장애인용 어플이 이용이 안 된다 여기 백화점에서는 이 어플을 사용하려면 어떻게 해야 되는지를 한번 질문을 해 주셨습니다. 그렇지만 저는 처음에 장애인 전용 어플이 우리 백화점에 있었는지조차를 몰랐기 때문에 너무 당황했었습니다. 그렇지만 저는 먼저 고객님께 저 역시도 어 어떻게 활용하는지는 모르겠지만 제가 한번 업 어 인터넷에 검색해 본 뒤에 응대를 해 드리겠다 잠시만 기다려 달라 라고 말씀을 드렸고 실제로 구글과 네이버에서 어떻게 하면 이 장애인용 어플 음성 지원 어플을 사용할 수 있는지를 한번 검색해 보았고 이를 토대로 고객님의 핸드폰이 안드로디 안드로이드 폰이셔서 권한 설정을 한번 허용해 본 뒤에 그 어플을 활용하실 수 있도록 직접 도움을 드렸던 경험이 가장 기억에 남습니다.',
 '제가 생각하는 좋은 회사란 동료들끼리 서로 피드백을 주고받는 문화가 강력한 곳이 정말 발전 가능성이 있는 좋은 회사라고 생각을 합니다. 그 이유는 제가 기존에 서비스업에서 어 대학 시절에 간략하게 아르바이트를 했었는데요. 동료들끼리 서로 피드백을 해 줄 때마다 더 좋은 성과 그리고 고객들을 더 잘 대할 수 있는 그런 응대 아이디어가 나온다 라고 생각했습니다. 저는 경영 지원 업무 역시도 마찬가지라고 생각합니다. 저희가 함께 근무하는 동료들끼리 서로 치열하게 피드백을 주고받을 수 있는 조직 문화가 형성이 된다 라면 저희는 그 안에서 스스로 한계를 이겨내고 어 새롭게 고객들을 잘 응대할 수 있고 혹은 동료들과 더 좋은 아이디어를 주고받을 수 있는 상황들이 많이 나올 것이라고 생각합니다. 그래서 편하게 피드백을 주고받을 수 있고 혹은 불편함을 감수하더라도 동료들에게 피드백을 하는 문화가 우리를 발전시킬 수 있다 라고 생각합니다.',
 '태어나서 지금까지 한 일 가운데 제가 가장 후회하는 일은 대학 졸업 후에 어 조그마한 곳에서 빨리 인턴을 했어야 했는데 그러지 못하고 계속 어 공무원 시험을 준비했던 경험입니다. 물론 공무원 시험을 준비했던 경험을 통해서 저는 여러 가지 공부들을 많이 해 보았고 음 실제로도 업무를 하는 데 있어서 도움이 되는 부분이 있을 수 있습니다. 그렇지만 조금 더 빠르게 실무를 경험할 수 있는 경험들을 내가 시도해 보았다면은 음 지금 더 커리어도 발전할 수 있었지 않았을까 하는 후회들을 하고 있습니다. 왜냐하면 저는 당시에 공무원 시험을 치러서 공무원이 되는 게 제 장래에 굉장히 도움이 될 거라고 생각을 했었는데요. 실제로는 제가 조그만한 곳에서라도 인턴을 해보고 또 고객들을 직접 만나보고 동료들과 함께 협업을 해 보았던 그런 경험들이 음 제가 어 지금 현재 직무를 지원하는 데 있어서도 훨씬 더 도움이 된다 라고 생각했기 때문입니다.',
 '기차가 운행할 때 산사태로 삼십 분 동안 정차되어 있을 경우에는 제가 관리 책임에 위치에 있다면 우선 가장 중요한 것은 타고 있는 탑승객에게 상황을 설명하고 사과의 말씀을 전하는 것을 최우선으로 하겠습니다. 어 어 그 기차를 타고 있는 탑승자라면 이 기차가 어떻게 음 이런 이렇게 이런 상황이 되었는지 그리고 자신의 안전은 보장이 되는 것인지 가장 불안하고 걱정이 될 것이고 그렇기 때문에 가장 우선적으로 해결해야 될 문제는 이 기차가 어 정차되어 있지만 안전하다는 것 그리고 언제 다시 운행을 재개할 수 있다는 것을 미리 알려서 어 승객께서 다음 대안을 스스로 찾거나 아니면 편안한 마음으로 기다릴 수 있도록 돕는 것이 중요하다고 생각합니다.',
 '과거에 대학 시절 프로젝트를 수행했던 경험이 생각나는데요. 저는 대학 시절에 프로젝트를 수행할 때 항상 리더의 역할을 해 왔습니다. 음 팀원들과 함께 의견을 나누고 의견을 조율하고 그리고 프로젝트가 나아가야 할 방향을 정하는 역할을 했고요. 그 방향에 맞게 어 팀원들에게 역할을 부여하고 그리고 그 부여한 역할이 잘 수행되고 있는지에 대해서 체크하는 역할까지 수행을 했었고 모든 자료를 자료가 수집이 되면 그것을 취합해서 결과물을 만드는 그런 역할 또한 제가 맡아서 진행을 했습니다. 이 과정에서 리더십이 음 발현이 될 기회가 많았고 이러한 경험은 이 회사에서 근무를 할 때에도 좋은 긍정적인 모습으로 나타날 것으로 생각이 되겠습니 됩니다.',
 '저는 지금부터 삼 년 뒤까지 삼 년 내에 경영과 사무에 관련한 어 더 유용한 지식들을 보충하고 그래서 어떤 일이든 저에게 맡겨 주시면 편안하게 그 일이 음 잘 수행될 수 있을 것이라고 신뢰하는 사람이 되고 싶습니다. 그러기 위해서는 다양한 경영 서적 그리고 사무 관련한 음 능력들을 발전시켜 나가야 할 것이라고 생각이 드는데요. 우선 경영과 관련된 지식은 서적이나 뭐 업무 메뉴얼을 숙지하는 데에서 음 그것을 이룰 수 있을 것 같고요. 추가로 사무적인 부분에서는 엑셀이나 파워포인트 그리고 사무에 필요한 필요하다면 포토샵이나 영상 제작까지 배워볼 수 있는 것들을 배우고 싶습니다. 그래서 꼭 이 회사에 도움이 되는 사람이 되고 싶습니다.',
 '만약 일을 하던 중에 직무가 적성에 맞지 않는 경우가 생긴다면 저는 이 회사에서 제가 할 수 있는 일을 어 찾아보고 그리고 위에 제 위에 계시는 선배님들 상관님들과 이야기를 나눠서 어 조율을 해보고 싶습니다. 어쨌든 제가 이 회사에 지원하게 된 이유는 회사의 모토가 그리고 나아가야 하는 하 나아가려고 하는 방향이 저의 가치관과 맞았기 때문에 회사에 지원을 하기 한 거 것이기 때문에 직무가 적성에 맞지 않더라도 다른 직무 이 회사 안에서 다른 직무를 꼭 한 번 해보고 싶고요. 우선은 직무가 적성에 맞지 않더라도 바로 그렇게 얘기를 할 것 같지는 않고 그 직 적성에 맞지 않는 직무라 하더라도 적응을 하려고 노력은 해볼 것 같습니다. 그러다가 정 안되면 말씀을 드리겠다는 말입니다.',
 '제 전공과 관련해서 최근 부족하다고 느끼고 따로 공부를 하고 있는 분야는 음 저는 사회복지학과를 나왔습니다. 그래서 이 사회복지와 관련해서 부족하다고 느끼는 부분은 정책이나 아니면 음 그 정보 수집과 관련해서 이것은 계속해서 공부를 해나가야 할 부분이고 어 리뉴얼 아 최신으로 리 리뉴얼 된 정보에 대해서도 관심을 가지고 지켜보아야 되는 부분이라 따로 공부를 하고 있습니다. 음 사회복지 조사론 같은 경우에는 어떤 업무를 하더라도 이 조사에 관련된 부분은 중요한 중요하고 또 필요한 부분이기 때문에 지속해서 공부를 해 나가고 음 하다 보면 제 직무에도 꼭 필요한 그런 지식이 될 것이라고 저는 확신을 하기 때문에 공부를 하고 있었습니다.',
 '만약에 상사가 업무와 무관한 일을 시킨다면 어 어떤 일 인가에 따라서 제가 다를 것 같은데요. 어 완전히 개인적인 일을 시키신다면 저는 우선의 이 일을 해야 하는 이유를 찾을 것 같습니다. 제가 이 회사에 취직을 한다는 것은 회사를 위해 일하는 것이지 상사를 위해서 일을 하는 것은 아니기 때문에 개인적인 그런 일에 제가 쓰여야 한다면 제가 납득할 만한 상황이면 그것을 열심히 도와드리겠지만 납득할 수 없고 또 저를 아랫사람으로 여기시고 아무 일이나 시키는 신다고 한다면 그것은 명확히 끊어내야 하는 것이라고 생각이 듭니다. 어 넵.',
 '다른 사람이 생각하는 지 저의 장단점은 우선 장점을 먼저 얘기하겠습니다. 장점은 음 사람들과 함께 이야기할 때 제가 공감을 잘해준다고 사람들이 많이 이야기를 하는데요. 저는 공감이란 상대방의 마음과 저의 마음을 백 퍼센트 일치시키려고 하는 것이 아니라 그 사람이 하는 말을 귀담아 듣고 그리고 그 사람의 감정을 이해하려고 노력하는 것이라고 생각을 합니다. 그래서인지 사람들은 저에게 이야기를 할 때 좀 더 편안하게 자신의 이야기를 저에게 해주고 그리고 고민 상담도 많이 어 저에게 하는 것 같습니다. 반면에 단점은 제가 그런 고민을 들었을 때 그 감정이 저에게 전이가 잘 되는 편이라서 그런 면은 조심을 해야 할 것 같고 그런 감정이 업무에 영향을 주지 않도록 제가 스스로 조절하는 그런 노력을 해보도록 하겠습니다.',
 '일을 하게 되면 중국으로 출장을 갈 일이 있다고 하셨는데 저는 중국에 대해서 일을 할 때 있어서 다른 나라에 해외로 가서 일을 하는 것을 아주 흥미롭게 생각하고 음 신나는 일이라고 생각을 합니다. 그래서 어 두렵거나 그런 그런 감정이 들기보다는 가서 제가 어떤 일을 할 수 있을지 그런 설렘이 있는 편이고요. 그리고 다른 대학 시절 그리고 이 회사에 입사 신청을 하기 전에 많은 나라를 접해보고 여행이나 아니면 국제 자원봉사 등을 통해서 다른 나라에 많이 체류를 하거나 여행을 했는데 그때마다 그 나라의 문화를 알아가고 그리고 그 나라 사람들과 함께 관계를 맺어 나가는 것에 어 흥미를 느꼈기 때문에 어 일을 할 때도 그런 일이 그런 해외 출장과 같은 일이 있다면 즐겁게 수행하고 그리고 어렵지 않게 적응을 할 수 있을 것이라고 생각이 듭니다.',
 '저의 십 년 후 미래는 어 이 회사에 계속 다니고 싶은 마음입니다. 음 십 년이라는 시간 동안에 저는 여자이기 때문에 임신도 할 거고 아이도 낳을 것이고 그런 과정을 거칠 것인데 제가 알기로는 이 회사의 복지가 아주 좋다고 들었습니다. 그 복지 좋은 복지에 어 기대에 부응할 수 있도록 열심히 일도 할 것이고 아이를 낳더라도 중도에 이 일을 그만두는 일 없이 어 회사에 중요한 사람이 될 수 있도록 노력하는 사람이 되고 싶 되고 싶습니다. 십 년이라는 시간이면 이 업무에 있어서는 전문가가 될 것이고 또 앞으로 들어오는 신입 직원이나 또 후배 직원들에게 모범이 되고 또 영감을 줄 수 있는 그런 선배 직원이 되고 싶고요. 어 꼭 그렇게 될 수 있도록 제가 노력하겠습니다.',
 '동물 실험이 인간에게 주는 이익은 어 인간에게 음 사전에 실험할 수 없는 그런 약품이나 또 화장품과 같은 그런 것들을 실험할 수 있는 실험체로서에 음 역할을 한다고 하면 그것이 인간에게 주는 이익이라고 생각을 하고요. 하지만 동물의 인권에 제가 관심이 많은 편인데 이 살아있는 생물을 인간이라는 이유만으로 그렇게 생명을 어 갈취하고 이용할 수 있는 그런 권리가 있는가에 대해서는 생각이 많습니다. 그래서 대체할 수 있는 부분이 있다면 대체를 할 수 있도록 인공 피부 이 인공 피부 어 를 만들어서 거기에 실험을 하거나 하는 식으로 뭔가의 대체제가 필요하다고 생각이 들고 하루빨리 그런 대체 할 수 있는 방법이 생겼으면 좋겠습니다.',
 '사람들과 협업을 하면서 가장 어려웠던 점은 각자의 생각을 나누고 그것을 조율하는 과정이었습니다. 사람마다 한 가지 질문을 하더라도 그 질문을 받아들이는 어 사고가 다르고 그리고 생각을 생 그 질문에 대한 생각을 하는 것도 다 다르기 때문에 그것을 맞춰가는 것이 가장 어렵다고 생각하고 어 하지만 그런 과정이 잘 수행되었을 때 신뢰가 쌓이고 또 협업이 잘 이루어진다고 생각이 듭니다. 음 저는 대학 시절부터 이렇게 협업을 하면서 그렇게 의견을 조율하고 한 가지 방향으로 모두를 이끌어가는 경험을 많이 해봤기 때문에 앞으로 회사에서 협업할 일이 많이 생긴다고 많이 생길 것이라고 생각이 듭니다. 그때마다 자신 있게 어 자신의 제가 할 수 있는 역할과 그리고 제가 할 수 있는 역할들을 어 확실하게 얘기하고 또 어려워하는 분들이 있으면 그것을 도와줄 수도 있을 거라고 생각이 듭니다.',
 '저는 스리랑카로 국제자원봉사를 어 장기간 가고 싶어서 그 쓰리랑카 아이들에게 필요한 것이 무엇인지 조사를 해 보다가 한국어에 대한 니즈가 있다는 것을 파악하고 한국어 교원 자격증을 다 따기 위해서 취득하기 위해서 이 년간 열심히 노력을 해서 목표를 달성했습니다. 한국인이 한국어를 배우는 것이 이상 하게느끼실 수도 있는데요. 한국어의 학문적인 학문적인 접근으로 어 취득하는 자격증이고 또 어떻게 하면 이것을 외국인에게 효과적으로 가르칠 수 있는지에 대한 그런 자격증입니다. 그래서 어 제가 한국인의 한국인임에도 불구하고 그런 공부를 하는 데 있어서 생소한 것도 많고 또 어려운 점도 많았지만 결국에는 그 자격증을 취득해서 어 쓰리랑카로 장기간 국제 자원봉사를 떠날 수 있었고 그 경험이 제 인생에서 정말 중요하고 무엇인지 무엇이든지 할 수 있겠다 라는 자신감을 주는 경험으로 작용하게 되었습니다.',
 '최근에 제가 가장 재미있게 하고 있는 일은 운동인데요. 어 제가 얼마 전부터 크로스핏 이라는 운동을 시작했습니다. 크로스핏 이라는 운동은 제가 가족들과 가족 여행을 갔는데 사진에 찍힌 제 모습이 너무 부하게 느껴져서 처음에 시작하게 된 계기는 그러하고요. 하지만 어 직접 가서 해보니까 땀을 흘리는 운동은 기분이 나쁘고 또 힘들기만 할 것이라고 생각했던 그런 생각을 완전히 바꿔줄 수 있는 그런 운동이었습니다. 하루하루 정해진 운동을 다 수행하고 나면 하 제가 하루를 정말 열심히 살았구나 하는 그런 뿌듯함 그리고 보람이 있구요. 그리고 운동을 하고 나서 체력도 많이 좋아져서 하길 잘했다 라고 생각하는 운동이고 또 최근에 가장 재미있는 그런 활동이 아닐까 생각을 합니다.',
 '경영이란 어떤 한 회사를 꾸려가는 것이라고 생각을 합니다. 그렇지만 경영이라고 해서 모두 다 좋은 경영이라고 할 수는 없는 것이 이 회사를 꾸려가는 것도 잘 꾸려가야 되지 않습니까. 그래서 어 꼭 말씀드려야 할 것이 이에스지 경영을 말씀드리지 않을 수 없는데요. 이에스지 경영은 환경이나 그리고 음 그런 조직 문화 이런 것들이 지속 가능할 수 있도록 유지할 수 있는 그런 기업의 마인드 라고 생각을 하는데 이렇게 기업이 자신의 이익만 생각하지 않고 자신과 연결된 어 사회와 그리고 어 근무하고 있는 근로자 그리고 그 기업이 존재하고 있는 국가 그리고 세계 이런 것들을 다 연관지어서 생각할 수 있을 때 이 기업 기업의 경영이 어 좋게 흘러가고 있다 라고 말할 수 있을 것 같습니다.',
 '제가 지금 지원한 이 직무가 아닌 다른 부서에 배치되게 된다면 저는 그렇다 하더라도 그 부서에 우선적으로 잘 적응할 수 있도록 노력을 최대한의 노력을 할 것입니다. 어 업무 매뉴얼과 그리고 그 직무에 관련한 서적 어 그리고 다양한 유튜브 채널에서 이런 정보들을 얻어서 그 일을 제가 잘 해낼 수 있도록 노력을 할 것이고 제 저에게 너무 맞지 않는 직무라서 제가 노력을 했는데도 그것이 잘 수행되지 않아서 회사에 폐해를 끼치는 것 같은 느낌이 든다면 저의 선배나 상사 분들과 이야기를 해서 제가 잘 할 수 있는 부분을 어필을 하겠습니다.그래서 음 정말 노력을 했는데 또 되지 않는다면 다른 직무로 배치 받을 수 있도록 어 저의 의견을 어필할 생각입니다.',
 '저는 대학 시절에 프로젝트를 많이 수행했었는데요. 어 주로 프로젝트 내에서 리더의 역할을 해 해 왔습니다. 팀원들의 의견을 조율하고 그리고 그들에게 어 그들이 잘 할 수 있는 역할을 분배하고 또 역할을 분배한 거 한 이후에도 그 역할을 잘 수행하고 있는지 체크하고 어 또 어떤 방향으로 프로젝트가 흘러가고 있는지 즉 계속해서 저희가 처음 생각했던 방향으로 잘 흘러가고 있는지 이런 전체적인 것들까지 체크를 했습니다. 그래서 저는 제가 나무와 숲을 동시에 볼 수 있는 사람이라고 생각을 합니다. 그렇기 때문에 이 회사에 입사를 해서 프로젝트를 같이 팀원들과 협업해서 진행하게 된다고 하더라도 이렇게 어 열심히 프로젝트를 진행해 왔던 그리고 리더의 역할을 해왔던 그런 경험들이 빛을 발할 것이라고 생각이 생각이 들고 그것이 회사에 꼭 도움이 될 것이라고 생각합니다.',
 '저는 창의성과 팀워크 중에서 팀워크가 더 중요하다고 생각합니다. 창의성이라는 것은 완전히 무에서 유를 창조하는 것은 많은 사람들이 하지 못하는 일이 있고 또 이 회사를 위해서 크레이티브한 사람은 필요하지만 그 크레이티브한 사람이 팀워크가 좋지 않다면 그 능력을 최대한으로 발휘하지 못할 것이라고 생각합니다. 그 아이디어가 얼 정말 어 좋다고 해도 팀워크가 없다면 그것이 자신의 생각대로 발현되지 않을 것이라고 생각이 됩니다. 하지만 음 조금 미흡한 아이디어라도 팀워크를 통해서 더 발전시킬 수 있다고 생각하고 결국에는 회사에서 일을 하는 것은 혼자 하는 것이 아니라 함께 하는 것이기 때문에 팀워크를 더 중요하게 생각했을 때 이 회사에 그리고 업무에 더 좋은 결과가 있을 것이라고 생각합니다.',
 '맞습니다. 요즘 고령화 사회로 치매 문제가 많이 대두되고 있는데요. 건강보험 공단에서 어 이 치매와 관련되서 어 장애 등급을 받게 되면 어 거기에 관련된 지원 경제적인 지원이나 어 예 그 후에 뭔가 그것을 치매를 늦출 수 있는 여러 가지 교육도 제공할 수 있는 것으로 알고 있습니다. 음 하지만 저 제가 가장 중요하게 생각하고 개선해야 할 방안으로 생각하는 것은 치매라 함은 치매가 걸리고 나면 나머지 가족들이 그 치매가 걸린 가족을 돌보면서 많은 스트레스를 받고 또 경제적으로도 음 조금 더 쪼들리는 생활을 할 수 밖에 없지 않습니까 그래서 가족들을 위한 그런 정신건강에 관련된 지원 그리고 또 어 치매 노인을 돌보는 가족들에게 경제적인 혜택이 많이 돌아갈 수 있도록 그런 방안들이 많이 고안이 됐으면 좋겠다는 생각입니다.',
 '저는 의견을 주장할 때 일단 제가 의견을 낼 대상에 대해서 한번 생각을 해 봅니다. 제가 어찌됐든 의견을 주장할 때 제가 원하는 것은 제 의견을 피력하는 것이기 때문에 어떤 형태로 제가 의견을 얘기했을 때 제가 말하는 사람에게 잘 먹혀들 수 있는지를 먼저 생각하는 것 같습니다. 의견을 강하게 이야기 했을 때 그 의견이 어 설득력을 갖는 경우에는 그렇게 얘기해야겠고 제가 애둘러서 얘기해야 할 때 그 의견이 잘 먹혀든다고 생각하는 사람인 사람이라면 그렇게 이야기를 해야겠죠. 그래서 그래서 저는 대화를 나누는 사람을 관찰하고 그 사람의 성향을 고려해서 이야기를 하려고 노력하는 편인 것 같습니다.',
 '다른 계열사도 많이 있으 있지만 이 계열사에 특별히 제가 지원한 이유는 어 이 제가 이 주변에 살고 있습니다 사실. 그래서 여기에 출퇴근하는 사람들의 표정을 보는 본 적이 많은데요. 이 계열사가 특별히 어 출퇴근하는 직원들의 얼굴을 봤을 때 어 힘들거나 짜증스럽게 느껴지는 사람보다는 어 즐겁게 출퇴근하는 사람들이 많았기 때문에 이 계열사에 지원을 하게 되었고요. 그리고 출근 시간과 퇴근시간이 너무 늘어지지 않고 지켜지는 것 때문에 어 이 회사를 지원한 점도 있습니다. 어 직원으로서 회사에서 일할 때 워 일 과 그리고 휴식의 그 밸런스를 잡는 것도 저는 참 중요하다고 생각하는데요. 어 워 워라벨이 지켜지는 이 계열사의 계열사만의 그런 음 장점이 저에게 와 닿았고 어 이런 장점이 저에 제가 일을 해 나가는 데 있어서 어 중요한 동력이 될 것 같습니다.',
 '사실 많은 문서 작성을 해 본 적이 있었는데요. 제가 작성한 문서는 그 오탈자나 아니면 실수가 제 눈에는 잘 보이지 않더라구요. 그래서 네 이중 체크를 다른 사람에게 부탁을 하는 경우가 굉장히 많았습니다. 그리고 저 또한 다른 사람의 어 문서들을 제 봐줌으로써 그러한 실수들을 바로잡아주는 경우가 되게 많았는데요. 이렇게 이중 체크를 하다 보면은 훨씬 더 내가 보지 못한 것들을 남들이 봐줄 수 있기 때문에 훨씬 더 더 많이 실수를 줄일 수 있다 라고 생각합니다.',
 '경영과 사무의 측면에서 중요한 것들은 어 사람이 라고 사람이라고 생각합니다. 어 어떤 프로젝트를 진행할지 프로젝트의 방향이나 목표를 설정하는 게 모두 사람의 성향에서 드러나기 때문에 인사란 그러한 앞으로의 경영과 사무가 어떤 방향으로 나갈지 그 어떤 방향으로 나아갈지를 결정하는 토대와 같다고 생각합니다.',
 '음 저는 조금 무뚝뚝하더라도 정확하게 일을 하는 선배를 만나고 싶습니다. 회사에 처음 들어갔을 때 신입인 신입의 입장에서 새로운 새로운 그 회사의 시스템에 처음 적응하는 입장에서 시스템에 가장 가까이서 보고 배울 수 있는 선배가 일을 정확하게 하지 못하는 것만큼 본인의 어떤 적응 적응 정도를 낮출 수 있는 것은 없다고 생각합니다. 그래서 좀 인간적인 모습은 덜하더라도 나에게 정확한 방향과 시스템을 안내할 수 있는 선배의 를 만나는 게 만나고 싶습니다.',
 '경영은 미래를 위한 비전을 세우는 일이라고 생각합니다. 단순히 삼 년 오 년 안에 이 회사가 어떻게 굴러갈지를 결정하는 것도 물론 경영의 몫이지만 어 경영을 한다는 것은 회사가 어떻게 살아남을지 수십 년 뒤에는 어떤 모습을 할지 거시적인 시점에서 시장과 회사 그 시장에서 회사의 위치를 바라봐야 하는 일이라고 생각합니다.',
 '어 제가 자칭 헤비 콘텐츠 소비러라고 합니다. 그만큼 다양한 분야의 콘텐츠를 소비하는데 대표적으로는 드라마나 영화도 좋아하고 미술관 같 미술관에 가서 전시를 보는 것도 좋아합니다. 제가 현재 경험하고 있는 일상과 동떨어질 수 있는 것들을 정말 좋아하는데 예를 들면 미술관에 가면 한 시간이 넘는 시간 동안 아무하고도 말을 안 할 수도 있고 그렇지만 잘 정돈되고 새로운 환경에서 좋은 의미를 전달하는 작품을 볼 수 있습니다. 그게 뭔가 뇌를 청소하는 느낌이 들게 했고 드라마 같은 경우에도 어 일상이라는 한 쪽에 세계가 있다면 드라마는 아무리 일상적인 소재를 다루고 있더라도 어 굉장히 판타지적이고 많은 것들을 정제한 것이기 때문에 그 균형을 맞추는 데 도움이 됩니다.',
 '어 저는 지금 컴퓨터 프로그래밍 컴퓨터공학과에 재학 중이라서 컴퓨터 프로그래밍을 배우고 있습니다. 제가 이 과에 진학한 이유는 애초에 많은 비전과 미래가 있다고 생각했기 때문입니다. 지금까지는 저는 대학에 들어와서 처음 컴퓨터 프로그램을 배웠기 때문에 다양한 언어의 기초를 공부하는 데 집중하고 있습니다.',
 '음 기존의 시장에 있는 것들과는 다른 무언가를 제공하기 때문이라고 생각합니다. 아이패드 같은 경우에는 어 변화한 시대의 흐름에 맞춰서 오티티 서비스를 보기에도 적합하고 애플의 감성을 느끼기에도 적합하고 펜슬과의 조합을 통해서 다양한 일상에서 활용이 가능했고 맥북 또한 특정 카페에서의 입장권이라고 불릴 만큼 어떤 감성의 측면에서 굉장히 시 어 시장의 마음을 사로잡았다고 생각합니다. 어 에어팟은 어 기존에 있는 애플 제품과 연동성도 굉장히 뛰어나고 제트플립은 어 기존의 시장에 소비자들의 니즈에 맞춰서 니즈를 충족시킨 제품이 없었는데 접는 핸드폰에 대체 유행을 제트플립이 그 니즈를 맞추면서 성공시켰다고 생각합니다.',
 '제가 굉장히 인상적으로 기억하고 있는 드라마 대사가 있습니다. 사회에서 사과는 개인 간의 화합을 위한 것이 아니라 집단 평화를 위한 것이라는. 어 일단 상사와 상사분과 저희 만남은 집단의 목표를 이루기 위해서 만난 것이기 때문에 정말 불합리하고 제 감정을 건드리고 제가 그 집단 속에서 일을 못할 정도가 아니라면 어 저 저희 제가 속한 집단에 일을 진행시키기 위해서 그걸 참고 또 어느 정도는 수용을 하고 그 니즈에 맞춰서 받아들이는 부분도 있어야 한다고 생각합니다. 어 일단 그 상사분이 저보다 오래 연 그 집단에 속해있기 때문에 사람들이 목표하는 바가 무엇인지 저보다는 더 잘 알고 있으리라 생각합니다.',
 '어 신제품을 가장 인간에게 가장 큰 피해 없이 적용시킬 수 있다는 점에서 동물 실험이 우리에게 주는 이익이 있다고 생각합니다. 그러나 어 사실 저는 동물 실험에 대해서 반대합니다. 어 신체 구조가 비슷하다고 하더라도 첫 번째로 그들 또한 인간이 느끼는 고통을 느끼며 두 번째로 어 아직 밝혀지지 않은 많은 분야의 생명 시스템이 인간과 동물이 서로 다르다는 것을 입증하기 때문에 저는 동물 실험을 백 프로 믿어서는 믿으면 안 된다고 생각합니다. 따라서 동물 실험이 인간 인 동물 실험에 하는 것에 대해서 반대합니다.',
 '어 지원한 분야가 저 어떻 어떤 부분이 잘 안 맞는지 잘 안 맞는 이유가 무엇인지 한번 생각해 볼 것 같습니다. 제 성향과 맞지 않는지 아니면 제 능력이 부족한 탓인지 혹은 제가 흥미가 담기지 않는지를 조금 살펴봐야 할 것 같은데 저는 모든 분 부분이 맞을 수 있다고는 생각하지 않기 때문에 좋은 점과 나쁜 점을 구분해서 나쁜 점 중에서 개선할 수 있는 부분이 어떤 건지 판단을 할 것이고 개선을 하도록 노력할 것이고 어 이 좋은 점이 있기 때문에 좀 더 버텨보자 라고 마음을 먹을 것 같고 그 걸 그 걸 저울질을 했을 때도 제가 버틸 수 없을 때 그땐 어쩔 수 없이 그만두게 되지 않을까 생각합니다.',
 '어 어 홍콩이나 마카오가 어떨까 어 마카오가 가장 좋을 거 같습니다. 저는 회사가 해외로 진출하게 된다면 경제적으로 활발하고 인구 밀도가 높고 어 자본금은 필요한 자본금은 받고 그러나 국제적으로 많은 영향력이 있는 경 그런 나라를 꼽을 것 같은데 그게 마카오라고 생각합니다.',

In [68]:
len(texts)

12804

In [44]:
train_docs = texts[:100]
train_sums = summary[:100]
valid_docs = texts[-10:]
valid_sums = summary[-10:]

In [47]:
raw_ds = DatasetDict(
    {
        'train' : Dataset.from_dict(
            {
                'document' : train_docs,
                'summary' : train_sums
             }
        ),
        'validation' : Dataset.from_dict(
            {
                'document' : valid_docs,
                'summary' : valid_sums
            }
        )
    }
)

In [49]:
raw_ds

DatasetDict({
    train: Dataset({
        features: ['document', 'summary'],
        num_rows: 100
    })
    validation: Dataset({
        features: ['document', 'summary'],
        num_rows: 10
    })
})

In [51]:
model_name = 'gogamza/kobart-base-v2'

In [52]:
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# 입력 / 출력 문장의 최대 길이 설정
max_input_len = 512
max_target_len = 256

You passed `num_labels=3` which is incompatible to the `id2label` map of length `2`.
You passed `num_labels=3` which is incompatible to the `id2label` map of length `2`.
You passed `num_labels=3` which is incompatible to the `id2label` map of length `2`.

In [53]:
def tok_fn(batch):

    inputs = tokenizer(
        batch['document'],
        max_length = max_input_len,
        padding = 'max_length',       # 고정길이 패딩 사용
        truncation = True             # 최대 길이보다 긴 경우 자른다
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            batch['summary'],
            max_length = max_target_len,
            padding = 'max_length',
            truncation = True
        )

    labels_ids = np.array(labels['input_ids'])

    labels_ids[labels_ids == tokenizer.pad_token_id] = -100

    inputs['labels'] = labels_ids.tolist()

    return inputs

In [54]:
tokenized_ds = raw_ds.map(tok_fn, batched=True, remove_columns=['document', 'summary'])

Map:   0%|          | 0/100 [00:00<?, ? examples/s]c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\transformers\tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(
Map: 100%|██████████| 100/100 [00:00<00:00, 1026.74 examples/s]
Map: 100%|██████████| 10/10 [00:00<00:00, 615.49 examples/s]

In [55]:
tokenized_ds

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 100
    })
    validation: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 10
    })
})

In [56]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [57]:
rouge = evaluate.load('rouge')

In [58]:
def compute_metrics(eval_pred):
    preds, labels = eval_pred

    # vocab -> ['A', 'B', 'C']
    # decoder -> preds = [13, 17, 102, ...] -> 
    # vocab 인덱스로 구성된 리스트를 다시 문자의 형태로 변환하기 위해서 padding 토큰은 무시하기 위해 -100으로 구성 -> 원래의 padding 토큰의 id값으로 전환
    labels = np.where(
        labels != -100, labels, tokenizer.pad_token_id
    )
    # 텍스트 디코딩
    pred_str = tokenizer.batch_decode(preds, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # 문장에서 좌우의 공백이 존재하는 경우 다른 값으로 측정하기 때문에 좌우 공백 제거
    pred_str = [doc.strip() for doc in pred_str]
    label_str = [doc.strip() for doc in label_str]

    # ROUGE 계산
    result = rouge.compute(
        predictions = pred_str,
        references = label_str,
        use_stemmer = True          # 점수 계산시 단어의 어간을 기준으로 비교하는 의미
    )
    
    # ROUGE를 보기 편한 형태로 변경
    result = {k : round(v * 100, 2) for k, v in result.items()}

    return result

In [59]:
args = Seq2SeqTrainingArguments(
    output_dir='./kobart',
    eval_strategy='epoch',
    save_strategy='epoch',
    learning_rate=5e-5,
    num_train_epochs=10,
    logging_steps=10,

    # generate 설정을 변경
    predict_with_generate=True,
    generation_max_length=70,
    # 요약 데이터를 생성할때 문장 후보의 탐색의 개수를 설정
    generation_num_beams=4,

    load_best_model_at_end=True,
    metric_for_best_model='rougeL',
    greater_is_better=True,
    report_to=[]
)

In [60]:
trainer = Seq2SeqTrainer(
    model=model,
    args=args,
    train_dataset=tokenized_ds['train'],
    eval_dataset=tokenized_ds['validation'],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)
trainer.train()

C:\Users\student\AppData\Local\Temp\ipykernel_13108\1366852772.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\transformers\modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'forced_eos_token_id': 1}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=130, training_loss=0.042517339570734364, metrics={'train_runtime': 2039.0765, 'train_samples_per_second': 0.49, 'train_steps_per_second': 0.064, 'total_flos': 304868229120000.0, 'train_loss': 0.042517339570734364, 'epoch': 10.0})

In [74]:
test_text = texts[200]

inputs = tokenizer(test_text, return_tensors='pt', truncation=True, max_length=max_input_len)
inputs.pop('token_type_ids', None)

gen_ids = model.generate(
    **inputs.to(model.device),
    max_length = 20,
    num_beams = 4,
    do_sample=False
)

print(tokenizer.decode(gen_ids[0], skip_special_tokens=True))

네 저는 지금 백지연이 지은 크리티컬 매스 라는 책을 요즘 읽고 있는데요. 제가

In [75]:
test_text

'네 저는 지금 백지연이 지은 크리티컬 매스 라는 책을 요즘 읽고 있는데요. 제가 백지연을 예전에는 제가 굉장히 존경하기도 했었는데 소통 능력이 굉장히 뛰어나다 라는 생각이 많이 들었었고 그리고 다양한 사람들과 인터뷰 경력이 있으시잖아요. 그래서 타인을 이해할 수 있는 폭이 넓지 않을까 라는 생각에서 이 책을 읽게 되었고 그리고 이 책에서 느낀 게 제가 정말 남들이 감동시킬 만한 노력을 한다면 그것은 타인들이 다 알아줄 것이다 라는 이야기가 있어요. 그래서 정말 노력을 해서 어떤 재능이든 개발할 수 있겠구나 라는 생각이 들었고 여기에 많은 분들을 인터뷰한 그런 내용이 있습니다. 그래서 저도 예전에 다 다양한 사람들의 이야기를 들으면서 저도 많이 발전이 됐었는데 타인의 이야기에서 제 장점을 또 끌어내고 그것을 할 수 있는 그런 깨달음을 제가 얻게 되어서 이 책을 굉장히 감명 깊게 읽고 있고요. 그리고 이 책을 읽으면서 인터뷰를 하고 다른 사람의 이야기를 듣는 법에 대해서도 깨닫게 된 것 같습니다.'