In [165]:
# csv 폴더 안에 있는 uriage.csv 파일을 로드
import pandas as pd

In [166]:
# 상대경로
# 상위 디렉토리 이동(../) -> 하위 csv 디렉터리(csv/) -> uriage.csv

uriage = pd.read_csv("../csv/uriage.csv")

In [167]:
uriage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   purchase_date  2999 non-null   object
 1   item_name      2999 non-null   object
 2   item_price     2612 non-null   float64
 3   customer_name  2999 non-null   object
dtypes: float64(1), object(3)
memory usage: 93.8+ KB

In [168]:
uriage.head()

      purchase_date item_name  item_price customer_name
0  2019-06-13 18:02       상품A       100.0           김가온
1  2019-07-13 13:05     상 품 S         NaN           김우찬
2  2019-05-11 19:42     상 품 a         NaN           김유찬
3  2019-02-12 23:40       상품Z      2600.0           김재현
4   2019-04-22 3:09       상품a         NaN           김강현

In [169]:
uriage.tail()

         purchase_date item_name  item_price customer_name
2994   2019-02-15 2:56       상품Y      2500.0           김정민
2995   2019-06-22 4:03       상품M      1300.0           김재원
2996  2019-03-29 11:14       상품Q         NaN           김지율
2997  2019-07-14 12:56       상품H         NaN           김승주
2998   2019-07-21 0:31       상품D       400.0           정준기

In [170]:
# 결측치의 개수를 확인
uriage.isna().sum()

purchase_date      0
item_name          0
item_price       387
customer_name      0
dtype: int64

- 문제점
    1. 결측치
        - item_price 컬럼에서 결측치 존재
        - 결측치의 개수가 전체 데이터 개수와 비교해서 대략 10% 이상
        - 결측치를 특정 데이터로 치환
    2. 데이터 정형화
        - item_name의 데이터에서 데이터의 규칙의 문제
            - 대, 소문자 문제
                - 모든 문자를 대문자, 소문자로 통일
                - 문자열 함수 중 upper(), lower(), title()
            - 문자 사이의 공백 문제
                - 문자 사이에 있는 공백을 제거 
                - 문자 시작과 끝에만 공백이 존재한다면 -> strip() 함수를 이용하여 제거 가능
                - 문자열 사이에 공백을 제거하려면 -> replace() 함수를 이용하여 공백을 빈 문자로 치환하여 해결

In [171]:
# 문자를 모두 대문자로 변경
# item_name의 데이터를 확인
# Series 안에 values의 개수를 파악한다.
# value + 개수(count) -> value_counts()
uriage['item_name'].value_counts()

item_name
상품A      133
상품R      133
상품S      133
상품P      132
상품C      130
        ...
상 품I       1
 상품 W      1
 상품 X      1
상품 M       1
상 품P       1
Name: count, Length: 99, dtype: int64

In [172]:
# 데이터에서 중복 값들은 제외 -> 유일한 리스트 데이터 생성
# 유일(unique)
uriage['item_name'].unique()

array(['상품A', '상 품 S', '상 품 a', '상품Z', '상품a', '상품S', '상품 a', '상품V', '상품O',
       '상 품U', '상품L', '상  품V', '상 품O', '상품C', '상품I', '상품r', '상품X', '상품 g',
       '상품R', '상품P', '상품Q', '상품y', '상품 A', '상품N', '상품W', '상 품E', '상품K',
       '상품B', '상품F', '상 품s', ' 상품W', ' 상 품 n', '상 품F', '상품D', '상품M',
       '상품Y', '상품U', '상품H', '상품T', '상품J', '상  품O', '상품E', '상  품Q',
       ' 상품 S', ' 상품 M', '상  품T', '상품G', '상 품G', ' 상품 P', ' 상품 E', '상 품N',
       '상 품Y', '상품 J', '상품 V', '상품 K', '상 품V', '상 품D', '상 품A', '상품 F',
       '상품 H', '상 품K', '상 품T', '상품 X', '상품 Q', '상 품X', '상 품H', '상 품C',
       '상품 B', '상품 O', '상품 T', '상품v', '상품p', '상품i', '상품 w', '상 품 s',
       '상 품 q', '상품s', '상품l', '상품t', '상품k', '상품g', '상품o', '상품 R', '상품 S',
       '상 품M', '상품j', '상품d', '상품 I', '상품 E', '상품 o', '상품c', '상품 v', '상품e',
       '상품x', '상 품I', ' 상품 W', ' 상품 X', '상품 M', '상 품P'], dtype=object)

In [173]:
# 문자를 대문자로 변경 -> upper() -> str class 안에 존재하는 함수
# str.upper()
uriage.loc[2, 'item_name'].upper()

'상 품 A'

In [174]:
# Series에서는 upper() 함수가 사용이 가능한가?? -> 불가능 -> 해당 함수가 존재하지 않는다.
# uriage['item_name'].upper()

In [175]:
# 복사본 생성
df = uriage.copy()

In [176]:
# case1
# 반복문을 이용하여 모든 문자를 대분자로 변경
# 반복 횟수 : 2999번 (데이터프레임의 길이)
for i in range(0, len(df)) :
    df.loc[i, 'item_name'] = df.loc[i, 'item_name'].upper()

In [177]:
df['item_name']

0         상품A
1       상 품 S
2       상 품 A
3         상품Z
4         상품A
        ...
2994      상품Y
2995      상품M
2996      상품Q
2997      상품H
2998      상품D
Name: item_name, Length: 2999, dtype: object

In [178]:
# uriage = pd.read_csv("https://raw.githubusercontent.com/bsmoon-86/multicam_2025/refs/heads/main/csv/uriage.csv")
# display(uriage)

In [179]:
# case2
df2 = uriage.copy()

In [180]:
# case2
# Series.map() 함수를 이용하여 데이터 변환
# map() -> 1차원 데이터에서 각각의 원소들을 함수에 대입하여 결과를 받아와서 새로운 1차원 데이터를 생성
# map에서 사용하는 함수 일반 def 키워드 함수, lambda 함수 가능
# lambda 함수를 이용
df2['item_name'].map(
    # x의 타입은 str -> 문자열 내장함수인 upper() 사용 가능
    lambda x : x.upper()
)

0         상품A
1       상 품 S
2       상 품 A
3         상품Z
4         상품A
        ...
2994      상품Y
2995      상품M
2996      상품Q
2997      상품H
2998      상품D
Name: item_name, Length: 2999, dtype: object

In [181]:
# map + 일반함수
def change(x):
    # x의 대입이 되는 데이터는 타입이 str인 데이터
    # x에 문자열 내장함수 사용 가능
    x = x.upper()
    return x

df2['item_name'] = df2['item_name'].map(
    change
)

In [182]:
df3 = uriage.copy()

In [183]:
# case3
# Series 데이터에서 문자열 함수를 사용하기 위해 타입은 변경
df3['item_name'] = df3['item_name'].str.upper()

In [184]:
# 문자열 대문자 변환 문제는 해결

In [185]:
# 문자열 사이에 있는 공백을 제거 문제
# replace(' ', '')
df['item_name'].str.replace(' ','')

0       상품A
1       상품S
2       상품A
3       상품Z
4       상품A
       ...
2994    상품Y
2995    상품M
2996    상품Q
2997    상품H
2998    상품D
Name: item_name, Length: 2999, dtype: object

In [186]:
_val = [True, False, True]

test = pd.Series(
    _val
)

In [187]:
test.astype(str).str.upper().astype(bool)

0    True
1    True
2    True
dtype: bool

In [188]:
# uriage 데이터에서 item_name의 문자들을 일괄적으로 변환
uriage['item_name'].str.upper().str.replace(' ','')

0       상품A
1       상품S
2       상품A
3       상품Z
4       상품A
       ...
2994    상품Y
2995    상품M
2996    상품Q
2997    상품H
2998    상품D
Name: item_name, Length: 2999, dtype: object

In [189]:
uriage['item_name'] = uriage['item_name'].str.upper()
uriage['item_name'] = uriage['item_name'].str.replace(' ','')

In [190]:
type(
    uriage['item_name'].str.upper().str.replace(' ', '')
)

pandas.core.series.Series

In [191]:
uriage['item_name'].value_counts()

item_name
상품S    140
상품A    139
상품R    136
상품P    135
상품V    134
상품C    133
상품F    126
상품D    125
상품Q    125
상품O    124
상품W    121
상품N    119
상품T    117
상품X    116
상품J    116
상품I    114
상품B    113
상품M    113
상품L    110
상품G    110
상품K    109
상품H    109
상품U    107
상품E    105
상품Y    102
상품Z      1
Name: count, dtype: int64

In [192]:
uriage['item_name'].unique()

array(['상품A', '상품S', '상품Z', '상품V', '상품O', '상품U', '상품L', '상품C', '상품I',
       '상품R', '상품X', '상품G', '상품P', '상품Q', '상품Y', '상품N', '상품W', '상품E',
       '상품K', '상품B', '상품F', '상품D', '상품M', '상품H', '상품T', '상품J'],
      dtype=object)

- item_price 데이터에 결측치 채우기
    - 상품별 결측치를 제외한 item_price의 평균을 구한다.
    - 해당 상품의 item_price가 결측치인 데이터에 평균값을 대입

In [193]:
# 상품A의 item_price가 결측치가 아닌 데이터를 확인
# 조건식 -> item_name이 상품A인 (uriage['item_name'] == '상품A')
#          item_price가 결측치인 조건(uriage['item_price].isna())
flag = uriage['item_name'] == '상품A'
flag_null = uriage['item_price'].isna()

In [194]:
# item_name이 상품A(flag)이고 (그리고) item_price가 결측치가 아닌 (~flag_null) 상품 정보(모든 컬럼)를 확인
uriage.loc[
    flag & ~flag_null,
]
# 위의 인덱스 조건에서 item_price 컬럼(컬럼의 조건식)의 데이터의 평균값(mean()) 구한다.
mean_price = uriage.loc[
    flag & ~flag_null,
    'item_price'
].mean()

In [199]:
# mean_price를 item_name(flag)이 상품A이고 item_price가 결측치(flag_null)인 item_price에 대입
# item_price에(컬럼의 조건)에 대입
uriage.loc[flag & flag_null, 'item_price'].fillna(mean_price)

2       100.0
4       100.0
6       100.0
14      100.0
300     100.0
361     100.0
667     100.0
838     100.0
844     100.0
957     100.0
1260    100.0
1394    100.0
1474    100.0
1892    100.0
1937    100.0
1977    100.0
2063    100.0
2278    100.0
2636    100.0
2669    100.0
2732    100.0
2821    100.0
Name: item_price, dtype: float64

In [ ]:
uriage.loc[flag & flag_null, 'item_price'] = uriage.loc[flag & flag_null, 'item_price'].fillna(mean_price)

In [202]:
uriage.loc[flag & flag_null, 'item_price']

2       100.0
4       100.0
6       100.0
14      100.0
300     100.0
361     100.0
667     100.0
838     100.0
844     100.0
957     100.0
1260    100.0
1394    100.0
1474    100.0
1892    100.0
1937    100.0
1977    100.0
2063    100.0
2278    100.0
2636    100.0
2669    100.0
2732    100.0
2821    100.0
Name: item_price, dtype: float64

In [213]:
# 위의 작업들을 상품A부터 상품Z까지(item_name 데이터에서 중복으로 제거한 리스트) 반복 실행
item_list = uriage['item_name'].unique()

# 반복문을 작성
# item_list의 길이만큼 반복
for item_name in item_list:
# for i in range(len(item_list)):
    # item_name 변수에는 item_list의 각각의 원소들이 대입
    # i는 -> item_list의 index 값이 대입
    flag = uriage['item_name'] == item_name
    # flag = uriage['item_name'] == item_list[i]
    flag_null = uriage['item_price'].isna()

    mean_price = uriage.loc[flag & ~flag_null, 'item_price'].mean()

    uriage.loc[flag & flag_null, 'item_price'] = mean_price

In [218]:
# 결측치의 개수를 확인
uriage.isna().sum()

purchase_date    0
item_name        0
item_price       0
customer_name    0
dtype: int64

In [220]:
uriage.groupby(['item_name'])['item_price'].mean()

item_name
상품A     100.0
상품B     200.0
상품C     300.0
상품D     400.0
상품E     500.0
상품F     600.0
상품G     700.0
상품H     800.0
상품I     900.0
상품J    1000.0
상품K    1100.0
상품L    1200.0
상품M    1300.0
상품N    1400.0
상품O    1500.0
상품P    1600.0
상품Q    1700.0
상품R    1800.0
상품S    1900.0
상품T    2000.0
상품U    2100.0
상품V    2200.0
상품W    2300.0
상품X    2400.0
상품Y    2500.0
상품Z    2600.0
Name: item_price, dtype: float64